# Knowledge Base and Dense Retrieval

## 1. Цель этапа

На этом этапе клинические рекомендации преобразуются в структурированную базу знаний, по которой затем можно искать релевантные фрагменты для медицинского вопроса.

Основные задачи:

- загрузить и проверить исходные PDF;
- извлечь текст и структуру документов;
- сохранить информацию об источнике, разделе и странице;
- разбить документы на смысловые фрагменты;
- построить baseline dense retrieval и проверить корректность его работы на вопросах из `debug`.

На этом этапе генерация ответов с помощью Qwen не используется. Сначала отдельно проверяется качество retrieval.

## 2. Подготовка документов

PDF хранит в первую очередь расположение текста на странице, а не готовую структуру вида «заголовок - раздел - абзац».

Поэтому простого извлечения всего текста недостаточно. Для RAG важно по возможности сохранить структуру документа: название рекомендации, раздел, страницу и сам текст.

Это позволит не только находить релевантный фрагмент, но и понимать, из какого источника он был получен.

In [1]:
import pymupdf
import pandas as pd

import re

from collections import Counter

In [2]:
from pathlib import Path

GUIDELINES_DIR = Path("../data/source_documents/guidelines")

pdf_paths = sorted(GUIDELINES_DIR.rglob("*.pdf"))

print("Количество PDF:", len(pdf_paths))

for path in pdf_paths:
    print(path)

Количество PDF: 8
..\data\source_documents\guidelines\cdc\cdc_sti_2021.pdf
..\data\source_documents\guidelines\va_dod\va_dod_asthma_2025.pdf
..\data\source_documents\guidelines\va_dod\va_dod_ckd_2025.pdf
..\data\source_documents\guidelines\va_dod\va_dod_low_back_pain_2022.pdf
..\data\source_documents\guidelines\va_dod\va_dod_major_depression_2022.pdf
..\data\source_documents\guidelines\va_dod\va_dod_pregnancy_2023.pdf
..\data\source_documents\guidelines\va_dod\va_dod_type2_diabetes_2023.pdf
..\data\source_documents\guidelines\who\who_hypertension_2021.pdf

## 3. Проверка извлечения текста

Перед построением parser проверим, насколько хорошо текст извлекается из исходных PDF.

PDF описывает расположение элементов на странице, поэтому после извлечения могут появляться:

- повторяющиеся headers и footers;
- неправильный порядок текста;
- разрывы слов и строк;
- смешивание текста из таблиц;
- потеря структуры заголовков.

Сначала проверим наличие текстового слоя во всех документах, затем посмотрим несколько страниц подробнее.

In [3]:
pdf_stats = []

for path in pdf_paths:
    doc = pymupdf.open(path)

    empty_pages = 0
    total_chars = 0

    for page in doc:
        text = page.get_text("text").strip()

        total_chars += len(text)

        if not text:
            empty_pages += 1

    pdf_stats.append(
        {
            "file": path.name,
            "pages": len(doc),
            "empty_pages": empty_pages,
            "characters": total_chars,
        }
    )

    doc.close()

pdf_stats_df = pd.DataFrame(pdf_stats)

pdf_stats_df

                               file  pages  empty_pages  characters
0                  cdc_sti_2021.pdf    192            2     1122703
1            va_dod_asthma_2025.pdf    149            0      322893
2               va_dod_ckd_2025.pdf    198            0      554221
3     va_dod_low_back_pain_2022.pdf    141            0      435526
4  va_dod_major_depression_2022.pdf    159            0      456683
5         va_dod_pregnancy_2023.pdf    193            0      539638
6    va_dod_type2_diabetes_2023.pdf    165            0      421845
7         who_hypertension_2021.pdf     61            3      159357

In [4]:
sample_paths = [
    GUIDELINES_DIR / "who" / "who_hypertension_2021.pdf",
    GUIDELINES_DIR / "cdc" / "cdc_sti_2021.pdf",
    GUIDELINES_DIR / "va_dod" / "va_dod_asthma_2025.pdf",
]

for path in sample_paths:
    doc = pymupdf.open(path)

    page_number = 10
    text = doc[page_number].get_text("text")

    print("\n" + "=" * 100)
    print(path.name)
    print("=" * 100)
    print(text[:3000])

    doc.close()

====================================================================================================
who_hypertension_2021.pdf
====================================================================================================
WHO recommends a target systolic blood pressure treatment goal of <130 mmHg in patients
with hypertension and known cardiovascular disease (CVD).
Strong recommendation, moderate-certainty evidence
WHO suggests a target systolic blood pressure treatment goal of <130 mmHg in high-risk
patients with hypertension (those with high CVD risk, diabetes mellitus, chronic kidney
disease).
Conditional recommendation, moderate-certainty evidence
7.	 RECOMMENDATIONS ON FREQUENCY OF ASSESSMENT
WHO suggests a monthly follow up after initiation or a change in antihypertensive
medications until patients reach target.
Conditional recommendation, low-certainty evidence
WHO suggests a follow up every 3–6 months for patients whose blood pressure is under
control.
Conditional recommendation, low-certainty evidence
8.	 RECOMMENDATION ON TREATMENT BY NONPHYSICIAN PROFESSIONALS
WHO suggests that pharmacological treatment of hypertension can be provided by
nonphysician professionals such as pharmacists and nurses, as long as the following
conditions are met: proper training, prescribing authority, specific management protocols
and physician oversight.
Conditional recommendation, low-certainty evidence
ix


====================================================================================================
cdc_sti_2021.pdf
====================================================================================================
Recommendations and Reports
MMWR  /  July 23, 2021  /  Vol. 70  /  No. 4
9
US Department of Health and Human Services/Centers for Disease Control and Prevention
the risk that serosorting can lead to HIV infection. Serosorting
has not been studied among heterosexually active persons.
Abstinence and Reduction of Number of
Sex Partners
Abstinence from oral, vaginal, and anal sex and participating
in a long-term, mutually monogamous relationship with a
partner known to be uninfected are prevention approaches to
avoid transmission of STIs. For persons who are being treated
for an STI (or whose partners are undergoing treatment),
counseling that encourages abstinence from sexual intercourse
until completion of the entire course of medication is vital
for preventing reinfection. A trial conducted among women
regarding the effectiveness of counseling messages when
patients have cervicitis or vaginal discharge demonstrated
that women whose sex partners have used condoms might
benefit from a hierarchical message that includes condoms
but women without such experience might benefit more from
an abstinence-only message (104). A more comprehensive
discussion of abstinence and other sexual practices that can help
persons reduce their risk for STIs is available in Contraceptive
Technology, 21st Edition (31).
Partner Services
The term “partner services” refers to a continuum of clinical
evaluation, counseling, diagnostic testing, and treatment
designed to increase the number of infected persons brought to
treatment and to reduce transmission among sexual networks.
This continuum includes efforts of health departments,
medical providers, and patients themselves. The term “public
health partner services” refers to efforts by public health
departments to identify the sex and needle-sharing partners
of infected persons to ensure their medical evaluation and
treatment. Health departments are increasingly incorporating
referral to additional services, as indicated, into the partner services
continuum. Aside from the general benefit to patients and partners,
service referrals and linkage can mitigate the circumstances that
increase risk for future STI and HIV acquisition.
The types and comprehensiveness of public health partner
services and the specific STIs for which they are offered vary
by public health agency, their resources, and the geographic
prevalence of STIs. In most areas of the United States, health
departments routinely attempt to provide partner services to
all persons with infectious syphilis (primary or secondary)
and persons with a new diagnosis of HIV infection. Health
departments should provide partner services for persons who
might have cephalosporin-resistant gonorrhea. In contrast,
relatively few U.S. health departments routinely provide
STI partner services to persons with gonorrhea, chlamydia,
trichomoniasis, or other STIs (105). Because STI diagnoses
often can serve as risk markers for HIV acquisition

====================================================================================================
va_dod_asthma_2025.pdf
====================================================================================================
VA/DOD Clinical Practice Guideline for the Primary Care Management of Asthma



March 2025
Page 11 of 149
•
In patients with exercise-induced bronchoconstriction, we suggest pre-exertional short-
acting beta agonists. (Weak for)
•
We suggest offering the treatment of gastroesophageal reflux disease in patients with
gastroesophageal reflux disease and asthma for improving asthma control and lung
function. (Weak for)
•
We suggest weight loss in adults with asthma and obesity to improve asthma control.
(Weak for)
•
We suggest against the use of indoor air filtration devices such as high efficiency
particulate air and nitric oxide filters, for asthma control. (Weak against)
•
For patients with asthma, there is insufficient evidence to recommend for or against
offering telemedicine as an alternative to in-person treatment. (Neither for nor against)
Finally, the 2025 VA/DOD Asthma CPG applied rigorous criteria for reviewing evidence compared
with prior versions of this CPG. The GRADE methodology carefully defines how data will be
interpreted. It applies rating criteria that assign strength of evidence to critical outcomes, which
might result in some recommendations being excluded or downgraded (see Evidence Quality and
Recommendation Strength). However, these methods protect the integrity of the Asthma CPG
and ensure the recommendation statements are true to the underlying and available evidence.
B. Components of This Guideline
This CPG provides clinical practice recommendations for the care of patients with asthma (see
Recommendations). In addition, the Algorithm incorporates the recommendations in the context of
the flow of patient care. This CPG also includes Research Priorities which list areas the Work
Group identified as needing additional research. To accompany this CPG, the Work Group also
developed toolkit materials for providers and patients, including a provider summary, a patient
summary, and a quick reference guide, which can be found at:
https://www.healthquality.va.gov/index.asp.
C. Demographic Terminology in this Guideline
The demographic terms used in this guideline are derived from the published literature sources
included in the systematic review and evidence base. The Work Group used terms such as Black
rather than African American and White rather than Caucasian to avoid presumptions about
ancestry and to improve clarity and consistency. In order to most accurately present the research
evidence on which this CPG is based, the Work Group made every effort to use the same
terminology as reported in the published literature base of systematic reviews (SR), clinical trials,
and other studies. Consequently, usage of demographic terms in this CPG may vary and appear
inconsistent.

### Результат проверки

Все документы содержат доступный текстовый слой, поэтому OCR для корпуса не требуется.

Основной клинический текст извлекается корректно, однако присутствуют элементы PDF-разметки, которые не должны оставаться в текстовом содержимом chunks: повторяющиеся headers и footers, служебные номера страниц и переносы слов между строками.

При этом информация о происхождении фрагмента должна быть сохранена отдельно в metadata: источник, название документа, год, раздел и страница.

Обычное извлечение текста не сохраняет явно структуру разделов. Поэтому перед chunking необходимо определить, можно ли восстановить заголовки по форматированию PDF.

## 4. Структура текста внутри PDF

Для retrieval полезно знать не только страницу, но и раздел, к которому относится найденный фрагмент.

PDF не хранит структуру как HTML, однако `PyMuPDF` позволяет получить отдельные text spans вместе с размером и названием шрифта. Проверим, отличаются ли таким образом заголовки от обычного текста.

In [5]:
def inspect_page_spans(path, page_number, limit=40):
    doc = pymupdf.open(path)
    page = doc[page_number]

    page_dict = page.get_text("dict")

    rows = []

    for block in page_dict["blocks"]:
        if "lines" not in block:
            continue

        for line in block["lines"]:
            for span in line["spans"]:
                text = span["text"].strip()

                if text:
                    rows.append(
                        {
                            "text": text,
                            "font_size": round(span["size"], 1),
                            "font": span["font"],
                        }
                    )

    doc.close()

    return pd.DataFrame(rows).head(limit)

In [6]:
asthma_path = (
    GUIDELINES_DIR
    / "va_dod"
    / "va_dod_asthma_2025.pdf"
)

inspect_page_spans(
    asthma_path,
    page_number=29,
    limit=50,
)

,text,font_size,font
0,VA/DOD Clinical Practice Guideline for the Pri...,10.0,Arial-ItalicMT
1,March 2025,10.0,ArialMT
2,Page 30 of 149,10.0,ArialMT
3,IX. Recommendations,14.0,Arial-BoldMT
4,The evidence-based clinical practice recommend...,11.0,ArialMT
5,using a systematic approach considering four d...,11.0,ArialMT
6,Summary of Guideline Development Methodology).,11.0,ArialMT
7,These domains include confidence in the,11.0,ArialMT
8,"quality of the evidence, balance of desirable ...",11.0,ArialMT
9,"patient values and preferences, and other impl...",11.0,ArialMT
10,Table 4. Evidence-Based Clinical Practice Reco...,11.0,Arial-BoldMT
11,"a,b",7.0,Arial-BoldMT
12,Topic,11.0,Arial-BoldMT
13,Sub-,11.0,Arial-BoldMT
14,topic #,11.0,Arial-BoldMT
15,Recommendation,11.0,Arial-BoldMT
16,Strength,11.0,Arial-BoldMT
17,a,7.0,Arial-BoldMT
18,Category,11.0,Arial-BoldMT
19,b,7.0,Arial-BoldMT
20,Diagnosis and,11.0,Arial-BoldMT
21,Assessment,11.0,Arial-BoldMT
22,1. We suggest identifying known risk factors ...,10.0,ArialMT
23,"deployment, smoking) for developing asthma and",10.0,ArialMT
24,"asthma-associated conditions (e.g., depression,",10.0,ArialMT
25,anxiety disorders).,10.0,ArialMT
26,Weak for,10.0,ArialMT
27,"Reviewed,",10.0,ArialMT
28,New-replaced,10.0,ArialMT
29,"2. In adults and children with asthma, we sug...",10.0,ArialMT
30,identifying known risk factors of asthma-related,10.0,ArialMT
31,"outcomes including overweight/obesity, atopy, air",10.0,ArialMT
32,"quality, secondhand smoke exposure in children,",10.0,ArialMT
33,and history of lower respiratory infection and,10.0,ArialMT
34,screening for presence of anxiety or depression.,10.0,ArialMT
35,Weak for,10.0,ArialMT
36,Not,10.0,ArialMT
37,"Reviewed,",10.0,ArialMT
38,Amended,10.0,ArialMT
39,Treatment and Management,11.0,Arial-BoldMT
40,Asthma,10.0,Arial-BoldItalicMT
41,Education,10.0,Arial-BoldItalicMT
42,3. We suggest offering a written asthma actio...,10.0,ArialMT
43,improve asthma control and asthma-related quality,10.0,ArialMT
44,of life.,10.0,ArialMT
45,Weak for,10.0,ArialMT
46,"Reviewed,",10.0,ArialMT
47,Amended,10.0,ArialMT
48,4. There is insufficient evidence to recommen...,10.0,ArialMT
49,against offering any particular patient-oriented,10.0,ArialMT

По форматированию VA/DoD видно, что заголовки разделов отличаются от основного текста размером и начертанием шрифта. Это позволяет использовать информацию о форматировании для восстановления структуры документа.

При этом жирный шрифт используется не только для заголовков, но и внутри таблиц, поэтому определять раздел только по признаку `bold` нельзя.

Перед написанием parser необходимо проверить, как оформлены заголовки в документах WHO и CDC.

In [7]:
def find_pages_with_text(path, query):
    doc = pymupdf.open(path)

    matches = []

    for page_number, page in enumerate(doc):
        text = page.get_text("text")

        if query.lower() in text.lower():
            matches.append(page_number)

    doc.close()

    return matches

In [8]:
who_path = (
    GUIDELINES_DIR
    / "who"
    / "who_hypertension_2021.pdf"
)

find_pages_with_text(
    who_path,
    "Blood pressure threshold",
)

[4, 8, 13, 18, 55]

In [9]:
cdc_path = (
    GUIDELINES_DIR
    / "cdc"
    / "cdc_sti_2021.pdf"
)

find_pages_with_text(
    cdc_path,
    "Chlamydial Infections",
)

[1, 11, 12, 15, 17, 23, 28, 63, 64, 65, 66, 70, 73, 76, 98, 143, 148, 163, 164]

In [10]:
inspect_page_spans(
    who_path,
    page_number=18,
    limit=50,
)

,text,font_size,font
0,3\t Recommendations,25.0,Frutiger-Bold
1,3.1,12.0,Frutiger-Bold
2,Blood pressure threshold for initiation of pha...,12.0,Frutiger-Bold
3,1.,10.0,Frutiger-Bold
4,RECOMMENDATION ON BLOOD PRESSURE THRESHOLD FOR...,10.0,Frutiger-Bold
5,PHARMACOLOGICAL TREATMENT,10.0,Frutiger-Bold
6,WHO recommends initiation of pharmacological a...,10.0,Frutiger-Roman
7,with a confirmed diagnosis of hypertension and...,10.0,Frutiger-Roman
8,≥,10.0,Symbol
9,140 mmHg or,10.0,Frutiger-Roman
10,diastolic blood pressure of,10.0,Frutiger-Roman
11,≥,10.0,Symbol
12,90 mmHg.,10.0,Frutiger-Roman
13,"Strong recommendation, moderate- to high-certa...",10.0,Frutiger-Italic
14,WHO recommends pharmacological antihypertensiv...,10.0,Frutiger-Roman
15,cardiovascular disease and systolic blood pres...,10.0,Frutiger-Roman
16,"Strong recommendation, moderate- to high-certa...",10.0,Frutiger-Italic
17,WHO suggests pharmacological antihypertensive ...,10.0,Frutiger-Roman
18,cardiovascular disease but with high cardiovas...,10.0,Frutiger-Roman
19,"disease, and systolic blood pressure of 130–13...",10.0,Frutiger-Roman
20,"Conditional recommendation, moderate- to high-...",10.0,Frutiger-Italic
21,Implementation remarks:,10.0,Frutiger-Light
22,[,10.0,Frutiger-Light
23,[,10.0,DeltaSymbol
24,Initiation of pharmacological hypertension (HT...,10.0,Frutiger-Light
25,weeks following diagnosis of HTN. If blood pre...,10.0,Frutiger-Light
26,≥,10.0,Symbol
27,160 mmHg or,10.0,Frutiger-Light
28,diastolic,10.0,Frutiger-Light
29,≥,10.0,Symbol
30,100 mmHg) or there is accompanying evidence of...,10.0,Frutiger-Light
31,treatment should be started without delay.,10.0,Frutiger-Light
32,Evidence and rationale,10.0,Frutiger-Bold
33,The GDG reviewed evidence from 14 relevant sys...,10.0,Frutiger-Light
34,number of randomized trials involving over 120...,10.0,Frutiger-Light
35,summaries are presented for the general popula...,10.0,Frutiger-Light
36,"coronary artery disease (CAD), prior stroke) a...",10.0,Frutiger-Light
37,thresholds (Web Annex A).,10.0,Frutiger-Light
38,The anticipated benefits of a lower blood pres...,10.0,Frutiger-Light
39,and 130 SBP in a high-risk population) were re...,10.0,Frutiger-Light
40,myocardial infarction (MI) and heart failure e...,10.0,Frutiger-Light
41,"side-effects, and some were a surrogate outcom...",10.0,Frutiger-Light
42,"relevant. On average, treatment was associated...",10.0,Frutiger-Light
43,that ranged from 5 to 10/1000 and harms that r...,10.0,Frutiger-Light
44,reduction in severe events with significant mo...,10.0,Frutiger-Light
45,clinically significant.,10.0,Frutiger-Light
46,"In summary, the anticipated benefits were larg...",10.0,Frutiger-Light
47,"varied from moderate to high, depending on the...",10.0,Frutiger-Light
48,RECOMMENDATIONS,10.0,Frutiger-Cn
49,7,10.0,Frutiger-BoldCn

In [11]:
inspect_page_spans(
    cdc_path,
    page_number=64,
    limit=50,
)

,text,font_size,font
0,Recommendations and Reports,9.0,MyriadPro-Regular
1,"MMWR / July 23, 2021 / Vol. 70 / No. 4",8.0,MyriadPro-Regular
2,63,8.0,MyriadPro-Regular
3,US Department of Health and Human Services/Cen...,8.0,MyriadPro-Regular
4,completion of a 7-day regimen and symptoms hav...,11.0,AGaramondPro-Regular
5,for 7 days after single-dose therapy). Men wit...,11.0,AGaramondPro-Regular
6,be tested for HIV and syphilis.,11.0,AGaramondPro-Regular
7,Follow-Up,12.0,MyriadPro-Semibold
8,Men should be provided their testing results o...,11.0,AGaramondPro-Regular
9,part of the NGU evaluation. Those with a speci...,11.0,AGaramondPro-Regular
10,"of chlamydia, gonorrhea, or trichomoniasis sho...",11.0,AGaramondPro-Regular
11,offered partner services and instructed to ret...,11.0,AGaramondPro-Regular
12,after treatment for repeat testing because of ...,11.0,AGaramondPro-Regular
13,"reinfection, regardless of whether their sex p...",11.0,AGaramondPro-Regular
14,(,11.0,AGaramondPro-Regular
15,136,11.0,AGaramondPro-Italic
16,",",11.0,AGaramondPro-Regular
17,137,11.0,AGaramondPro-Italic
18,",",11.0,AGaramondPro-Regular
19,753,11.0,AGaramondPro-Italic
20,",",11.0,AGaramondPro-Regular
21,754,11.0,AGaramondPro-Italic
22,) (see Chlamydial Infections; Gonococcal,11.0,AGaramondPro-Regular
23,Infections; Trichomoniasis).,11.0,AGaramondPro-Regular
24,If symptoms persist or recur after therapy com...,11.0,AGaramondPro-Regular
25,should be instructed to return for reevaluatio...,11.0,AGaramondPro-Regular
26,tested for,11.0,AGaramondPro-Regular
27,M. genitalium,11.0,AGaramondPro-Italic
28,and,11.0,AGaramondPro-Regular
29,T. vaginalis,11.0,AGaramondPro-Italic
30,". Symptoms alone,",11.0,AGaramondPro-Regular
31,without documentation of signs or laboratory e...,11.0,AGaramondPro-Regular
32,"urethral inflammation, are insufficient basis ...",11.0,AGaramondPro-Regular
33,Providers should be alert to the possible diag...,11.0,AGaramondPro-Regular
34,prostatitis or chronic pelvic pain syndrome in...,11.0,AGaramondPro-Regular
35,"persistent perineal, penile, or pelvic pain or...",11.0,AGaramondPro-Regular
36,voiding symptoms; pain during or after ejacula...,11.0,AGaramondPro-Regular
37,onset premature ejaculation lasting for >3 mon...,11.0,AGaramondPro-Regular
38,persistent pain should be referred to a urolog...,11.0,AGaramondPro-Regular
39,in pelvic pain disorders.,11.0,AGaramondPro-Regular
40,Management of Sex Partners,12.0,MyriadPro-Semibold
41,All sex partners of men with NGU within the pr...,11.0,AGaramondPro-Regular
42,60 days should be referred for evaluation and ...,11.0,AGaramondPro-Regular
43,presumptive treatment with a drug regimen effe...,11.0,AGaramondPro-Regular
44,chlamydia. All partners should be evaluated an...,11.0,AGaramondPro-Regular
45,according to the management section for their ...,11.0,AGaramondPro-Regular
46,pathogen; EPT could be an alternate approach i...,11.0,AGaramondPro-Regular
47,unable to access timely care. To avoid reinfec...,11.0,AGaramondPro-Regular
48,should abstain from sexual intercourse until t...,11.0,AGaramondPro-Regular
49,partners are treated.,11.0,AGaramondPro-Regular

In [12]:
def find_matching_spans(path, query):
    doc = pymupdf.open(path)

    matches = []

    for page_number, page in enumerate(doc):
        page_dict = page.get_text("dict")

        for block in page_dict["blocks"]:
            if "lines" not in block:
                continue

            for line in block["lines"]:
                line_text = "".join(
                    span["text"] for span in line["spans"]
                ).strip()

                if query.lower() in line_text.lower():
                    matches.append(
                        {
                            "pdf_page": page_number + 1,
                            "text": line_text,
                            "spans": [
                                {
                                    "text": span["text"],
                                    "size": round(span["size"], 1),
                                    "font": span["font"],
                                }
                                for span in line["spans"]
                            ],
                        }
                    )

    doc.close()

    return matches

In [13]:
find_matching_spans(
    cdc_path,
    "Chlamydial Infections",
)

[{'pdf_page': 2,
  'text': 'Chlamydial Infections........................................................................................ 65',
  'spans': [{'text': 'Chlamydial Infections........................................................................................ 65',
    'size': 9.0,
    'font': 'MyriadPro-Regular'}]},
 {'pdf_page': 12,
  'text': 'or chlamydial infections among MSM, compared with',
  'spans': [{'text': 'or chlamydial infections among MSM, compared with ',
    'size': 11.0,
    'font': 'AGaramondPro-Regular'}]},
 {'pdf_page': 12,
  'text': 'or chlamydial infections (133,134); however, more recent data',
  'spans': [{'text': 'or chlamydial infections (',
    'size': 11.0,
    'font': 'AGaramondPro-Regular'},
   {'text': '133', 'size': 11.0, 'font': 'AGaramondPro-Italic'},
   {'text': ',', 'size': 11.0, 'font': 'AGaramondPro-Regular'},
   {'text': '134', 'size': 11.0, 'font': 'AGaramondPro-Italic'},
   {'text': '); however, more recent data ',
    'size': 11.0,
    'font': 'AGaramondPro-Regular'}]},
 {'pdf_page': 13,
  'text': 'report (see Chlamydial Infections; Gonococcal Infections;',
  'spans': [{'text': 'report (see Chlamydial Infections; Gonococcal Infections; ',
    'size': 11.0,
    'font': 'AGaramondPro-Regular'}]},
 {'pdf_page': 16,
  'text': 'of young men with a high prevalence of chlamydial infections',
  'spans': [{'text': 'of young men with a high prevalence of chlamydial infections ',
    'size': 11.0,
    'font': 'AGaramondPro-Regular'}]},
 {'pdf_page': 18,
  'text': '70% of gonococcal and chlamydial infections might be',
  'spans': [{'text': '70% of gonococcal and chlamydial infections might be ',
    'size': 11.0,
    'font': 'AGaramondPro-Regular'}]},
 {'pdf_page': 24,
  'text': 'chlamydial infections among females (and males if screened)',
  'spans': [{'text': 'chlamydial infections among females (and males if screened) ',
    'size': 11.0,
    'font': 'AGaramondPro-Regular'}]},
 {'pdf_page': 29,
  'text': 'Chlamydial Infections (111).',
  'spans': [{'text': 'Chlamydial Infections',
    'size': 11.0,
    'font': 'AGaramondPro-Italic'},
   {'text': ' (', 'size': 11.0, 'font': 'AGaramondPro-Regular'},
   {'text': '111', 'size': 11.0, 'font': 'AGaramondPro-Italic'},
   {'text': ').', 'size': 11.0, 'font': 'AGaramondPro-Regular'}]},
 {'pdf_page': 64,
  'text': 'infections and is also effective for chlamydial infections of',
  'spans': [{'text': 'infections and is also effective for chlamydial infections of ',
    'size': 11.0,
    'font': 'AGaramondPro-Regular'}]},
 {'pdf_page': 65,
  'text': '(136,137,753,754) (see Chlamydial Infections; Gonococcal',
  'spans': [{'text': '(', 'size': 11.0, 'font': 'AGaramondPro-Regular'},
   {'text': '136', 'size': 11.0, 'font': 'AGaramondPro-Italic'},
   {'text': ',', 'size': 11.0, 'font': 'AGaramondPro-Regular'},
   {'text': '137', 'size': 11.0, 'font': 'AGaramondPro-Italic'},
   {'text': ',', 'size': 11.0, 'font': 'AGaramondPro-Regular'},
   {'text': '753', 'size': 11.0, 'font': 'AGaramondPro-Italic'},
   {'text': ',', 'size': 11.0, 'font': 'AGaramondPro-Regular'},
   {'text': '754', 'size': 11.0, 'font': 'AGaramondPro-Italic'},
   {'text': ') (see Chlamydial Infections; Gonococcal ',
    'size': 11.0,
    'font': 'AGaramondPro-Regular'}]},
 {'pdf_page': 66,
  'text': 'Chlamydial Infections; Gonococcal Infections). Women',
  'spans': [{'text': 'Chlamydial Infections; Gonococcal Infections). Women ',
    'size': 11.0,
    'font': 'AGaramondPro-Regular'}]},
 {'pdf_page': 67,
  'text': 'Chlamydial Infections',
  'spans': [{'text': 'Chlamydial Infections',
    'size': 16.0,
    'font': 'MyriadPro-Semibold'}]},
 {'pdf_page': 71,
  'text': 'chlamydial infections, including ophthalmia and pneumonia,',
  'spans': [{'text': 'chlamydial infections, including ophthalmia and pneumonia, ',
    'size': 11.0,
    'font': 'AGaramondPro-Regular'}]},
 {'pdf_page': 74,
  'text': 'efficacy for chlamydia (see Chlamydial Infections).',
  'spans': [{'text': 'efficacy for chlamydia (see Chlamydial Infections).',
    'size': 11.0,
    'font': 'AGaramondPro-Regular'}]},
 {'pdf_page': 77,
  'text': 'chlamydia (see Chlamydial Infections). Provision of medication',
  'spans': [{'text': 'chlamydia (see Chlamydial Infections). Provision of medication ',
    'size': 11.0,
    'font': 'AGaramondPro-Regular'}]},
 {'pdf_page': 99,
  'text': 'treated (see Chlamydial Infections; Gonococcal Infections).',
  'spans': [{'text': 'treated (see Chlamydial Infections; Gonococcal Infections). ',
    'size': 11.0,
    'font': 'AGaramondPro-Regular'}]},
 {'pdf_page': 144,
  'text': 'chlamydial infections in men who have sex with men sexually',
  'spans': [{'text': 'chlamydial infections in men who have sex with men sexually ',
    'size': 9.0,
    'font': 'AGaramondPro-Regular'}]},
 {'pdf_page': 149,
  'text': 'genital gonorrheal and chlamydial infections among high-risk men',
  'spans': [{'text': 'genital gonorrheal and chlamydial infections among high-risk men ',
    'size': 9.0,
    'font': 'AGaramondPro-Regular'}]},
 {'pdf_page': 164,
  'text': 'and chlamydial infections detected by nucleic acid amplification',
  'spans': [{'text': 'and chlamydial infections detected by nucleic acid amplification ',
    'size': 9.0,
    'font': 'AGaramondPro-Regular'}]},
 {'pdf_page': 165,
  'text': 'L. Longitudinal studies on chlamydial infections in the first year of',
  'spans': [{'text': 'L. Longitudinal studies on chlamydial infections in the first year of ',
    'size': 9.0,
    'font': 'AGaramondPro-Regular'}]}]

In [14]:
find_matching_spans(
    who_path,
    "Blood pressure threshold for initiation",
)

[{'pdf_page': 5,
  'text': 'Blood pressure threshold for initiation of pharmacological treatment',
  'spans': [{'text': 'Blood pressure threshold for initiation of pharmacological treatment\t',
    'size': 10.0,
    'font': 'Frutiger-Light'}]},
 {'pdf_page': 9,
  'text': '1.\t RECOMMENDATION ON BLOOD PRESSURE THRESHOLD FOR INITIATION OF',
  'spans': [{'text': '1.\t', 'size': 10.0, 'font': 'Frutiger-Bold'},
   {'text': ' ', 'size': 10.0, 'font': 'Frutiger-Bold'},
   {'text': 'RECOMMENDATION ON BLOOD PRESSURE THRESHOLD FOR INITIATION OF ',
    'size': 10.0,
    'font': 'Frutiger-Bold'}]},
 {'pdf_page': 19,
  'text': '3.1\t Blood pressure threshold for initiation of pharmacological treatment',
  'spans': [{'text': '3.1\t', 'size': 12.0, 'font': 'Frutiger-Bold'},
   {'text': ' ', 'size': 12.0, 'font': 'Frutiger-Bold'},
   {'text': 'Blood pressure threshold for initiation of pharmacological treatment',
    'size': 12.0,
    'font': 'Frutiger-Bold'}]},
 {'pdf_page': 19,
  'text': '1.\t RECOMMENDATION ON BLOOD PRESSURE THRESHOLD FOR INITIATION OF',
  'spans': [{'text': '1.\t', 'size': 10.0, 'font': 'Frutiger-Bold'},
   {'text': ' ', 'size': 10.0, 'font': 'Frutiger-Bold'},
   {'text': 'RECOMMENDATION ON BLOOD PRESSURE THRESHOLD FOR INITIATION OF ',
    'size': 10.0,
    'font': 'Frutiger-Bold'}]}]

### Результат анализа структуры

Структура документов может быть частично восстановлена по размеру и начертанию шрифта, однако правила различаются между издателями.

Для VA/DoD крупные разделы и подразделы преимущественно выделяются Arial Bold разного размера.

В WHO наблюдается несколько уровней заголовков: крупные заголовки глав, нумерованные подразделы и внутренние блоки рекомендаций.

В CDC основной текст и заголовки используют разные семейства шрифтов: основной текст преимущественно набран AGaramondPro, тогда как заголовки разделов используют MyriadPro-Semibold.

Поэтому один универсальный критерий вида `bold = heading` ненадёжен. Для трёх семейств документов будут использоваться отдельные правила определения структуры, но результат parser будет приведён к единой схеме metadata.

Для каждого текстового фрагмента будут сохраняться:

- источник;
- название документа;
- год;
- иерархический путь раздела (`section_path`);
- номер страницы документа;
- физическая страница PDF;
- текст.

In [15]:
doc = pymupdf.open(asthma_path)

for pdf_index in [0, 1, 10, 29, 30]:
    page = doc[pdf_index]

    print(
        "pdf_index =", pdf_index,
        "| pdf_page =", pdf_index + 1,
        "| page_label =", page.get_label(),
    )

doc.close()

pdf_index = 0 | pdf_page = 1 | page_label =
pdf_index = 1 | pdf_page = 2 | page_label =
pdf_index = 10 | pdf_page = 11 | page_label =
pdf_index = 29 | pdf_page = 30 | page_label =
pdf_index = 30 | pdf_page = 31 | page_label =

In [16]:
doc = pymupdf.open(who_path)

for pdf_index in [0, 4, 8, 18]:
    page = doc[pdf_index]

    print(
        "pdf_index =", pdf_index,
        "| pdf_page =", pdf_index + 1,
        "| page_label =", page.get_label(),
    )

doc.close()

pdf_index = 0 | pdf_page = 1 | page_label = a
pdf_index = 4 | pdf_page = 5 | page_label = iii
pdf_index = 8 | pdf_page = 9 | page_label = vii
pdf_index = 18 | pdf_page = 19 | page_label = 7

In [17]:
doc = pymupdf.open(cdc_path)

for pdf_index in [0, 1, 66, 67]:
    page = doc[pdf_index]

    print(
        "pdf_index =", pdf_index,
        "| pdf_page =", pdf_index + 1,
        "| page_label =", page.get_label(),
    )

doc.close()

pdf_index = 0 | pdf_page = 1 | page_label = i
pdf_index = 1 | pdf_page = 2 | page_label = ii
pdf_index = 66 | pdf_page = 67 | page_label = 65
pdf_index = 67 | pdf_page = 68 | page_label = 66

### Нумерация страниц

PDF metadata различается между источниками.

В документах WHO логические номера страниц доступны через `page.get_label()`. Они учитывают внутреннюю нумерацию документа, включая римские номера во вводных разделах и обычные номера в основном тексте.

В документах CDC логические page labels также доступны через `page.get_label()` и корректно отражают номер страницы, напечатанный в документе, который может отличаться от физической позиции страницы в PDF.

В документах VA/DoD page labels отсутствуют. В проверенных страницах физическая нумерация PDF совпадает с номером страницы, указанным в самом документе, поэтому для этих документов можно использовать физический номер страницы как номер документа.

Таким образом:

- `pdf_page` — физическая позиция страницы в PDF, начиная с 1;
- `page` — логический номер страницы документа, используемый для цитирования.

`pdf_page` будет сохраняться всегда. Для WHO и CDC значение `page` будет получаться через `page.get_label()`, а для VA/DoD — из физического номера страницы.

Для VA/DoD отдельно необходимо учитывать таблицы: жирный текст внутри таблиц может визуально совпадать с форматированием заголовков разделов. Поэтому признаки шрифта будут использоваться вместе с положением текста и структурой страницы, а не как единственный критерий.

## 5. Дизайн parser

Документы WHO, CDC и VA/DoD имеют разные правила форматирования, поэтому определение заголовков будет выполняться отдельно для каждого семейства документов.

При этом результат parsing должен иметь единую структуру, чтобы последующие этапы chunking и retrieval не зависели от формата исходного PDF.

Для каждого текстового фрагмента сохраняются:

- `document_id` — уникальный идентификатор документа;
- `source` — организация-источник;
- `document_title` — название исходного документа;
- `year` — год публикации;
- `section_path` — иерархический путь раздела;
- `page` — логический номер страницы документа;
- `pdf_page` — физическая страница PDF;
- `text` — очищенный текст.

Сначала документы будут преобразованы в структурированные текстовые фрагменты. Chunking выполняется отдельным этапом после проверки качества parsing.

In [18]:
DOCUMENT_METADATA = {
    "cdc_sti_2021.pdf": {
    "source": "CDC",
    "year": 2021,
    "family": "cdc",
    "document_title": (
        "Sexually Transmitted Infections Treatment Guidelines, 2021"
    ),
    },
    "who_hypertension_2021.pdf": {
    "source": "WHO",
    "year": 2021,
    "family": "who",
    "document_title": (
        "Guideline for the pharmacological treatment "
        "of hypertension in adults"
    ),
    },
    "va_dod_asthma_2025.pdf": {
        "source": "VA/DoD",
        "year": 2025,
        "family": "va_dod",
        "document_title": (
            "VA/DOD Clinical Practice Guideline for the "
            "Primary Care Management of Asthma"
        ),
    },
    "va_dod_ckd_2025.pdf": {
        "source": "VA/DoD",
        "year": 2025,
        "family": "va_dod",
        "document_title": (
            "VA/DOD Clinical Practice Guideline for the "
            "Primary Care Management of Chronic Kidney Disease"
        ),
    },
    "va_dod_low_back_pain_2022.pdf": {
        "source": "VA/DoD",
        "year": 2022,
        "family": "va_dod",
        "document_title": (
            "VA/DoD Clinical Practice Guideline for the "
            "Diagnosis and Treatment of Low Back Pain"
        ),
    },
    "va_dod_major_depression_2022.pdf": {
        "source": "VA/DoD",
        "year": 2022,
        "family": "va_dod",
        "document_title": (
            "VA/DoD Clinical Practice Guideline for the "
            "Management of Major Depressive Disorder"
        ),
    },
    "va_dod_pregnancy_2023.pdf": {
        "source": "VA/DoD",
        "year": 2023,
        "family": "va_dod",
        "document_title": (
            "VA/DoD Clinical Practice Guideline for the "
            "Management of Pregnancy"
        ),
    },
    "va_dod_type2_diabetes_2023.pdf": {
        "source": "VA/DoD",
        "year": 2023,
        "family": "va_dod",
        "document_title": (
            "VA/DoD Clinical Practice Guideline for the "
            "Management of Type 2 Diabetes Mellitus"
        ),
    },

}

In [19]:
def get_page_number(page):
    label = page.get_label().strip()

    if label:
        return label

    return str(page.number + 1)

In [20]:
for path in pdf_paths:
    metadata = DOCUMENT_METADATA[path.name]

    with pymupdf.open(path) as doc:
        sample_page = doc[min(10, len(doc) - 1)]

        print(
            path.name,
            "| source:", metadata["source"],
            "| family:", metadata["family"],
            "| page:", get_page_number(sample_page),
            "| pdf_page:", sample_page.number + 1,
        )

cdc_sti_2021.pdf | source: CDC | family: cdc | page: 9 | pdf_page: 11
va_dod_asthma_2025.pdf | source: VA/DoD | family: va_dod | page: 11 | pdf_page: 11
va_dod_ckd_2025.pdf | source: VA/DoD | family: va_dod | page: 11 | pdf_page: 11
va_dod_low_back_pain_2022.pdf | source: VA/DoD | family: va_dod | page: 11 | pdf_page: 11
va_dod_major_depression_2022.pdf | source: VA/DoD | family: va_dod | page: 11 | pdf_page: 11
va_dod_pregnancy_2023.pdf | source: VA/DoD | family: va_dod | page: 11 | pdf_page: 11
va_dod_type2_diabetes_2023.pdf | source: VA/DoD | family: va_dod | page: 11 | pdf_page: 11
who_hypertension_2021.pdf | source: WHO | family: who | page: ix | pdf_page: 11

### Проверка встроенной структуры PDF

Перед восстановлением заголовков по форматированию проверим, содержат ли PDF встроенный outline (bookmarks).

Если он доступен, его предпочтительнее использовать для определения `section_path`, поскольку он уже содержит иерархию разделов и номера страниц и не требует эвристик по размеру или начертанию шрифта.

In [21]:
def inspect_toc(path, limit=30):
    with pymupdf.open(path) as doc:
        toc = doc.get_toc()

    return pd.DataFrame(
        toc[:limit],
        columns=["level", "title", "pdf_page"],
    )

In [22]:
inspect_toc(asthma_path, limit=40)

    level                                              title  pdf_page
0       1                                Structure Bookmarks        -1
1       2                                                            1
2       3                                                            1
3       3  VA/DOD CLINICAL PRACTICE GUIDELINE FOR THE PRI...         1
4       3                                                            1
5       3                    Department of Veterans Affairs          1
6       3                             Department of Defense          1
7       3                             QUALIFYING STATEMENTS          1
8       3  The Department of Veterans Affairs (VA) and th...         1
9       3  This clinical practice guideline (CPG) is base...         1
10      3  Variations in practice will inevitably and app...         1
11      3  These guidelines are not intended to represent...         1
12      3                                 Version 3.0 – 2025         1
13      3                                                            2
14      3                                                            2
15      3                                                            2
16      3                                       Prepared by          2
17      3            The Primary Care Management of Asthma           2
18      3                                        Work Group          2
19      3                                                            2
20      3                                 With support from          2
21      3  Office of Quality and Patient Safety, Veterans...         2
22      3                                                            2
23      3                                                            2
24      3                                               And          2
25      3                                                            2
26      3  Clinical Quality Improvement Program, Defense ...         2
27      3                                                            2
28      3                                                            2
29      3                                                            2
30      3                                Version 3.0 – 2025          2
31      3       Based on evidence reviewed through May 2024          2
32      3                                                            2
33      3                                 Table of Contents          3
34      4                                 Table of Contents          3
35      4  I. Introduction .................................         3
36      5  I. Introduction .................................         3
37      5                                                  6         3
38      5                                                            3
39      4  II. Background ..................................         3

In [23]:
inspect_toc(who_path, limit=40)

    level                                              title  pdf_page
0       1                                   Acknowledgements         7
1       1                         Acronyms and abbreviations         8
2       1                                  Executive summary         9
3       2                                    1\tIntroduction        13
4       2            2\tMethod for developing the guideline         15
5       3                       2.1\tGuideline contributors         15
6       4                2.2\tAnalytical framework and PICOs        15
7       5                    2.3\tOutcome importance rating         16
8       5                          2.4\tReviews of evidence         16
9       5  2.5\tCertainty of evidence and strength of rec...        17
10      5                 2.6\tDeciding upon recommendations        18
11      5                                      2.7\tFunding         18
12      2                                 3\tRecommendations        19
13      3  3.1\tBlood pressure threshold for initiation o...        19
14      4  3.2\tLaboratory testing before and during phar...        20
15      5  3.3\tCardiovascular disease risk assessment as...        22
16      5  3.4\tDrug classes to be used as first-line agents        23
17      5                           3.5\tCombination therapy        25
18      5                         3.6\tTarget blood pressure        28
19      5                    3.7\tFrequency of re-assessment        29
20      5  3.8\tAdministration of treatment by nonphysici...        31
21      2                                4\tSpecial settings        33
22      3  4.1\tHypertension in disaster, humanitarian an...        33
23      4                     4.2\tCOVID-19 and hypertension        34
24      5                    4.3\tPregnancy and hypertension        34
25      2  5\tPublication, implementation, evaluation and...        36
26      3                                  5.1\tPublication         36
27      4             5.2\tImplementation and dissemination         36
28      5                                   5.3\tEvaluation         36
29      5             5.4\tFuture updating of the guideline         36
30      5                                 5.5\tResearch gaps        36
31      2                            6\tImplementation tools        38
32      3                     6.1\tGuideline recommendations        38
33      4             6.2\tDrug- and dose-specific protocols        40
34      5                                         References        42
35      6                      Annex 1: List of contributors        49
36      6  Annex 2. Managing declarations of interest and...        54
37      6  Annex 3: Treatment outcomes relevant to hypert...        55
38      6                           Annex 4: PICO questions         56
39      1  Fig. 1\tAnalytic framework for antihypertensiv...        15

In [24]:
inspect_toc(cdc_path, limit=40)

    level                                              title  pdf_page
0       1  Sexually Transmitted Infections Treatment Guid...         1
1       1                                       Introduction         3
2       1                                            Methods         3
3       1                       Clinical Prevention Guidance         4
4       1            STI Detection Among Special Populations        13
5       1                                      HIV Infection        26
6       1  Diseases Characterized by Genital, Anal, or Pe...        29
7       1                                           Syphilis        41
8       1  Management of Persons Who Have a History of Pe...        58
9       1  Diseases Characterized by Urethritis and Cervi...        62
10      1                              Chlamydial Infections        67
11      1                              Gonococcal Infections        73
12      1                              Mycoplasma genitalium        82
13      1  Diseases Characterized by Vulvovaginal Itching...        84
14      1                        Pelvic Inflammatory Disease        96
15      1                                       Epididymitis       100
16      1                    Human Papillomavirus Infections       102
17      1                                    Viral Hepatitis       115
18      1            Proctitis, Proctocolitis, and Enteritis       126
19      1                           Ectoparasitic Infections       128
20      1                  Sexual Assault and Abuse and STIs       130
21      1                                         References       137

### Результат проверки PDF outline

Встроенная структура PDF неодинакова по качеству и не может использоваться одинаково для всех источников.

**WHO.** Bookmarks содержат полезные названия разделов и страницы, однако значения `level` не всегда корректно отражают реальную иерархию. Поэтому названия и границы разделов можно использовать, а иерархию восстанавливать по нумерации заголовков.

**CDC.** Bookmarks корректно определяют крупные тематические разделы, но не содержат полной иерархии внутренних подразделов. Более мелкие headings необходимо определять по форматированию текста.

**VA/DoD.** Встроенный outline содержит большое количество технических и текстовых элементов и не представляет собой надёжное оглавление. Для этих документов структура будет восстанавливаться непосредственно из текста и форматирования.

Таким образом, parser будет использовать общую выходную схему, но разные стратегии определения структуры для WHO, CDC и VA/DoD.

## 6. Извлечение страниц и базовая очистка

Перед определением структуры разделов создадим общий слой извлечения страниц.

Для каждой страницы сохраняются исходный текст и metadata документа. На этом уровне выполняется только очистка PDF-артефактов, которая не зависит от конкретной клинической тематики.

Определение `section_path` будет выполняться после этого отдельной стратегией для каждого семейства документов.

In [25]:
def clean_page_text(text):
    text = re.sub(r"-\n(?=\w)", "-", text)
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()

In [26]:
def extract_page_lines(page):
    page_dict = page.get_text("dict", sort=True)

    lines = []

    for block in page_dict["blocks"]:
        if "lines" not in block:
            continue

        for line in block["lines"]:
            spans = [
                span
                for span in line["spans"]
                if span["text"].strip()
            ]

            if not spans:
                continue

            text = "".join(span["text"] for span in line["spans"]).strip()

            if not text:
                continue

            lines.append(
                {
                    "text": text,
                    "bbox": tuple(round(x, 1) for x in line["bbox"]),
                    "font_size": round(max(span["size"] for span in spans), 1),
                    "fonts": sorted({span["font"] for span in spans}),
                }
            )

    return lines

In [27]:
def extract_document_pages(path):
    metadata = DOCUMENT_METADATA[path.name]
    document_id = path.stem

    pages = []

    with pymupdf.open(path) as doc:
        for page in doc:
            text = page.get_text("text", sort=True)

            pages.append(
                {
                    "document_id": document_id,
                    "source": metadata["source"],
                    "year": metadata["year"],
                    "family": metadata["family"],
                    "page": get_page_number(page),
                    "pdf_page": page.number + 1,
                    "width": round(page.rect.width, 1),
                    "height": round(page.rect.height, 1),
                    "text": clean_page_text(text),
                    "lines": extract_page_lines(page),
                }
            )

    return pages

In [28]:
who_pages = extract_document_pages(who_path)

pd.DataFrame(who_pages[18]["lines"]).tail(15)

,text,bbox,font_size,fonts
25,summaries are presented for the general popula...,"(79.4, 547.9, 526.9, 559.2)",10.0,[Frutiger-Light]
26,"coronary artery disease (CAD), prior stroke) a...","(79.4, 561.9, 522.3, 573.2)",10.0,[Frutiger-Light]
27,thresholds (Web Annex A).,"(79.4, 575.9, 193.5, 587.2)",10.0,[Frutiger-Light]
28,The anticipated benefits of a lower blood pres...,"(79.4, 595.6, 494.1, 606.9)",10.0,[Frutiger-Light]
29,and 130 SBP in a high-risk population) were re...,"(79.4, 609.6, 501.9, 620.9)",10.0,[Frutiger-Light]
30,myocardial infarction (MI) and heart failure e...,"(79.4, 623.6, 497.6, 634.9)",10.0,[Frutiger-Light]
31,"side-effects, and some were a surrogate outcom...","(79.4, 637.6, 510.3, 648.9)",10.0,[Frutiger-Light]
32,"relevant. On average, treatment was associated...","(79.4, 651.6, 509.8, 662.9)",10.0,[Frutiger-Light]
33,that ranged from 5 to 10/1000 and harms that r...,"(79.4, 665.6, 491.7, 676.9)",10.0,[Frutiger-Light]
34,reduction in severe events with significant mo...,"(79.4, 679.6, 518.1, 690.9)",10.0,[Frutiger-Light]
35,clinically significant.,"(79.4, 693.6, 166.0, 704.9)",10.0,[Frutiger-Light]
36,"In summary, the anticipated benefits were larg...","(79.4, 713.3, 523.3, 724.5)",10.0,[Frutiger-Light]
37,"varied from moderate to high, depending on the...","(79.4, 727.3, 393.7, 738.5)",10.0,[Frutiger-Light]
38,RECOMMENDATIONS,"(557.2, 703.2, 569.0, 785.2)",10.0,[Frutiger-Cn]
39,7,"(561.4, 811.4, 566.6, 823.3)",10.0,[Frutiger-BoldCn]

## 7. Parser для WHO

Для WHO структура документа достаточно хорошо представлена встроенными bookmarks, а служебные элементы страницы можно отделить от основного текста по их положению.

Сначала удалим элементы из боковых и нижних полей страницы, сохранив при этом номер страницы отдельно в metadata.

In [29]:
def clean_who_lines(page_data):
    clean_lines = []

    width = page_data["width"]
    height = page_data["height"]

    for line in page_data["lines"]:
        x0, y0, x1, y1 = line["bbox"]
        text = line["text"].strip()

        # Вертикальный footer в правом поле
        if x0 > 0.9 * width:
            continue

        # Номер страницы внизу
        if y0 > 0.95 * height:
            continue

        # PDF-артефакт маркировки
        if text == "[":
            continue

        if text:
            clean_lines.append(
                {
                    **line,
                    "text": text,
                }
            )

    return clean_lines

In [30]:
who_clean_lines = clean_who_lines(who_pages[18])

pd.DataFrame(who_clean_lines)[
    ["text", "bbox", "font_size", "fonts"]
]

,text,bbox,font_size,fonts
0,3\t Recommendations,"(79.4, 52.8, 324.4, 81.7)",25.0,[Frutiger-Bold]
1,3.1\t Blood pressure threshold for initiation ...,"(79.4, 118.6, 496.6, 132.5)",12.0,[Frutiger-Bold]
2,1.\t RECOMMENDATION ON BLOOD PRESSURE THRESHOL...,"(88.1, 152.4, 454.6, 163.9)",10.0,[Frutiger-Bold]
3,PHARMACOLOGICAL TREATMENT,"(102.3, 165.4, 259.8, 176.9)",10.0,[Frutiger-Bold]
4,WHO recommends initiation of pharmacological a...,"(88.1, 190.1, 512.7, 201.7)",10.0,[Frutiger-Roman]
5,with a confirmed diagnosis of hypertension and...,"(88.1, 203.1, 505.9, 215.5)",10.0,"[Frutiger-Roman, Symbol]"
6,diastolic blood pressure of ≥90 mmHg.,"(88.1, 216.1, 267.0, 228.5)",10.0,"[Frutiger-Roman, Symbol]"
7,"Strong recommendation, moderate- to high-certa...","(88.1, 241.0, 381.5, 252.5)",10.0,[Frutiger-Italic]
8,WHO recommends pharmacological antihypertensiv...,"(88.1, 265.7, 517.1, 277.3)",10.0,[Frutiger-Roman]
9,cardiovascular disease and systolic blood pres...,"(88.1, 278.7, 408.8, 290.3)",10.0,[Frutiger-Roman]
10,"Strong recommendation, moderate- to high-certa...","(88.1, 303.6, 381.5, 315.1)",10.0,[Frutiger-Italic]
11,WHO suggests pharmacological antihypertensive ...,"(88.1, 328.3, 474.3, 339.9)",10.0,[Frutiger-Roman]
12,cardiovascular disease but with high cardiovas...,"(88.1, 341.3, 518.2, 352.9)",10.0,[Frutiger-Roman]
13,"disease, and systolic blood pressure of 130–13...","(88.1, 354.3, 342.6, 365.9)",10.0,[Frutiger-Roman]
14,"Conditional recommendation, moderate- to high-...","(88.1, 379.1, 404.8, 390.7)",10.0,[Frutiger-Italic]
15,Implementation remarks:,"(88.1, 404.2, 194.6, 415.5)",10.0,[Frutiger-Light]
16,Initiation of pharmacological hypertension (HT...,"(106.1, 420.0, 491.0, 431.3)",10.0,[Frutiger-Light]
17,weeks following diagnosis of HTN. If blood pre...,"(106.1, 433.0, 504.7, 445.1)",10.0,"[Frutiger-Light, Symbol]"
18,diastolic ≥100 mmHg) or there is accompanying ...,"(106.1, 446.0, 502.6, 458.1)",10.0,"[Frutiger-Light, Symbol]"
19,treatment should be started without delay.,"(106.1, 459.0, 287.8, 470.3)",10.0,[Frutiger-Light]
20,Evidence and rationale,"(79.4, 497.2, 187.2, 508.8)",10.0,[Frutiger-Bold]
21,The GDG reviewed evidence from 14 relevant sys...,"(79.4, 519.9, 507.9, 531.2)",10.0,[Frutiger-Light]
22,number of randomized trials involving over 120...,"(79.4, 533.9, 490.9, 545.2)",10.0,[Frutiger-Light]
23,summaries are presented for the general popula...,"(79.4, 547.9, 526.9, 559.2)",10.0,[Frutiger-Light]
24,"coronary artery disease (CAD), prior stroke) a...","(79.4, 561.9, 522.3, 573.2)",10.0,[Frutiger-Light]
25,thresholds (Web Annex A).,"(79.4, 575.9, 193.5, 587.2)",10.0,[Frutiger-Light]
26,The anticipated benefits of a lower blood pres...,"(79.4, 595.6, 494.1, 606.9)",10.0,[Frutiger-Light]
27,and 130 SBP in a high-risk population) were re...,"(79.4, 609.6, 501.9, 620.9)",10.0,[Frutiger-Light]
28,myocardial infarction (MI) and heart failure e...,"(79.4, 623.6, 497.6, 634.9)",10.0,[Frutiger-Light]
29,"side-effects, and some were a surrogate outcom...","(79.4, 637.6, 510.3, 648.9)",10.0,[Frutiger-Light]
30,"relevant. On average, treatment was associated...","(79.4, 651.6, 509.8, 662.9)",10.0,[Frutiger-Light]
31,that ranged from 5 to 10/1000 and harms that r...,"(79.4, 665.6, 491.7, 676.9)",10.0,[Frutiger-Light]
32,reduction in severe events with significant mo...,"(79.4, 679.6, 518.1, 690.9)",10.0,[Frutiger-Light]
33,clinically significant.,"(79.4, 693.6, 166.0, 704.9)",10.0,[Frutiger-Light]
34,"In summary, the anticipated benefits were larg...","(79.4, 713.3, 523.3, 724.5)",10.0,[Frutiger-Light]
35,"varied from moderate to high, depending on the...","(79.4, 727.3, 393.7, 738.5)",10.0,[Frutiger-Light]

In [31]:
who_clean_text = "\n".join(
    line["text"]
    for line in who_clean_lines
)

print(who_clean_text)

3	 Recommendations
3.1	 Blood pressure threshold for initiation of pharmacological treatment
1.	 RECOMMENDATION ON BLOOD PRESSURE THRESHOLD FOR INITIATION OF
PHARMACOLOGICAL TREATMENT
WHO recommends initiation of pharmacological antihypertensive treatment of individuals
with a confirmed diagnosis of hypertension and systolic blood pressure of ≥140 mmHg or
diastolic blood pressure of ≥90 mmHg.
Strong recommendation, moderate- to high-certainty evidence
WHO recommends pharmacological antihypertensive treatment of individuals with existing
cardiovascular disease and systolic blood pressure of 130–139 mmHg.
Strong recommendation, moderate- to high-certainty evidence
WHO suggests pharmacological antihypertensive treatment of individuals without
cardiovascular disease but with high cardiovascular risk, diabetes mellitus, or chronic kidney
disease, and systolic blood pressure of 130–139 mmHg.
Conditional recommendation, moderate- to high-certainty evidence
Implementation remarks:
Initiation of pharmacological hypertension (HTN) treatment should start no later than four
weeks following diagnosis of HTN. If blood pressure level is high (e.g. systolic ≥160 mmHg or
diastolic ≥100 mmHg) or there is accompanying evidence of end organ damage, initiation of
treatment should be started without delay.
Evidence and rationale
The GDG reviewed evidence from 14 relevant systematic reviews that summarized data from a large
number of randomized trials involving over 120 000 adult participants (Web Annex A). Evidence
summaries are presented for the general population and for higher-risk populations (with diabetes (DM),
coronary artery disease (CAD), prior stroke) and were presented for various systolic blood pressure (SBP)
thresholds (Web Annex A).
The anticipated benefits of a lower blood pressure (BP) target (140 SBP in the general population
and 130 SBP in a high-risk population) were reduction in mortality, cardiovascular mortality, stroke,
myocardial infarction (MI) and heart failure events. The anticipated harms were mostly not serious
side-effects, and some were a surrogate outcome, such as rise in creatinine that may not be clinically
relevant. On average, treatment was associated with a reduction in deaths and cardiovascular events
that ranged from 5 to 10/1000 and harms that ranged from 20 to 30/1000. The benefits were a
reduction in severe events with significant morbidity and mortality whereas the harms were mostly not
clinically significant.
In summary, the anticipated benefits were large and clearly outweighed the harms. The overall certainty
varied from moderate to high, depending on the BP level and agent used.

## 8. Восстановление структуры WHO

Для WHO основные разделы имеют явную числовую иерархию (`3`, `3.1`, `3.2`, ...).

Будем использовать такие нумерованные заголовки для формирования `section_path`. Внутренние элементы вроде `Evidence and rationale` и `Implementation remarks` сохраняются в тексте, но не создают отдельный уровень metadata.

In [32]:
WHO_SECTION_PATTERN = re.compile(
    r"^(\d+(?:\.\d+)*)\s+(.+)$"
)


def get_who_section_heading(line):
    text = re.sub(r"\s+", " ", line["text"]).strip()

    if "Frutiger-Bold" not in line["fonts"]:
        return None

    match = WHO_SECTION_PATTERN.match(text)

    if not match:
        return None

    section_number = match.group(1)
    section_title = match.group(2)

    return {
        "number": section_number,
        "title": section_title,
    }

In [33]:
def merge_who_heading_lines(lines):
    merged = []
    i = 0

    while i < len(lines):
        line = lines[i].copy()

        heading = get_who_section_heading(line)

        # Объединяем только крупные top-level headings:
        # 2 Method for developing the
        # guideline
        if (
            heading is not None
            and "." not in heading["number"]
        ):
            while i + 1 < len(lines):
                next_line = lines[i + 1]

                next_heading = get_who_section_heading(
                    next_line
                )

                same_size = (
                    abs(
                        next_line["font_size"]
                        - line["font_size"]
                    )
                    <= 0.3
                )

                current_bold = any(
                    "bold" in font.lower()
                    for font in line["fonts"]
                )

                next_bold = any(
                    "bold" in font.lower()
                    for font in next_line["fonts"]
                )

                vertical_gap = (
                    next_line["bbox"][1]
                    - line["bbox"][3]
                )

                close_alignment = (
                    next_line["bbox"][0]
                    <= line["bbox"][0] + 60
                )

                if not (
                    next_heading is None
                    and same_size
                    and current_bold
                    and next_bold
                    and vertical_gap <= 5
                    and close_alignment
                ):
                    break

                line["text"] = re.sub(
                    r"\s+",
                    " ",
                    (
                        f'{line["text"]} '
                        f'{next_line["text"]}'
                    ),
                ).strip()

                line["bbox"] = (
                    min(
                        line["bbox"][0],
                        next_line["bbox"][0],
                    ),
                    min(
                        line["bbox"][1],
                        next_line["bbox"][1],
                    ),
                    max(
                        line["bbox"][2],
                        next_line["bbox"][2],
                    ),
                    max(
                        line["bbox"][3],
                        next_line["bbox"][3],
                    ),
                )

                line["fonts"] = sorted(
                    set(line["fonts"])
                    | set(next_line["fonts"])
                )

                i += 1

        merged.append(line)
        i += 1

    return merged

In [34]:
who_clean_lines = clean_who_lines(who_pages[18])

for line in who_clean_lines:
    heading = get_who_section_heading(line)

    if heading:
        print(heading)

{'number': '3', 'title': 'Recommendations'}
{'number': '3.1', 'title': 'Blood pressure threshold for initiation of pharmacological treatment'}

## 9. Структурированный parser WHO

Parser проходит документ последовательно по страницам и поддерживает текущую иерархию разделов.

При появлении нового нумерованного заголовка обновляется `section_path`. Текст между заголовками сохраняется как отдельный структурированный фрагмент вместе с информацией об источнике и странице.

Это ещё не финальные chunks для retrieval: сначала проверяется корректность структуры документа.

In [35]:
def build_section_path(section_stack):
    return " > ".join(
        section_stack[level]
        for level in sorted(section_stack)
    )

In [36]:
def get_references_start_page(path):
    with pymupdf.open(path) as doc:
        toc = doc.get_toc()

    for level, title, pdf_page in toc:
        if title.strip().lower() == "references":
            return pdf_page

    return None

In [37]:
def get_who_body_start_page(path):
    with pymupdf.open(path) as doc:
        toc = doc.get_toc()

    section_pages = []

    for level, title, pdf_page in toc:
        title = re.sub(
            r"\s+",
            " ",
            title,
        ).strip()

        match = WHO_SECTION_PATTERN.match(title)

        if not match:
            continue

        section_number = match.group(1)

        # Нас интересуют только разделы верхнего уровня:
        # 1 Introduction, 2 Method..., 3 Recommendations...
        if "." not in section_number:
            section_pages.append(pdf_page)

    if not section_pages:
        return None

    return min(section_pages)

In [38]:
get_who_body_start_page(who_path)

13

In [39]:
def parse_who(path):
    pages = extract_document_pages(path)
    metadata = DOCUMENT_METADATA[path.name]

    body_start = get_who_body_start_page(path)
    references_start = get_references_start_page(path)

    section_stack = {}
    records = []
    started = False

    for page_data in pages:
        # Не читаем title pages / licence / contents.
        if (
            body_start is not None
            and page_data["pdf_page"] < body_start
        ):
            continue

        if (
            references_start is not None
            and page_data["pdf_page"] >= references_start
        ):
            break

        lines = clean_who_lines(page_data)

        lines = merge_who_heading_lines(
            lines
        )

        current_text = []

        def flush_text():
            if not current_text:
                return

            if not started:
                current_text.clear()
                return

            text = clean_page_text(
                "\n".join(current_text)
            )

            if text:
                records.append(
                    {
                        "document_id": page_data["document_id"],
                        "source": metadata["source"],
                        "document_title": metadata["document_title"],
                        "year": metadata["year"],
                        "section_path": build_section_path(
                            section_stack
                        ),
                        "page": page_data["page"],
                        "pdf_page": page_data["pdf_page"],
                        "text": text,
                    }
                )

            current_text.clear()

        for line in lines:
            heading = get_who_section_heading(line)

            if heading:
                flush_text()

                started = True

                depth = len(
                    heading["number"].split(".")
                )

                section_stack[depth] = (
                    f'{heading["number"]} '
                    f'{heading["title"]}'
                )

                for level in list(section_stack):
                    if level > depth:
                        del section_stack[level]

                continue

            current_text.append(
                line["text"]
            )

        flush_text()

    return records

In [40]:
who_records = parse_who(who_path)

len(who_records)

42

In [41]:
who_records_df = pd.DataFrame(who_records)

who_records_df[
    who_records_df["section_path"].str.contains(
        "Blood pressure threshold",
        case=False,
        na=False,
    )
][
    ["page", "pdf_page", "section_path", "text"]
]

,page,pdf_page,section_path,text
9,7,19,3 Recommendations > 3.1 Blood pressure thresho...,1.\t RECOMMENDATION ON BLOOD PRESSURE THRESHOL...
10,8,20,3 Recommendations > 3.1 Blood pressure thresho...,Evidence-to-decision considerations\nThe value...

In [42]:
record = who_records_df[
    who_records_df["section_path"].str.contains(
        "Blood pressure threshold",
        case=False,
        na=False,
    )
].iloc[0]

print("page:", record["page"])
print("pdf_page:", record["pdf_page"])
print("section:", record["section_path"])
print()
print(record["text"][:3000])

page: 7
pdf_page: 19
section: 3 Recommendations > 3.1 Blood pressure threshold for initiation of pharmacological treatment

1.	 RECOMMENDATION ON BLOOD PRESSURE THRESHOLD FOR INITIATION OF
PHARMACOLOGICAL TREATMENT
WHO recommends initiation of pharmacological antihypertensive treatment of individuals
with a confirmed diagnosis of hypertension and systolic blood pressure of ≥140 mmHg or
diastolic blood pressure of ≥90 mmHg.
Strong recommendation, moderate- to high-certainty evidence
WHO recommends pharmacological antihypertensive treatment of individuals with existing
cardiovascular disease and systolic blood pressure of 130–139 mmHg.
Strong recommendation, moderate- to high-certainty evidence
WHO suggests pharmacological antihypertensive treatment of individuals without
cardiovascular disease but with high cardiovascular risk, diabetes mellitus, or chronic kidney
disease, and systolic blood pressure of 130–139 mmHg.
Conditional recommendation, moderate- to high-certainty evidence
Implementation remarks:
Initiation of pharmacological hypertension (HTN) treatment should start no later than four
weeks following diagnosis of HTN. If blood pressure level is high (e.g. systolic ≥160 mmHg or
diastolic ≥100 mmHg) or there is accompanying evidence of end organ damage, initiation of
treatment should be started without delay.
Evidence and rationale
The GDG reviewed evidence from 14 relevant systematic reviews that summarized data from a large
number of randomized trials involving over 120 000 adult participants (Web Annex A). Evidence
summaries are presented for the general population and for higher-risk populations (with diabetes (DM),
coronary artery disease (CAD), prior stroke) and were presented for various systolic blood pressure (SBP)
thresholds (Web Annex A).
The anticipated benefits of a lower blood pressure (BP) target (140 SBP in the general population
and 130 SBP in a high-risk population) were reduction in mortality, cardiovascular mortality, stroke,
myocardial infarction (MI) and heart failure events. The anticipated harms were mostly not serious
side-effects, and some were a surrogate outcome, such as rise in creatinine that may not be clinically
relevant. On average, treatment was associated with a reduction in deaths and cardiovascular events
that ranged from 5 to 10/1000 and harms that ranged from 20 to 30/1000. The benefits were a
reduction in severe events with significant morbidity and mortality whereas the harms were mostly not
clinically significant.
In summary, the anticipated benefits were large and clearly outweighed the harms. The overall certainty
varied from moderate to high, depending on the BP level and agent used.

## 10. Parser для CDC

CDC содержит полезные bookmarks для крупных тематических разделов. Внутренние подразделы, например `Follow-Up` и `Management of Sex Partners`, выделяются шрифтом `MyriadPro-Semibold`.

Перед построением parser необходимо проверить порядок извлечения текста на странице, поскольку журнальная верстка может содержать несколько колонок.

In [43]:
cdc_pages = extract_document_pages(cdc_path)

cdc_page = cdc_pages[66]  # pdf_page = 67

pd.DataFrame(cdc_page["lines"])[
    ["text", "bbox", "font_size", "fonts"]
].head(40)

,text,bbox,font_size,fonts
0,Recommendations and Reports,"(246.9, 34.2, 365.1, 45.0)",9.0,[MyriadPro-Regular]
1,reduces HIV shedding from the cervix and there...,"(318.6, 69.9, 578.9, 83.9)",11.0,[AGaramondPro-Regular]
2,reduce HIV transmission to susceptible sex par...,"(318.6, 82.9, 576.0, 96.9)",11.0,"[AGaramondPro-Italic, AGaramondPro-Regular]"
3,Pregnancy,"(318.6, 102.5, 369.2, 115.9)",11.0,[MyriadPro-Semibold]
4,Diagnosis and treatment of cervicitis for preg...,"(327.6, 119.7, 578.8, 133.7)",11.0,[AGaramondPro-Regular]
5,does not differ from that for women who are no...,"(318.6, 132.7, 578.8, 146.7)",11.0,[AGaramondPro-Regular]
6,Diagnostic Considerations; Treatment).,"(318.6, 145.7, 486.3, 159.7)",11.0,[AGaramondPro-Regular]
7,cervicitis has resolved. Women with a specific...,"(36.0, 69.9, 296.1, 83.9)",11.0,[AGaramondPro-Regular]
8,"chlamydia, gonorrhea, or trichomoniasis should...","(36.0, 82.9, 296.1, 96.9)",11.0,[AGaramondPro-Regular]
9,partner services and instructed to return in 3...,"(36.0, 95.9, 296.2, 109.9)",11.0,[AGaramondPro-Regular]
10,treatment for repeat testing because of high r...,"(36.0, 108.9, 295.9, 122.9)",11.0,[AGaramondPro-Regular]
11,regardless of whether their sex partners were ...,"(36.0, 121.9, 296.1, 135.9)",11.0,"[AGaramondPro-Italic, AGaramondPro-Regular]"
12,"symptoms persist or recur, women should be ins...","(36.0, 134.9, 296.0, 148.9)",11.0,[AGaramondPro-Regular]
13,return for reevaluation.,"(36.0, 147.9, 134.3, 161.9)",11.0,[AGaramondPro-Regular]
14,Contraceptive Management,"(318.6, 165.3, 451.3, 178.7)",11.0,[MyriadPro-Semibold]
15,Management of Sex Partners,"(36.0, 167.5, 185.5, 182.2)",12.0,[MyriadPro-Semibold]
16,According to U.S. Medical Eligibility Criteria...,"(327.6, 182.5, 578.6, 196.5)",11.0,"[AGaramondPro-Italic, AGaramondPro-Regular]"
17,"Use, 2016, leaving an IUD in place during trea...","(318.6, 195.5, 578.8, 209.5)",11.0,"[AGaramondPro-Italic, AGaramondPro-Regular]"
18,"cervicitis is advisable (58). However, current...","(318.6, 208.5, 578.7, 222.5)",11.0,"[AGaramondPro-Italic, AGaramondPro-Regular]"
19,specify that an IUD should not be placed if ac...,"(318.6, 221.5, 578.8, 235.5)",11.0,[AGaramondPro-Regular]
20,is diagnosed (59).,"(318.6, 234.5, 393.7, 248.5)",11.0,"[AGaramondPro-Italic, AGaramondPro-Regular]"
21,Chlamydial Infections,"(372.6, 268.6, 522.0, 288.2)",16.0,[MyriadPro-Semibold]
22,Chlamydial Infection Among,"(361.1, 293.8, 536.4, 310.9)",14.0,[MyriadPro-Semibold]
23,Management of sex partners of women treated fo...,"(45.0, 185.7, 296.1, 199.7)",11.0,[AGaramondPro-Regular]
24,should be tailored for the specific infection ...,"(36.0, 198.7, 296.2, 212.7)",11.0,[AGaramondPro-Regular]
25,suspected. All sex partners during the previou...,"(36.0, 211.7, 296.1, 225.7)",11.0,[AGaramondPro-Regular]
26,"be referred for evaluation, testing, and presu...","(36.0, 224.7, 296.1, 238.7)",11.0,[AGaramondPro-Regular]
27,"if chlamydia, gonorrhea, or trichomoniasis was...","(36.0, 237.7, 296.3, 251.7)",11.0,[AGaramondPro-Regular]
28,and other effective partner referral strategie...,"(36.0, 250.7, 296.2, 264.7)",11.0,[AGaramondPro-Regular]
29,approaches for treating male partners of women...,"(36.0, 263.7, 296.1, 277.7)",11.0,[AGaramondPro-Regular]
30,chlamydial or gonococcal infection (125–127) (...,"(36.0, 276.7, 296.1, 290.7)",11.0,"[AGaramondPro-Italic, AGaramondPro-Regular]"
31,"Services). To avoid reinfection, sex partners ...","(36.0, 289.7, 296.3, 303.7)",11.0,[AGaramondPro-Regular]
32,from sexual intercourse until they and their p...,"(36.0, 302.7, 293.4, 316.7)",11.0,[AGaramondPro-Regular]
33,Adolescents and Adults,"(376.4, 309.8, 518.2, 326.9)",14.0,[MyriadPro-Semibold]
34,Persistent or Recurrent Cervicitis,"(36.0, 322.3, 204.2, 337.0)",12.0,[MyriadPro-Semibold]
35,Chlamydial infection is the most frequently re...,"(327.6, 329.9, 578.6, 343.9)",11.0,[AGaramondPro-Regular]
36,bacterial infectious disease in the United Sta...,"(318.6, 342.9, 578.8, 356.9)",11.0,[AGaramondPro-Regular]
37,"is highest among persons aged ≤24 years (141,7...","(318.6, 355.9, 578.7, 369.9)",11.0,"[AGaramondPro-Italic, AGaramondPro-Regular]"
38,sequelae can result from C. trachomatis infect...,"(318.6, 368.9, 578.7, 382.9)",11.0,"[AGaramondPro-Italic, AGaramondPro-Regular]"
39,"women, the most serious of which include PID, ...","(318.6, 381.9, 578.9, 395.9)",11.0,[AGaramondPro-Regular]

### Порядок чтения CDC

Документ CDC использует двухколоночную верстку. Стандартное извлечение с `sort=True` не всегда восстанавливает правильный порядок чтения и может чередовать строки из левой и правой колонок.

Поэтому для CDC порядок текста восстанавливается явно: сначала строки левой колонки сверху вниз, затем строки правой колонки сверху вниз. Служебные элементы header/footer удаляются отдельно.

In [44]:
def clean_and_order_cdc_lines(page_data):
    clean_lines = []

    width = page_data["width"]
    height = page_data["height"]
    middle = width / 2

    for line in page_data["lines"]:
        x0, y0, x1, y1 = line["bbox"]

        text = re.sub(r"\s+", " ", line["text"]).strip()

        if not text:
            continue

        # Повторяющиеся элементы MMWR
        if text == "Recommendations and Reports":
            continue

        if text.startswith("MMWR"):
            continue

        if text.startswith(
            "US Department of Health and Human Services"
        ):
            continue

        # Номер страницы в header/footer
        if (
            re.fullmatch(r"\d+", text)
            and (y0 < 60 or y0 > 0.9 * height)
        ):
            continue

        column = "left" if x0 < middle else "right"

        clean_lines.append(
            {
                **line,
                "text": text,
                "column": column,
            }
        )

    clean_lines.sort(
        key=lambda line: (
            0 if line["column"] == "left" else 1,
            line["bbox"][1],
            line["bbox"][0],
        )
    )

    return clean_lines

In [45]:
cdc_clean_lines = clean_and_order_cdc_lines(
    cdc_pages[66]
)

pd.DataFrame(cdc_clean_lines)[
    ["text", "column", "bbox", "font_size", "fonts"]
].head(50)

,text,column,bbox,font_size,fonts
0,cervicitis has resolved. Women with a specific...,left,"(36.0, 69.9, 296.1, 83.9)",11.0,[AGaramondPro-Regular]
1,"chlamydia, gonorrhea, or trichomoniasis should...",left,"(36.0, 82.9, 296.1, 96.9)",11.0,[AGaramondPro-Regular]
2,partner services and instructed to return in 3...,left,"(36.0, 95.9, 296.2, 109.9)",11.0,[AGaramondPro-Regular]
3,treatment for repeat testing because of high r...,left,"(36.0, 108.9, 295.9, 122.9)",11.0,[AGaramondPro-Regular]
4,regardless of whether their sex partners were ...,left,"(36.0, 121.9, 296.1, 135.9)",11.0,"[AGaramondPro-Italic, AGaramondPro-Regular]"
5,"symptoms persist or recur, women should be ins...",left,"(36.0, 134.9, 296.0, 148.9)",11.0,[AGaramondPro-Regular]
6,return for reevaluation.,left,"(36.0, 147.9, 134.3, 161.9)",11.0,[AGaramondPro-Regular]
7,Management of Sex Partners,left,"(36.0, 167.5, 185.5, 182.2)",12.0,[MyriadPro-Semibold]
8,Management of sex partners of women treated fo...,left,"(45.0, 185.7, 296.1, 199.7)",11.0,[AGaramondPro-Regular]
9,should be tailored for the specific infection ...,left,"(36.0, 198.7, 296.2, 212.7)",11.0,[AGaramondPro-Regular]
10,suspected. All sex partners during the previou...,left,"(36.0, 211.7, 296.1, 225.7)",11.0,[AGaramondPro-Regular]
11,"be referred for evaluation, testing, and presu...",left,"(36.0, 224.7, 296.1, 238.7)",11.0,[AGaramondPro-Regular]
12,"if chlamydia, gonorrhea, or trichomoniasis was...",left,"(36.0, 237.7, 296.3, 251.7)",11.0,[AGaramondPro-Regular]
13,and other effective partner referral strategie...,left,"(36.0, 250.7, 296.2, 264.7)",11.0,[AGaramondPro-Regular]
14,approaches for treating male partners of women...,left,"(36.0, 263.7, 296.1, 277.7)",11.0,[AGaramondPro-Regular]
15,chlamydial or gonococcal infection (125–127) (...,left,"(36.0, 276.7, 296.1, 290.7)",11.0,"[AGaramondPro-Italic, AGaramondPro-Regular]"
16,"Services). To avoid reinfection, sex partners ...",left,"(36.0, 289.7, 296.3, 303.7)",11.0,[AGaramondPro-Regular]
17,from sexual intercourse until they and their p...,left,"(36.0, 302.7, 293.4, 316.7)",11.0,[AGaramondPro-Regular]
18,Persistent or Recurrent Cervicitis,left,"(36.0, 322.3, 204.2, 337.0)",12.0,[MyriadPro-Semibold]
19,Women with persistent or recurrent cervicitis ...,left,"(45.0, 340.5, 296.3, 354.5)",11.0,[AGaramondPro-Regular]
20,antimicrobial therapy should be reevaluated fo...,left,"(36.0, 353.5, 296.3, 367.5)",11.0,[AGaramondPro-Regular]
21,reexposure or treatment failure. If relapse or...,left,"(36.0, 366.5, 296.2, 380.5)",11.0,[AGaramondPro-Regular]
22,"a specific infection has been excluded, BV is ...",left,"(36.0, 379.5, 296.1, 393.5)",11.0,[AGaramondPro-Regular]
23,"sex partners have been evaluated and treated, ...",left,"(36.0, 392.5, 296.1, 406.5)",11.0,[AGaramondPro-Regular]
24,options for persistent cervicitis are undefine...,left,"(36.0, 405.5, 296.0, 419.5)",11.0,[AGaramondPro-Regular]
25,the usefulness of repeated or prolonged admini...,left,"(36.0, 418.5, 296.2, 432.5)",11.0,[AGaramondPro-Regular]
26,antimicrobial therapy for persistent symptomat...,left,"(36.0, 431.5, 296.0, 445.5)",11.0,[AGaramondPro-Regular]
27,remains unknown. The etiology of persistent ce...,left,"(36.0, 444.5, 296.1, 458.5)",11.0,[AGaramondPro-Regular]
28,including the potential role of M. genitalium ...,left,"(36.0, 457.5, 296.2, 471.5)",11.0,"[AGaramondPro-Italic, AGaramondPro-Regular]"
29,M. genitalium might be considered for cases of...,left,"(36.0, 470.5, 296.2, 484.5)",11.0,"[AGaramondPro-Italic, AGaramondPro-Regular]"
30,persist after azithromycin or doxycycline ther...,left,"(36.0, 483.5, 296.0, 497.5)",11.0,[AGaramondPro-Regular]
31,reexposure to an infected partner or medical n...,left,"(36.0, 496.5, 296.1, 510.5)",11.0,[AGaramondPro-Regular]
32,unlikely. Among women with persistent cervicit...,left,"(36.0, 509.5, 296.2, 523.5)",11.0,[AGaramondPro-Regular]
33,previously treated with doxycycline or azithro...,left,"(36.0, 522.5, 296.2, 536.5)",11.0,[AGaramondPro-Regular]
34,for M. genitalium can be considered and treatm...,left,"(36.0, 535.5, 296.3, 549.5)",11.0,"[AGaramondPro-Italic, AGaramondPro-Regular]"
35,the basis of results of diagnostic testing (31...,left,"(36.0, 548.5, 296.2, 562.5)",11.0,"[AGaramondPro-Italic, AGaramondPro-Regular]"
36,genitalium). For women with persistent symptom...,left,"(36.0, 561.5, 296.0, 575.5)",11.0,"[AGaramondPro-Italic, AGaramondPro-Regular]"
37,"clearly attributable to cervicitis, referral t...",left,"(36.0, 574.5, 296.0, 588.5)",11.0,[AGaramondPro-Regular]
38,specialist can be considered for evaluation of...,left,"(36.0, 587.5, 296.1, 601.5)",11.0,[AGaramondPro-Regular]
39,"causes (e.g., cervical dysplasia or polyps) (7...",left,"(36.0, 600.5, 235.1, 614.5)",11.0,"[AGaramondPro-Italic, AGaramondPro-Regular]"
40,Special Considerations,left,"(36.0, 620.1, 153.4, 634.8)",12.0,[MyriadPro-Semibold]
41,HIV Infection,left,"(36.0, 641.3, 97.8, 654.7)",11.0,[MyriadPro-Semibold]
42,Women with cervicitis and HIV infection should...,left,"(45.0, 658.5, 296.1, 672.5)",11.0,[AGaramondPro-Regular]
43,the same treatment regimen as those who do not...,left,"(36.0, 671.5, 296.1, 685.5)",11.0,[AGaramondPro-Regular]
44,"Cervicitis can increase cervical HIV shedding,...",left,"(36.0, 684.5, 296.2, 698.5)",11.0,[AGaramondPro-Regular]
45,reduces HIV shedding from the cervix and there...,right,"(318.6, 69.9, 578.9, 83.9)",11.0,[AGaramondPro-Regular]
46,reduce HIV transmission to susceptible sex par...,right,"(318.6, 82.9, 576.0, 96.9)",11.0,"[AGaramondPro-Italic, AGaramondPro-Regular]"
47,Pregnancy,right,"(318.6, 102.5, 369.2, 115.9)",11.0,[MyriadPro-Semibold]
48,Diagnosis and treatment of cervicitis for preg...,right,"(327.6, 119.7, 578.8, 133.7)",11.0,[AGaramondPro-Regular]
49,does not differ from that for women who are no...,right,"(318.6, 132.7, 578.8, 146.7)",11.0,[AGaramondPro-Regular]

Порядок чтения после явного разделения на колонки восстановлен корректно.

На одной физической странице могут одновременно находиться конец предыдущего раздела и начало нового. Поэтому `section_path` должен обновляться в момент появления заголовка внутри последовательности строк, а не назначаться целиком по номеру страницы.

In [46]:
def get_cdc_major_headings(path):
    with pymupdf.open(path) as doc:
        toc = doc.get_toc()

    return {
        (
            pdf_page,
            re.sub(r"\s+", " ", title).strip(),
        )
        for level, title, pdf_page in toc
        if level == 1
        and title.strip()
        and title != "References"
        and not title.startswith(
            "Sexually Transmitted Infections Treatment Guidelines"
        )
    }


CDC_MAJOR_HEADINGS = get_cdc_major_headings(cdc_path)

In [47]:
def normalize_cdc_text(text):
    return re.sub(r"\s+", " ", text).strip()


CDC_MAJOR_BY_PAGE = {}

for pdf_page, title in CDC_MAJOR_HEADINGS:
    CDC_MAJOR_BY_PAGE.setdefault(
        pdf_page,
        set(),
    ).add(title)

In [48]:
page_82_lines = clean_and_order_cdc_lines(
    cdc_pages[81]
)

[
    line
    for line in page_82_lines
    if "mycoplasma" in line["text"].lower()
    or "genitalium" in line["text"].lower()
]

[{'text': 'Mycoplasma genitalium',
  'bbox': (366.8, 360.0, 527.8, 379.5),
  'font_size': 16.0,
  'fonts': ['MyriadPro-SemiboldIt'],
  'column': 'right'},
 {'text': 'M. genitalium causes symptomatic and asymptomatic',
  'bbox': (327.6, 382.0, 578.7, 396.0),
  'font_size': 11.0,
  'fonts': ['AGaramondPro-Italic', 'AGaramondPro-Regular'],
  'column': 'right'},
 {'text': 'areas (911–913), although M. genitalium is often the sole',
  'bbox': (318.6, 447.0, 578.8, 461.0),
  'font_size': 11.0,
  'fonts': ['AGaramondPro-Italic', 'AGaramondPro-Regular'],
  'column': 'right'},
 {'text': 'pathogen. Data are insufficient to implicate M. genitalium',
  'bbox': (318.6, 460.0, 578.8, 474.0),
  'font_size': 11.0,
  'fonts': ['AGaramondPro-Italic', 'AGaramondPro-Regular'],
  'column': 'right'},
 {'text': 'of asymptomatic infection with M. genitalium among men',
  'bbox': (318.6, 499.0, 578.7, 513.0),
  'font_size': 11.0,
  'fonts': ['AGaramondPro-Italic', 'AGaramondPro-Regular'],
  'column': 'right'},
 {'text': 'Among women, M. genitalium has been associated with',
  'bbox': (327.6, 525.0, 578.6, 539.0),
  'font_size': 11.0,
  'fonts': ['AGaramondPro-Italic', 'AGaramondPro-Regular'],
  'column': 'right'},
 {'text': 'for these outcomes among women infected with M. genitalium',
  'bbox': (318.6, 564.0, 578.8, 578.0),
  'font_size': 11.0,
  'fonts': ['AGaramondPro-Italic', 'AGaramondPro-Regular'],
  'column': 'right'},
 {'text': '(766). M. genitalium infections among women are also',
  'bbox': (318.6, 577.0, 578.8, 591.0),
  'font_size': 11.0,
  'fonts': ['AGaramondPro-Italic', 'AGaramondPro-Regular'],
  'column': 'right'},
 {'text': 'with asymptomatic M. genitalium infection are unknown.',
  'bbox': (318.6, 603.0, 563.6, 617.0),
  'font_size': 11.0,
  'fonts': ['AGaramondPro-Italic', 'AGaramondPro-Regular'],
  'column': 'right'},
 {'text': 'M. genitalium can be detected among 10%–30% of women',
  'bbox': (327.6, 616.0, 578.7, 630.0),
  'font_size': 11.0,
  'fonts': ['AGaramondPro-Italic', 'AGaramondPro-Regular'],
  'column': 'right'},
 {'text': 'evidence between M. genitalium and cervicitis is mostly',
  'bbox': (318.6, 642.0, 578.7, 656.0),
  'font_size': 11.0,
  'fonts': ['AGaramondPro-Italic', 'AGaramondPro-Regular'],
  'column': 'right'},
 {'text': 'M. genitalium, with return to baseline levels after clearance of',
  'bbox': (318.6, 681.0, 578.8, 695.0),
  'font_size': 11.0,
  'fonts': ['AGaramondPro-Italic', 'AGaramondPro-Regular'],
  'column': 'right'}]

In [49]:
def is_cdc_semibold(line):
    return any(
        font.startswith("MyriadPro-Semibold")
        for font in line["fonts"]
    )

In [50]:
def match_cdc_major_heading(
    lines,
    start,
    pdf_page,
    max_lines=6,
):
    targets = CDC_MAJOR_BY_PAGE.get(
        pdf_page,
        set(),
    )

    if not targets:
        return None

    first_column = lines[start]["column"]
    parts = []

    for j in range(
        start,
        min(start + max_lines, len(lines)),
    ):
        line = lines[j]

        if line["column"] != first_column:
            break

        if not is_cdc_semibold(line):
            break

        parts.append(line["text"])

        candidate = normalize_cdc_text(
            " ".join(parts)
        )

        if candidate in targets:
            return {
                "title": candidate,
                "end": j + 1,
            }

        if not any(
            target.startswith(candidate)
            for target in targets
        ):
            break

    return None

In [51]:
def merge_cdc_heading_lines(lines, pdf_page):
    merged = []
    i = 0

    while i < len(lines):
        major_heading = match_cdc_major_heading(
            lines,
            i,
            pdf_page,
        )

        if major_heading is not None:
            line = lines[i].copy()
            line["text"] = major_heading["title"]
            line["heading_level"] = 1

            merged.append(line)
            i = major_heading["end"]
            continue

        line = lines[i].copy()

        if not is_cdc_semibold(line):
            merged.append(line)
            i += 1
            continue

        size = line["font_size"]

        if size >= 13.5:
            level = 2
        elif size >= 11.5:
            level = 3
        elif size >= 10.5:
            level = 4
        else:
            merged.append(line)
            i += 1
            continue

        parts = [line["text"]]
        current_bottom = line["bbox"][3]
        column = line["column"]

        j = i + 1

        while j < len(lines):
            next_line = lines[j]

            if next_line["column"] != column:
                break

            if not is_cdc_semibold(next_line):
                break

            next_size = next_line["font_size"]

            if level == 2:
                same_level = next_size >= 13.5
            elif level == 3:
                same_level = 11.5 <= next_size < 13.5
            else:
                same_level = 10.5 <= next_size < 11.5

            if not same_level:
                break

            vertical_gap = (
                next_line["bbox"][1]
                - current_bottom
            )

            if vertical_gap > 5:
                break

            parts.append(next_line["text"])
            current_bottom = next_line["bbox"][3]
            j += 1

        line["text"] = normalize_cdc_text(
            " ".join(parts)
        )
        line["heading_level"] = level

        merged.append(line)
        i = j

    return merged

In [52]:
cdc_structured_lines = merge_cdc_heading_lines(
    cdc_clean_lines,
    cdc_pages[66]["pdf_page"],
)

for line in cdc_structured_lines:
    if line.get("heading_level") is not None:
        print(
            line["heading_level"],
            "|",
            line["text"],
        )

3 | Management of Sex Partners
3 | Persistent or Recurrent Cervicitis
3 | Special Considerations
4 | HIV Infection
4 | Pregnancy
4 | Contraceptive Management
1 | Chlamydial Infections
2 | Chlamydial Infection Among Adolescents and Adults

In [53]:
def parse_cdc(path):
    pages = extract_document_pages(path)
    metadata = DOCUMENT_METADATA[path.name]

    references_start = get_references_start_page(path)

    section_stack = {}
    records = []
    started = False

    for page_data in pages:
        if (
            references_start is not None
            and page_data["pdf_page"] >= references_start
        ):
            break

        lines = clean_and_order_cdc_lines(
            page_data
        )

        lines = merge_cdc_heading_lines(
            lines,
            page_data["pdf_page"],
        )

        current_text = []

        def flush_text():
            if not current_text:
                return

            if not started:
                current_text.clear()
                return

            text = " ".join(current_text)

            text = re.sub(
                r"\s+",
                " ",
                text,
            ).strip()

            text = re.sub(
                r"-\s+(?=\w)",
                "-",
                text,
            )

            if text:
                records.append(
                    {
                        "document_id": page_data["document_id"],
                        "source": metadata["source"],
                        "document_title": metadata["document_title"],
                        "year": metadata["year"],
                        "section_path": build_section_path(
                            section_stack
                        ),
                        "page": page_data["page"],
                        "pdf_page": page_data["pdf_page"],
                        "text": text,
                    }
                )

            current_text.clear()

        for line in lines:
            level = line.get("heading_level")

            if level is not None:
                flush_text()

                started = True

                section_stack[level] = line["text"]

                for existing_level in list(
                    section_stack
                ):
                    if existing_level > level:
                        del section_stack[
                            existing_level
                        ]

                continue

            current_text.append(
                line["text"]
            )

        flush_text()

    return records

In [54]:
cdc_records = parse_cdc(cdc_path)

len(cdc_records)

599

In [55]:
cdc_records_df = pd.DataFrame(cdc_records)

cdc_records_df[
    cdc_records_df["pdf_page"].isin([66, 67, 68])
][
    ["page", "pdf_page", "section_path", "text"]
]

,page,pdf_page,section_path,text
292,64,66,Diseases Characterized by Urethritis and Cervi...,2) sustained endocervical bleeding easily indu...
293,64,66,Diseases Characterized by Urethritis and Cervi...,C. trachomatis or N. gonorrhoeae is the most c...
294,64,66,Diseases Characterized by Urethritis and Cervi...,Because cervicitis might be a sign of upper ge...
295,64,66,Diseases Characterized by Urethritis and Cervi...,Multiple factors should affect the decision to...
296,64,66,Diseases Characterized by Urethritis and Cervi...,Doxycycline 100 mg orally 2 times/day for 7 da...
297,64,66,Diseases Characterized by Urethritis and Cervi...,"To minimize transmission and reinfection, wome..."
298,64,66,Diseases Characterized by Urethritis and Cervi...,Women receiving treatment should return to the...
299,65,67,Diseases Characterized by Urethritis and Cervi...,cervicitis has resolved. Women with a specific...
300,65,67,Diseases Characterized by Urethritis and Cervi...,Management of sex partners of women treated fo...
301,65,67,Diseases Characterized by Urethritis and Cervi...,Women with persistent or recurrent cervicitis ...
302,65,67,Diseases Characterized by Urethritis and Cervi...,Women with cervicitis and HIV infection should...
303,65,67,Diseases Characterized by Urethritis and Cervi...,Diagnosis and treatment of cervicitis for preg...
304,65,67,Diseases Characterized by Urethritis and Cervi...,According to U.S. Medical Eligibility Criteria...
305,65,67,Chlamydial Infections > Chlamydial Infection A...,Chlamydial infection is the most frequently re...
306,66,68,Chlamydial Infections > Chlamydial Infection A...,clinics) or for populations with a high burden...
307,66,68,Chlamydial Infections > Chlamydial Infection A...,"For women, C. trachomatis urogenital infection..."
308,66,68,Chlamydial Infections > Chlamydial Infection A...,Treating persons with C. trachomatis prevents ...

In [56]:
cdc_records_df[
    cdc_records_df["section_path"].str.contains(
        "Chlamydial Infections",
        case=False,
        na=False,
    )
][
    ["page", "pdf_page", "section_path"]
].drop_duplicates().head(20)

    page  pdf_page                                       section_path
305   65        67  Chlamydial Infections > Chlamydial Infection A...
306   66        68  Chlamydial Infections > Chlamydial Infection A...
307   66        68  Chlamydial Infections > Chlamydial Infection A...
308   66        68  Chlamydial Infections > Chlamydial Infection A...
309   67        69  Chlamydial Infections > Chlamydial Infection A...
310   67        69  Chlamydial Infections > Chlamydial Infection A...
311   67        69  Chlamydial Infections > Chlamydial Infection A...
312   67        69  Chlamydial Infections > Chlamydial Infection A...
313   68        70  Chlamydial Infections > Chlamydial Infection A...
314   68        70  Chlamydial Infections > Chlamydial Infection A...
315   68        70  Chlamydial Infections > Chlamydial Infection A...
316   68        70  Chlamydial Infections > Chlamydial Infection A...
317   69        71  Chlamydial Infections > Chlamydial Infection A...
318   69        71  Chlamydial Infections > Chlamydial Infection A...
319   69        71  Chlamydial Infections > Chlamydial Infection A...
320   69        71  Chlamydial Infections > Chlamydial Infection A...
321   69        71  Chlamydial Infections > Chlamydial Infection A...
322   70        72  Chlamydial Infections > Chlamydial Infection A...
323   70        72  Chlamydial Infections > Chlamydial Infection A...
324   70        72  Chlamydial Infections > Chlamydial Infection A...

### Проверка структуры CDC

Крупные тематические разделы CDC присутствуют во встроенных bookmarks PDF. Используем их как независимую проверку font-based parser: основные разделы, найденные по форматированию текста, должны в целом совпадать с bookmarks документа.

In [57]:
parsed_cdc_level1 = []

for page_data in cdc_pages:
    lines = clean_and_order_cdc_lines(page_data)

    lines = merge_cdc_heading_lines(
        lines,
        page_data["pdf_page"],
    )

    for line in lines:
        if line.get("heading_level") == 1:
            parsed_cdc_level1.append(
                (
                    page_data["pdf_page"],
                    line["text"],
                )
            )

parsed_cdc_level1 = set(parsed_cdc_level1)

print("Missing:")
print(CDC_MAJOR_HEADINGS - parsed_cdc_level1)

print("\nExtra:")
print(parsed_cdc_level1 - CDC_MAJOR_HEADINGS)

Missing:
set()

Extra:
set()

In [58]:
pd.set_option("display.max_colwidth", None)
cdc_records_df[
    cdc_records_df["pdf_page"].isin([66, 67, 68])
][
    ["page", "pdf_page", "section_path"]
].drop_duplicates()

,page,pdf_page,section_path
292,64,66,Diseases Characterized by Urethritis and Cervicitis > Cervicitis
293,64,66,Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Etiology
294,64,66,Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Diagnostic Considerations
295,64,66,Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Treatment
296,64,66,Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Treatment > Recommended Regimen for Cervicitis*
297,64,66,Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Other Management Considerations
298,64,66,Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Follow-Up
299,65,67,Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Follow-Up
300,65,67,Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Management of Sex Partners
301,65,67,Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Persistent or Recurrent Cervicitis
302,65,67,Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Special Considerations > HIV Infection
303,65,67,Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Special Considerations > Pregnancy
304,65,67,Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Special Considerations > Contraceptive Management
305,65,67,Chlamydial Infections > Chlamydial Infection Among Adolescents and Adults
306,66,68,Chlamydial Infections > Chlamydial Infection Among Adolescents and Adults
307,66,68,Chlamydial Infections > Chlamydial Infection Among Adolescents and Adults > Diagnostic Considerations
308,66,68,Chlamydial Infections > Chlamydial Infection Among Adolescents and Adults > Treatment

## 11. Parser для VA/DoD

В отличие от WHO и CDC, встроенные bookmarks документов VA/DoD не дают надёжной иерархии разделов.

Кроме того, корпус содержит несколько рекомендаций разных лет, поэтому нельзя заранее предполагать, что все документы используют абсолютно одинаковое форматирование.

Сначала проверим, как оформлены основные нумерованные разделы во всех шести документах, и только после этого сформулируем правила parser.

In [59]:
va_dod_paths = sorted(
    (GUIDELINES_DIR / "va_dod").glob("*.pdf")
)

for path in va_dod_paths:
    print(path.name)

va_dod_asthma_2025.pdf
va_dod_ckd_2025.pdf
va_dod_low_back_pain_2022.pdf
va_dod_major_depression_2022.pdf
va_dod_pregnancy_2023.pdf
va_dod_type2_diabetes_2023.pdf

In [60]:
VA_DOD_ROMAN_PATTERN = re.compile(
    r"^"
    r"(?=[MDCLXVI]+\.)"
    r"M{0,4}"
    r"(?:CM|CD|D?C{0,3})"
    r"(?:XC|XL|L?X{0,3})"
    r"(?:IX|IV|V?I{0,3})"
    r"\.\s+\S"
)


def collect_va_dod_section_candidates(path):
    rows = []

    with pymupdf.open(path) as doc:
        for page in doc:
            lines = extract_page_lines(page)

            for line in lines:
                text = re.sub(
                    r"\s+",
                    " ",
                    line["text"],
                ).strip()

                if not VA_DOD_ROMAN_PATTERN.match(text):
                    continue

                # Строки Table of Contents с dot leaders
                if re.search(r"\.{4,}", text):
                    continue

                rows.append(
                    {
                        "file": path.name,
                        "pdf_page": page.number + 1,
                        "text": text,
                        "font_size": line["font_size"],
                        "fonts": line["fonts"],
                        "bbox": line["bbox"],
                    }
                )

    return rows

In [61]:
va_dod_section_candidates = []

for path in va_dod_paths:
    va_dod_section_candidates.extend(
        collect_va_dod_section_candidates(path)
    )

va_dod_sections_df = pd.DataFrame(
    va_dod_section_candidates
)

pd.set_option("display.max_colwidth", None)

In [62]:
va_dod_sections_df.groupby(
    ["file", "font_size"]
).size().reset_index(name="count")

                                file  font_size  count
0             va_dod_asthma_2025.pdf       11.0      1
1             va_dod_asthma_2025.pdf       13.0     12
2             va_dod_asthma_2025.pdf       14.0      5
3                va_dod_ckd_2025.pdf       11.0      2
4                va_dod_ckd_2025.pdf       13.0     14
5                va_dod_ckd_2025.pdf       14.0      6
6      va_dod_low_back_pain_2022.pdf       10.4      1
7      va_dod_low_back_pain_2022.pdf       12.0      2
8      va_dod_low_back_pain_2022.pdf       14.4      4
9   va_dod_major_depression_2022.pdf       10.0      1
10  va_dod_major_depression_2022.pdf       13.0      2
11  va_dod_major_depression_2022.pdf       14.0      6
12         va_dod_pregnancy_2023.pdf       11.0      1
13         va_dod_pregnancy_2023.pdf       13.0      9
14         va_dod_pregnancy_2023.pdf       14.0      8
15    va_dod_type2_diabetes_2023.pdf       12.0      1
16    va_dod_type2_diabetes_2023.pdf       13.0      6
17    va_dod_type2_diabetes_2023.pdf       14.0      5

### Результат анализа VA/DoD

Несмотря на различия между версиями документов, основные уровни структуры оформлены достаточно последовательно.

Крупные разделы документа (`III. Scope`, `VIII. Algorithm`, `IX. Recommendations` и т.д.) имеют жирное начертание и размер около 14 pt.

Внутренние буквенные подразделы (`A.`, `B.`, `C.` и т.д.) также выделены жирным шрифтом, но имеют меньший размер — обычно 12–13 pt.

Конкретные семейства шрифтов различаются между версиями документов, поэтому название шрифта не используется как основной признак. Для определения структуры будут использоваться сочетание размера, жирного начертания и формы нумерации.

In [63]:
def is_va_dod_bold(line):
    return any(
        "bold" in font.lower()
        for font in line["fonts"]
    )

In [64]:
VA_DOD_MAJOR_PATTERN = re.compile(
    r"^"
    r"(?=[MDCLXVI]+\.)"
    r"M{0,4}"
    r"(?:CM|CD|D?C{0,3})"
    r"(?:XC|XL|L?X{0,3})"
    r"(?:IX|IV|V?I{0,3})"
    r"\.\s+\S"
)

VA_DOD_APPENDIX_PATTERN = re.compile(
    r"^Appendix\s+[A-Z]\s*[:.]\s*\S",
    flags=re.IGNORECASE,
)

VA_DOD_SUBSECTION_PATTERN = re.compile(
    r"^[A-Z]\.\s+\S"
)

In [65]:
def get_va_dod_heading_level(line):
    text = re.sub(
        r"\s+",
        " ",
        line["text"],
    ).strip()

    if not is_va_dod_bold(line):
        return None

    size = line["font_size"]

    # Основные римские разделы:
    # I. Introduction, IX. Recommendations ...
    if (
        size >= 13.8
        and VA_DOD_MAJOR_PATTERN.match(text)
    ):
        return 1

    # Appendices являются самостоятельными
    # разделами верхнего уровня
    if (
        size >= 13.8
        and VA_DOD_APPENDIX_PATTERN.match(text)
    ):
        return 1

    # Буквенные подразделы:
    # A. Background, B. Treatment ...
    if (
        11.8 <= size < 13.8
        and VA_DOD_SUBSECTION_PATTERN.match(text)
    ):
        return 2

    return None

In [66]:
def normalize_va_dod_text(text):
    return re.sub(r"\s+", " ", text).strip()

In [67]:
def merge_va_dod_inline_labels(lines):
    merged = []
    i = 0

    def is_standalone_subsection_label(text):
        return bool(
            re.fullmatch(
                r"[A-Z]\.",
                text.strip(),
            )
        )

    def is_standalone_roman_label(text):
        text = text.strip()

        if not text.endswith("."):
            return False

        roman = text[:-1]

        return bool(
            re.fullmatch(
                r"(?=[MDCLXVI]+$)"
                r"M{0,4}"
                r"(?:CM|CD|D?C{0,3})"
                r"(?:XC|XL|L?X{0,3})"
                r"(?:IX|IV|V?I{0,3})",
                roman,
            )
        )

    while i < len(lines):
        current = lines[i]

        if i + 1 >= len(lines):
            merged.append(current)
            break

        next_line = lines[i + 1]

        current_text = current["text"].strip()
        next_text = next_line["text"].strip()

        current_bbox = current["bbox"]
        next_bbox = next_line["bbox"]

        current_x0, current_y0, current_x1, current_y1 = (
            current_bbox
        )
        next_x0, next_y0, next_x1, next_y1 = (
            next_bbox
        )

        vertical_overlap = (
            min(current_y1, next_y1)
            - max(current_y0, next_y0)
        )

        horizontal_gap = (
            next_x0 - current_x1
        )

        same_visual_line = (
            vertical_overlap > 0
            and -2 <= horizontal_gap <= 40
        )

        both_bold = (
            is_va_dod_bold(current)
            and is_va_dod_bold(next_line)
        )

        is_subsection_label = (
            is_standalone_subsection_label(
                current_text
            )
        )

        is_roman_label = (
            is_standalone_roman_label(
                current_text
            )
        )

        should_merge = (
            same_visual_line
            and both_bold
            and (
                is_subsection_label
                or is_roman_label
            )
        )

        if should_merge:
            combined = current.copy()

            combined["text"] = (
                f"{current_text} {next_text}"
            )

            combined["bbox"] = (
                min(current_x0, next_x0),
                min(current_y0, next_y0),
                max(current_x1, next_x1),
                max(current_y1, next_y1),
            )

            combined["fonts"] = list(
                dict.fromkeys(
                    current["fonts"]
                    + next_line["fonts"]
                )
            )

            # Для Roman major heading вроде:
            # II. + Background
            # IX. + Recommendations
            #
            # берём размер основного текста heading.
            #
            # Для subsection вроде:
            # C. + Diabetes Mellitus
            # F. + Guideline Development Team
            #
            # сохраняем размер буквенного label,
            # чтобы heading остался level 2.
            if (
                is_roman_label
                and next_line["font_size"] >= 13.8
            ):
                combined["font_size"] = max(
                    current["font_size"],
                    next_line["font_size"],
                )
            else:
                combined["font_size"] = (
                    current["font_size"]
                )

            merged.append(combined)

            i += 2
            continue

        merged.append(current)
        i += 1

    return merged

In [68]:
def merge_va_dod_heading_lines(lines):
    lines = merge_va_dod_inline_labels(lines)

    merged = []
    i = 0

    while i < len(lines):
        line = lines[i].copy()

        level = get_va_dod_heading_level(
            line
        )

        if level is None:
            merged.append(line)
            i += 1
            continue

        heading_x0 = line["bbox"][0]

        is_appendix = bool(
            VA_DOD_APPENDIX_PATTERN.match(
                normalize_va_dod_text(
                    line["text"]
                )
            )
        )

        i += 1

        while i < len(lines):
            next_line = lines[i]

            # Если следующая строка сама является
            # новым heading, текущий heading закончен.
            if (
                get_va_dod_heading_level(
                    next_line
                )
                is not None
            ):
                break

            if not is_va_dod_bold(
                next_line
            ):
                break

            same_size = (
                abs(
                    next_line["font_size"]
                    - line["font_size"]
                )
                <= 0.3
            )

            if not same_size:
                break

            vertical_gap = (
                next_line["bbox"][1]
                - line["bbox"][3]
            )

            if vertical_gap > 6:
                break

            # В VA/DoD продолжения Appendix headings
            # имеют больший отступ вправо.
            max_indent = (
                100
                if is_appendix
                else 60
            )

            next_x0 = next_line["bbox"][0]

            if not (
                heading_x0 - 5
                <= next_x0
                <= heading_x0 + max_indent
            ):
                break

            line["text"] = (
                f'{normalize_va_dod_text(line["text"])} '
                f'{normalize_va_dod_text(next_line["text"])}'
            )

            line["bbox"] = (
                min(
                    line["bbox"][0],
                    next_line["bbox"][0],
                ),
                min(
                    line["bbox"][1],
                    next_line["bbox"][1],
                ),
                max(
                    line["bbox"][2],
                    next_line["bbox"][2],
                ),
                max(
                    line["bbox"][3],
                    next_line["bbox"][3],
                ),
            )

            line["fonts"] = sorted(
                set(line["fonts"])
                | set(next_line["fonts"])
            )

            i += 1

        line["heading_level"] = level
        merged.append(line)

    return merged

In [69]:
lbp_pages = extract_document_pages(
    GUIDELINES_DIR
    / "va_dod"
    / "va_dod_low_back_pain_2022.pdf"
)

lbp_lines = merge_va_dod_heading_lines(
    lbp_pages[14]["lines"]
)

for line in lbp_lines:
    if line.get("heading_level") is not None:
        print(
            line["heading_level"],
            "|",
            line["text"],
        )

2 | D. Patient Perspective
2 | E. External Peer Review
2 | F. Implementation
1 | VII. Approach to Care in Department of Veterans Affairs and Department of Defense
2 | A. Patient-centered Care

In [70]:
asthma_pages = extract_document_pages(
    GUIDELINES_DIR
    / "va_dod"
    / "va_dod_asthma_2025.pdf"
)

asthma_lines = merge_va_dod_heading_lines(
    asthma_pages[7]["lines"]
)

for line in asthma_lines:
    if line.get("heading_level") is not None:
        print(
            line["heading_level"],
            "|",
            line["text"],
        )

2 | C. Epidemiology and Impact in the General Population
2 | D. Asthma in the Department of Defense and the Department of Veterans Affairs Populations

### Служебные элементы VA/DoD

Перед формированием структурированных records необходимо удалить повторяющиеся headers и footers.

Поскольку документы VA/DoD относятся к разным версиям шаблона, не будем заранее задавать конкретные строки вручную. Сначала проверим, какие элементы регулярно встречаются в верхней и нижней частях страниц.

In [71]:
def collect_va_dod_margin_texts(path):
    top_texts = Counter()
    bottom_texts = Counter()

    pages = extract_document_pages(path)

    for page_data in pages:
        height = page_data["height"]

        for line in page_data["lines"]:
            text = normalize_va_dod_text(
                line["text"]
            )

            y0 = line["bbox"][1]

            if y0 < 0.08 * height:
                top_texts[text] += 1

            if y0 > 0.92 * height:
                bottom_texts[text] += 1

    return top_texts, bottom_texts

In [72]:
def get_va_dod_margin_noise(path, min_fraction=0.25):
    top_texts, bottom_texts = collect_va_dod_margin_texts(path)

    with pymupdf.open(path) as doc:
        n_pages = len(doc)

    min_count = max(
        3,
        int(n_pages * min_fraction),
    )

    noise = {
        text
        for text, count in top_texts.items()
        if count >= min_count
    }

    noise.update(
        text
        for text, count in bottom_texts.items()
        if count >= min_count
    )

    return noise

In [73]:
def clean_va_dod_lines(page_data, margin_noise):
    clean_lines = []

    height = page_data["height"]

    for line in page_data["lines"]:
        text = normalize_va_dod_text(
            line["text"]
        )

        if not text:
            continue

        y0 = line["bbox"][1]

        in_margin = (
            y0 < 0.08 * height
            or y0 > 0.92 * height
        )

        # Повторяющийся header/footer
        if in_margin and text in margin_noise:
            continue

        # Уникальный номер каждой страницы:
        # Page 31 of 149 и т.п.
        if (
            y0 > 0.90 * height
            and re.fullmatch(
                r"Page\s+\d+\s+of\s+\d+",
                text,
                flags=re.IGNORECASE,
            )
        ):
            continue

        clean_lines.append(
            {
                **line,
                "text": text,
            }
        )

    return clean_lines

In [74]:
for path in va_dod_paths:
    margin_noise = get_va_dod_margin_noise(path)

    print("\n", path.name)

    for text in sorted(margin_noise):
        print("REMOVE:", text)

 va_dod_asthma_2025.pdf
REMOVE: March 2025
REMOVE: VA/DOD Clinical Practice Guideline for the Primary Care Management of Asthma

 va_dod_ckd_2025.pdf
REMOVE: April 2025
REMOVE: VA/DOD Clinical Practice Guideline for the Primary Care Management of Chronic Kidney Disease

 va_dod_low_back_pain_2022.pdf
REMOVE: February 2022
REMOVE: VA/DoD Clinical Practice Guideline for the Diagnosis and Treatment of Low Back Pain

 va_dod_major_depression_2022.pdf
REMOVE: February 2022
REMOVE: VA/DoD Clinical Practice Guideline for the Management of Major Depressive Disorder

 va_dod_pregnancy_2023.pdf
REMOVE: July 2023
REMOVE: VA/DoD Clinical Practice Guideline for Management of Pregnancy
REMOVE: VA/DoD Clinical Practice Guideline for the Management of Pregnancy

 va_dod_type2_diabetes_2023.pdf
REMOVE: May 2023
REMOVE: VA/DoD Clinical Practice Guideline for Management of Type 2 Diabetes Mellitus
REMOVE: VA/DoD Clinical Practice Guideline for the Management of Type 2 Diabetes Mellitus

In [75]:
remaining_page_markers = []

for path in va_dod_paths:
    margin_noise = get_va_dod_margin_noise(path)
    pages = extract_document_pages(path)

    for page_data in pages:
        lines = clean_va_dod_lines(
            page_data,
            margin_noise,
        )

        for line in lines:
            if re.fullmatch(
                r"Page\s+\d+\s+of\s+\d+",
                line["text"],
                flags=re.IGNORECASE,
            ):
                remaining_page_markers.append(
                    (
                        path.name,
                        page_data["pdf_page"],
                        line["text"],
                    )
                )

remaining_page_markers

[]

In [76]:
def get_va_dod_references_start_page(path):
    with pymupdf.open(path) as doc:
        for page in doc:
            lines = extract_page_lines(page)

            for line in lines:
                text = normalize_va_dod_text(
                    line["text"]
                )

                x0, y0, x1, y1 = line["bbox"]

                if (
                    text.lower() == "references"
                    and is_va_dod_bold(line)
                    and line["font_size"] >= 13.8
                    and x0 < 150
                    and y0 < 120
                ):
                    return page.number + 1

    return None

In [77]:
va_dod_references_pages = []

for path in va_dod_paths:
    va_dod_references_pages.append(
        {
            "file": path.name,
            "references_pdf_page": (
                get_va_dod_references_start_page(path)
            ),
        }
    )

pd.DataFrame(va_dod_references_pages)

                               file  references_pdf_page
0            va_dod_asthma_2025.pdf                  142
1               va_dod_ckd_2025.pdf                  174
2     va_dod_low_back_pain_2022.pdf                  125
3  va_dod_major_depression_2022.pdf                  144
4         va_dod_pregnancy_2023.pdf                  163
5    va_dod_type2_diabetes_2023.pdf                  150

### Структурированный parser VA/DoD

Для каждого документа parser:

1. удаляет повторяющиеся headers, footers и номера страниц;
2. объединяет части многострочных заголовков;
3. восстанавливает два уровня структуры: крупный раздел и буквенный подраздел;
4. сохраняет текущий `section_path` при переходе между страницами;
5. прекращает обработку перед началом библиографии `References`.

Результат приводится к той же metadata-схеме, которая используется для WHO и CDC.

In [78]:
def parse_va_dod(path):
    pages = extract_document_pages(path)
    metadata = DOCUMENT_METADATA[path.name]

    margin_noise = get_va_dod_margin_noise(path)
    references_start = get_va_dod_references_start_page(path)

    section_stack = {}
    records = []
    started = False

    for page_data in pages:
        if (
            references_start is not None
            and page_data["pdf_page"] >= references_start
        ):
            break

        lines = clean_va_dod_lines(
            page_data,
            margin_noise,
        )

        lines = merge_va_dod_heading_lines(
            lines
        )

        current_text = []

        def flush_text():
            if not current_text:
                return

            if not started:
                current_text.clear()
                return

            text = " ".join(
                current_text
            )

            text = re.sub(
                r"\s+",
                " ",
                text,
            ).strip()

            text = re.sub(
                r"-\s+(?=\w)",
                "-",
                text,
            )

            if text:
                records.append(
                    {
                        "document_id": page_data["document_id"],
                        "source": metadata["source"],
                        "document_title": metadata["document_title"],
                        "year": metadata["year"],
                        "section_path": build_section_path(
                            section_stack
                        ),
                        "page": page_data["page"],
                        "pdf_page": page_data["pdf_page"],
                        "text": text,
                    }
                )

            current_text.clear()

        for line in lines:
            level = line.get(
                "heading_level"
            )

            if level is not None:
                flush_text()

                started = True

                section_stack[level] = (
                    line["text"]
                )

                for existing_level in list(
                    section_stack
                ):
                    if existing_level > level:
                        del section_stack[
                            existing_level
                        ]

                continue

            current_text.append(
                line["text"]
            )

        flush_text()

    return records

In [79]:
va_dod_records = []

for path in va_dod_paths:
    va_dod_records.extend(
        parse_va_dod(path)
    )

va_dod_records_df = pd.DataFrame(
    va_dod_records
)

len(va_dod_records_df)

1110

In [80]:
va_dod_records_df.groupby(
    [
        "document_id",
        "document_title",
    ]
).size().reset_index(
    name="records"
)

,document_id,document_title,records
0,va_dod_asthma_2025,VA/DOD Clinical Practice Guideline for the Primary Care Management of Asthma,174
1,va_dod_ckd_2025,VA/DOD Clinical Practice Guideline for the Primary Care Management of Chronic Kidney Disease,205
2,va_dod_low_back_pain_2022,VA/DoD Clinical Practice Guideline for the Diagnosis and Treatment of Low Back Pain,160
3,va_dod_major_depression_2022,VA/DoD Clinical Practice Guideline for the Management of Major Depressive Disorder,174
4,va_dod_pregnancy_2023,VA/DoD Clinical Practice Guideline for the Management of Pregnancy,212
5,va_dod_type2_diabetes_2023,VA/DoD Clinical Practice Guideline for the Management of Type 2 Diabetes Mellitus,185

In [81]:
reference_leaks = []

for path in va_dod_paths:
    reference_page = (
        get_va_dod_references_start_page(path)
    )

    document_id = path.stem

    leaked = va_dod_records_df[
        (va_dod_records_df["document_id"] == document_id)
        & (
            va_dod_records_df["pdf_page"]
            >= reference_page
        )
    ]

    if not leaked.empty:
        reference_leaks.append(
            {
                "document_id": document_id,
                "records": len(leaked),
            }
        )

reference_leaks

[]

In [82]:
va_dod_major_headings = []

for path in va_dod_paths:
    margin_noise = get_va_dod_margin_noise(path)
    references_start = (
        get_va_dod_references_start_page(path)
    )

    pages = extract_document_pages(path)

    for page_data in pages:
        if (
            references_start is not None
            and page_data["pdf_page"] >= references_start
        ):
            break

        lines = clean_va_dod_lines(
            page_data,
            margin_noise,
        )

        lines = merge_va_dod_heading_lines(lines)

        for line in lines:
            if line.get("heading_level") == 1:
                va_dod_major_headings.append(
                    {
                        "file": path.name,
                        "pdf_page": page_data["pdf_page"],
                        "title": line["text"],
                    }
                )

va_dod_major_headings_df = pd.DataFrame(
    va_dod_major_headings
)

va_dod_major_headings_df

,file,pdf_page,title
0,va_dod_asthma_2025.pdf,6,I. Introduction
1,va_dod_asthma_2025.pdf,6,II. Background
2,va_dod_asthma_2025.pdf,9,III. Scope of This Guideline
3,va_dod_asthma_2025.pdf,10,IV. Highlighted Features of This Guideline
4,va_dod_asthma_2025.pdf,12,V. Guideline Development Team
...,...,...,...
127,va_dod_type2_diabetes_2023.pdf,114,Appendix F: 2017 CPG Recommendation Categorization Table
128,va_dod_type2_diabetes_2023.pdf,118,Appendix G: Participant List
129,va_dod_type2_diabetes_2023.pdf,120,Appendix H: Literature Review Search Terms and Strategy
130,va_dod_type2_diabetes_2023.pdf,145,Appendix I: Alternative Text Descriptions of Algorithm
131,va_dod_type2_diabetes_2023.pdf,147,Appendix J: Abbreviations

## 12. Проверка качества parsing

Перед chunking проверяем, что структурированный корпус удовлетворяет базовым инвариантам:

- каждый документ представлен в корпусе;
- `text` не пустой;
- `section_path` не пустой;
- front matter не попадает в корпус до первого содержательного раздела;
- библиография `References` не индексируется;
- основные разделы документов корректно восстанавливаются.

In [83]:
parser_dfs = {
    "WHO": who_records_df,
    "CDC": cdc_records_df,
    "VA/DoD": va_dod_records_df,
}

parser_summary = []

for source, df in parser_dfs.items():
    parser_summary.append(
        {
            "source": source,
            "records": len(df),
            "documents": df["document_id"].nunique(),
            "empty_section_path": (
                df["section_path"].fillna("").str.strip().eq("").sum()
            ),
            "empty_text": (
                df["text"].fillna("").str.strip().eq("").sum()
            ),
        }
    )

pd.DataFrame(parser_summary)

   source  records  documents  empty_section_path  empty_text
0     WHO       42          1                   0           0
1     CDC      599          1                   0           0
2  VA/DoD     1110          6                   0           0

### Результат parsing

Все 8 документов успешно преобразованы в единую структурированную схему.

После удаления front matter и восстановления структуры разделов:

- WHO: 42 records;
- CDC: 599 records;
- VA/DoD: 1110 records;
- пустых `section_path` нет;
- пустых текстовых records нет;
- библиографические разделы `References` исключены;
- многострочные заголовки корректно объединяются;
- основные разделы и подразделы отдельно проверены для каждого семейства документов;
- VA/DoD appendices распознаются как самостоятельные разделы верхнего уровня.

На этом этапе parsing считается завершённым.

## 13. Формирование retrieval corpus

После parsing в корпусе остаются не только клинические разделы, но и служебные части документов: описание разработки guideline, списки участников, поисковые стратегии, abbreviations и другие материалы.

Для dense retrieval такие разделы могут создавать шум: они формально относятся к медицинскому документу, но редко содержат информацию, полезную для ответа на клинический вопрос.

Поэтому перед chunking сначала анализируем состав структурированного корпуса и явно определяем, какие разделы будут индексироваться.

In [84]:
corpus_records_df = pd.concat(
    [
        who_records_df,
        cdc_records_df,
        va_dod_records_df,
    ],
    ignore_index=True,
)

len(corpus_records_df)

1751

In [85]:
corpus_records_df["top_level_section"] = (
    corpus_records_df["section_path"]
    .str.split(" > ")
    .str[0]
)

corpus_records_df[
    [
        "document_id",
        "top_level_section",
    ]
].drop_duplicates()

,document_id,top_level_section
0,who_hypertension_2021,1 Introduction
2,who_hypertension_2021,2 Method for developing the guideline
9,who_hypertension_2021,3 Recommendations
28,who_hypertension_2021,4 Special settings
32,who_hypertension_2021,"5 Publication, implementation, evaluation and research gaps"
...,...,...
1715,va_dod_type2_diabetes_2023,Appendix F: 2017 CPG Recommendation Categorization Table
1719,va_dod_type2_diabetes_2023,Appendix G: Participant List
1721,va_dod_type2_diabetes_2023,Appendix H: Literature Review Search Terms and Strategy
1746,va_dod_type2_diabetes_2023,Appendix I: Alternative Text Descriptions of Algorithm
1748,va_dod_type2_diabetes_2023,Appendix J: Abbreviations

In [86]:
section_inventory = (
    corpus_records_df
    .groupby(
        [
            "document_id",
            "top_level_section",
        ]
    )
    .agg(
        records=("text", "size"),
        first_pdf_page=("pdf_page", "min"),
        last_pdf_page=("pdf_page", "max"),
    )
    .reset_index()
)

pd.set_option(
    "display.max_colwidth",
    None,
)

section_inventory

,document_id,top_level_section,records,first_pdf_page,last_pdf_page
0,cdc_sti_2021,Chlamydial Infections,29,67,73
1,cdc_sti_2021,Clinical Prevention Guidance,30,4,13
2,cdc_sti_2021,"Diseases Characterized by Genital, Anal, or Perianal Ulcers",62,29,41
3,cdc_sti_2021,Diseases Characterized by Urethritis and Cervicitis,28,62,67
4,cdc_sti_2021,"Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge",47,84,96
...,...,...,...,...,...
160,who_hypertension_2021,2 Method for developing the guideline,7,15,18
161,who_hypertension_2021,3 Recommendations,19,19,32
162,who_hypertension_2021,4 Special settings,4,33,35
163,who_hypertension_2021,"5 Publication, implementation, evaluation and research gaps",6,36,37
164,who_hypertension_2021,6 Implementation tools,4,38,41

In [87]:
who_records_df["top_level_section"] = (
    who_records_df["section_path"]
    .str.split(" > ")
    .str[0]
)

(
    who_records_df
    .groupby("top_level_section")
    .agg(
        records=("text", "size"),
        first_pdf_page=("pdf_page", "min"),
        last_pdf_page=("pdf_page", "max"),
    )
    .reset_index()
)

,top_level_section,records,first_pdf_page,last_pdf_page
0,1 Introduction,2,13,14
1,2 Method for developing the guideline,7,15,18
2,3 Recommendations,19,19,32
3,4 Special settings,4,33,35
4,"5 Publication, implementation, evaluation and research gaps",6,36,37
5,6 Implementation tools,4,38,41

In [88]:
appendix_inventory = (
    section_inventory[
        section_inventory["top_level_section"]
        .str.startswith(
            "Appendix",
            na=False,
        )
    ][
        [
            "document_id",
            "top_level_section",
            "records",
        ]
    ]
    .sort_values(
        [
            "document_id",
            "top_level_section",
        ]
    )
    .reset_index(drop=True)
)

pd.set_option(
    "display.max_rows",
    None,
)

appendix_inventory

,document_id,top_level_section,records
0,va_dod_asthma_2025,Appendix A: Guideline Development Methodology,23
1,va_dod_asthma_2025,Appendix B: Patient Focus Group Methods and Findings,3
2,va_dod_asthma_2025,Appendix C: Assessments of Asthma Severity and Control,10
3,va_dod_asthma_2025,Appendix D: Details of a Comprehensive History and Physical Exam,5
4,va_dod_asthma_2025,Appendix E: DOD Service-Specific Regulation Concerning Asthma,2
5,va_dod_asthma_2025,Appendix F: Example Asthma Action Plan Templates,8
6,va_dod_asthma_2025,Appendix G: Additional Information on Pharmacotherapy,10
7,va_dod_asthma_2025,Appendix H: Evidence Table,4
8,va_dod_asthma_2025,Appendix I: 2019 Recommendation Categorization,3
9,va_dod_asthma_2025,Appendix J: Participant List,2
10,va_dod_asthma_2025,Appendix K: Alternative Text Descriptions of Algorithms,5
11,va_dod_asthma_2025,Appendix L: Literature Review Search Terms and Strategy,15
12,va_dod_asthma_2025,Appendix M: Abbreviation List,2
13,va_dod_ckd_2025,Appendix A: Guideline Development Methodology,23
14,va_dod_ckd_2025,Appendix B: Evidence Table,5
15,va_dod_ckd_2025,Appendix C: 2019 Recommendation Categorization,5
16,va_dod_ckd_2025,Appendix D: Participant List,2
17,va_dod_ckd_2025,Appendix E: Patient Focus Group Methods and Findings,3
18,va_dod_ckd_2025,Appendix F: Literature Review Search Terms and Strategy,9
19,va_dod_ckd_2025,Appendix G. Alternative Text Descriptions of Algorithms,5
20,va_dod_ckd_2025,Appendix H. Management of CKD Table,3
21,va_dod_ckd_2025,Appendix I. Monitoring of CKD Table,4
22,va_dod_ckd_2025,Appendix J. Approaches for eGFR Calculation,4
23,va_dod_ckd_2025,Appendix K. Nephrotoxic Agents and Medication Dose Adjustments in CKD,6
24,va_dod_ckd_2025,Appendix L. List of Pharmacotherapies,7
25,va_dod_ckd_2025,Appendix M. Management of Hyperkalemia,7
26,va_dod_ckd_2025,Appendix N. Chronic Pain Management in CKD,9
27,va_dod_ckd_2025,Appendix O. Military Occupation Exposures and CKD,2
28,va_dod_ckd_2025,Appendix P. Special Considerations when Caring for Older Patients,5
29,va_dod_ckd_2025,Appendix Q. Gadolinium and Iodinated Contrast,4
30,va_dod_ckd_2025,Appendix R. General Medical and Lifestyle Management Recommendations to Improve Standard of Care in CKD Patients,2
31,va_dod_ckd_2025,Appendix S: Abbreviation List,5
32,va_dod_low_back_pain_2022,Appendix A: Guideline Development Methodology,18
33,va_dod_low_back_pain_2022,Appendix B: Patient Focus Group Methods and Findings,3
34,va_dod_low_back_pain_2022,Appendix C: Evidence Table,5
35,va_dod_low_back_pain_2022,Appendix D: 2017 Recommendation Categorization Table,5
36,va_dod_low_back_pain_2022,"Appendix E: Dosing for Select Pharmacologic Agentsa,b",1
37,va_dod_low_back_pain_2022,Appendix F: Glossary,2
38,va_dod_low_back_pain_2022,Appendix G: Participant List,2
39,va_dod_low_back_pain_2022,Appendix H: Literature Review Search Terms and Strategy,10
40,va_dod_low_back_pain_2022,Appendix I: Alternative Text Descriptions of Algorithm,5
41,va_dod_low_back_pain_2022,Appendix J: Abbreviations,3
42,va_dod_major_depression_2022,Appendix A: Guideline Development Methodology,15
43,va_dod_major_depression_2022,Appendix B: Patient Focus Group Methods and Findings,3
44,va_dod_major_depression_2022,Appendix C: Evidence Table,6
45,va_dod_major_depression_2022,Appendix D: 2016 Recommendation Categorization Table,6
46,va_dod_major_depression_2022,Appendix E: Participant List,2
47,va_dod_major_depression_2022,Appendix F: Literature Review Search Terms and Strategy,22
48,va_dod_major_depression_2022,Appendix G: Alternative Text Descriptions of Algorithm,3
49,va_dod_major_depression_2022,Appendix H: Abbreviations,2
50,va_dod_major_depression_2022,Appendix I: Quick Guide to the Patient Health Questionnaire in Clinical Practice,7
51,va_dod_major_depression_2022,Appendix J: Pharmacotherapy,8
52,va_dod_major_depression_2022,Appendix K: Definitions,4
53,va_dod_pregnancy_2023,Appendix A: Guideline Development Methodology,20
54,va_dod_pregnancy_2023,Appendix B: Patient Focus Group Methods and Findings,3
55,va_dod_pregnancy_2023,Appendix C: Evidence Table,5
56,va_dod_pregnancy_2023,Appendix D: 2018 Recommendation Categorization Table,4
57,va_dod_pregnancy_2023,Appendix E. Participant List,2
58,va_dod_pregnancy_2023,Appendix F: Literature Review Search Terms and Strategy,24
59,va_dod_pregnancy_2023,Appendix G: Abbreviations,3
60,va_dod_type2_diabetes_2023,Appendix A: Guideline Development Methodology,23
61,va_dod_type2_diabetes_2023,Appendix B: Glycemic Control Targets and Monitoring,2
62,va_dod_type2_diabetes_2023,Appendix C: Pharmacotherapy,8
63,va_dod_type2_diabetes_2023,Appendix D: Patient Focus Group Methods and Findings,3
64,va_dod_type2_diabetes_2023,Appendix E: Evidence Table,5
65,va_dod_type2_diabetes_2023,Appendix F: 2017 CPG Recommendation Categorization Table,4
66,va_dod_type2_diabetes_2023,Appendix G: Participant List,2
67,va_dod_type2_diabetes_2023,Appendix H: Literature Review Search Terms and Strategy,25
68,va_dod_type2_diabetes_2023,Appendix I: Alternative Text Descriptions of Algorithm,2
69,va_dod_type2_diabetes_2023,Appendix J: Abbreviations,3

### Отбор VA/DoD appendices для retrieval

Не все приложения клинических рекомендаций одинаково полезны для поиска.

Для baseline retrieval исключаем приложения, которые описывают создание документа, участников, поисковую стратегию, служебные сокращения и историческую категоризацию рекомендаций. Такие разделы увеличивают вероятность нерелевантных совпадений, но редко помогают ответить на клинический вопрос.

Клинические приложения — схемы ведения, pharmacotherapy, dosing, monitoring, diagnostic tools, definitions и текстовые описания алгоритмов — сохраняем.

Фильтрация выполняется только для retrieval corpus. Исходные parsed records остаются неизменными.

In [89]:
APPENDIX_DROP_RULES = [
    (
        "Guideline Development Methodology",
        "guideline development methodology",
    ),
    (
        "Patient Focus Group Methods and Findings",
        "patient focus group",
    ),
    (
        "Evidence Table",
        "evidence table duplicated by clinical recommendations",
    ),
    (
        "Recommendation Categorization",
        "historical recommendation categorization",
    ),
    (
        "Participant List",
        "participant list",
    ),
    (
        "Literature Review Search Terms and Strategy",
        "literature search methodology",
    ),
    (
        "Abbreviation",
        "abbreviation list",
    ),
]


def classify_va_dod_appendix(title):
    title_lower = title.lower()

    for pattern, reason in APPENDIX_DROP_RULES:
        if pattern.lower() in title_lower:
            return "DROP", reason


    if (
        "service-specific regulation"
        in title_lower
    ):
        return (
            "DROP",
            "military-specific regulatory content",
        )

    return (
        "KEEP",
        "clinically useful appendix",
    )

In [90]:
appendix_classification = (
    appendix_inventory.copy()
)

appendix_classification[
    ["retrieval_status", "reason"]
] = (
    appendix_classification[
        "top_level_section"
    ]
    .apply(
        lambda title: pd.Series(
            classify_va_dod_appendix(
                title
            )
        )
    )
)

appendix_classification[
    [
        "document_id",
        "top_level_section",
        "records",
        "retrieval_status",
        "reason",
    ]
]

,document_id,top_level_section,records,retrieval_status,reason
0,va_dod_asthma_2025,Appendix A: Guideline Development Methodology,23,DROP,guideline development methodology
1,va_dod_asthma_2025,Appendix B: Patient Focus Group Methods and Findings,3,DROP,patient focus group
2,va_dod_asthma_2025,Appendix C: Assessments of Asthma Severity and Control,10,KEEP,clinically useful appendix
3,va_dod_asthma_2025,Appendix D: Details of a Comprehensive History and Physical Exam,5,KEEP,clinically useful appendix
4,va_dod_asthma_2025,Appendix E: DOD Service-Specific Regulation Concerning Asthma,2,DROP,military-specific regulatory content
5,va_dod_asthma_2025,Appendix F: Example Asthma Action Plan Templates,8,KEEP,clinically useful appendix
6,va_dod_asthma_2025,Appendix G: Additional Information on Pharmacotherapy,10,KEEP,clinically useful appendix
7,va_dod_asthma_2025,Appendix H: Evidence Table,4,DROP,evidence table duplicated by clinical recommendations
8,va_dod_asthma_2025,Appendix I: 2019 Recommendation Categorization,3,DROP,historical recommendation categorization
9,va_dod_asthma_2025,Appendix J: Participant List,2,DROP,participant list
10,va_dod_asthma_2025,Appendix K: Alternative Text Descriptions of Algorithms,5,KEEP,clinically useful appendix
11,va_dod_asthma_2025,Appendix L: Literature Review Search Terms and Strategy,15,DROP,literature search methodology
12,va_dod_asthma_2025,Appendix M: Abbreviation List,2,DROP,abbreviation list
13,va_dod_ckd_2025,Appendix A: Guideline Development Methodology,23,DROP,guideline development methodology
14,va_dod_ckd_2025,Appendix B: Evidence Table,5,DROP,evidence table duplicated by clinical recommendations
15,va_dod_ckd_2025,Appendix C: 2019 Recommendation Categorization,5,DROP,historical recommendation categorization
16,va_dod_ckd_2025,Appendix D: Participant List,2,DROP,participant list
17,va_dod_ckd_2025,Appendix E: Patient Focus Group Methods and Findings,3,DROP,patient focus group
18,va_dod_ckd_2025,Appendix F: Literature Review Search Terms and Strategy,9,DROP,literature search methodology
19,va_dod_ckd_2025,Appendix G. Alternative Text Descriptions of Algorithms,5,KEEP,clinically useful appendix
20,va_dod_ckd_2025,Appendix H. Management of CKD Table,3,KEEP,clinically useful appendix
21,va_dod_ckd_2025,Appendix I. Monitoring of CKD Table,4,KEEP,clinically useful appendix
22,va_dod_ckd_2025,Appendix J. Approaches for eGFR Calculation,4,KEEP,clinically useful appendix
23,va_dod_ckd_2025,Appendix K. Nephrotoxic Agents and Medication Dose Adjustments in CKD,6,KEEP,clinically useful appendix
24,va_dod_ckd_2025,Appendix L. List of Pharmacotherapies,7,KEEP,clinically useful appendix
25,va_dod_ckd_2025,Appendix M. Management of Hyperkalemia,7,KEEP,clinically useful appendix
26,va_dod_ckd_2025,Appendix N. Chronic Pain Management in CKD,9,KEEP,clinically useful appendix
27,va_dod_ckd_2025,Appendix O. Military Occupation Exposures and CKD,2,KEEP,clinically useful appendix
28,va_dod_ckd_2025,Appendix P. Special Considerations when Caring for Older Patients,5,KEEP,clinically useful appendix
29,va_dod_ckd_2025,Appendix Q. Gadolinium and Iodinated Contrast,4,KEEP,clinically useful appendix
30,va_dod_ckd_2025,Appendix R. General Medical and Lifestyle Management Recommendations to Improve Standard of Care in CKD Patients,2,KEEP,clinically useful appendix
31,va_dod_ckd_2025,Appendix S: Abbreviation List,5,DROP,abbreviation list
32,va_dod_low_back_pain_2022,Appendix A: Guideline Development Methodology,18,DROP,guideline development methodology
33,va_dod_low_back_pain_2022,Appendix B: Patient Focus Group Methods and Findings,3,DROP,patient focus group
34,va_dod_low_back_pain_2022,Appendix C: Evidence Table,5,DROP,evidence table duplicated by clinical recommendations
35,va_dod_low_back_pain_2022,Appendix D: 2017 Recommendation Categorization Table,5,DROP,historical recommendation categorization
36,va_dod_low_back_pain_2022,"Appendix E: Dosing for Select Pharmacologic Agentsa,b",1,KEEP,clinically useful appendix
37,va_dod_low_back_pain_2022,Appendix F: Glossary,2,KEEP,clinically useful appendix
38,va_dod_low_back_pain_2022,Appendix G: Participant List,2,DROP,participant list
39,va_dod_low_back_pain_2022,Appendix H: Literature Review Search Terms and Strategy,10,DROP,literature search methodology
40,va_dod_low_back_pain_2022,Appendix I: Alternative Text Descriptions of Algorithm,5,KEEP,clinically useful appendix
41,va_dod_low_back_pain_2022,Appendix J: Abbreviations,3,DROP,abbreviation list
42,va_dod_major_depression_2022,Appendix A: Guideline Development Methodology,15,DROP,guideline development methodology
43,va_dod_major_depression_2022,Appendix B: Patient Focus Group Methods and Findings,3,DROP,patient focus group
44,va_dod_major_depression_2022,Appendix C: Evidence Table,6,DROP,evidence table duplicated by clinical recommendations
45,va_dod_major_depression_2022,Appendix D: 2016 Recommendation Categorization Table,6,DROP,historical recommendation categorization
46,va_dod_major_depression_2022,Appendix E: Participant List,2,DROP,participant list
47,va_dod_major_depression_2022,Appendix F: Literature Review Search Terms and Strategy,22,DROP,literature search methodology
48,va_dod_major_depression_2022,Appendix G: Alternative Text Descriptions of Algorithm,3,KEEP,clinically useful appendix
49,va_dod_major_depression_2022,Appendix H: Abbreviations,2,DROP,abbreviation list
50,va_dod_major_depression_2022,Appendix I: Quick Guide to the Patient Health Questionnaire in Clinical Practice,7,KEEP,clinically useful appendix
51,va_dod_major_depression_2022,Appendix J: Pharmacotherapy,8,KEEP,clinically useful appendix
52,va_dod_major_depression_2022,Appendix K: Definitions,4,KEEP,clinically useful appendix
53,va_dod_pregnancy_2023,Appendix A: Guideline Development Methodology,20,DROP,guideline development methodology
54,va_dod_pregnancy_2023,Appendix B: Patient Focus Group Methods and Findings,3,DROP,patient focus group
55,va_dod_pregnancy_2023,Appendix C: Evidence Table,5,DROP,evidence table duplicated by clinical recommendations
56,va_dod_pregnancy_2023,Appendix D: 2018 Recommendation Categorization Table,4,DROP,historical recommendation categorization
57,va_dod_pregnancy_2023,Appendix E. Participant List,2,DROP,participant list
58,va_dod_pregnancy_2023,Appendix F: Literature Review Search Terms and Strategy,24,DROP,literature search methodology
59,va_dod_pregnancy_2023,Appendix G: Abbreviations,3,DROP,abbreviation list
60,va_dod_type2_diabetes_2023,Appendix A: Guideline Development Methodology,23,DROP,guideline development methodology
61,va_dod_type2_diabetes_2023,Appendix B: Glycemic Control Targets and Monitoring,2,KEEP,clinically useful appendix
62,va_dod_type2_diabetes_2023,Appendix C: Pharmacotherapy,8,KEEP,clinically useful appendix
63,va_dod_type2_diabetes_2023,Appendix D: Patient Focus Group Methods and Findings,3,DROP,patient focus group
64,va_dod_type2_diabetes_2023,Appendix E: Evidence Table,5,DROP,evidence table duplicated by clinical recommendations
65,va_dod_type2_diabetes_2023,Appendix F: 2017 CPG Recommendation Categorization Table,4,DROP,historical recommendation categorization
66,va_dod_type2_diabetes_2023,Appendix G: Participant List,2,DROP,participant list
67,va_dod_type2_diabetes_2023,Appendix H: Literature Review Search Terms and Strategy,25,DROP,literature search methodology
68,va_dod_type2_diabetes_2023,Appendix I: Alternative Text Descriptions of Algorithm,2,KEEP,clinically useful appendix
69,va_dod_type2_diabetes_2023,Appendix J: Abbreviations,3,DROP,abbreviation list

In [91]:
appendix_classification.groupby(
    [
        "retrieval_status",
        "reason",
    ]
).agg(
    sections=(
        "top_level_section",
        "size",
    ),
    records=(
        "records",
        "sum",
    ),
).reset_index()

,retrieval_status,reason,sections,records
0,DROP,abbreviation list,6,18
1,DROP,evidence table duplicated by clinical recommendations,6,30
2,DROP,guideline development methodology,6,122
3,DROP,historical recommendation categorization,6,27
4,DROP,literature search methodology,6,105
5,DROP,military-specific regulatory content,1,2
6,DROP,participant list,6,12
7,DROP,patient focus group,6,18
8,KEEP,clinically useful appendix,27,138

In [92]:
appendix_classification.loc[
    appendix_classification[
        "retrieval_status"
    ].eq("KEEP"),
    [
        "document_id",
        "top_level_section",
        "records",
    ],
].reset_index(drop=True)

,document_id,top_level_section,records
0,va_dod_asthma_2025,Appendix C: Assessments of Asthma Severity and Control,10
1,va_dod_asthma_2025,Appendix D: Details of a Comprehensive History and Physical Exam,5
2,va_dod_asthma_2025,Appendix F: Example Asthma Action Plan Templates,8
3,va_dod_asthma_2025,Appendix G: Additional Information on Pharmacotherapy,10
4,va_dod_asthma_2025,Appendix K: Alternative Text Descriptions of Algorithms,5
5,va_dod_ckd_2025,Appendix G. Alternative Text Descriptions of Algorithms,5
6,va_dod_ckd_2025,Appendix H. Management of CKD Table,3
7,va_dod_ckd_2025,Appendix I. Monitoring of CKD Table,4
8,va_dod_ckd_2025,Appendix J. Approaches for eGFR Calculation,4
9,va_dod_ckd_2025,Appendix K. Nephrotoxic Agents and Medication Dose Adjustments in CKD,6
10,va_dod_ckd_2025,Appendix L. List of Pharmacotherapies,7
11,va_dod_ckd_2025,Appendix M. Management of Hyperkalemia,7
12,va_dod_ckd_2025,Appendix N. Chronic Pain Management in CKD,9
13,va_dod_ckd_2025,Appendix O. Military Occupation Exposures and CKD,2
14,va_dod_ckd_2025,Appendix P. Special Considerations when Caring for Older Patients,5
15,va_dod_ckd_2025,Appendix Q. Gadolinium and Iodinated Contrast,4
16,va_dod_ckd_2025,Appendix R. General Medical and Lifestyle Management Recommendations to Improve Standard of Care in CKD Patients,2
17,va_dod_low_back_pain_2022,"Appendix E: Dosing for Select Pharmacologic Agentsa,b",1
18,va_dod_low_back_pain_2022,Appendix F: Glossary,2
19,va_dod_low_back_pain_2022,Appendix I: Alternative Text Descriptions of Algorithm,5
20,va_dod_major_depression_2022,Appendix G: Alternative Text Descriptions of Algorithm,3
21,va_dod_major_depression_2022,Appendix I: Quick Guide to the Patient Health Questionnaire in Clinical Practice,7
22,va_dod_major_depression_2022,Appendix J: Pharmacotherapy,8
23,va_dod_major_depression_2022,Appendix K: Definitions,4
24,va_dod_type2_diabetes_2023,Appendix B: Glycemic Control Targets and Monitoring,2
25,va_dod_type2_diabetes_2023,Appendix C: Pharmacotherapy,8
26,va_dod_type2_diabetes_2023,Appendix I: Alternative Text Descriptions of Algorithm,2

### Фильтрация служебных VA/DoD appendices

Исходные parsed records сохраняются без изменений.

Для retrieval создаётся отдельная версия корпуса, из которой исключаются только заранее классифицированные служебные VA/DoD appendices. Клинические приложения сохраняются.

In [93]:
va_dod_appendices_to_drop = set(
    appendix_classification.loc[
        appendix_classification[
            "retrieval_status"
        ].eq("DROP"),
        "top_level_section",
    ]
)

len(va_dod_appendices_to_drop)

28

In [94]:
retrieval_records_df = (
    corpus_records_df.copy()
)

drop_appendix_mask = (
    retrieval_records_df["source"].eq("VA/DoD")
    & retrieval_records_df[
        "top_level_section"
    ].isin(
        va_dod_appendices_to_drop
    )
)

retrieval_records_df = (
    retrieval_records_df.loc[
        ~drop_appendix_mask
    ]
    .reset_index(drop=True)
)

In [ ]:
records_after_appendix_filtering = len(
    retrieval_records_df
)

print(
    "Records after appendix filtering:",
    records_after_appendix_filtering,
)

In [95]:
pd.DataFrame(
    {
        "stage": [
            "parsed corpus",
            "after appendix filtering",
        ],
        "records": [
            len(corpus_records_df),
            len(retrieval_records_df),
        ],
    }
)

                      stage  records
0             parsed corpus     1751
1  after appendix filtering     1417

In [96]:
drop_appendix_mask.sum()

np.int64(334)

In [97]:
remaining_dropped_appendices = (
    retrieval_records_df[
        retrieval_records_df[
            "top_level_section"
        ].isin(
            va_dod_appendices_to_drop
        )
    ][
        [
            "document_id",
            "top_level_section",
        ]
    ]
    .drop_duplicates()
)

remaining_dropped_appendices

Empty DataFrame
Columns: [document_id, top_level_section]
Index: []

In [98]:
non_appendix_inventory = (
    retrieval_records_df[
        ~retrieval_records_df[
            "top_level_section"
        ].str.startswith(
            "Appendix",
            na=False,
        )
    ]
    .groupby(
        [
            "document_id",
            "top_level_section",
        ]
    )
    .agg(
        records=("text", "size"),
    )
    .reset_index()
    .sort_values(
        [
            "document_id",
            "top_level_section",
        ]
    )
)

pd.set_option(
    "display.max_rows",
    None,
)

non_appendix_inventory

,document_id,top_level_section,records
0,cdc_sti_2021,Chlamydial Infections,29
1,cdc_sti_2021,Clinical Prevention Guidance,30
2,cdc_sti_2021,"Diseases Characterized by Genital, Anal, or Perianal Ulcers",62
3,cdc_sti_2021,Diseases Characterized by Urethritis and Cervicitis,28
4,cdc_sti_2021,"Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge",47
5,cdc_sti_2021,Ectoparasitic Infections,19
6,cdc_sti_2021,Epididymitis,9
7,cdc_sti_2021,Gonococcal Infections,43
8,cdc_sti_2021,HIV Infection,12
9,cdc_sti_2021,Human Papillomavirus Infections,45
10,cdc_sti_2021,Introduction,1
11,cdc_sti_2021,Management of Persons Who Have a History of Penicillin Allergy,15
12,cdc_sti_2021,Methods,2
13,cdc_sti_2021,Mycoplasma genitalium,8
14,cdc_sti_2021,Pelvic Inflammatory Disease,19
15,cdc_sti_2021,"Proctitis, Proctocolitis, and Enteritis",10
16,cdc_sti_2021,STI Detection Among Special Populations,55
17,cdc_sti_2021,Sexual Assault and Abuse and STIs,22
18,cdc_sti_2021,"Sexually Transmitted Infections Treatment Guidelines, 2021",4
19,cdc_sti_2021,Syphilis,96
20,cdc_sti_2021,Viral Hepatitis,43
21,va_dod_asthma_2025,I. Introduction,1
22,va_dod_asthma_2025,II. Background,7
23,va_dod_asthma_2025,III. Scope of This Guideline,3
24,va_dod_asthma_2025,IV. Highlighted Features of This Guideline,4
25,va_dod_asthma_2025,IX. Recommendations,33
26,va_dod_asthma_2025,V. Guideline Development Team,2
27,va_dod_asthma_2025,VI. Summary of Guideline Development Methodology,12
28,va_dod_asthma_2025,VII. Approach to Care in the Department of Veterans Affairs and the Department of Defense,4
29,va_dod_asthma_2025,VIII. Algorithm,10
30,va_dod_asthma_2025,X. Research Priorities,6
31,va_dod_ckd_2025,I. Introduction,1
32,va_dod_ckd_2025,II. Background,8
33,va_dod_ckd_2025,III. Scope of This Guideline,3
34,va_dod_ckd_2025,IV. Highlighted Features of This Guideline,4
35,va_dod_ckd_2025,IX. Recommendations,43
36,va_dod_ckd_2025,V. Guideline Development Team,3
37,va_dod_ckd_2025,VI. Summary of Guideline Development Methodology,10
38,va_dod_ckd_2025,VII. Approach to Care in the Department of Veterans Affairs and the Department of Defense,4
39,va_dod_ckd_2025,VIII. Algorithm,12
40,va_dod_ckd_2025,X. Research Priorities,7
41,va_dod_low_back_pain_2022,I. Introduction,1
42,va_dod_low_back_pain_2022,II. Background,5
43,va_dod_low_back_pain_2022,III. Scope of this Guideline,3
44,va_dod_low_back_pain_2022,IV. Highlighted Features of this Guideline,3
45,va_dod_low_back_pain_2022,IX. Recommendations,56
46,va_dod_low_back_pain_2022,V. Guideline Development Team,3
47,va_dod_low_back_pain_2022,VI. Summary of Guideline Development Methodology,10
48,va_dod_low_back_pain_2022,VII. Approach to Care in Department of Veterans Affairs and Department of Defense,4
49,va_dod_low_back_pain_2022,VIII. Algorithm,6
50,va_dod_low_back_pain_2022,X. Research Priorities,15
51,va_dod_major_depression_2022,I. Introduction,1
52,va_dod_major_depression_2022,II. Background,5
53,va_dod_major_depression_2022,III. Scope of this Guideline,3
54,va_dod_major_depression_2022,IV. Highlighted Features of this Guideline,3
55,va_dod_major_depression_2022,IX. Recommendations,55
56,va_dod_major_depression_2022,V. Guideline Development Team,3
57,va_dod_major_depression_2022,VI. Summary of Guideline Development Methodology,9
58,va_dod_major_depression_2022,VII. Approach to Care in Department of Veterans Affairs and Department of Defense,3
59,va_dod_major_depression_2022,VIII. Algorithm,6
60,va_dod_major_depression_2022,X. Research Priorities,8
61,va_dod_pregnancy_2023,I. Introduction,1
62,va_dod_pregnancy_2023,I. Introduction ........................................................................................................... 6 II. Background ........................................................................................................... 6,1
63,va_dod_pregnancy_2023,II. Background,11
64,va_dod_pregnancy_2023,III. Scope of This Guideline,3
65,va_dod_pregnancy_2023,IV. Highlighted Features of This Guideline,10
66,va_dod_pregnancy_2023,IX. Algorithm,7
67,va_dod_pregnancy_2023,V. Guideline Development Team............................................................................ 18 VI. Summary of Guideline Development Methodology ......................................... 20,2
68,va_dod_pregnancy_2023,VI. Summary of Guideline Development Methodology,12
69,va_dod_pregnancy_2023,VII. Approach to Care in the Department of Veterans Affairs and the Department of Defense,3
70,va_dod_pregnancy_2023,VIII. Recommendations,49
71,va_dod_pregnancy_2023,X. Routine Pregnancy Care,19
72,va_dod_pregnancy_2023,X. Routine Pregnancy Care .................................................................................... 78,2
73,va_dod_pregnancy_2023,XI. Referral Indications,7
74,va_dod_pregnancy_2023,XII. Emerging Topics,6
75,va_dod_pregnancy_2023,XIII. Research Priorities,18
76,va_dod_type2_diabetes_2023,I. Introduction,1
77,va_dod_type2_diabetes_2023,I. Introduction ........................................................................................................... 5,1
78,va_dod_type2_diabetes_2023,II. Background,6
79,va_dod_type2_diabetes_2023,III. Scope of This Guideline,3
80,va_dod_type2_diabetes_2023,IV. Highlighted Features of this Guideline,4
81,va_dod_type2_diabetes_2023,IX. Recommendations,52
82,va_dod_type2_diabetes_2023,V. Guideline Development Team,3
83,va_dod_type2_diabetes_2023,V. Guideline Development Team............................................................................ 11,1
84,va_dod_type2_diabetes_2023,VI. Summary of Guideline Development Methodology,10
85,va_dod_type2_diabetes_2023,VII. Approach to Care in the Department of Veterans Affairs and the Department of Defense,4
86,va_dod_type2_diabetes_2023,VIII. Algorithm,6
87,va_dod_type2_diabetes_2023,X. Research Priorities,16
88,va_dod_type2_diabetes_2023,X. Research Priorities ............................................................................................. 71,1
89,who_hypertension_2021,1 Introduction,2
90,who_hypertension_2021,2 Method for developing the guideline,7
91,who_hypertension_2021,3 Recommendations,19
92,who_hypertension_2021,4 Special settings,4
93,who_hypertension_2021,"5 Publication, implementation, evaluation and research gaps",6
94,who_hypertension_2021,6 Implementation tools,4

### Фильтрация служебных основных разделов

Помимо приложений, часть основных разделов документов описывает создание guideline,
состав рабочей группы и будущие исследовательские направления.

Для baseline retrieval такие разделы исключаются, поскольку они не содержат информации,
непосредственно необходимой для ответа на клинические вопросы.

При этом сохраняются introduction/background, scope, clinical recommendations,
algorithms, special settings и другие разделы, потенциально содержащие клинический контекст.

In [99]:
NON_APPENDIX_DROP_RULES = [
    # VA/DoD
    "Guideline Development Team",
    "Summary of Guideline Development Methodology",
    "Research Priorities",

    # WHO
    "Method for developing the guideline",
    "Publication, implementation, evaluation and research gaps",

    # CDC
    "Methods",
]


def should_drop_non_appendix_section(title):
    title_lower = title.lower()

    return any(
        pattern.lower() in title_lower
        for pattern in NON_APPENDIX_DROP_RULES
    )

In [100]:
non_appendix_to_drop = (
    non_appendix_inventory[
        non_appendix_inventory[
            "top_level_section"
        ].apply(
            should_drop_non_appendix_section
        )
    ]
    .reset_index(drop=True)
)

non_appendix_to_drop

,document_id,top_level_section,records
0,cdc_sti_2021,Methods,2
1,va_dod_asthma_2025,V. Guideline Development Team,2
2,va_dod_asthma_2025,VI. Summary of Guideline Development Methodology,12
3,va_dod_asthma_2025,X. Research Priorities,6
4,va_dod_ckd_2025,V. Guideline Development Team,3
5,va_dod_ckd_2025,VI. Summary of Guideline Development Methodology,10
6,va_dod_ckd_2025,X. Research Priorities,7
7,va_dod_low_back_pain_2022,V. Guideline Development Team,3
8,va_dod_low_back_pain_2022,VI. Summary of Guideline Development Methodology,10
9,va_dod_low_back_pain_2022,X. Research Priorities,15
10,va_dod_major_depression_2022,V. Guideline Development Team,3
11,va_dod_major_depression_2022,VI. Summary of Guideline Development Methodology,9
12,va_dod_major_depression_2022,X. Research Priorities,8
13,va_dod_pregnancy_2023,V. Guideline Development Team............................................................................ 18 VI. Summary of Guideline Development Methodology ......................................... 20,2
14,va_dod_pregnancy_2023,VI. Summary of Guideline Development Methodology,12
15,va_dod_pregnancy_2023,XIII. Research Priorities,18
16,va_dod_type2_diabetes_2023,V. Guideline Development Team,3
17,va_dod_type2_diabetes_2023,V. Guideline Development Team............................................................................ 11,1
18,va_dod_type2_diabetes_2023,VI. Summary of Guideline Development Methodology,10
19,va_dod_type2_diabetes_2023,X. Research Priorities,16
20,va_dod_type2_diabetes_2023,X. Research Priorities ............................................................................................. 71,1
21,who_hypertension_2021,2 Method for developing the guideline,7
22,who_hypertension_2021,"5 Publication, implementation, evaluation and research gaps",6

In [101]:
drop_non_appendix_mask = (
    ~retrieval_records_df[
        "top_level_section"
    ].str.startswith(
        "Appendix",
        na=False,
    )
    & retrieval_records_df[
        "top_level_section"
    ].apply(
        should_drop_non_appendix_section
    )
)

retrieval_records_df = (
    retrieval_records_df.loc[
        ~drop_non_appendix_mask
    ]
    .reset_index(drop=True)
)

drop_non_appendix_mask.sum()

np.int64(166)

In [ ]:
retrieval_summary = pd.DataFrame(
    {
        "stage": [
            "parsed corpus",
            "after appendix filtering",
            "final retrieval corpus",
        ],
        "records": [
            len(corpus_records_df),
            records_after_appendix_filtering,
            len(retrieval_records_df),
        ],
    }
)

retrieval_summary

                      stage  records
0             parsed corpus     1751
1  after appendix filtering     1382
2    final retrieval corpus     1251

In [103]:
retrieval_records_df.groupby(
    "document_id"
).size().reset_index(
    name="records"
)

                    document_id  records
0                  cdc_sti_2021      597
1            va_dod_asthma_2025      100
2               va_dod_ckd_2025      133
3     va_dod_low_back_pain_2022       86
4  va_dod_major_depression_2022       98
5         va_dod_pregnancy_2023      119
6    va_dod_type2_diabetes_2023       89
7         who_hypertension_2021       29

### Итоговый retrieval corpus

После структурного parsing и фильтрации служебных разделов retrieval corpus содержит 1251 record из 8 клинических документов.

Из корпуса исключены:
- библиографические разделы `References`;
- front matter;
- методология разработки guideline;
- списки участников;
- поисковые стратегии;
- служебные abbreviation lists;
- historical recommendation categorization;
- другие явно неклинические приложения.

Клинические рекомендации, algorithms, diagnostic and monitoring information,
pharmacotherapy, dosing и клинически полезные appendices сохранены.

Исходный parsed corpus при этом остаётся неизменным; фильтрация применяется только к retrieval corpus.

## 14. Chunking

Dense retrieval работает не с целыми документами, а с отдельными фрагментами текста — chunks.

Слишком крупный chunk может содержать несколько разных тем и давать менее точный embedding.
Слишком маленький chunk теряет контекст, необходимый для интерпретации рекомендации.

Поэтому размер chunk нельзя выбирать произвольно. Сначала анализируем длину уже полученных structured records и определяем, требуется ли дополнительное разбиение.

In [104]:
retrieval_records_df = retrieval_records_df.copy()

retrieval_records_df["char_count"] = (
    retrieval_records_df["text"].str.len()
)

retrieval_records_df["word_count"] = (
    retrieval_records_df["text"]
    .str.split()
    .str.len()
)

retrieval_records_df[
    [
        "char_count",
        "word_count",
    ]
].describe(
    percentiles=[
        0.50,
        0.75,
        0.90,
        0.95,
        0.99,
    ]
)

        char_count   word_count
count  1251.000000  1251.000000
mean   1675.223821   245.045564
std    1223.099497   180.087002
min      10.000000     2.000000
50%    1365.000000   197.000000
75%    2837.500000   413.500000
90%    3442.000000   505.000000
95%    3692.500000   546.000000
99%    4302.500000   636.000000
max    5522.000000   819.000000

In [105]:
retrieval_records_df.nlargest(
    20,
    "word_count",
)[
    [
        "document_id",
        "section_path",
        "pdf_page",
        "word_count",
        "char_count",
        "text",
    ]
]

                   document_id  \
524               cdc_sti_2021
498               cdc_sti_2021
415               cdc_sti_2021
103               cdc_sti_2021
35                cdc_sti_2021
40                cdc_sti_2021
611               cdc_sti_2021
855            va_dod_ckd_2025
511               cdc_sti_2021
58                cdc_sti_2021
461               cdc_sti_2021
14       who_hypertension_2021
60                cdc_sti_2021
918  va_dod_low_back_pain_2022
895  va_dod_low_back_pain_2022
13       who_hypertension_2021
18       who_hypertension_2021
775            va_dod_ckd_2025
20       who_hypertension_2021
892  va_dod_low_back_pain_2022

                                                                                                                                  section_path  \
524                   Human Papillomavirus Infections > Cervical Cancer > Follow-Up of Abnormal Cytology and Human Papillomavirus Test Results
498                                                                             Human Papillomavirus Infections > Anogenital Warts > Treatment
415  Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Bacterial Vaginosis > Diagnostic Considerations
103                          STI Detection Among Special Populations > Women Who Have Sex with Women and Women Who Have Sex with Women and Men
35                                                                        Clinical Prevention Guidance > STI and HIV Infection Risk Assessment
40                                                      Clinical Prevention Guidance > Primary Prevention Methods > Condoms > External Condoms
611                                              Sexual Assault and Abuse and STIs > Adolescents and Adults > Risk for Acquiring HIV Infection
855                                                                                              Appendix Q. Gadolinium and Iodinated Contrast
511                                                              Human Papillomavirus Infections > Cervical Cancer > Screening Recommendations
58                                                                                             Clinical Prevention Guidance > Partner Services
461                                                                                    Pelvic Inflammatory Disease > Diagnostic Considerations
14                                                                                                 3 Recommendations > 3.5 Combination therapy
60                                                                 Clinical Prevention Guidance > Partner Services > Expedited Partner Therapy
918                                                                                                   IX. Recommendations > D. Pharmacotherapy
895                                                                                   IX. Recommendations > B. Patient Education and Self-care
13                                                                                                 3 Recommendations > 3.5 Combination therapy
18                                                                                          3 Recommendations > 3.7 Frequency of re-assessment
775                                                                                                                        IX. Recommendations
20                                                           3 Recommendations > 3.8 Administration of treatment by nonphysician professionals
892                                                                                IX. Recommendations > A. Evaluation and Diagnostic Approach

     pdf_page  word_count  char_count  \
524       113         819        5380
498       105         789        5522
415        86         737        4963
103        22         722        4873
35          5         713        4552
40          7         707        4790
611       132         693        4646
855       165         688        4014
511       109         683        4273
58         11         652        4521
461        97         649        4343
14         27         643        4346
60         12         636        4317
918        57         636        3943
895        35         624        4264
13         26         622        4455
18         30         614        4018
775        49         610        4094
20         32         608        4168
892        33         606        4076

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   text
524                                                                                                                                                TABLE 2. Comparison of 2012 and 2019 consensus recommendations for management of common abnormalities — American Society for Colposcopy and Cervical Pathology Current Pap Current HPV result test result Previous result Negative ASC-US Unknown or HPV negative* Negative LSIL Unknown or HPV negative* Negative ASC-H Noncontributory Noncontributory AGC Noncontributory Positive NILM Unknown or HPV negative* HPV positive† Positive NILM Positive for genotype HPV 16, NILM Noncontributory HPV 18, or both Positive for genotype HPV 16, ASC-US or LSIL Noncontributory HPV 18, or both Positive ASC-US or LSIL Unknown or HPV positive Positive ASC-US or LSIL Negative screening results with HPV testing or HPV plus Pap testing within the previous 5 yrs Positive ASC-US or LSIL Colposcopy confirming the absence of high-grade lesion within the past yr Positive ASC-H Noncontributory Positive untyped, positive for HSIL Noncontributory genotype other than HPV 16, or negative Positive for genotype HPV 16 HSIL Noncontributory Sources: Massad LS, Einstein MH, Huh WK, et al.; 2012 ASCCP Consensus Guidelines Conference. 2012 updated consensus guidelines for the management of abnormal cervical cancer screening tests and cancer precursors. Obstet Gynecol 2013;121:829–46; Perkins RB, Guido RS, Castle PE, et al; 2019 ASCCP Risk-Based Management Consensus Guidelines Committee. 2019 ASCCP risk-based management consensus guidelines for abnormal cervical cancer screening tests and cancer precursors. J Low Genit Tract Dis 2020;24:102–31; Perkins R, Guido R, Saraiya M, et al. Summary of current guidelines for cervical cancer screening and management of abnormal test results: 2016–2020. J Womens Health (Larchmt) 2021;30:5–13. Abbreviations: AGC = atypical glandular cells; AIS = adenocarcinoma in situ; ASC-H = atypical squamous cells cannot exclude high-grade squamous intraepithelial lesion; ASC-US = atypical squamous cells of undetermined significance; CIN = cervical intraepithelial neoplasia; HPV = human papillomavirus; HSIL = high-grade squamous intraepithelial lesion; LSIL = low-grade squamous intraepithelial lesion; NILM = negative for intraepithelial lesion or malignancy; Pap = Papanicolaou. * Colposcopy may be warranted for patients with a history of high-grade lesions (CIN 2 or CIN 3, histologic or cytologic HSIL, ASC-H, AGC, or AIS). † Previous Pap test results do not modify the recommendation; colposcopy is always recommended for two consecutive HPV-positive tests. § Negative HPV test or cotest (HPV plus Pap test) results only reduce risk sufficiently to defer colposcopy if performed for screening purposes within the last 5 years. Colposcopy is still warranted if negative HPV test or cotest results occurred in the context of surveillance for a previous abnormal result. ¶ Expedited treatment is preferred for nonpregnant patients aged ≥25 years. Colposcopy with biopsy is an acceptable option if desired by patient after shared decision-making. űű If a patient has a high-grade cytology (Pap test) result (i.e., HSIL) and an HPV test that is positive for HPV type 16, then treatment with a loop electrosurgical excision procedure (LEEP) is preferred. A colposcopy with biopsy is not necessary to confirm the diagnosis first. űű If a patient who has not been screened in more than 5 years (i.e., rarely screened) has an HSIL cytology result and a positive HPV test (regardless of type), then treatment with LEEP is preferred. A colposcopy with biopsy is not necessary to confirm the diagnosis first. űű When considering treatment without confirmatory biopsy, shared decision-making with the patient is important. Considerations include age, concern about cancer, ability to follow up, financial concerns, and Management by 2012 Management by 2019 guidelines guidelines Repeat Pap plus HPV testing Repeat HPV test with or without in 3 yrs concurrent Pap test in 3 yrs Repeat Pap plus HPV testing Repeat HPV test with or without in 1 yr preferred, colposcopy concurrent Pap test in 1 yr acceptable Colposcopy Colposcopy Colposcopy Colposcopy Repeat Pap plus HPV testing Repeat HPV test with or without in 1 yr concurrent Pap test in 1 yr Colposcopy Colposcopy Colposcopy Colposcopy Not applicable, genotyping Colposcopy not recommended for ASC-US or LSIL in 2012 Colposcopy Colposcopy Colposcopy Repeat HPV test with or without concurrent Pap test in 1 yr§ Colposcopy Repeat HPV test with or without concurrent Pap test in 1 yr§ Colposcopy Colposcopy or expedited treatment Colposcopy or expedited Colposcopy or expedited treatment treatment Expedited treatment¶ Colposcopy or expedited treatment concerns about the potential effect of treatment on a future pregnancy. • When primary HPV testing is used for screening, cytology testing should be performed for all positive HPV test results to help determine the next steps in management. űű Ideally, cytology testing should be performed by the laboratory as a reflex test from the same specimen so the patient does not need to return to the clinic. Colposcopy is recommended if HPV genotyping is positive for types 16 or 18, and it can be considered if it is infeasible for the patient to return for cytology alone (1274). űű HPV 16 is the highest-risk HPV type. Expedited treatment should be considered for HSIL cytology results, and colposcopy is recommended in all other cases, even if the cytology test is normal.

In [106]:
pd.set_option(
    "display.max_colwidth",
    300,
)

In [107]:
retrieval_records_df.groupby(
    "source"
)["word_count"].describe(
    percentiles=[
        0.50,
        0.90,
        0.95,
        0.99,
    ]
)

,count,mean,std,min,50%,90%,95%,99%,max
source,,,,,,,,,
CDC,597.0,164.437186,147.296925,6.0,122.0,369.4,465.2,693.56,819.0
VA/DoD,625.0,315.358400,175.437675,2.0,346.0,528.0,557.8,594.00,688.0
WHO,29.0,389.103448,172.327832,48.0,382.0,609.2,618.8,637.12,643.0

### Вывод по размеру structured records

Structured record нельзя напрямую считать retrieval chunk.

Распределение длины неоднородно:

- медиана — около 201 слова;
- 25% records длиннее 419 слов;
- 10% длиннее 508 слов;
- максимальный record содержит 819 слов;
- VA/DoD и WHO в среднем существенно длиннее CDC.

Это означает, что часть records можно оставить целиком, а длинные records необходимо дополнительно разбивать.

При этом размер chunk должен задаваться в токенах embedding-модели, а не в словах, поскольку именно tokenizer embedding-модели определяет фактическую длину входа и риск truncation.

Поэтому сначала фиксируем embedding model для baseline dense retrieval, а затем подбираем token-based chunking.

In [ ]:
from transformers import AutoTokenizer

EMBEDDING_MODEL_NAME = "BAAI/bge-base-en-v1.5"

embedding_tokenizer = AutoTokenizer.from_pretrained(
    EMBEDDING_MODEL_NAME
)

In [109]:
def count_embedding_tokens(text):
    return len(
        embedding_tokenizer.encode(
            text,
            add_special_tokens=False,
        )
    )


retrieval_records_df["token_count"] = (
    retrieval_records_df["text"]
    .apply(count_embedding_tokens)
)

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (784 > 512). Running this sequence through the model will result in indexing errors

In [110]:
retrieval_records_df[
    "token_count"
].describe(
    percentiles=[
        0.50,
        0.75,
        0.90,
        0.95,
        0.99,
    ]
)

count    1251.000000
mean      373.112710
std       280.499356
min         3.000000
50%       314.000000
75%       607.500000
90%       753.000000
95%       836.500000
99%       965.000000
max      2391.000000
Name: token_count, dtype: float64

In [111]:
(
    retrieval_records_df[
        "token_count"
    ] > 512
).value_counts()

token_count
False    846
True     405
Name: count, dtype: int64

In [112]:
long_record_share = (
    retrieval_records_df[
        "token_count"
    ]
    .gt(512)
    .mean()
)

long_record_share

np.float64(0.3237410071942446)

### Стратегия chunking

Анализ длины показал, что structured records нельзя напрямую использовать как retrieval chunks:

- медиана составляет 314 токенов;
- 32.4% records превышают 512 токенов;
- максимальный record содержит 2391 токена.

Для baseline используется token-based chunking с целевым размером 384 токена и overlap 64 токена.

Chunking выполняется внутри одного structured record, поэтому chunk никогда не смешивает разные `section_path` и сохраняет точную page-level provenance.

В embedding input дополнительно включаются название документа и `section_path`, чтобы короткие или локальные фрагменты сохраняли смысловой контекст.

In [113]:
TARGET_CHUNK_TOKENS = 384
CHUNK_OVERLAP_TOKENS = 64

embedding_tokenizer.model_max_length

512

In [114]:
def build_embedding_prefix(row):
    return (
        f'Document: {row["document_title"]}\n'
        f'Section: {row["section_path"]}\n\n'
    )


def split_record_into_chunks(
    row,
    tokenizer,
    target_tokens=TARGET_CHUNK_TOKENS,
    overlap_tokens=CHUNK_OVERLAP_TOKENS,
):
    prefix = build_embedding_prefix(row)

    prefix_token_count = len(
        tokenizer.encode(
            prefix,
            add_special_tokens=False,
        )
    )

    body_budget = (
        target_tokens
        - prefix_token_count
    )

    if body_budget <= overlap_tokens:
        raise ValueError(
            "Metadata prefix is too long "
            "for the selected chunk size."
        )

    encoded = tokenizer(
        row["text"],
        add_special_tokens=False,
        return_offsets_mapping=True,
        truncation=False,
    )

    offsets = encoded["offset_mapping"]
    n_tokens = len(offsets)

    chunks = []

    if n_tokens == 0:
        return chunks

    start_token = 0
    chunk_index = 0

    while start_token < n_tokens:
        end_token = min(
            start_token + body_budget,
            n_tokens,
        )

        char_start = offsets[start_token][0]
        char_end = offsets[end_token - 1][1]

        chunk_text = (
            row["text"][char_start:char_end]
            .strip()
        )

        embedding_text = (
            prefix + chunk_text
        )

        chunks.append(
            {
                "record_id": row["record_id"],
                "chunk_id": (
                    f'{row["record_id"]}_chunk_{chunk_index:02d}'
                ),
                "document_id": row["document_id"],
                "source": row["source"],
                "document_title": row["document_title"],
                "year": row["year"],
                "section_path": row["section_path"],
                "page": row["page"],
                "pdf_page": row["pdf_page"],
                "chunk_index": chunk_index,
                "text": chunk_text,
                "embedding_text": embedding_text,
            }
        )

        if end_token == n_tokens:
            break

        start_token = (
            end_token
            - overlap_tokens
        )

        chunk_index += 1

    return chunks

### Формирование chunks

Разбиваем каждый structured record на один или несколько retrieval chunks.

Chunking выполняется независимо внутри каждого record, поэтому chunks не смешивают разные документы, страницы или `section_path`.

После разбиения проверяем общее количество полученных chunks.

In [115]:
retrieval_records_df = (
    retrieval_records_df
    .reset_index(drop=True)
    .copy()
)

retrieval_records_df["record_id"] = [
    f"record_{i:05d}"
    for i in range(len(retrieval_records_df))
]

In [116]:
chunks = []

for _, row in retrieval_records_df.iterrows():
    chunks.extend(
        split_record_into_chunks(
            row,
            embedding_tokenizer,
        )
    )

chunks_df = pd.DataFrame(chunks)

len(chunks_df)

2135

### Проверка длины полного embedding input

Embedding-модель получает не только текст chunk, но и metadata-prefix с названием документа и `section_path`.

Поэтому считаем длину именно полного `embedding_text`, который будет передаваться embedding-модели.

Цель проверки — убедиться, что выбранный chunk size действительно укладывается в заданный token budget.

In [117]:
chunks_df["embedding_token_count"] = (
    chunks_df["embedding_text"]
    .apply(
        lambda text: len(
            embedding_tokenizer.encode(
                text,
                add_special_tokens=True,
            )
        )
    )
)

chunks_df[
    "embedding_token_count"
].describe(
    percentiles=[
        0.50,
        0.75,
        0.90,
        0.95,
        0.99,
    ]
)

count    2135.000000
mean      279.805152
std       114.235610
min        29.000000
50%       324.000000
75%       386.000000
90%       386.000000
95%       386.000000
99%       386.000000
max       387.000000
Name: embedding_token_count, dtype: float64

### Проверка отсутствия truncation

Проверяем, что ни один `embedding_text` не превышает максимальную длину входа tokenizer.

Если результат — пустой DataFrame, embedding-модель сможет обработать все chunks без автоматического обрезания текста.

In [118]:
chunks_df[
    chunks_df["embedding_token_count"]
    > embedding_tokenizer.model_max_length
]

Empty DataFrame
Columns: [record_id, chunk_id, document_id, source, document_title, year, section_path, page, pdf_page, chunk_index, text, embedding_text, embedding_token_count]
Index: []

### Проверка длины текста внутри chunks

Отдельно считаем длину только содержимого chunk без metadata-prefix.

Это позволяет проверить качество самого разбиения и обнаружить слишком короткие chunks, которые могут возникать как остаток в конце длинного record.

In [119]:
chunks_df["text_token_count"] = (
    chunks_df["text"]
    .apply(
        lambda text: len(
            embedding_tokenizer.encode(
                text,
                add_special_tokens=False,
            )
        )
    )
)

chunks_df[
    "text_token_count"
].describe(
    percentiles=[
        0.01,
        0.05,
        0.50,
        0.95,
        0.99,
    ]
)

count    2135.000000
mean      245.130211
std       114.788787
min         3.000000
1%         15.680000
5%         52.700000
50%       283.000000
95%       361.000000
99%       364.660000
max       370.000000
Name: text_token_count, dtype: float64

**Наблюдение:**

Большинство chunks имеют содержательный размер, однако минимальная длина составляет всего несколько токенов.

Такие короткие chunks могут быть двух типов:

1. короткий исходный record — это допустимо;
2. искусственный хвост, появившийся после разбиения длинного record — такой chunk желательно устранить.

Поэтому отдельно проверяем короткие chunks с `chunk_index > 0`.

### Проверка коротких хвостовых chunks

Не удаляем все короткие chunks автоматически: короткий исходный record может быть содержательно полноценным.

Проблемой считаем прежде всего короткий chunk с `chunk_index > 0`, поскольку он возник в результате splitting и может представлять собой небольшой остаток предыдущего record.

In [120]:
SHORT_CHUNK_THRESHOLD = 64

short_chunk_summary = pd.DataFrame(
    {
        "short_first_chunks": [
            (
                (chunks_df["text_token_count"] < SHORT_CHUNK_THRESHOLD)
                & (chunks_df["chunk_index"] == 0)
            ).sum()
        ],
        "short_split_tails": [
            (
                (chunks_df["text_token_count"] < SHORT_CHUNK_THRESHOLD)
                & (chunks_df["chunk_index"] > 0)
            ).sum()
        ],
    }
)

short_chunk_summary

   short_first_chunks  short_split_tails
0                 144                  0

### Просмотр коротких хвостов

Выводим только короткие chunks, появившиеся после splitting.

Проверяем, действительно ли это искусственные остатки текста. Если таких chunks заметное количество, корректируем алгоритм chunking так, чтобы маленький хвост объединялся с предыдущим окном.

In [121]:
chunks_df[
    (chunks_df["text_token_count"] < SHORT_CHUNK_THRESHOLD)
    & (chunks_df["chunk_index"] > 0)
][
    [
        "document_id",
        "section_path",
        "pdf_page",
        "chunk_index",
        "text_token_count",
        "text",
    ]
]

Empty DataFrame
Columns: [document_id, section_path, pdf_page, chunk_index, text_token_count, text]
Index: []

### Результат проверки chunking

Token-based chunking прошёл основные sanity-checks:

- сформировано 2135 chunks из 1251 structured records;
- ни один `embedding_text` не превышает максимальную длину tokenizer;
- максимальная длина полного embedding input составляет 388 токенов;
- короткие chunks встречаются только среди исходно коротких records;
- искусственных коротких хвостов после splitting не обнаружено (`short_split_tails = 0`);
- chunks не пересекают границы `section_path` и сохраняют page-level provenance.

Для baseline фиксируем параметры:

- target chunk size: 384 tokens;
- overlap: 64 tokens.

На этом этапе стратегия chunking считается зафиксированной.

Сейчас у chunks есть chunk_index, но он начинается заново для каждого record. Для retrieval evaluation и отладки нужен уникальный chunk_id.

### Идентификаторы records и chunks

Для воспроизводимой retrieval evaluation каждому исходному structured record присваивается уникальный `record_id`, а каждому chunk — уникальный `chunk_id`.

Это позволяет:

- однозначно связать найденный chunk с исходным record;
- отслеживать несколько chunks, полученных из одного record;
- анализировать retrieval errors;
- сравнивать результаты разных конфигураций chunking и retrieval.

Проверяем, что `chunk_id` уникален, а число уникальных `record_id` в chunks совпадает с числом исходных records.

In [122]:
retrieval_records_df = (
    retrieval_records_df
    .reset_index(drop=True)
    .copy()
)

retrieval_records_df["record_id"] = [
    f"record_{i:05d}"
    for i in range(len(retrieval_records_df))
]

In [123]:
chunks_df["chunk_id"].is_unique

True

In [124]:
chunks_df["record_id"].nunique(), len(retrieval_records_df)

(1251, 1251)

**Результат.**

Все `chunk_id` уникальны, а все 1251 исходных records представлены в `chunks_df`.

Идентификаторы сформированы корректно.

## 15. Dense embeddings

Каждый retrieval chunk преобразуется в dense vector с помощью
`BAAI/bge-base-en-v1.5`.

Семантически похожие тексты должны иметь близкие векторы в embedding space.
В дальнейшем query будет преобразовываться тем же encoder, после чего
релевантные chunks будут находиться по близости между query embedding и
document embeddings.

Для baseline embeddings L2-нормализуются. Поэтому cosine similarity между
двумя векторами эквивалентна их dot product, что удобно для последующего
vector search.

In [125]:
import numpy as np
import torch

from sentence_transformers import SentenceTransformer

device = (
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

device

'cuda'

In [126]:
embedding_model = SentenceTransformer(
    EMBEDDING_MODEL_NAME,
    device=device,
)

embedding_model

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 7656.16it/s]

SentenceTransformer(
  (0): Transformer({'transformer_task': 'feature-extraction', 'modality_config': {'text': {'method': 'forward', 'method_output_name': 'last_hidden_state'}}, 'module_output_name': 'token_embeddings', 'architecture': 'BertModel'})
  (1): Pooling({'embedding_dimension': 768, 'pooling_mode': 'cls', 'include_prompt': True})
  (2): Normalize({'module_input_name': 'sentence_embedding', 'module_output_name': 'sentence_embedding'})
)

In [ ]:
embedding_model.get_sentence_embedding_dimension()

### Построение document embeddings

Для индексации кодируем `embedding_text`, а не только чистый текст chunk.

`embedding_text` содержит название документа и `section_path`, поэтому
embedding получает дополнительный контекст о том, к какому guideline и
клиническому разделу относится локальный фрагмент.

Document embeddings считаются один раз при построении knowledge base.

In [128]:
document_embeddings = embedding_model.encode(
    chunks_df["embedding_text"].tolist(),
    batch_size=32,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True,
)

Batches: 100%|██████████| 67/67 [00:22<00:00,  2.98it/s]

In [129]:
document_embeddings.shape

(2135, 768)

### Проверка embeddings

Проверяем три базовых свойства:

- число embeddings совпадает с числом chunks;
- в embeddings нет `NaN` или бесконечных значений;
- после L2-нормализации длина каждого вектора приблизительно равна 1.

In [130]:
embedding_checks = {
    "n_chunks": len(chunks_df),
    "n_embeddings": document_embeddings.shape[0],
    "embedding_dim": document_embeddings.shape[1],
    "has_nan": np.isnan(document_embeddings).any(),
    "has_inf": np.isinf(document_embeddings).any(),
}

embedding_checks

{'n_chunks': 2135,
 'n_embeddings': 2135,
 'embedding_dim': 768,
 'has_nan': np.False_,
 'has_inf': np.False_}

In [131]:
embedding_norms = np.linalg.norm(
    document_embeddings,
    axis=1,
)

pd.Series(
    embedding_norms,
    name="embedding_norm",
).describe()

count    2.135000e+03
mean     1.000000e+00
std      3.157785e-08
min      9.999999e-01
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      1.000000e+00
Name: embedding_norm, dtype: float64

In [132]:
assert document_embeddings.shape[0] == len(chunks_df)
assert not np.isnan(document_embeddings).any()
assert not np.isinf(document_embeddings).any()
assert np.allclose(
    embedding_norms,
    1.0,
    atol=1e-5,
)

print("Embedding sanity checks passed.")

Embedding sanity checks passed.

## 16. Проверка работы dense retrieval

Перед построением vector index проверяем, что dense retrieval действительно находит
клинически релевантные chunks.

Поскольку embeddings были L2-нормализованы, близость между query и chunk можно
считать через dot product, который в данном случае эквивалентен cosine similarity.

Для BGE запрос кодируется с отдельной retrieval-инструкцией, а chunks документа
кодируются без неё.

На этом этапе мы пока не измеряем итоговое качество retrieval количественно.
Цель — проверить базовую корректность поиска:

- находится ли нужный документ;
- находится ли нужный клинический раздел;
- содержит ли найденный chunk информацию, связанную с запросом.

In [133]:
BGE_QUERY_INSTRUCTION = (
    "Represent this sentence for searching relevant passages: "
)

In [134]:
def encode_query(query):
    query_text = (
        BGE_QUERY_INSTRUCTION
        + query
    )

    query_embedding = embedding_model.encode(
        query_text,
        convert_to_numpy=True,
        normalize_embeddings=True,
    )

    return query_embedding

In [135]:
def dense_search(
    query,
    top_k=5,
):
    query_embedding = encode_query(
        query
    )

    scores = (
        document_embeddings
        @ query_embedding
    )

    top_indices = np.argsort(
        scores
    )[::-1][:top_k]

    results = (
        chunks_df
        .iloc[top_indices]
        .copy()
    )

    results.insert(
        0,
        "score",
        scores[top_indices],
    )

    return results[
        [
            "score",
            "chunk_id",
            "document_id",
            "section_path",
            "page",
            "pdf_page",
            "text",
        ]
    ]

### Проверка на одном клиническом запросе

In [136]:
query = (
    "How should hyperkalemia be managed "
    "in patients with chronic kidney disease?"
)

results = dense_search(
    query,
    top_k=5,
)

pd.set_option(
    "display.max_colwidth",
    300,
)

results

,score,chunk_id,document_id,section_path,page,pdf_page,text
1286,0.798135,record_00834_chunk_01,va_dod_ckd_2025,Appendix M. Management of Hyperkalemia > D. Dietary Considerations,147,147,"for the Evaluation and Management of Chronic Kidney Disease (3) recommends, “Provide advice to limit the intake of foods rich in bioavailable potassium (e.g., processed foods) for people with CKD G3-G5 who have a history of hyperkalemia.” The involvement of a renal dietitian can be helpful, as c..."
1283,0.793694,record_00832_chunk_01,va_dod_ckd_2025,Appendix M. Management of Hyperkalemia > C. Management,146,146,upper limit of normal range They acknowledge that it is not known whether EKG changes are sensitive in the prediction of potentially lethal arrhythmia. The KDIGO 2024 Clinical Practice Guideline for the Evaluation and Management of Chronic Kidney Disease (3) recommends the following steps to man...
1282,0.789073,record_00832_chunk_00,va_dod_ckd_2025,Appendix M. Management of Hyperkalemia > C. Management,146,146,"The aggressiveness of treatment of hyperkalemia depends on the degree of elevation and the presence or absence of electrocardiogram (EKG) findings. Observationally, the risk of death from a given level of hyperkalemia is lower in more advanced CKD, suggesting that there are adaptive mechanisms t..."
1281,0.768300,record_00831_chunk_00,va_dod_ckd_2025,Appendix M. Management of Hyperkalemia > B. Definition,146,146,"An acute episode of hyperkalemia is a potassium result above the upper limit of normal that is not known to be chronic. However, there is no consensus on the magnitude, duration, and frequency of elevated potassium values that define chronicity.(277)"
1284,0.762154,record_00833_chunk_00,va_dod_ckd_2025,Appendix M. Management of Hyperkalemia > C. Management,147,147,• Optimize serum bicarbonate levels • Consider potassium-exchange agents Third-line (Last resort): • Reduce or discontinue RAASi/MRA; restart in future if patient condition allows Providers may consider reducing or stopping ACEI/ARB when eGFR drops below a given eGFR threshold or when hyperkalem...

In [137]:
sanity_queries = [
    "How should asthma severity and control be assessed?",
    "What treatment is recommended for chlamydial infection?",
    "What blood pressure treatment is recommended for adults with hypertension?",
    "What pharmacologic treatments are recommended for major depressive disorder?",
    "How should glycemic control be monitored in type 2 diabetes?",
]

In [138]:
for query in sanity_queries:
    print("\n" + "=" * 100)
    print("QUERY:", query)

    results = dense_search(
        query,
        top_k=3,
    )

    for _, row in results.iterrows():
        print(
            f'\nscore={row["score"]:.3f}'
            f'\n{row["document_id"]}'
            f'\n{row["section_path"]}'
            f'\n{row["text"][:300]}...'
        )

====================================================================================================
QUERY: How should asthma severity and control be assessed?

score=0.765
va_dod_asthma_2025
Appendix C: Assessments of Asthma Severity and Control > A. Assessment of Asthma Severity
Table C-1. Assessment of Asthma Severitya, b, c, d Asthma Severity Description of Asthma Control (assess after trial of 2-3 months of treatment) Mild Controlled on low-intensity treatment (ex: prn low dose ICS-formoterol or low dose ICS + prn rapid-onset LABA/SABA) Moderate Controlled with low or me...

score=0.750
va_dod_asthma_2025
II. Background > B. Classification of Asthma Severity and Control
the initial evaluation of a newly diagnosed patient. This table was carried forward from the 2019 VA/DOD Asthma CPG. The Algorithm within this CPG refers to Appendix C for the initial management of newly diagnosed patients. Decision points in the algorithm are determined by the CPG’s key recommendat...

score=0.749
va_dod_asthma_2025
II. Background > B. Classification of Asthma Severity and Control
Asthma severity is commonly classified as mild, moderate, or severe. The GINA (Global Initiative for Asthma) guidelines were updated in 2024 (3) and shifted the paradigm for asthma classification from symptom burden on initial evaluation to therapy required for adequate control of symptoms. However,...

====================================================================================================
QUERY: What treatment is recommended for chlamydial infection?

score=0.788
cdc_sti_2021
Chlamydial Infections > Chlamydial Infection Among Adolescents and Adults > Treatment
Treating persons with C. trachomatis prevents adverse reproductive health complications and continued sexual transmission. Furthermore, treating their sex partners can prevent reinfection and infection of other partners. Treating pregnant women usually prevents transmission of C. trachomatis to neon...

score=0.763
cdc_sti_2021
Chlamydial Infections > Chlamydial Infection Among Neonates > Ophthalmia Neonatorum Caused by C. trachomatis > Treatment
Recommended Regimen for Chlamydial Infection Among Neonates Erythromycin base or ethyl succinate 50 mg/kg body weight/day orally, divided into 4 doses daily for 14 days* * An association between oral erythromycin and azithromycin and infantile hypertrophic pyloric stenosis (IHPS) has been reported a...

score=0.760
cdc_sti_2021
Chlamydial Infections > Chlamydial Infection Among Adolescents and Adults > Treatment
trointestinal side effects (817). Levofloxacin is an effective treatment alternative but is more expensive. Erythromycin is no longer recommended because of the frequency of gastrointestinal side effects, which can result in nonadherence. When nonadherence to doxycycline regimen is a substantial con...

====================================================================================================
QUERY: What blood pressure treatment is recommended for adults with hypertension?

score=0.778
who_hypertension_2021
3 Recommendations > 3.6 Target blood pressure
6.	 RECOMMENDATION ON TARGET BLOOD PRESSURES
WHO recommends a target blood pressure treatment goal of <140/90 mmHg in all patients
with hypertension without comorbidities.
Strong recommendation, moderate-certainty evidence
WHO recommends a target systolic blood pressure treatment goal of <130 mmHg i...

score=0.767
who_hypertension_2021
3 Recommendations > 3.6 Target blood pressure
treated patients was 20 (for SBP <130 vs <140) and 5 (for SBP 140/90 vs 150–160/95–105).
Summary results from a systematic review focusing on adults 65 years and older by Murad et al (59).
suggests that treatment to a lower BP target in individuals 65 years or older leads to a significant
reduction ...

score=0.765
who_hypertension_2021
6 Implementation tools > 6.1 Guideline recommendations
Graphic summaries of the guideline recommendations are presented below in an algorithmic approach
(Figs 3 and 4). This maps the recommendations to a patient-care pathway.
Fig. 3	 An approach for starting treatment with a single-pill combination
Treat adults with BP ≥140 mmHg or ≥90
(SBP ≥130 mmHg fo...

====================================================================================================
QUERY: What pharmacologic treatments are recommended for major depressive disorder?

score=0.760
va_dod_major_depression_2022
IX. Recommendations > E. Treatment of MDD that is Severe or has a Partial or Limited Response to Initial Treatment
Recommendation 15. We suggest offering a combination of pharmacotherapy and evidence-based psychotherapy for the treatment of patients with MDD characterized as: · Severe (e.g., PHQ-9 >20) · Persistent major depressive disorder (duration greater than two years) · Recurrent (with two or more episodes...

score=0.758
va_dod_major_depression_2022
IX. Recommendations
Topic # Recommendation Strengtha Categoryb Reviewed, Weak for 11. New-replaced When choosing an initial pharmacotherapy, or for patients who have previously responded well to pharmacotherapy, we suggest offering one of the following (not rank ordered): · Bupropion · Mirtazapine · A serotonin-norepin...

score=0.748
va_dod_major_depression_2022
IX. Recommendations > D. Treatment of Uncomplicated MDD
small sample sizes, lack of blinding, high loss of follow-up, and other considerations). The benefits of computer/internet-based psychotherapy over no treatment outweigh the harms. Patient values and preferences varied somewhat. Thus, the Work Group decided upon a Weak for recommendation. Recommenda...

====================================================================================================
QUERY: How should glycemic control be monitored in type 2 diabetes?

score=0.735
va_dod_type2_diabetes_2023
IX. Recommendations > C. Diabetes Mellitus
the following recommendation: For adults with type 2 diabetes mellitus, we suggest using high glycemic variability over time (e.g., fluctuation in HbA1c or fasting blood glucose) as a prognostic indicator for risk of hypoglycemia, morbidity, and mortality....

score=0.725
va_dod_type2_diabetes_2023
IX. Recommendations > E. Pharmacotherapy
Recommendation 25. In adults with type 2 diabetes mellitus, especially those 65 years and older, we suggest prioritizing drug classes other than insulin, sulfonylureas, or meglitinides to minimize the risk of hypoglycemia, if glycemic control can be achieved with other treatments. (Weak for | Review...

score=0.720
va_dod_type2_diabetes_2023
IX. Recommendations > C. Diabetes Mellitus
Discussion Although evidence is increasing that continuous glucose monitoring (CGM) can improve glucose control and might reduce hypoglycemia in T1DM patients, whether CGM improves outcomes in patients with T2DM is unclear. However, the systematic evidence review found that results differed dependin...

### Результат первой проверки dense retrieval

Dense retrieval корректно находит тематически релевантные chunks из нужных
clinical guidelines для нескольких разных медицинских тем.

В ходе ручной проверки запроса о glycemic control при type 2 diabetes была
обнаружена ошибка VA/DoD parser: часть текста ошибочно относилась к subsection
`B. Telehealth` вместо `C. Diabetes Mellitus`. После исправления составных
subsection headings metadata стала корректной.

При этом один медицинский вопрос может иметь релевантную информацию сразу
в нескольких разделах документа. Например, запрос о monitoring glycemic control
находит как рекомендации по HbA1c variability и continuous glucose monitoring,
так и appendix `Glycemic Control Targets and Monitoring`.

Поэтому качество retrieval нельзя оценивать только по совпадению с одним
заранее выбранным `section_path`. Для дальнейшей количественной оценки нужен
отдельный evaluation-набор с разметкой всех допустимых релевантных разделов.

## 17. Количественная оценка dense retrieval

Ручные примеры показывают, что retrieval работает, но не позволяют объективно сравнивать разные настройки.

Для оценки retrieval нужен набор запросов с заранее известным релевантным содержимым.

Используем только `dev`-часть данных. `test` остаётся замороженным и не используется для выбора embedding model, chunk size, overlap, `top_k` или других параметров.

Для каждого evaluation query фиксируем как минимум релевантный `document_id` и, где возможно, релевантный `section_path`.

In [139]:
retrieval_eval = [
    {
        "query": (
            "How should hyperkalemia be managed "
            "in patients with chronic kidney disease?"
        ),
        "relevant_document_id": "va_dod_ckd_2025",
        "relevant_section_contains": "Management of Hyperkalemia",
    },
    {
        "query": (
            "How should asthma severity and control be assessed?"
        ),
        "relevant_document_id": "va_dod_asthma_2025",
        "relevant_section_contains": "Assessments of Asthma Severity and Control",
    },
    {
        "query": (
            "What treatment is recommended "
            "for chlamydial infection in adults?"
        ),
        "relevant_document_id": "cdc_sti_2021",
        "relevant_section_contains": (
            "Chlamydial Infection Among Adolescents and Adults > Treatment"
        ),
    },
    {
        "query": (
            "What blood pressure target is recommended "
            "for adults with hypertension?"
        ),
        "relevant_document_id": "who_hypertension_2021",
        "relevant_section_contains": "Target blood pressure",
    },
    {
        "query": (
            "What pharmacologic treatments are recommended "
            "for major depressive disorder?"
        ),
        "relevant_document_id": "va_dod_major_depression_2022",
        "relevant_section_contains": "Recommendations",
    },
    {
        "query": (
            "How should glycemic control be monitored "
            "in type 2 diabetes?"
        ),
        "relevant_document_id": "va_dod_type2_diabetes_2023",
        "relevant_section_contains": "Glycemic Control Targets and Monitoring",
    },
]

retrieval_eval_df = pd.DataFrame(
    retrieval_eval
)

retrieval_eval_df

,query,relevant_document_id,relevant_section_contains
0,How should hyperkalemia be managed in patients with chronic kidney disease?,va_dod_ckd_2025,Management of Hyperkalemia
1,How should asthma severity and control be assessed?,va_dod_asthma_2025,Assessments of Asthma Severity and Control
2,What treatment is recommended for chlamydial infection in adults?,cdc_sti_2021,Chlamydial Infection Among Adolescents and Adults > Treatment
3,What blood pressure target is recommended for adults with hypertension?,who_hypertension_2021,Target blood pressure
4,What pharmacologic treatments are recommended for major depressive disorder?,va_dod_major_depression_2022,Recommendations
5,How should glycemic control be monitored in type 2 diabetes?,va_dod_type2_diabetes_2023,Glycemic Control Targets and Monitoring

In [140]:
def get_relevant_rank(
    query,
    relevant_document_id,
    relevant_section_contains,
    top_k=10,
):
    results = dense_search(
        query,
        top_k=top_k,
    )

    mask = (
        results["document_id"].eq(
            relevant_document_id
        )
        & results["section_path"].str.contains(
            relevant_section_contains,
            case=False,
            regex=False,
            na=False,
        )
    )

    matching_positions = np.flatnonzero(
        mask.to_numpy()
    )

    if len(matching_positions) == 0:
        return None

    return int(
        matching_positions[0] + 1
    )

In [141]:
eval_results = []

for _, row in retrieval_eval_df.iterrows():
    rank = get_relevant_rank(
        query=row["query"],
        relevant_document_id=(
            row["relevant_document_id"]
        ),
        relevant_section_contains=(
            row["relevant_section_contains"]
        ),
        top_k=10,
    )

    eval_results.append(
        {
            **row.to_dict(),
            "relevant_rank": rank,
        }
    )

retrieval_debug_results_df = pd.DataFrame(
    eval_results
)

retrieval_debug_results_df

,query,relevant_document_id,relevant_section_contains,relevant_rank
0,How should hyperkalemia be managed in patients with chronic kidney disease?,va_dod_ckd_2025,Management of Hyperkalemia,1
1,How should asthma severity and control be assessed?,va_dod_asthma_2025,Assessments of Asthma Severity and Control,1
2,What treatment is recommended for chlamydial infection in adults?,cdc_sti_2021,Chlamydial Infection Among Adolescents and Adults > Treatment,1
3,What blood pressure target is recommended for adults with hypertension?,who_hypertension_2021,Target blood pressure,1
4,What pharmacologic treatments are recommended for major depressive disorder?,va_dod_major_depression_2022,Recommendations,1
5,How should glycemic control be monitored in type 2 diabetes?,va_dod_type2_diabetes_2023,Glycemic Control Targets and Monitoring,6

### Результат debug-проверки

На 5 из 6 проверочных запросов релевантный раздел находится на первом месте.

Для запроса о monitoring glycemic control при type 2 diabetes нужный раздел
`Glycemic Control Targets and Monitoring` находится только на 6-м месте.

Это показывает, что dense retrieval в целом работает, но ranking не всегда оптимален.

Эти запросы уже использовались при разработке pipeline, поэтому они рассматриваются
только как debug-набор и не используются как независимая оценка качества.

In [142]:
def hit_at_k(ranks, k):
    return np.mean(
        [
            rank is not None and rank <= k
            for rank in ranks
        ]
    )


def mean_reciprocal_rank(ranks):
    reciprocal_ranks = [
        0.0 if rank is None else 1.0 / rank
        for rank in ranks
    ]

    return np.mean(reciprocal_ranks)


debug_ranks = (
    retrieval_debug_results_df[
        "relevant_rank"
    ].tolist()
)

debug_metrics = {
    "Hit@1": hit_at_k(debug_ranks, 1),
    "Hit@3": hit_at_k(debug_ranks, 3),
    "Hit@5": hit_at_k(debug_ranks, 5),
    "Hit@10": hit_at_k(debug_ranks, 10),
    "MRR": mean_reciprocal_rank(debug_ranks),
}

debug_metrics

{'Hit@1': np.float64(0.8333333333333334),
 'Hit@3': np.float64(0.8333333333333334),
 'Hit@5': np.float64(0.8333333333333334),
 'Hit@10': np.float64(1.0),
 'MRR': np.float64(0.8611111111111112)}

### Разбор запроса с неидеальным ranking

Запрос о monitoring glycemic control является полезным примером ошибки ranking.

Проверяем top-10, чтобы понять, какие тематически близкие chunks вытесняют
наиболее специфичный раздел.

In [143]:
t2d_query = (
    "How should glycemic control be monitored "
    "in type 2 diabetes?"
)

t2d_results = dense_search(
    t2d_query,
    top_k=10,
)

t2d_results[
    [
        "score",
        "document_id",
        "section_path",
        "text",
    ]
]

,score,document_id,section_path,text
2029,0.735175,va_dod_type2_diabetes_2023,IX. Recommendations > C. Diabetes Mellitus,"the following recommendation: For adults with type 2 diabetes mellitus, we suggest using high glycemic variability over time (e.g., fluctuation in HbA1c or fasting blood glucose) as a prognostic indicator for risk of hypoglycemia, morbidity, and mortality."
2104,0.724610,va_dod_type2_diabetes_2023,IX. Recommendations > E. Pharmacotherapy,"Recommendation 25. In adults with type 2 diabetes mellitus, especially those 65 years and older, we suggest prioritizing drug classes other than insulin, sulfonylureas, or meglitinides to minimize the risk of hypoglycemia, if glycemic control can be achieved with other treatments. (Weak for | Re..."
2046,0.720311,va_dod_type2_diabetes_2023,IX. Recommendations > C. Diabetes Mellitus,"Discussion Although evidence is increasing that continuous glucose monitoring (CGM) can improve glucose control and might reduce hypoglycemia in T1DM patients, whether CGM improves outcomes in patients with T2DM is unclear. However, the systematic evidence review found that results differed depe..."
1994,0.719733,va_dod_type2_diabetes_2023,IX. Recommendations,"’s appraisal of the risk benefit ratio, patient characteristics, presence or absence of type 2 diabetes mellitus complications, comorbidities, and life expectancy. 10. We suggest an HbA1c range of 7.0–8.5% for most patients, if it can be safely achieved. Weak for Not reviewed, Amended Glycemic M..."
1993,0.716697,va_dod_type2_diabetes_2023,IX. Recommendations,"Topic Sub-topic # Recommendation Strengtha Categoryb Neither for nor against Reviewed, New­added 4. There is insufficient evidence to recommend for or against routine screening or using a specific tool to screen for or diagnose diabetes distress. 5. Weak for Reviewed, New­added In adults with ty..."
2115,0.715480,va_dod_type2_diabetes_2023,Appendix B: Glycemic Control Targets and Monitoring,"in some patients based on other factors, balancing safety and tolerability of therapy. n Major comorbidity is present, but is not end-stage, and management is achievable. o Major comorbidity is present and is either end-stage or management is significantly challenging, including mental health co..."
2028,0.710746,va_dod_type2_diabetes_2023,IX. Recommendations > C. Diabetes Mellitus,causal effect on adverse events and whether prospectively reducing fasting blood glucose or HbA1c variability will favorably impact outcomes are also unknown. The Work Group systematically reviewed evidence related to this recommendation and considered the assessment of the evidence put forth in...
2027,0.709554,va_dod_type2_diabetes_2023,IX. Recommendations > C. Diabetes Mellitus,"events.(75, 76, 83) The increased risk for hypoglycemia events in the setting of higher variability generally ranged from 50–300%. Notably, the median duration of follow-up ranged from 8 months to nearly 9 years, so the number of measures of fasting glucose or HbA1c differed substantially across..."
2022,0.707995,va_dod_type2_diabetes_2023,IX. Recommendations > C. Diabetes Mellitus,"be burdensome for providers with limited time. Most screening tools were developed to target older patients, so their accuracy in younger patients is unclear. The Work Group systematically searched for evidence and did not identify any studies that met inclusion criteria regarding routine screen..."
2050,0.705465,va_dod_type2_diabetes_2023,IX. Recommendations > C. Diabetes Mellitus,"it is categorized as Reviewed, New-added. The Work Group’s confidence in the quality of the evidence was moderate. The body of evidence had some limitations, including a small sample size spread among relatively few studies.(92–95) We found moderate evidence that rtCGM led to decreased hypoglyce..."

### Проверка структуры T2D recommendations

В результатах поиска несколько фрагментов о glycemic variability, HbA1c и CGM
имеют `section_path = IX. Recommendations > B. Telehealth`.

Поскольку guideline содержит последующие тематические подразделы recommendations,
проверяем, корректно ли parser распознал переход от `B. Telehealth`
к следующим subsection headings.

Это важно проверить до количественной оценки retrieval, поскольку ошибочный
`section_path` сделает разметку релевантных разделов ненадёжной.

In [144]:
t2d_path = (
    GUIDELINES_DIR
    / "va_dod"
    / "va_dod_type2_diabetes_2023.pdf"
)

t2d_pages = extract_document_pages(
    t2d_path
)

for pdf_page in range(30, 36):
    page_data = t2d_pages[
        pdf_page - 1
    ]

    lines = clean_va_dod_lines(
        page_data,
        get_va_dod_margin_noise(
            t2d_path
        ),
    )

    lines = merge_va_dod_heading_lines(
        lines
    )

    print(
        "\n",
        "=" * 80,
        f"\npdf_page = {pdf_page}",
    )

    for line in lines:
        if (
            line.get("heading_level") is not None
            or "Diabetes Mellitus" in line["text"]
            or "Telehealth" in line["text"]
        ):
            print(
                "level:",
                line.get("heading_level"),
                "| text:",
                line["text"],
                "| size:",
                line["font_size"],
                "| fonts:",
                line["fonts"],
                "| bbox:",
                line["bbox"],
            )

 ================================================================================
pdf_page = 30

 ================================================================================
pdf_page = 31
level: 2 | text: B. Telehealth | size: 13.0 | fonts: ['Arial-BoldMT'] | bbox: (72.0, 367.3, 165.1, 380.3)

 ================================================================================
pdf_page = 32

 ================================================================================
pdf_page = 33
level: 2 | text: C. Diabetes Mellitus | size: 13.0 | fonts: ['Arial-BoldMT'] | bbox: (72.0, 74.2, 207.0, 87.2)

 ================================================================================
pdf_page = 34

 ================================================================================
pdf_page = 35

### Проверка переноса subsection между страницами

Заголовок `Diabetes Mellitus` имеет формат subsection, но parser не распознаёт его,
поскольку в строке отсутствует буквенный префикс `C.`.

Проверяем конец предыдущей страницы и начало следующей, чтобы понять,
не был ли заголовок разделён между страницами PDF.

In [145]:
for pdf_page in [32, 33]:
    print("\n", "=" * 80)
    print("pdf_page =", pdf_page)

    page_data = t2d_pages[pdf_page - 1]

    lines = clean_va_dod_lines(
        page_data,
        get_va_dod_margin_noise(t2d_path),
    )

    for i, line in enumerate(lines):
        if (
            line["font_size"] >= 12.5
            and is_va_dod_bold(line)
        ):
            print(
                i,
                "|",
                line["text"],
                "| size:",
                line["font_size"],
                "| bbox:",
                line["bbox"],
            )

 ================================================================================
pdf_page = 32

 ================================================================================
pdf_page = 33
0 | C. | size: 13.0 | bbox: (72.0, 74.2, 88.6, 87.2)
1 | Diabetes Mellitus | size: 13.0 | bbox: (100.8, 74.2, 207.0, 87.2)

### Проверка объединения составного заголовка

В PDF subsection heading `C. Diabetes Mellitus` разбит на два текстовых блока,
расположенных на одной строке.

Проверяем отдельно работу `merge_va_dod_inline_labels()` и
`merge_va_dod_heading_lines()`.

In [146]:
page_data = t2d_pages[33 - 1]

lines = clean_va_dod_lines(
    page_data,
    get_va_dod_margin_noise(t2d_path),
)

print("BEFORE:")
for line in lines[:5]:
    print(
        line["text"],
        "| size:", line["font_size"],
        "| fonts:", line["fonts"],
        "| bbox:", line["bbox"],
    )


inline_merged = merge_va_dod_inline_labels(
    lines
)

print("\nAFTER merge_va_dod_inline_labels:")
for line in inline_merged[:5]:
    print(
        line["text"],
        "| size:", line["font_size"],
        "| fonts:", line["fonts"],
        "| bbox:", line["bbox"],
    )


heading_merged = merge_va_dod_heading_lines(
    lines
)

print("\nAFTER merge_va_dod_heading_lines:")
for line in heading_merged[:5]:
    print(
        line["text"],
        "| level:", line.get("heading_level"),
        "| size:", line["font_size"],
        "| bbox:", line["bbox"],
    )

BEFORE:
C. | size: 13.0 | fonts: ['Arial-BoldMT'] | bbox: (72.0, 74.2, 88.6, 87.2)
Diabetes Mellitus | size: 13.0 | fonts: ['Arial-BoldMT'] | bbox: (100.8, 74.2, 207.0, 87.2)
Recommendation | size: 12.0 | fonts: ['Arial-BoldItalicMT'] | bbox: (72.0, 93.9, 172.7, 105.9)
4. There is insufficient evidence to recommend for or against routine screening or | size: 12.0 | fonts: ['ArialMT'] | bbox: (90.0, 112.7, 532.3, 124.7)
using a specific tool to screen for or diagnose diabetes distress. | size: 12.0 | fonts: ['ArialMT'] | bbox: (111.6, 127.8, 452.6, 139.8)

AFTER merge_va_dod_inline_labels:
C. Diabetes Mellitus | size: 13.0 | fonts: ['Arial-BoldMT'] | bbox: (72.0, 74.2, 207.0, 87.2)
Recommendation | size: 12.0 | fonts: ['Arial-BoldItalicMT'] | bbox: (72.0, 93.9, 172.7, 105.9)
4. There is insufficient evidence to recommend for or against routine screening or | size: 12.0 | fonts: ['ArialMT'] | bbox: (90.0, 112.7, 532.3, 124.7)
using a specific tool to screen for or diagnose diabetes distress. | size: 12.0 | fonts: ['ArialMT'] | bbox: (111.6, 127.8, 452.6, 139.8)
(Neither for nor against | Reviewed, New-added) | size: 12.0 | fonts: ['Arial-BoldMT'] | bbox: (111.6, 143.1, 384.4, 155.1)

AFTER merge_va_dod_heading_lines:
C. Diabetes Mellitus | level: 2 | size: 13.0 | bbox: (72.0, 74.2, 207.0, 87.2)
Recommendation | level: None | size: 12.0 | bbox: (72.0, 93.9, 172.7, 105.9)
4. There is insufficient evidence to recommend for or against routine screening or | level: None | size: 12.0 | bbox: (90.0, 112.7, 532.3, 124.7)
using a specific tool to screen for or diagnose diabetes distress. | level: None | size: 12.0 | bbox: (111.6, 127.8, 452.6, 139.8)
(Neither for nor against | Reviewed, New-added) | level: None | size: 12.0 | bbox: (111.6, 143.1, 384.4, 155.1)

In [147]:
heading_merged = (
    merge_va_dod_heading_lines(
        lines
    )
)

for line in heading_merged[:5]:
    print(
        line["text"],
        "| level:",
        line.get("heading_level"),
        "| size:",
        line["font_size"],
    )

C. Diabetes Mellitus | level: 2 | size: 13.0
Recommendation | level: None | size: 12.0
4. There is insufficient evidence to recommend for or against routine screening or | level: None | size: 12.0
using a specific tool to screen for or diagnose diabetes distress. | level: None | size: 12.0
(Neither for nor against | Reviewed, New-added) | level: None | size: 12.0

### Проверка составных subsection headings

В некоторых VA/DoD PDF буквенный префикс subsection и название раздела
хранятся как отдельные текстовые блоки на одной строке.

Например:

`C.` + `Diabetes Mellitus`

Parser объединяет такие блоки до определения уровня заголовка.

In [148]:
t2d_test_lines = merge_va_dod_heading_lines(
    clean_va_dod_lines(
        t2d_pages[33 - 1],
        get_va_dod_margin_noise(t2d_path),
    )
)

[
    (
        line["text"],
        line.get("heading_level"),
    )
    for line in t2d_test_lines
    if "Diabetes Mellitus" in line["text"]
]

[('C. Diabetes Mellitus', 2)]

In [149]:
va_dod_records_df[
    (
        va_dod_records_df["document_id"]
        == "va_dod_type2_diabetes_2023"
    )
    & (
        va_dod_records_df["section_path"]
        .str.contains(
            "Diabetes Mellitus",
            case=False,
            regex=False,
            na=False,
        )
    )
][
    [
        "section_path",
        "pdf_page",
        "text",
    ]
].head(10)

,section_path,pdf_page,text
929,II. Background > A. Description of Type 2 Diabetes Mellitus,5,"Diabetes mellitus (DM) is a disease caused by an absolute or relative insulin deficiency resulting in hyperglycemia. Type 1 DM (T1DM) is due to deficient insulin production and secretion and can present across the lifespan, with older patients often having a more indolent presentation that has b..."
930,II. Background > A. Description of Type 2 Diabetes Mellitus,6,skeletal muscle. Prediabetes refers to the development of dysglycemia that does not reach the threshold for a diagnosis of diabetes. Gestational diabetes mellitus (GDM) is diabetes diagnosed in the second or third trimester of pregnancy that is typically not clinically overt. A variety of other ...
931,II. Background > A. Description of Type 2 Diabetes Mellitus,7,"· Women with polycystic ovary syndrome(3) · History of GDM(3) or history of delivering babies weighing >9 pounds (about 4 kg) · Other clinical conditions associated with insulin resistance (e.g., severe obesity, acanthosis nigricans)(3) · Physical inactivity/sedentary lifestyle(3) · Patients wit..."
932,II. Background > A. Description of Type 2 Diabetes Mellitus,8,"An oral glucose tolerance test (OGTT) is not commonly used to diagnose DM. Although both the ADA and the American Association of Clinical Endocrinology guidelines include the OGTT as a diagnostic criterion for T2DM, it is cumbersome and needs better reproducibility, making it less useful for rou..."
976,IX. Recommendations > C. Diabetes Mellitus,33,"Recommendation 4. There is insufficient evidence to recommend for or against routine screening or using a specific tool to screen for or diagnose diabetes distress. (Neither for nor against | Reviewed, New-added) Discussion The Work Group found no evidence in the systematic evidence review relat..."
977,IX. Recommendations > C. Diabetes Mellitus,34,"progressive disease such as non-alcoholic steatohepatitis (NASH), a more severe form of fatty liver disease associated with a greater risk of advanced fibrosis and cirrhosis. Approximately 70% of patients with T2DM and NAFLD are diagnosed with biopsy-proven NASH, which is two to three times the ..."
978,IX. Recommendations > C. Diabetes Mellitus,35,general population might be extrapolated to patients with T2DM and used as justification for their application in clinical practice. Other noninvasive methods that require no imaging may be used to assess advanced liver fibrosis in patients with T2DM and co-occurring NAFLD. These methods include...
979,IX. Recommendations > C. Diabetes Mellitus,36,"inclined to reserve testing until signs and symptoms appear. Other considerations, such as acceptability and feasibility, are unlikely to have a significant impact. The Work Group systematically reviewed evidence related to this recommendation. Therefore, it is categorized as Reviewed, New-added..."
980,IX. Recommendations > C. Diabetes Mellitus,37,"be burdensome for providers with limited time. Most screening tools were developed to target older patients, so their accuracy in younger patients is unclear. The Work Group systematically searched for evidence and did not identify any studies that met inclusion criteria regarding routine screen..."
981,IX. Recommendations > C. Diabetes Mellitus,38,"The Work Group considered the assessment of the evidence put forth in the 2017 VA/ DoD DM CPG. Therefore, it is categorized as Not reviewed, Amended.(70–72) The Work Group’s confidence in the quality of the evidence was moderate. The body of evidence had some limitations, including inability to ..."

In [ ]:
va_dod_path_by_document_id = {
    "va_dod_asthma_2025": (
        GUIDELINES_DIR
        / "va_dod"
        / "va_dod_asthma_2025.pdf"
    ),
    "va_dod_ckd_2025": (
        GUIDELINES_DIR
        / "va_dod"
        / "va_dod_ckd_2025.pdf"
    ),
    "va_dod_low_back_pain_2022": (
        GUIDELINES_DIR
        / "va_dod"
        / "va_dod_low_back_pain_2022.pdf"
    ),
    "va_dod_major_depression_2022": (
        GUIDELINES_DIR
        / "va_dod"
        / "va_dod_major_depression_2022.pdf"
    ),
    "va_dod_pregnancy_2023": (
        GUIDELINES_DIR
        / "va_dod"
        / "va_dod_pregnancy_2023.pdf"
    ),
    "va_dod_type2_diabetes_2023": (
        GUIDELINES_DIR
        / "va_dod"
        / "va_dod_type2_diabetes_2023.pdf"
    ),
}

In [ ]:
body_start_pages = (
    va_dod_records_df
    .groupby("document_id")["pdf_page"]
    .min()
    .to_dict()
)

unmerged_heading_candidates = []

for document_id, path in va_dod_path_by_document_id.items():
    pages = extract_document_pages(path)
    margin_noise = get_va_dod_margin_noise(path)

    body_start = body_start_pages[document_id]

    for page_data in pages:
        if page_data["pdf_page"] < body_start:
            continue

        lines = clean_va_dod_lines(
            page_data,
            margin_noise,
        )

        lines = merge_va_dod_inline_labels(
            lines
        )

        for line in lines:
            if (
                re.fullmatch(
                    r"[A-Z]\.",
                    line["text"].strip(),
                )
                and is_va_dod_bold(line)
                and line["font_size"] >= 11.8
                and line["bbox"][0] < 120
            ):
                unmerged_heading_candidates.append(
                    {
                        "document_id": document_id,
                        "pdf_page": page_data["pdf_page"],
                        "text": line["text"],
                        "font_size": line["font_size"],
                        "bbox": line["bbox"],
                    }
                )

pd.DataFrame(unmerged_heading_candidates)

Empty DataFrame
Columns: []
Index: []

In [152]:
t2d_query = (
    "How should glycemic control be monitored "
    "in type 2 diabetes?"
)

dense_search(
    t2d_query,
    top_k=10,
)[
    [
        "score",
        "document_id",
        "section_path",
        "text",
    ]
]

,score,document_id,section_path,text
2029,0.735175,va_dod_type2_diabetes_2023,IX. Recommendations > C. Diabetes Mellitus,"the following recommendation: For adults with type 2 diabetes mellitus, we suggest using high glycemic variability over time (e.g., fluctuation in HbA1c or fasting blood glucose) as a prognostic indicator for risk of hypoglycemia, morbidity, and mortality."
2104,0.724610,va_dod_type2_diabetes_2023,IX. Recommendations > E. Pharmacotherapy,"Recommendation 25. In adults with type 2 diabetes mellitus, especially those 65 years and older, we suggest prioritizing drug classes other than insulin, sulfonylureas, or meglitinides to minimize the risk of hypoglycemia, if glycemic control can be achieved with other treatments. (Weak for | Re..."
2046,0.720311,va_dod_type2_diabetes_2023,IX. Recommendations > C. Diabetes Mellitus,"Discussion Although evidence is increasing that continuous glucose monitoring (CGM) can improve glucose control and might reduce hypoglycemia in T1DM patients, whether CGM improves outcomes in patients with T2DM is unclear. However, the systematic evidence review found that results differed depe..."
1994,0.719733,va_dod_type2_diabetes_2023,IX. Recommendations,"’s appraisal of the risk benefit ratio, patient characteristics, presence or absence of type 2 diabetes mellitus complications, comorbidities, and life expectancy. 10. We suggest an HbA1c range of 7.0–8.5% for most patients, if it can be safely achieved. Weak for Not reviewed, Amended Glycemic M..."
1993,0.716697,va_dod_type2_diabetes_2023,IX. Recommendations,"Topic Sub-topic # Recommendation Strengtha Categoryb Neither for nor against Reviewed, New­added 4. There is insufficient evidence to recommend for or against routine screening or using a specific tool to screen for or diagnose diabetes distress. 5. Weak for Reviewed, New­added In adults with ty..."
2115,0.715480,va_dod_type2_diabetes_2023,Appendix B: Glycemic Control Targets and Monitoring,"in some patients based on other factors, balancing safety and tolerability of therapy. n Major comorbidity is present, but is not end-stage, and management is achievable. o Major comorbidity is present and is either end-stage or management is significantly challenging, including mental health co..."
2028,0.710746,va_dod_type2_diabetes_2023,IX. Recommendations > C. Diabetes Mellitus,causal effect on adverse events and whether prospectively reducing fasting blood glucose or HbA1c variability will favorably impact outcomes are also unknown. The Work Group systematically reviewed evidence related to this recommendation and considered the assessment of the evidence put forth in...
2027,0.709554,va_dod_type2_diabetes_2023,IX. Recommendations > C. Diabetes Mellitus,"events.(75, 76, 83) The increased risk for hypoglycemia events in the setting of higher variability generally ranged from 50–300%. Notably, the median duration of follow-up ranged from 8 months to nearly 9 years, so the number of measures of fasting glucose or HbA1c differed substantially across..."
2022,0.707995,va_dod_type2_diabetes_2023,IX. Recommendations > C. Diabetes Mellitus,"be burdensome for providers with limited time. Most screening tools were developed to target older patients, so their accuracy in younger patients is unclear. The Work Group systematically searched for evidence and did not identify any studies that met inclusion criteria regarding routine screen..."
2050,0.705465,va_dod_type2_diabetes_2023,IX. Recommendations > C. Diabetes Mellitus,"it is categorized as Reviewed, New-added. The Work Group’s confidence in the quality of the evidence was moderate. The body of evidence had some limitations, including a small sample size spread among relatively few studies.(92–95) We found moderate evidence that rtCGM led to decreased hypoglyce..."

**Вывод debug-проверки.**

Dense retrieval технически работает и возвращает тематически релевантные
chunks из правильных clinical guidelines.

В ходе проверки также была обнаружена и исправлена ошибка VA/DoD parser,
связанная с составными subsection headings.

Debug-примеры не используются для итоговой оценки качества retrieval,
поскольку их результаты уже анализировались в процессе разработки.

## 18. Подготовка evaluation-набора для retrieval

Debug-примеры использовались во время разработки и поэтому не подходят
для независимой оценки качества retrieval.

Для дальнейшей оценки используем новые вопросы только из `dev`.
`test` остаётся полностью замороженным.

Поскольку knowledge base покрывает ограниченный набор clinical guidelines,
не каждый вопрос из исходного датасета обязан иметь ответ в KB.

Поэтому сначала формируем набор кандидатов из `dev`, а затем вручную
определяем:

- можно ли ответить на вопрос с помощью текущей knowledge base;
- какой документ содержит релевантную информацию;
- какие разделы документа можно считать релевантными.

In [153]:
MATERIALS_DIR = Path("../materials")

dev_df = pd.read_csv(
    MATERIALS_DIR / "dev.csv"
)

print("dev shape:", dev_df.shape)
print("columns:", dev_df.columns.tolist())

dev_df.head()

dev shape: (1000, 2)
columns: ['input', 'output']

,input,output
0,my husband age is 29 yrs.height is 5.10ft.his sperm analysis report showsquantity,"Hello Thanks for writing to your husbands semen analysis report suggests infection. Infection is indicated by the presence of WBC in semen. Normally there shouldn't be any WBC in semen. Infection may be due to prostatitis, UTI etc. You need antibiotics for infection. You need few more investigat..."
1,"My HBeAg is non-reactive but my Anti-HBc is reactive. My liver is normal in size and it shows homogeneous echopattern. The intrahepatic ducts are not dilated and negatve for focal solid or sytic masses. Do I have hepa B and if I have, what is the condition of my health?",Hi dear thanks for asking question.... Noted you have anti HBC positive. You have not mentioned whether it is IG M or IG G type. Usually anti HBC is first antibody appear in Blood from current or past infection. IG M replaced by IG G and IG G type anti HE c remain for lie long. You might develop...
2,"hello Dr, The entire left side of my face has been swollen for nearly a week, my gums in that area is bubbling up, soft but scary feeling. This is very painful, I thought it would go down after a few days. But days pass and no kind of improvement has occured. Should I go to a doctor at a emergen...","Hi, in my opinion u should see a dentist at the earliest and not ignore it, as per your symptoms it seems to be an infection which needs to be investigated for the reason for infection and treating it with antibiotics and analgesics and treating the reason as well, if u want me to help me more u..."
3,"Hi, I have slight pain in my lower right abdomen when sneezing or coughing for a couple of weeks now. Does not hurt when I lift something, even very heavy (slightly feel it if try to do abdominal crunches). I am a 49 years old male, quite fit, exersize regularly. No nausea, no temperature or hig...","HI ! Good afternoon. I am Chat Doctor answering your query. If I were your doctor, I would clinically examine your abdomen to rule out chances of any inguinal hernia in its early stages when it becomes painful due to stretching of its covering. Also, I would like to see if there is any other int..."
4,I am a physician investigating a workers compensation claim in which the client claims he was bitten by a tic while at a work retreat in Georgia in May 2015. My question is whether Lyme disease is common in Georgia and whether it can cause Bell s Palsey.,"Hello, Yes, Lyme disease can cause Bells palsy. Caused by the bacterium Cordelia burgdorferi and transmitted to humans through the bite of infected black legged ticks, the typical symptoms of Lyme disease include fever, headache, fatigue, and a characteristic skin rash called Erythema migrant. I..."

### Исключение debug-вопросов

`debug` является подмножеством `dev` и уже использовался во время разработки pipeline.

Чтобы вопросы, которые мы уже видели, не попали в независимую retrieval evaluation,
исключаем их из `dev`.

Далее нам нужны только вопросы, потенциально относящиеся к тем клиническим темам,
которые представлены в текущей knowledge base.

In [154]:
debug_df = pd.read_csv(
    MATERIALS_DIR / "debug.csv"
)

dev_retrieval_df = (
    dev_df[
        ~dev_df["input"].isin(
            debug_df["input"]
        )
    ]
    .reset_index(drop=True)
    .copy()
)

print("dev:", len(dev_df))
print("debug:", len(debug_df))
print(
    "dev after debug exclusion:",
    len(dev_retrieval_df),
)

dev: 1000
debug: 30
dev after debug exclusion: 970

### Поиск вопросов, потенциально покрываемых knowledge base

Knowledge base содержит восемь clinical guidelines по ограниченному набору тем.

Поэтому случайная выборка из всего `dev` будет содержать много вопросов,
для которых в KB в принципе нет подходящего источника.

Используем простой keyword-фильтр только для предварительного отбора кандидатов
на ручную разметку.

Этот фильтр не определяет релевантность и не участвует в расчёте retrieval-метрик.
Окончательное решение о том, покрывается ли вопрос knowledge base, принимается
вручную по содержанию guideline.

In [155]:
KB_TOPIC_PATTERNS = {
    "asthma": (
        r"\basthma\b|"
        r"\bwheez\w*\b|"
        r"\bbronchial asthma\b"
    ),

    "ckd": (
        r"\bchronic kidney disease\b|"
        r"\bckd\b|"
        r"\brenal insufficien\w*\b|"
        r"\bkidney disease\b|"
        r"\begfr\b|"
        r"\bhyperkal\w*\b"
    ),

    "low_back_pain": (
        r"\blow back pain\b|"
        r"\blower back pain\b|"
        r"\blumbar pain\b|"
        r"\bsciatica\b"
    ),

    "major_depression": (
        r"\bmajor depressive\b|"
        r"\bdepress\w*\b|"
        r"\bantidepress\w*\b|"
        r"\bphq[- ]?9\b"
    ),

    "pregnancy": (
        r"\bpregnan\w*\b|"
        r"\bprenatal\b|"
        r"\bantenatal\b|"
        r"\bgestation\w*\b"
    ),

    "type2_diabetes": (
        r"\btype 2 diabetes\b|"
        r"\bt2dm\b|"
        r"\bdiabet\w*\b|"
        r"\bhba1c\b|"
        r"\ba1c\b"
    ),

    "hypertension": (
        r"\bhypertension\b|"
        r"\bhigh blood pressure\b"
    ),

    "sti": (
        r"\bsexually transmitted\b|"
        r"\bsti\b|"
        r"\bstd\b|"
        r"\bchlamyd\w*\b|"
        r"\bgonorrh\w*\b|"
        r"\bsyphilis\b|"
        r"\btrichomon\w*\b|"
        r"\bgenital herpes\b"
    ),
}

In [156]:
def detect_kb_topics(text):
    topics = []

    for topic, pattern in KB_TOPIC_PATTERNS.items():
        if re.search(
            pattern,
            str(text),
            flags=re.IGNORECASE,
        ):
            topics.append(topic)

    return topics

In [157]:
dev_retrieval_df["kb_topics"] = (
    dev_retrieval_df["input"]
    .apply(detect_kb_topics)
)

retrieval_candidates_df = (
    dev_retrieval_df[
        dev_retrieval_df["kb_topics"]
        .str.len()
        .gt(0)
    ]
    .reset_index(drop=True)
    .copy()
)

retrieval_candidates_df["candidate_id"] = [
    f"candidate_{i:04d}"
    for i in range(
        len(retrieval_candidates_df)
    )
]

print(
    "Candidate questions:",
    len(retrieval_candidates_df),
)

Candidate questions: 162

In [158]:
topic_counts = (
    retrieval_candidates_df[
        ["candidate_id", "kb_topics"]
    ]
    .explode("kb_topics")
    .groupby("kb_topics")
    .size()
    .sort_values(ascending=False)
    .rename("questions")
)

topic_counts

kb_topics
pregnancy           63
asthma              27
type2_diabetes      21
hypertension        18
low_back_pain       18
major_depression    14
sti                  7
ckd                  2
Name: questions, dtype: int64

### Формирование набора для ручной разметки

Количество потенциально подходящих вопросов заметно различается между темами.
Поэтому простая случайная выборка из всех кандидатов могла бы быть сильно
смещена в сторону наиболее частых тем, например pregnancy.

Для первого retrieval evaluation формируем стратифицированную выборку:

- до 5 вопросов на каждую клиническую тему;
- если доступно меньше 5 вопросов, используем все;
- выбор выполняется до запуска retrieval, чтобы результаты поиска не влияли
  на состав evaluation-набора.

Колонка `output` при разметке не используется, поскольку ответы исходного
датасета не рассматриваются как эталон клинической корректности.

In [159]:
EVAL_PER_TOPIC = 5
EVAL_RANDOM_STATE = 42

candidate_topics_df = (
    retrieval_candidates_df[
        [
            "candidate_id",
            "input",
            "kb_topics",
        ]
    ]
    .explode("kb_topics")
    .rename(
        columns={
            "kb_topics": "kb_topic"
        }
    )
    .reset_index(drop=True)
)

In [ ]:
retrieval_eval_candidates_df = (
    candidate_topics_df
    .groupby(
        "kb_topic",
        group_keys=False,
    )
    .apply(
        lambda group: group.sample(
            n=min(
                EVAL_PER_TOPIC,
                len(group),
            ),
            random_state=EVAL_RANDOM_STATE,
        )
    )
    .reset_index(drop=True)
)

In [161]:
retrieval_eval_candidates_df[
    "candidate_id"
].duplicated().sum()

np.int64(1)

In [162]:
retrieval_eval_candidates_df.groupby(
    "kb_topic"
).size()

kb_topic
asthma              5
ckd                 2
hypertension        5
low_back_pain       5
major_depression    5
pregnancy           5
sti                 5
type2_diabetes      5
dtype: int64

In [163]:
pd.set_option(
    "display.max_colwidth",
    500,
)

retrieval_eval_candidates_df[
    [
        "candidate_id",
        "kb_topic",
        "input",
    ]
]

,candidate_id,kb_topic,input
0,candidate_0063,asthma,"My 9 year old grandson who has a history of asthma but has not been on any medication nor had a reaction in at least 3 months had Eosinophils,absolute of 544 and AST of 33. doctor didnt seem at all concerned. Should there be any follow up or need for concern?"
1,candidate_0097,asthma,"ihave severe asthma and have been 5 times in the last 9 weeks and been given lots of steroids, so i am on insulin now. i am so wore ouy and can hardly get around. thw wheezing has stopped. i have high numbers of latic acid in the muscles. please tell me what to do."
2,candidate_0071,asthma,hi there i am 24 an a female im a mum of 4 last sunday i had this extreme pain on both sides of my spine which to this day i still have it i was subscribed codiene for the pain which didnt doanything i cant sleep at night as lying down hurt any movement to my back bring tears i cant touch my back also breathing coughing hurts... an i have now another problem that happend 2 nights ago an i had a very sharp pain in my heart which made my left arm go dead an all my finger tips went numb an felt...
3,candidate_0135,asthma,"I experience respiratory distress symptoms (SOB, decreased O2, voice changes) when I am exposed to perfumes and a few other strong oders and flying dust/dirt. What could this be a symptoms of?I am 37 years old, weigh 145, and have no hx of asthma or any other respiratory issues."
4,candidate_0004,asthma,Had a cold for 3 weeks. Went away. 2 weeks later came back. Doctor treated me with 5 day Z Pak (250 mg) & a corticosteroid pill (4 mg). Still sick. Bad cough. Cough up white foamy stuff. Using Mucinex & Robitussin. Lots of clear discharge from nose. Wheezing.
5,candidate_0067,ckd,hi i am 30 years old and my husband an i have been trying to conceive for 19 cycles now with no success. I was diagnosed with medullary sponge kidney 5 years ago and am wondering if this is causing us to not conceive. We have both been tested by fertility specialists and he was by urologist and we are both fine. Except this kidney disease and frequent uti s that i keep having. Your help and advise is greatly appreciated.
6,candidate_0029,ckd,"I have been told that I have stage 5 advanced chronic kidney disease, blood pressure perfect cholesterol perfect.Feel great look great, drs are surprised say that considering my blood work I shoulod be deathly sick but Im not at all. I was told that i need dialysis and transplant...shouldnt I be tested further"
7,candidate_0001,hypertension,"hi in 2010 I was diagnosed with the right right bundle branch block also with a sinus tachycardia and a heart murmur I recently went to the hospital and was diagnosed with chest wall pain and Mild tricuspid regurgitation and mild tricuspid pulmonic regurgitation, my question is what do I expect from this point on? Should I be concerned? Also diagnosed with a specified essential hypertension and ectopic atrial rhythm other specified cardiac dysrhythmias. Tachycardia unspecified? ? What does t..."
8,candidate_0003,hypertension,"I had chest pains, back pains going up to my throat and neck, tropamine in my blood. Heart rate 90 bpm. High blood pressure. An ambulance took me to hospital, 4 days of monitoring and an angiogram and echo. They do not know what it was.Still feel washed out and tired with a pain in my chest like I have been kicked. I am a fit 58 year old woman. Was diagnosed with BC in 2010 had chemo, radiotherapy, Herceptin.... and am on Tamoxifen at the moment."
9,candidate_0066,hypertension,I have hypertension currently 160 / 95 and has been for some weeks. I exercise regularly run 5k 3 times per week. I recently had gout but it has gone and I am back into regular exercise. I keep having pains in the base of my foot to the point it is difficult to walk and go extremely cold. I currently have 2 fleeces on.
10,candidate_0035,hypertension,"my blood pressure readings today have been 106/69, 119/62, and 108/64 are any of these low? yesterday my reading was 80/50 at the drs ofc. im currently on high blood pressure meds. and lost 25lbs. dr. my take me off blood pressure med. he said to monitor it til tomorrow."
11,candidate_0023,hypertension,"Hello,My grand daughter has been suffering with severe abdominal pain for 9 days. She is not running a fever, no vomiting, no diarrhea. She has had high blood pressure for 6 days. She eats in the morning and is feeling pretty good, then come early afternoon abdominal pain, high blood pressure. She is on an IV and has had multiple blood work done, several ultrasounds and x-rays. Doctors can not find an answer. She is four and has a blood pressure 138/111 when pain occurs. Does anyone have any..."
12,candidate_0000,low_back_pain,"Hi! I recently had been tested for pregnancy due to low back pain, headaches, nausea and no appetite. It came back negative. But now, I m constantly sick. I have lower abdomen pains and sharp stabbing center abdomen pains. I have also been very shaky with my hands. And I have no appetite. I have headaches that will last for days on end if I don t take ibuprofen every 6-8 hours. I m not sure what it is. Please help?!"
13,candidate_0014,low_back_pain,"Hi, I am suffering from lower back pain going to my lower right ribs. Ive undergone blood test, urinary test, whole abdominal ultrasound and even kidney xray but found nothing on it. Also lately i feel thirsty all the time. Is there any other kind of test that I need to undergo in order to determine the cause of this?."
14,candidate_0078,low_back_pain,"two months now into it...started off lower back pain then soreness in hip flexor both legs but more on right. now pain and ackey in both legs ham strings and quads. When driving, 10 min in, severe pain or acke from butt down ham into back of knee. I have to get out and stand up. then good for another 10 min. This is getting unbearable."
15,candidate_0048,low_back_pain,hi sir iam having a sciatica problem and lumber spine problem for this pain i had taken a electro homeopathy treatment in that doctor had given me a electric shock on my left leg main nerve for 3 times and the pain is gone for few days only after that it came again i had taken lot of pills but no cure now my doctor suggest me duzella 30 mg so how much its useful for me pls suggest me some good medicine iam fearing tht any side affects will come because my marriage is thier in a month and ia...
16,candidate_0030,low_back_pain,"hi doctor, iam a 42 year old lady with lower back pain on my spine area,iam also experiencing sweating but have no temp. and my tummy has continued to swell over the last 6 months.iam sure iam not pregnant last period 2days ago,heavy for first 2 days with clotting.thanks"
17,candidate_0105,major_depression,"What mental disorder do I have? I m really depressed so it s hard for me to type. I ve just had to re write this so I m very angry, but i ll just put symptoms. Symptoms Used to hear voices (first of my guardian angel and then from god- lasted from January- till Christmas day 2012- only very rarely talk to him agin) - Have many beliefs (voices explained to me about the universe and how he created it from experiments on planets in the solar systems he had made then he let it all die out so tha..."
18,candidate_0139,major_depression,"i just had a surgical termination 2 days ago & i wish i can take it back. it was twins, i didnt want to do it. i still feel very much pregnant minus the extreme nausea. is it possible that the procedure was unsucessful? theres no bleeding, no pain, just alot of crying and an extremely large amount of depression. Is it possible that the surgery was unsuccessful?"
19,candidate_0005,major_depression,Hi my boyfriend and I have been together for over a year and just recently (about 5 months after his best friends death) he has begun to act strange. Hes temper has become a lot worse and he has a short fuse. He is only 20. He feels so much stress and pressure even when there isnt things to stress about. Hes not himself and admitted that he is feeling depressed lately. His moods switch in an instant. Is there something i can do about it? Does he need medical help for depression or manic depr...
20,candidate_0151,major_depression,"I am 18 years old with psychiatric problems. My doctor has prescribed me antidepressants a month ago. However, for the past couple days I have been feeling too happy and hyper. I cannot get an appointment booked immediately. Should I discontinue using my antidepressants until I can talk to my psychiatrist?"
21,candidate_0070,major_depression,My family reports that I am having occasional episodes that sound like absence seizures. What I read says they are rare in adults and I am 62 y.o. female. I have a history of anti-depressant use and my daughter has heard that that may be associated with these.
22,candidate_0160,pregnancy,"Hi doctor! I am 16 years old and I have had unprotected sex about a week ago it was a stupid decision and I regret it a lot. I m so afraid that I am pregnant. Is there anything that I can do to reduce my risk of me falling pregnant? Are there any sighs I should look out for which would indicate wether I m pregnant or not? If it turns out that I am, is there anything I can do to naturally increase my chances of miscarriage ? And if I needed an abortion, there is no chance I could ever ever te..."
23,candidate_0144,pregnancy,"I had sex 2 times the same night, we always use a condom and withdrawal, also the first time i used spermicide, but not the second time (about 2hours later). The thing is the condom broke just before he came and get out, and the tip of the condom was inside me (i was able to get it out). Im wondering about pregnancy chances, ive just finished my period 1 day earlier and it started 1 week ago, my month is about 26-28 days. My dr is away, but she told me to stay away from the morning after pil..."
24,candidate_0000,pregnancy,"Hi! I recently had been tested for pregnancy due to low back pain, headaches, nausea and no appetite. It came back negative. But now, I m constantly sick. I have lower abdomen pains and sharp stabbing center abdomen pains. I have also been very shaky with my hands. And I have no appetite. I have headaches that will last for days on end if I don t take ibuprofen every 6-8 hours. I m not sure what it is. Please help?!"
25,candidate_0116,pregnancy,i have kidney infection 1 week before my period. the doctor gave me tavanic 500mg as an antibiotics for 2 weeks. I am now 20 days delayed in my period but I have done pregnancy test when I was 10 days delayed and it was negative. Does the infection or antibiotics causes the delayed of my period?
26,candidate_0012,pregnancy,"HI, I am 30 years old and my husband is the same age. We have been trying to conceive for almost two years. I had a missed miscarriage last year in September and had a septum removal (disovered during the D&C) in February. Since March we are trying to conceive but nothing happens. I also take low dose aspirin every day prescribed by a doctor as they have discovered that my blood clots a bit more than usual. My husband is alergic to aspirin and now I am worried that maybe that might stop us f..."
27,candidate_0011,sti,"I m 14 and I m sexually active, but I went 7 months without sex, and I received a hand job, then the shaft of my penis starting getting a rash and got a cut on it, it s red and spread to my balls, it has bumps and it hurts.. I don t think it s an std but you never know, it s been two months now and it s only gotten worse. My balls are red and have bumbs and do does my shaft, and my penis did but they disappeared, I m uncircumcised if that helps. It s only on the skin, nothing is on the head ..."
28,candidate_0076,sti,"my boy friend is having bleeding problems from his penis.sunday night while sitting atthe table he had a pain shoot from his kidney down when he got up to go pee he was drippig blood from penis and could not pee because it hurt that bad.i took him to the hospital they said he has a std and thats what they are treating him for,thats not whats wrong,he had kidney stones a couple months ago,last night when he went pee he passed a long worm like in shape blood clot.can you help me?"
29,candidate_0145,sti,"Hi, may I answer your health queries right now ? Hello i am a health 29 yr old female with two children and my boyfriend is a divorcee with no children however he recently said he was diagnosed with ureaplasma, while he has been overseas in Bahrain in the military and we havent been sexually active since Oct 2010. And he thinks it may have been from me however, i have never had any abnormalities in my pap smears in all my years (since 16). I would like to know what exactly causes ureaplasma ..."
30,candidate_0091,sti,"Hello, For the past few months I ve had a small reddish / brown (very light) spot on the head on my penis. It s in the centre on the front (not near the urethra). STD tests were negative, so I m not concerned about that. It doesn t appear to have changed size, nor is it rigid. It is completely flat. Any thoughts?"
31,candidate_0143,sti,I have recently been noticing some small burning pain on my penis shaft. And there have been small white bumps that arent exactly bumps and pop really easily leaving puss. It doesnt look like any STI it has only been happening in correlation to me and my girlfirend (not having sex) but playing with each other really hard. Can it be caused by to much
32,candidate_0008,type2_diabetes,"Hi. In the morning, I rarely have an issue, but in the evening (by 3-5pm and after) all of my arm and leg veins are bulging. There is also change in color from pink to red and swollen feet/toes. I wake up with numb limbs throughout the night very frequently but have not been diagnosed diabetic, vein disorders nothing. I will drink more water but don t know if it would make it worse. I recently quit smoking after 15years, if that helps form an opinion. Thank you. Jeanie."
33,candidate_0131,type2_diabetes,I have chest pains and feel like my heart cant calm down after I urinate. Its like a burning feeling. I am 41 and diabetic and overweight. I am also hypertensive. I also have had unpretected sex in the last four weeks. I was first started feeling this pain about 3 weeks ago.
34,candidate_0109,type2_diabetes,"I am type 2 non insulin diabetic and made very poor choices in food this evening. Just checked my glucometer and reading was 414. Took my vyctoza injection of 1.2 mgs right away. I am not having any symptoms at the moment, but it is bedtime and I cant go to sleep with this reading on my mind. Am I in danger of going into diabetic coma with this high reading? Is there anything I can do at this moment to counter act this reading?"
35,candidate_0010,type2_diabetes,Hi My father is diabetic and had a stroke couple of years ago. Now he has developed sinus in his big toe of right leg. I consulted ortho specialists and they suggested surgery on the big toe. Is there alternative treatement as the blood circulation is low on the right leg and healing might take longer
36,candidate_0058,type2_diabetes,"a friend of mine had stroke on his right side of the brain and for the past 5 days. Before the stroke, he had fever almost every night after 8PM almost for 7 days. He is now in hospital and has his right hand weakness and TOTALLY SPEECHLESS. When spoke with Doctor, he said that they are taking ct-scan to check if the bleeding is progressing - I don t know what he meant this - is that something that it could get worse... Again, please could you let me know if he would be able to gain back his..."

### Удаление повторов между темами

Один медицинский вопрос может содержать признаки нескольких тем knowledge base.

Поэтому после стратифицированного отбора один и тот же `candidate_id`
может встретиться несколько раз.

Для ручной разметки каждый вопрос должен присутствовать только один раз.
При этом сохраняем полный список тем, найденных на предыдущем этапе.

In [164]:
selected_candidate_ids = (
    retrieval_eval_candidates_df[
        "candidate_id"
    ]
    .unique()
)

retrieval_eval_labeling_df = (
    retrieval_candidates_df[
        retrieval_candidates_df[
            "candidate_id"
        ].isin(
            selected_candidate_ids
        )
    ][
        [
            "candidate_id",
            "kb_topics",
            "input",
        ]
    ]
    .reset_index(drop=True)
    .copy()
)

print(
    "Rows before deduplication:",
    len(retrieval_eval_candidates_df),
)

print(
    "Unique evaluation questions:",
    len(retrieval_eval_labeling_df),
)

Rows before deduplication: 37
Unique evaluation questions: 36

### Ручная проверка покрытия knowledge base

Keyword-фильтр определяет только потенциальную тематическую связь вопроса
с knowledge base.

Наличие ключевого слова ещё не означает, что текущие guidelines содержат
информацию, достаточную для ответа на вопрос.

Поэтому каждый кандидат вручную классифицируется как:

- `covered` — вопрос содержательно покрывается текущей knowledge base;
- `not_covered` — тема упоминается, но нужной информации в KB нет;
- `uncertain` — требуется дополнительная проверка guideline.

Для вопросов со статусом `covered` дополнительно указываются релевантный документ
и один или несколько релевантных разделов.

In [165]:
retrieval_eval_labeling_df[
    "coverage"
] = ""

retrieval_eval_labeling_df[
    "relevant_document_id"
] = ""

retrieval_eval_labeling_df[
    "relevant_sections"
] = ""

retrieval_eval_labeling_df[
    "notes"
] = ""

retrieval_eval_labeling_df

,candidate_id,kb_topics,input,coverage,relevant_document_id,relevant_sections,notes
0,candidate_0000,"[low_back_pain, pregnancy]","Hi! I recently had been tested for pregnancy due to low back pain, headaches, nausea and no appetite. It came back negative. But now, I m constantly sick. I have lower abdomen pains and sharp stabbing center abdomen pains. I have also been very shaky with my hands. And I have no appetite. I have headaches that will last for days on end if I don t take ibuprofen every 6-8 hours. I m not sure what it is. Please help?!",,,,
1,candidate_0001,[hypertension],"hi in 2010 I was diagnosed with the right right bundle branch block also with a sinus tachycardia and a heart murmur I recently went to the hospital and was diagnosed with chest wall pain and Mild tricuspid regurgitation and mild tricuspid pulmonic regurgitation, my question is what do I expect from this point on? Should I be concerned? Also diagnosed with a specified essential hypertension and ectopic atrial rhythm other specified cardiac dysrhythmias. Tachycardia unspecified? ? What does t...",,,,
2,candidate_0003,[hypertension],"I had chest pains, back pains going up to my throat and neck, tropamine in my blood. Heart rate 90 bpm. High blood pressure. An ambulance took me to hospital, 4 days of monitoring and an angiogram and echo. They do not know what it was.Still feel washed out and tired with a pain in my chest like I have been kicked. I am a fit 58 year old woman. Was diagnosed with BC in 2010 had chemo, radiotherapy, Herceptin.... and am on Tamoxifen at the moment.",,,,
3,candidate_0004,[asthma],Had a cold for 3 weeks. Went away. 2 weeks later came back. Doctor treated me with 5 day Z Pak (250 mg) & a corticosteroid pill (4 mg). Still sick. Bad cough. Cough up white foamy stuff. Using Mucinex & Robitussin. Lots of clear discharge from nose. Wheezing.,,,,
4,candidate_0005,[major_depression],Hi my boyfriend and I have been together for over a year and just recently (about 5 months after his best friends death) he has begun to act strange. Hes temper has become a lot worse and he has a short fuse. He is only 20. He feels so much stress and pressure even when there isnt things to stress about. Hes not himself and admitted that he is feeling depressed lately. His moods switch in an instant. Is there something i can do about it? Does he need medical help for depression or manic depr...,,,,
5,candidate_0008,[type2_diabetes],"Hi. In the morning, I rarely have an issue, but in the evening (by 3-5pm and after) all of my arm and leg veins are bulging. There is also change in color from pink to red and swollen feet/toes. I wake up with numb limbs throughout the night very frequently but have not been diagnosed diabetic, vein disorders nothing. I will drink more water but don t know if it would make it worse. I recently quit smoking after 15years, if that helps form an opinion. Thank you. Jeanie.",,,,
6,candidate_0010,[type2_diabetes],Hi My father is diabetic and had a stroke couple of years ago. Now he has developed sinus in his big toe of right leg. I consulted ortho specialists and they suggested surgery on the big toe. Is there alternative treatement as the blood circulation is low on the right leg and healing might take longer,,,,
7,candidate_0011,[sti],"I m 14 and I m sexually active, but I went 7 months without sex, and I received a hand job, then the shaft of my penis starting getting a rash and got a cut on it, it s red and spread to my balls, it has bumps and it hurts.. I don t think it s an std but you never know, it s been two months now and it s only gotten worse. My balls are red and have bumbs and do does my shaft, and my penis did but they disappeared, I m uncircumcised if that helps. It s only on the skin, nothing is on the head ...",,,,
8,candidate_0012,[pregnancy],"HI, I am 30 years old and my husband is the same age. We have been trying to conceive for almost two years. I had a missed miscarriage last year in September and had a septum removal (disovered during the D&C) in February. Since March we are trying to conceive but nothing happens. I also take low dose aspirin every day prescribed by a doctor as they have discovered that my blood clots a bit more than usual. My husband is alergic to aspirin and now I am worried that maybe that might stop us f...",,,,
9,candidate_0014,[low_back_pain],"Hi, I am suffering from lower back pain going to my lower right ribs. Ive undergone blood test, urinary test, whole abdominal ultrasound and even kidney xray but found nothing on it. Also lately i feel thirsty all the time. Is there any other kind of test that I need to undergo in order to determine the cause of this?.",,,,
10,candidate_0023,[hypertension],"Hello,My grand daughter has been suffering with severe abdominal pain for 9 days. She is not running a fever, no vomiting, no diarrhea. She has had high blood pressure for 6 days. She eats in the morning and is feeling pretty good, then come early afternoon abdominal pain, high blood pressure. She is on an IV and has had multiple blood work done, several ultrasounds and x-rays. Doctors can not find an answer. She is four and has a blood pressure 138/111 when pain occurs. Does anyone have any...",,,,
11,candidate_0029,[ckd],"I have been told that I have stage 5 advanced chronic kidney disease, blood pressure perfect cholesterol perfect.Feel great look great, drs are surprised say that considering my blood work I shoulod be deathly sick but Im not at all. I was told that i need dialysis and transplant...shouldnt I be tested further",,,,
12,candidate_0030,"[low_back_pain, pregnancy]","hi doctor, iam a 42 year old lady with lower back pain on my spine area,iam also experiencing sweating but have no temp. and my tummy has continued to swell over the last 6 months.iam sure iam not pregnant last period 2days ago,heavy for first 2 days with clotting.thanks",,,,
13,candidate_0035,[hypertension],"my blood pressure readings today have been 106/69, 119/62, and 108/64 are any of these low? yesterday my reading was 80/50 at the drs ofc. im currently on high blood pressure meds. and lost 25lbs. dr. my take me off blood pressure med. he said to monitor it til tomorrow.",,,,
14,candidate_0048,[low_back_pain],hi sir iam having a sciatica problem and lumber spine problem for this pain i had taken a electro homeopathy treatment in that doctor had given me a electric shock on my left leg main nerve for 3 times and the pain is gone for few days only after that it came again i had taken lot of pills but no cure now my doctor suggest me duzella 30 mg so how much its useful for me pls suggest me some good medicine iam fearing tht any side affects will come because my marriage is thier in a month and ia...,,,,
15,candidate_0058,[type2_diabetes],"a friend of mine had stroke on his right side of the brain and for the past 5 days. Before the stroke, he had fever almost every night after 8PM almost for 7 days. He is now in hospital and has his right hand weakness and TOTALLY SPEECHLESS. When spoke with Doctor, he said that they are taking ct-scan to check if the bleeding is progressing - I don t know what he meant this - is that something that it could get worse... Again, please could you let me know if he would be able to gain back his...",,,,
16,candidate_0063,[asthma],"My 9 year old grandson who has a history of asthma but has not been on any medication nor had a reaction in at least 3 months had Eosinophils,absolute of 544 and AST of 33. doctor didnt seem at all concerned. Should there be any follow up or need for concern?",,,,
17,candidate_0066,[hypertension],I have hypertension currently 160 / 95 and has been for some weeks. I exercise regularly run 5k 3 times per week. I recently had gout but it has gone and I am back into regular exercise. I keep having pains in the base of my foot to the point it is difficult to walk and go extremely cold. I currently have 2 fleeces on.,,,,
18,candidate_0067,[ckd],hi i am 30 years old and my husband an i have been trying to conceive for 19 cycles now with no success. I was diagnosed with medullary sponge kidney 5 years ago and am wondering if this is causing us to not conceive. We have both been tested by fertility specialists and he was by urologist and we are both fine. Except this kidney disease and frequent uti s that i keep having. Your help and advise is greatly appreciated.,,,,
19,candidate_0070,[major_depression],My family reports that I am having occasional episodes that sound like absence seizures. What I read says they are rare in adults and I am 62 y.o. female. I have a history of anti-depressant use and my daughter has heard that that may be associated with these.,,,,
20,candidate_0071,[asthma],hi there i am 24 an a female im a mum of 4 last sunday i had this extreme pain on both sides of my spine which to this day i still have it i was subscribed codiene for the pain which didnt doanything i cant sleep at night as lying down hurt any movement to my back bring tears i cant touch my back also breathing coughing hurts... an i have now another problem that happend 2 nights ago an i had a very sharp pain in my heart which made my left arm go dead an all my finger tips went numb an felt...,,,,
21,candidate_0076,[sti],"my boy friend is having bleeding problems from his penis.sunday night while sitting atthe table he had a pain shoot from his kidney down when he got up to go pee he was drippig blood from penis and could not pee because it hurt that bad.i took him to the hospital they said he has a std and thats what they are treating him for,thats not whats wrong,he had kidney stones a couple months ago,last night when he went pee he passed a long worm like in shape blood clot.can you help me?",,,,
22,candidate_0078,[low_back_pain],"two months now into it...started off lower back pain then soreness in hip flexor both legs but more on right. now pain and ackey in both legs ham strings and quads. When driving, 10 min in, severe pain or acke from butt down ham into back of knee. I have to get out and stand up. then good for another 10 min. This is getting unbearable.",,,,
23,candidate_0091,[sti],"Hello, For the past few months I ve had a small reddish / brown (very light) spot on the head on my penis. It s in the centre on the front (not near the urethra). STD tests were negative, so I m not concerned about that. It doesn t appear to have changed size, nor is it rigid. It is completely flat. Any thoughts?",,,,
24,candidate_0097,[asthma],"ihave severe asthma and have been 5 times in the last 9 weeks and been given lots of steroids, so i am on insulin now. i am so wore ouy and can hardly get around. thw wheezing has stopped. i have high numbers of latic acid in the muscles. please tell me what to do.",,,,
25,candidate_0105,[major_depression],"What mental disorder do I have? I m really depressed so it s hard for me to type. I ve just had to re write this so I m very angry, but i ll just put symptoms. Symptoms Used to hear voices (first of my guardian angel and then from god- lasted from January- till Christmas day 2012- only very rarely talk to him agin) - Have many beliefs (voices explained to me about the universe and how he created it from experiments on planets in the solar systems he had made then he let it all die out so tha...",,,,
26,candidate_0109,[type2_diabetes],"I am type 2 non insulin diabetic and made very poor choices in food this evening. Just checked my glucometer and reading was 414. Took my vyctoza injection of 1.2 mgs right away. I am not having any symptoms at the moment, but it is bedtime and I cant go to sleep with this reading on my mind. Am I in danger of going into diabetic coma with this high reading? Is there anything I can do at this moment to counter act this reading?",,,,
27,candidate_0116,[pregnancy],i have kidney infection 1 week before my period. the doctor gave me tavanic 500mg as an antibiotics for 2 weeks. I am now 20 days delayed in my period but I have done pregnancy test when I was 10 days delayed and it was negative. Does the infection or antibiotics causes the delayed of my period?,,,,
28,candidate_0131,[type2_diabetes],I have chest pains and feel like my heart cant calm down after I urinate. Its like a burning feeling. I am 41 and diabetic and overweight. I am also hypertensive. I also have had unpretected sex in the last four weeks. I was first started feeling this pain about 3 weeks ago.,,,,
29,candidate_0135,[asthma],"I experience respiratory distress symptoms (SOB, decreased O2, voice changes) when I am exposed to perfumes and a few other strong oders and flying dust/dirt. What could this be a symptoms of?I am 37 years old, weigh 145, and have no hx of asthma or any other respiratory issues.",,,,
30,candidate_0139,"[major_depression, pregnancy]","i just had a surgical termination 2 days ago & i wish i can take it back. it was twins, i didnt want to do it. i still feel very much pregnant minus the extreme nausea. is it possible that the procedure was unsucessful? theres no bleeding, no pain, just alot of crying and an extremely large amount of depression. Is it possible that the surgery was unsuccessful?",,,,
31,candidate_0143,[sti],I have recently been noticing some small burning pain on my penis shaft. And there have been small white bumps that arent exactly bumps and pop really easily leaving puss. It doesnt look like any STI it has only been happening in correlation to me and my girlfirend (not having sex) but playing with each other really hard. Can it be caused by to much,,,,
32,candidate_0144,[pregnancy],"I had sex 2 times the same night, we always use a condom and withdrawal, also the first time i used spermicide, but not the second time (about 2hours later). The thing is the condom broke just before he came and get out, and the tip of the condom was inside me (i was able to get it out). Im wondering about pregnancy chances, ive just finished my period 1 day earlier and it started 1 week ago, my month is about 26-28 days. My dr is away, but she told me to stay away from the morning after pil...",,,,
33,candidate_0145,[sti],"Hi, may I answer your health queries right now ? Hello i am a health 29 yr old female with two children and my boyfriend is a divorcee with no children however he recently said he was diagnosed with ureaplasma, while he has been overseas in Bahrain in the military and we havent been sexually active since Oct 2010. And he thinks it may have been from me however, i have never had any abnormalities in my pap smears in all my years (since 16). I would like to know what exactly causes ureaplasma ...",,,,
34,candidate_0151,[major_depression],"I am 18 years old with psychiatric problems. My doctor has prescribed me antidepressants a month ago. However, for the past couple days I have been feeling too happy and hyper. I cannot get an appointment booked immediately. Should I discontinue using my antidepressants until I can talk to my psychiatrist?",,,,
35,candidate_0160,[pregnancy],"Hi doctor! I am 16 years old and I have had unprotected sex about a week ago it was a stupid decision and I regret it a lot. I m so afraid that I am pregnant. Is there anything that I can do to reduce my risk of me falling pregnant? Are there any sighs I should look out for which would indicate wether I m pregnant or not? If it turns out that I am, is there anything I can do to naturally increase my chances of miscarriage ? And if I needed an abortion, there is no chance I could ever ever te...",,,,

In [166]:
coverage_labels = {
    "candidate_0000": "not_covered",
    "candidate_0001": "not_covered",
    "candidate_0003": "not_covered",
    "candidate_0004": "uncertain",
    "candidate_0005": "uncertain",
    "candidate_0008": "not_covered",
    "candidate_0010": "uncertain",
    "candidate_0011": "uncertain",
    "candidate_0012": "not_covered",
    "candidate_0014": "covered",
    "candidate_0023": "not_covered",
    "candidate_0029": "covered",
    "candidate_0030": "not_covered",
    "candidate_0035": "uncertain",
    "candidate_0048": "covered",
    "candidate_0058": "not_covered",
    "candidate_0063": "not_covered",
    "candidate_0066": "not_covered",
    "candidate_0067": "not_covered",
    "candidate_0070": "not_covered",
    "candidate_0071": "not_covered",
    "candidate_0076": "not_covered",
    "candidate_0078": "covered",
    "candidate_0091": "not_covered",
    "candidate_0097": "uncertain",
    "candidate_0105": "uncertain",
    "candidate_0109": "uncertain",
    "candidate_0116": "not_covered",
    "candidate_0131": "not_covered",
    "candidate_0135": "uncertain",
    "candidate_0139": "not_covered",
    "candidate_0143": "not_covered",
    "candidate_0144": "not_covered",
    "candidate_0145": "uncertain",
    "candidate_0151": "uncertain",
    "candidate_0160": "not_covered",
}

In [167]:
retrieval_eval_labeling_df["coverage"] = (
    retrieval_eval_labeling_df[
        "candidate_id"
    ].map(coverage_labels)
)

retrieval_eval_labeling_df[
    "coverage"
].value_counts()

coverage
not_covered    21
uncertain      11
covered         4
Name: count, dtype: int64

In [168]:
topic_coverage_df = (
    retrieval_eval_labeling_df[
        [
            "candidate_id",
            "kb_topics",
            "coverage",
        ]
    ]
    .explode("kb_topics")
)

topic_coverage_df.groupby(
    [
        "kb_topics",
        "coverage",
    ]
).size()

kb_topics         coverage
asthma            not_covered    2
                  uncertain      3
ckd               covered        1
                  not_covered    1
hypertension      not_covered    4
                  uncertain      1
low_back_pain     covered        3
                  not_covered    2
major_depression  not_covered    2
                  uncertain      3
pregnancy         not_covered    7
sti               not_covered    3
                  uncertain      2
type2_diabetes    not_covered    3
                  uncertain      2
dtype: int64

In [169]:
uncertain_questions_df = (
    retrieval_eval_labeling_df[
        retrieval_eval_labeling_df[
            "coverage"
        ].eq("uncertain")
    ][
        [
            "candidate_id",
            "kb_topics",
            "input",
        ]
    ]
    .reset_index(drop=True)
)

pd.set_option(
    "display.max_colwidth",
    None,
)

uncertain_questions_df

,candidate_id,kb_topics,input
0,candidate_0004,[asthma],Had a cold for 3 weeks. Went away. 2 weeks later came back. Doctor treated me with 5 day Z Pak (250 mg) & a corticosteroid pill (4 mg). Still sick. Bad cough. Cough up white foamy stuff. Using Mucinex & Robitussin. Lots of clear discharge from nose. Wheezing.
1,candidate_0005,[major_depression],Hi my boyfriend and I have been together for over a year and just recently (about 5 months after his best friends death) he has begun to act strange. Hes temper has become a lot worse and he has a short fuse. He is only 20. He feels so much stress and pressure even when there isnt things to stress about. Hes not himself and admitted that he is feeling depressed lately. His moods switch in an instant. Is there something i can do about it? Does he need medical help for depression or manic depression? Is there something besides medication to help?
2,candidate_0010,[type2_diabetes],Hi My father is diabetic and had a stroke couple of years ago. Now he has developed sinus in his big toe of right leg. I consulted ortho specialists and they suggested surgery on the big toe. Is there alternative treatement as the blood circulation is low on the right leg and healing might take longer
3,candidate_0011,[sti],"I m 14 and I m sexually active, but I went 7 months without sex, and I received a hand job, then the shaft of my penis starting getting a rash and got a cut on it, it s red and spread to my balls, it has bumps and it hurts.. I don t think it s an std but you never know, it s been two months now and it s only gotten worse. My balls are red and have bumbs and do does my shaft, and my penis did but they disappeared, I m uncircumcised if that helps. It s only on the skin, nothing is on the head of my penis, I m scared to go to the doctor. And puss come out of my balls and shaft and it s yellow, please help me. Thank you."
4,candidate_0035,[hypertension],"my blood pressure readings today have been 106/69, 119/62, and 108/64 are any of these low? yesterday my reading was 80/50 at the drs ofc. im currently on high blood pressure meds. and lost 25lbs. dr. my take me off blood pressure med. he said to monitor it til tomorrow."
5,candidate_0097,[asthma],"ihave severe asthma and have been 5 times in the last 9 weeks and been given lots of steroids, so i am on insulin now. i am so wore ouy and can hardly get around. thw wheezing has stopped. i have high numbers of latic acid in the muscles. please tell me what to do."
6,candidate_0105,[major_depression],"What mental disorder do I have? I m really depressed so it s hard for me to type. I ve just had to re write this so I m very angry, but i ll just put symptoms. Symptoms Used to hear voices (first of my guardian angel and then from god- lasted from January- till Christmas day 2012- only very rarely talk to him agin) - Have many beliefs (voices explained to me about the universe and how he created it from experiments on planets in the solar systems he had made then he let it all die out so that he could use all that power to create a world big enough to plant and create a cycle of many creations and many other stories) - laugh at innopropiate things- laugh at sad things or serious things (that inside i know is not funny, but I can t help it) such as people crying, people shouting or being shouted at, people saying there loved one had died or something sad had happened to them. Don t laugh at funny things, like people laughing so badly at a joke, that I don t think is funny, and I m the only one who doesn t get the joke and I look miserable. - sleeping patterns- cant get to sleep until at least 3am and don t get up until at least 11am. - scared of people- walking past people or seeing people that aren t my sister, my mother, sometimes my father or me makes me disturbed, petrified, paranoid and a panic attack feeling. - staying in bed all the time- always in my bed away from everyone either sleeping, hiding under bed sheets or planning a new life (obsessed with it even though it s not something I like). - obsession with certain numbers- obsession with numbers 2 and 5, always using them for things like, I will have 2 sips and 5 gulps, I will get out the cold shower in 2 minutes and 5 seconds then 5 minutes and 2 seconds. -Talking- I hadly answer people when they speak to me and I never seem like I m listening. - referred to as rude- although I see my self as being polite - don t have any ambitions in life, and just think about death -too scared to go out in public - dont care about anything (I mean anything except for my dad, sister and mother and pets) - crying- always cry when pet usually does but when my last pet died on my birthday I seemed ok about it. -uncomfortable with speaking to people - swearing- I ve never swore, but recently Ive been swearing with words that I would never dare say. - sex- got obsessed with sexual activity, such as wanting to have sex, imagine having sex, and planning my dream life as being raped (even though I would never dare to be raped) -hallucinations or dream- woke up at night seeing blue dots on the ceiling and hearing a Disney film being played although cannot see, then I m being strangled and cannot scream that I can feel- did not wake up from this- same side I was on- same darkness from outside and all just disapeared over time with a pain still in my neck- I believe it was a hallucination. Hugs- uncomfortable with being hugged Delusions- believe that talking or seeing someone that they will call me a lier, criticise me and spy on me all the time- feel as if someone is watching me and more. Thoughts- suicidal and depressive, unhappy, sick feeling thoughts. I just want to know if I have a disorder or not, because something is not right, I already treated for being depressed and there are a lot more symptoms but that s enough I think."
7,candidate_0109,[type2_diabetes],"I am type 2 non insulin diabetic and made very poor choices in food this evening. Just checked my glucometer and reading was 414. Took my vyctoza injection of 1.2 mgs right away. I am not having any symptoms at the moment, but it is bedtime and I cant go to sleep with this reading on my mind. Am I in danger of going into diabetic coma with this high reading? Is there anything I can do at this moment to counter act this reading?"
8,candidate_0135,[asthma],"I experience respiratory distress symptoms (SOB, decreased O2, voice changes) when I am exposed to perfumes and a few other strong oders and flying dust/dirt. What could this be a symptoms of?I am 37 years old, weigh 145, and have no hx of asthma or any other respiratory issues."
9,candidate_0145,[sti],"Hi, may I answer your health queries right now ? Hello i am a health 29 yr old female with two children and my boyfriend is a divorcee with no children however he recently said he was diagnosed with ureaplasma, while he has been overseas in Bahrain in the military and we havent been sexually active since Oct 2010. And he thinks it may have been from me however, i have never had any abnormalities in my pap smears in all my years (since 16). I would like to know what exactly causes ureaplasma in males..ive heard several things, it can be from a female carrier (who is infertile like his ex-wife) or from anal.But i am just not sure. I just want to get some clear answers...could I have given this to him Ive had BV since weve been sexually active... Is he the cause for it? What causes ureaplasma? Is it linked to HPV? Do I have reason to believe hes been unfaithful since he got to Bahrain if this is an STD or could he have contracted this from his ex-wife since the organism has been known to lie dormant for a while ....thank u for your time"
10,candidate_0151,[major_depression],"I am 18 years old with psychiatric problems. My doctor has prescribed me antidepressants a month ago. However, for the past couple days I have been feeling too happy and hyper. I cannot get an appointment booked immediately. Should I discontinue using my antidepressants until I can talk to my psychiatrist?"

In [170]:
resolved_coverage = {
    "candidate_0004": "not_covered",   # cough/wheezing after infection; слишком широкий respiratory differential
    "candidate_0005": "covered",       # depression + необходимость помощи + non-pharmacologic treatment
    "candidate_0010": "not_covered",   # diabetic foot lesion + surgery/vascular issue
    "candidate_0011": "not_covered",   # genital rash/pus без установленной STI; широкий differential
    "candidate_0035": "not_covered",   # hypotension на antihypertensives, вопрос об отмене препарата
    "candidate_0097": "covered",       # severe asthma, repeated steroid courses, poor control
    "candidate_0105": "not_covered",   # psychosis/hallucinations/suicidality, вопрос о psychiatric diagnosis
    "candidate_0109": "not_covered",   # acute severe hyperglycemia / possible emergency
    "candidate_0135": "covered",       # симптомы, провоцируемые irritants; asthma diagnosis/assessment
    "candidate_0145": "covered",       # Ureaplasma / STI-related question
    "candidate_0151": "not_covered",   # possible antidepressant-induced mania; immediate medication decision
}

for candidate_id, coverage in resolved_coverage.items():
    retrieval_eval_labeling_df.loc[
        retrieval_eval_labeling_df["candidate_id"].eq(candidate_id),
        "coverage",
    ] = coverage

In [171]:
retrieval_eval_labeling_df[
    "coverage"
].value_counts()

coverage
not_covered    28
covered         8
Name: count, dtype: int64

### Разметка covered-вопросов

Для независимой оценки retrieval оставляем только вопросы, которые однозначно
покрываются текущей knowledge base.

Для каждого такого вопроса вручную определяем:

- релевантный clinical guideline;
- один или несколько разделов, содержащих информацию для ответа.

Разметка выполняется по структуре knowledge base до просмотра результатов dense retrieval.

In [172]:
covered_dev_eval_df = (
    retrieval_eval_labeling_df[
        retrieval_eval_labeling_df[
            "coverage"
        ].eq("covered")
    ]
    .reset_index(drop=True)
    .copy()
)

covered_dev_eval_df[
    [
        "candidate_id",
        "kb_topics",
        "input",
    ]
]

,candidate_id,kb_topics,input
0,candidate_0005,[major_depression],Hi my boyfriend and I have been together for over a year and just recently (about 5 months after his best friends death) he has begun to act strange. Hes temper has become a lot worse and he has a short fuse. He is only 20. He feels so much stress and pressure even when there isnt things to stress about. Hes not himself and admitted that he is feeling depressed lately. His moods switch in an instant. Is there something i can do about it? Does he need medical help for depression or manic depression? Is there something besides medication to help?
1,candidate_0014,[low_back_pain],"Hi, I am suffering from lower back pain going to my lower right ribs. Ive undergone blood test, urinary test, whole abdominal ultrasound and even kidney xray but found nothing on it. Also lately i feel thirsty all the time. Is there any other kind of test that I need to undergo in order to determine the cause of this?."
2,candidate_0029,[ckd],"I have been told that I have stage 5 advanced chronic kidney disease, blood pressure perfect cholesterol perfect.Feel great look great, drs are surprised say that considering my blood work I shoulod be deathly sick but Im not at all. I was told that i need dialysis and transplant...shouldnt I be tested further"
3,candidate_0048,[low_back_pain],hi sir iam having a sciatica problem and lumber spine problem for this pain i had taken a electro homeopathy treatment in that doctor had given me a electric shock on my left leg main nerve for 3 times and the pain is gone for few days only after that it came again i had taken lot of pills but no cure now my doctor suggest me duzella 30 mg so how much its useful for me pls suggest me some good medicine iam fearing tht any side affects will come because my marriage is thier in a month and iam having high uric acid 9.0
4,candidate_0078,[low_back_pain],"two months now into it...started off lower back pain then soreness in hip flexor both legs but more on right. now pain and ackey in both legs ham strings and quads. When driving, 10 min in, severe pain or acke from butt down ham into back of knee. I have to get out and stand up. then good for another 10 min. This is getting unbearable."
5,candidate_0097,[asthma],"ihave severe asthma and have been 5 times in the last 9 weeks and been given lots of steroids, so i am on insulin now. i am so wore ouy and can hardly get around. thw wheezing has stopped. i have high numbers of latic acid in the muscles. please tell me what to do."
6,candidate_0135,[asthma],"I experience respiratory distress symptoms (SOB, decreased O2, voice changes) when I am exposed to perfumes and a few other strong oders and flying dust/dirt. What could this be a symptoms of?I am 37 years old, weigh 145, and have no hx of asthma or any other respiratory issues."
7,candidate_0145,[sti],"Hi, may I answer your health queries right now ? Hello i am a health 29 yr old female with two children and my boyfriend is a divorcee with no children however he recently said he was diagnosed with ureaplasma, while he has been overseas in Bahrain in the military and we havent been sexually active since Oct 2010. And he thinks it may have been from me however, i have never had any abnormalities in my pap smears in all my years (since 16). I would like to know what exactly causes ureaplasma in males..ive heard several things, it can be from a female carrier (who is infertile like his ex-wife) or from anal.But i am just not sure. I just want to get some clear answers...could I have given this to him Ive had BV since weve been sexually active... Is he the cause for it? What causes ureaplasma? Is it linked to HPV? Do I have reason to believe hes been unfaithful since he got to Bahrain if this is an STD or could he have contracted this from his ex-wife since the organism has been known to lie dormant for a while ....thank u for your time"

In [173]:
relevant_documents = {
    "candidate_0005": "va_dod_major_depression_2022",
    "candidate_0014": "va_dod_low_back_pain_2022",
    "candidate_0029": "va_dod_ckd_2025",
    "candidate_0048": "va_dod_low_back_pain_2022",
    "candidate_0078": "va_dod_low_back_pain_2022",
    "candidate_0097": "va_dod_asthma_2025",
    "candidate_0135": "va_dod_asthma_2025",
    "candidate_0145": "cdc_sti_2021",
}

covered_dev_eval_df[
    "relevant_document_id"
] = (
    covered_dev_eval_df[
        "candidate_id"
    ].map(relevant_documents)
)

In [174]:
def show_document_sections(document_id):
    return (
        retrieval_records_df[
            retrieval_records_df[
                "document_id"
            ].eq(document_id)
        ][
            "section_path"
        ]
        .drop_duplicates()
        .sort_values()
        .tolist()
    )

In [175]:
for section in show_document_sections(
    "va_dod_asthma_2025"
):
    print(section)

Appendix C: Assessments of Asthma Severity and Control > A. Assessment of Asthma Severity
Appendix C: Assessments of Asthma Severity and Control > B. Assessment of Asthma Control
Appendix C: Assessments of Asthma Severity and Control > C. Indications for Specialist Referral
Appendix C: Assessments of Asthma Severity and Control > D. Identifying Alternative Diagnoses
Appendix D: Details of a Comprehensive History and Physical Exam > A. Details of a Comprehensive History
Appendix D: Details of a Comprehensive History and Physical Exam > B. Details of a Comprehensive Physical Exam
Appendix F: Example Asthma Action Plan Templates
Appendix F: Example Asthma Action Plan Templates > A. National Heart, Lung, and Blood Institute Asthma Action Plan Example Template
Appendix F: Example Asthma Action Plan Templates > B. Department of Defense Asthma Action Plan Template
Appendix F: Example Asthma Action Plan Templates > C. CDC Asthma Action Plan Templates
Appendix G: Additional Information on Pharmacotherapy > A. Considerations Regarding Biological Agents
Appendix G: Additional Information on Pharmacotherapy > B. Considerations Regarding Theophylline
Appendix G: Additional Information on Pharmacotherapy > C. Additional Information on Drugs Used in Treatment of Asthma
Appendix K: Alternative Text Descriptions of Algorithms
Appendix K: Alternative Text Descriptions of Algorithms > A. Module A: Assessment and Diagnosis of Asthma
Appendix K: Alternative Text Descriptions of Algorithms > B. Module B: Initiation of Therapy
I. Introduction
II. Background > A. Description of Asthma
II. Background > B. Classification of Asthma Severity and Control
II. Background > C. Epidemiology and Impact in the General Population
II. Background > D. Asthma in the Department of Defense and the Department of Veterans Affairs Populations
III. Scope of This Guideline
III. Scope of This Guideline > A. Guideline Audience
III. Scope of This Guideline > B. Guideline Population
IV. Highlighted Features of This Guideline > A. Highlights in This Guideline Update
IV. Highlighted Features of This Guideline > B. Components of This Guideline
IV. Highlighted Features of This Guideline > C. Demographic Terminology in this Guideline
IX. Recommendations
IX. Recommendations > A. Diagnosis and Assessment
IX. Recommendations > B. Treatment and Management
VII. Approach to Care in the Department of Veterans Affairs and the Department of Defense > A. Patient-Centered Care
VII. Approach to Care in the Department of Veterans Affairs and the Department of Defense > B. Shared Decision Making
VII. Approach to Care in the Department of Veterans Affairs and the Department of Defense > C. Patients with Co-occurring Conditions
VIII. Algorithm

In [176]:
asthma_relevant_sections = {
    "candidate_0097": [
        (
            "Appendix C: Assessments of Asthma Severity and Control "
            "> B. Assessment of Asthma Control"
        ),
        (
            "Appendix C: Assessments of Asthma Severity and Control "
            "> C. Indications for Specialist Referral"
        ),
        "IX. Recommendations > B. Treatment and Management",
    ],

    "candidate_0135": [
        "IX. Recommendations > A. Diagnosis and Assessment",
        (
            "Appendix C: Assessments of Asthma Severity and Control "
            "> D. Identifying Alternative Diagnoses"
        ),
        (
            "Appendix D: Details of a Comprehensive History and Physical Exam "
            "> A. Details of a Comprehensive History"
        ),
        (
            "Appendix K: Alternative Text Descriptions of Algorithms "
            "> A. Module A: Assessment and Diagnosis of Asthma"
        ),
    ],
}

In [177]:
for candidate_id, sections in asthma_relevant_sections.items():
    covered_dev_eval_df.loc[
        covered_dev_eval_df["candidate_id"].eq(candidate_id),
        "relevant_sections",
    ] = pd.Series(
        [sections],
        index=covered_dev_eval_df.index[
            covered_dev_eval_df["candidate_id"].eq(candidate_id)
        ],
    )

In [178]:
for candidate_id, sections in asthma_relevant_sections.items():
    covered_dev_eval_df.loc[
        covered_dev_eval_df["candidate_id"].eq(candidate_id),
        "relevant_sections",
    ] = pd.Series(
        [sections],
        index=covered_dev_eval_df.index[
            covered_dev_eval_df["candidate_id"].eq(candidate_id)
        ],
    )

In [179]:
covered_dev_eval_df[
    covered_dev_eval_df["candidate_id"].isin(
        ["candidate_0097", "candidate_0135"]
    )
][
    [
        "candidate_id",
        "relevant_document_id",
        "relevant_sections",
    ]
]

,candidate_id,relevant_document_id,relevant_sections
5,candidate_0097,va_dod_asthma_2025,"[Appendix C: Assessments of Asthma Severity and Control > B. Assessment of Asthma Control, Appendix C: Assessments of Asthma Severity and Control > C. Indications for Specialist Referral, IX. Recommendations > B. Treatment and Management]"
6,candidate_0135,va_dod_asthma_2025,"[IX. Recommendations > A. Diagnosis and Assessment, Appendix C: Assessments of Asthma Severity and Control > D. Identifying Alternative Diagnoses, Appendix D: Details of a Comprehensive History and Physical Exam > A. Details of a Comprehensive History, Appendix K: Alternative Text Descriptions of Algorithms > A. Module A: Assessment and Diagnosis of Asthma]"

In [180]:
for section in show_document_sections(
    "va_dod_major_depression_2022"
):
    print(section)

Appendix G: Alternative Text Descriptions of Algorithm
Appendix I: Quick Guide to the Patient Health Questionnaire in Clinical Practice > A. Purpose
Appendix I: Quick Guide to the Patient Health Questionnaire in Clinical Practice > B. Scoring the PHQ-9 (223)
Appendix I: Quick Guide to the Patient Health Questionnaire in Clinical Practice > C. Using the PHQ-9 in Measurement-Based Care
Appendix I: Quick Guide to the Patient Health Questionnaire in Clinical Practice > D. Example of Using the PHQ-9 in Clinical Practice
Appendix I: Quick Guide to the Patient Health Questionnaire in Clinical Practice > E. Additional Clinical Considerations
Appendix J: Pharmacotherapy
Appendix K: Definitions > A. Major Depressive Disorder
Appendix K: Definitions > B. Treatments
I. Introduction
II. Background > A. Description of Major Depressive Disorder (MDD)
II. Background > B. Epidemiology and Impact on the General Population
II. Background > C. Major Depressive Disorder in the Department of Defense and the Department of Veterans Affairs Populations
III. Scope of this Guideline
III. Scope of this Guideline > A. Guideline Audience
III. Scope of this Guideline > B. Guideline Population
IV. Highlighted Features of this Guideline > A. Highlights in this Guideline Update
IV. Highlighted Features of this Guideline > B. Components of the Guideline
IX. Recommendations
IX. Recommendations > A. Screening
IX. Recommendations > B. Monitoring Outcomes
IX. Recommendations > C. Treatment Setting
IX. Recommendations > D. Treatment of Uncomplicated MDD
IX. Recommendations > E. Treatment of MDD that is Severe or has a Partial or Limited Response to Initial Treatment
IX. Recommendations > F. Relapse Prevention/Continuation Phase (All Severities and Complexities)
IX. Recommendations > G. Recommendations for Specific Populations
IX. Recommendations > H. Self-help, Complementary, and Alternative Treatments
IX. Recommendations > I. Other Treatments with a Recommendation Against Use
VII. Approach to Care in Department of Veterans Affairs and Department of Defense > A. Patient-centered Care
VII. Approach to Care in Department of Veterans Affairs and Department of Defense > B. Shared Decision Making
VII. Approach to Care in Department of Veterans Affairs and Department of Defense > C. Patients with Co-occurring Conditions
VIII. Algorithm
VIII. Algorithm > A. Module A: Initial Assessment and Treatment
VIII. Algorithm > B. Module B: Advanced Care Management

In [181]:
mdd_relevant_sections = {
    "candidate_0005": [
        "VIII. Algorithm > A. Module A: Initial Assessment and Treatment",
        "IX. Recommendations > C. Treatment Setting",
        "IX. Recommendations > D. Treatment of Uncomplicated MDD",
        (
            "IX. Recommendations > H. Self-help, "
            "Complementary, and Alternative Treatments"
        ),
    ],
}

In [182]:
for candidate_id, sections in mdd_relevant_sections.items():
    covered_dev_eval_df.loc[
        covered_dev_eval_df["candidate_id"].eq(candidate_id),
        "relevant_sections",
    ] = pd.Series(
        [sections],
        index=covered_dev_eval_df.index[
            covered_dev_eval_df["candidate_id"].eq(candidate_id)
        ],
    )

In [183]:
covered_dev_eval_df[
    covered_dev_eval_df["candidate_id"].eq(
        "candidate_0005"
    )
][
    [
        "candidate_id",
        "relevant_document_id",
        "relevant_sections",
    ]
]

,candidate_id,relevant_document_id,relevant_sections
0,candidate_0005,va_dod_major_depression_2022,"[VIII. Algorithm > A. Module A: Initial Assessment and Treatment, IX. Recommendations > C. Treatment Setting, IX. Recommendations > D. Treatment of Uncomplicated MDD, IX. Recommendations > H. Self-help, Complementary, and Alternative Treatments]"

In [184]:
for section in show_document_sections(
    "va_dod_low_back_pain_2022"
):
    print(section)

Appendix E: Dosing for Select Pharmacologic Agentsa,b
Appendix F: Glossary
Appendix I: Alternative Text Descriptions of Algorithm
Appendix I: Alternative Text Descriptions of Algorithm > A. Module A: Initial Evaluation of Low Back Pain
Appendix I: Alternative Text Descriptions of Algorithm > B. Module B: Management of Low Back Pain
I. Introduction
II. Background > A. Description of Low Back Pain
II. Background > B. Epidemiology and Impact
III. Scope of this Guideline
III. Scope of this Guideline > A. Guideline Audience
III. Scope of this Guideline > B. Guideline Population
IV. Highlighted Features of this Guideline > A. Highlights in this Guideline Update
IV. Highlighted Features of this Guideline > B. Components of the Guideline
IX. Recommendations
IX. Recommendations > A. Evaluation and Diagnostic Approach
IX. Recommendations > B. Patient Education and Self-care
IX. Recommendations > C. Non-pharmacologic and Non-invasive Therapy
IX. Recommendations > D. Pharmacotherapy
IX. Recommendations > E. Dietary Supplements
IX. Recommendations > F. Non-surgical Invasive Therapy
IX. Recommendations > G. Team Approach
VII. Approach to Care in Department of Veterans Affairs and Department of Defense > A. Patient-centered Care
VII. Approach to Care in Department of Veterans Affairs and Department of Defense > B. Shared Decision Making
VII. Approach to Care in Department of Veterans Affairs and Department of Defense > C. Patients with Co-occurring Conditions
VIII. Algorithm
VIII. Algorithm > A. Module A: Initial Evaluation of Low Back Pain
VIII. Algorithm > B. Module B: Management of Low Back Pain

In [185]:
lbp_relevant_sections = {
    "candidate_0014": [
        "IX. Recommendations > A. Evaluation and Diagnostic Approach",
        "VIII. Algorithm > A. Module A: Initial Evaluation of Low Back Pain",
        (
            "Appendix I: Alternative Text Descriptions of Algorithm "
            "> A. Module A: Initial Evaluation of Low Back Pain"
        ),
    ],

    "candidate_0048": [
        "IX. Recommendations > D. Pharmacotherapy",
        (
            "IX. Recommendations > C. "
            "Non-pharmacologic and Non-invasive Therapy"
        ),
        "VIII. Algorithm > B. Module B: Management of Low Back Pain",
        (
            "Appendix I: Alternative Text Descriptions of Algorithm "
            "> B. Module B: Management of Low Back Pain"
        ),
    ],

    "candidate_0078": [
        "IX. Recommendations > A. Evaluation and Diagnostic Approach",
        "VIII. Algorithm > A. Module A: Initial Evaluation of Low Back Pain",
        "VIII. Algorithm > B. Module B: Management of Low Back Pain",
    ],
}

In [186]:
for candidate_id, sections in lbp_relevant_sections.items():
    covered_dev_eval_df.loc[
        covered_dev_eval_df["candidate_id"].eq(candidate_id),
        "relevant_sections",
    ] = pd.Series(
        [sections],
        index=covered_dev_eval_df.index[
            covered_dev_eval_df["candidate_id"].eq(candidate_id)
        ],
    )

In [187]:
covered_dev_eval_df[
    covered_dev_eval_df["candidate_id"].isin(
        [
            "candidate_0014",
            "candidate_0048",
            "candidate_0078",
        ]
    )
][
    [
        "candidate_id",
        "relevant_document_id",
        "relevant_sections",
    ]
]

,candidate_id,relevant_document_id,relevant_sections
1,candidate_0014,va_dod_low_back_pain_2022,"[IX. Recommendations > A. Evaluation and Diagnostic Approach, VIII. Algorithm > A. Module A: Initial Evaluation of Low Back Pain, Appendix I: Alternative Text Descriptions of Algorithm > A. Module A: Initial Evaluation of Low Back Pain]"
3,candidate_0048,va_dod_low_back_pain_2022,"[IX. Recommendations > D. Pharmacotherapy, IX. Recommendations > C. Non-pharmacologic and Non-invasive Therapy, VIII. Algorithm > B. Module B: Management of Low Back Pain, Appendix I: Alternative Text Descriptions of Algorithm > B. Module B: Management of Low Back Pain]"
4,candidate_0078,va_dod_low_back_pain_2022,"[IX. Recommendations > A. Evaluation and Diagnostic Approach, VIII. Algorithm > A. Module A: Initial Evaluation of Low Back Pain, VIII. Algorithm > B. Module B: Management of Low Back Pain]"

In [188]:
for section in show_document_sections(
    "va_dod_ckd_2025"
):
    print(section)

Appendix G. Alternative Text Descriptions of Algorithms
Appendix H. Management of CKD Table
Appendix I. Monitoring of CKD Table
Appendix J. Approaches for eGFR Calculation
Appendix K. Nephrotoxic Agents and Medication Dose Adjustments in CKD > A. Background
Appendix K. Nephrotoxic Agents and Medication Dose Adjustments in CKD > B. Nephrotoxic Medications
Appendix K. Nephrotoxic Agents and Medication Dose Adjustments in CKD > C. Medication Management in CKD
Appendix L. List of Pharmacotherapies
Appendix M. Management of Hyperkalemia > A. Background
Appendix M. Management of Hyperkalemia > B. Definition
Appendix M. Management of Hyperkalemia > C. Management
Appendix M. Management of Hyperkalemia > D. Dietary Considerations
Appendix M. Management of Hyperkalemia > E. Use of Potassium Binders
Appendix N. Chronic Pain Management in CKD > A. Overview and Conceptual Approach
Appendix N. Chronic Pain Management in CKD > B. Non-Pharmacologic Pain Management in Patients with CKD
Appendix N. Chronic Pain Management in CKD > C. Pharmacologic Pain Management in Patients with CKD
Appendix O. Military Occupation Exposures and CKD
Appendix P. Special Considerations when Caring for Older Patients
Appendix P. Special Considerations when Caring for Older Patients > A. Other Considerations
Appendix Q. Gadolinium and Iodinated Contrast
Appendix R. General Medical and Lifestyle Management Recommendations to Improve Standard of Care in CKD Patients
I. Introduction
II. Background > A. Description of Chronic Kidney Disease
II. Background > B. Epidemiology and Impact in the General Population
II. Background > C. Chronic Kidney Disease in the Department of Veterans Affairs and the Department of Defense
II. Background > D. Social Determinants of Health
III. Scope of This Guideline
III. Scope of This Guideline > A. Guideline Audience
III. Scope of This Guideline > B. Guideline Population
IV. Highlighted Features of This Guideline > A. Highlights in This Guideline Update
IV. Highlighted Features of This Guideline > B. Components of This Guideline
IV. Highlighted Features of This Guideline > C. Demographic Terminology in This Guideline
IX. Recommendations
VII. Approach to Care in the Department of Veterans Affairs and the Department of Defense > A. Patient-Centered Care
VII. Approach to Care in the Department of Veterans Affairs and the Department of Defense > B. Shared Decision-Making
VII. Approach to Care in the Department of Veterans Affairs and the Department of Defense > C. Patients with Co-Occurring Conditions
VIII. Algorithm

### Проверка покрытия CKD-вопроса

Вопрос `candidate_0029` касается advanced CKD, dialysis, transplant и необходимости
дальнейшего обследования.

По названиям разделов нельзя уверенно определить, покрывает ли guideline эти вопросы.
Поэтому перед присвоением `covered` проверяем наличие соответствующей информации
непосредственно в тексте CKD records.

In [189]:
ckd_coverage_check = (
    retrieval_records_df[
        retrieval_records_df[
            "document_id"
        ].eq("va_dod_ckd_2025")
        &
        retrieval_records_df[
            "text"
        ].str.contains(
            (
                r"dialysis|"
                r"transplant|"
                r"kidney replacement|"
                r"renal replacement|"
                r"nephrolog"
            ),
            case=False,
            regex=True,
            na=False,
        )
    ][
        [
            "section_path",
            "pdf_page",
            "text",
        ]
    ]
)

pd.set_option(
    "display.max_colwidth",
    500,
)

ckd_coverage_check

,section_path,pdf_page,text
727,II. Background > A. Description of Chronic Kidney Disease,6,"Chronic kidney disease (CKD) is defined as abnormalities of kidney structure or function characterized by a glomerular filtration rate (GFR) of less than 60 mL/min/1.73m2 or a normal GFR with other markers of kidney disease such as proteinuria, hematuria, or abnormal imaging of the kidneys, present for greater than three months, with implications for health.(3) In 2002, the National Kidney Foundation (NKF) published treatment guidelines that classified five stages of CKD based on declining e..."
728,II. Background > A. Description of Chronic Kidney Disease,7,"stages of CKD and the relative risk of these complications are presented in Sidebar 9. The majority of patients with CKD are asymptomatic until CKD stage G5 when uremic symptoms develop, at which time kidney replacement therapy (KRT) may be recommended depending on patients’ co-occurring conditions and values. Interventions described in this CPG can slow the progression of CKD, improve cardiovascular outcomes, and reduce mortality. Testing within populations at high risk for CKD is suggested..."
730,II. Background > C. Chronic Kidney Disease in the Department of Veterans Affairs and the Department of Defense,7,"CKD prevalence is likely underestimated within the VA and DOD health systems. First, the presence of CKD could be an exclusion criterion for continued active service, thereby disincentivizing screening and non-disclosure, if known. Second, testing for CKD remains low, even among individuals with known risk factors such as diabetes mellitus. The National Health and Nutrition Examination Survey (NHANES) from 1999 to 2016 showed that the prevalence of CKD stages G1-G4 based on the presence of a..."
733,II. Background > D. Social Determinants of Health,9,"CKD within the VA between 2005-2016, followed for up to 10 years, found that Black Veterans were on average 7.8 years younger than White Veterans at CKD onset and had persistently >2-fold higher likelihood of requiring KRT, consistent with trends observed in the general U.S. population. A cohort study of VA patients with incident stage G3 and G4 CKD found that both Black and Hispanic patients experienced faster progression to stage G5 CKD compared with non-Hispanic White patients, despite hi..."
734,II. Background > D. Social Determinants of Health,10,"medical care – such as making informed referrals to specialists – enhances patient-centered care. This approach ensures that each patient receives appropriate treatment tailored to their specific needs and risks. Healthcare systems and primary care providers (PCPs) play a crucial role in facilitating early CKD diagnosis, managing CKD risk factors, and educating patients. Incorporating CKD detection into the workflow for preventive visits, automating lab monitoring, implementing care manageme..."
743,VII. Approach to Care in the Department of Veterans Affairs and the Department of Defense > B. Shared Decision-Making,18,"This CPG encourages providers to practice shared decision-making (SDM), a process in which providers, patients, and patient care partners (e.g., family, friends, caregivers) consider clinical evidence of benefits and risks as well as patient values and preferences to make decisions regarding the patient’s treatment.(56) Shared decision-making is emphasized in “Crossing the Quality Chasm”, an Institute of Medicine, now NAM, report in 2001 (57) and is a core component of a patient-centered, wh..."
753,VIII. Algorithm,27,"Module D. Pharmacologic Management of CKD in Patients Not on Dialysis The WG recommends stepwise addition of pharmacotherapies to slow progression of CKD and reduce MACE, noting that trials of SGLT2i, GLP-1 RA, and finerenone were each conducted on a background of ACEI/ARB therapy; however, the benefits of various combinations are unknown. * Strongest evidence for kidney protection with ACEI/ARB is in UACR>300 mg/g. ** In patients with HF, sacubitril/valsartan may be used as an alternative t..."
754,VIII. Algorithm,28,"Sidebar 6: Criteria for CKD • Markers of kidney damage (1 or more):  Albuminuria (UACR ≥30 mg/g) on at least two measurements separated by ≥3 months  Urine sediment abnormalities  Persistent hematuria  Evidence of kidney tubular disorders (e.g., renal tubular acidosis)  Abnormalities detected by histology or imaging  History of kidney transplantation AND/OR • Decreased GFR <60 mL/min/1.73 m2 (GFR categories G3a-G5) for ≥3 months Source: CKD Evaluation and Management – KDIGO Abbreviatio..."
755,VIII. Algorithm,29,"• Complications of CKD (e.g., anemia, metabolic acidosis, hyperphosphatemia, hyperparathyroidism) • Patient’s level of disease exceeds the comfort level of the primary care provider Abbreviations: CKD: chronic kidney disease; eGFR: estimated glomerular filtration rate; g: gram; hr: hour; m: meter; mg: milligram; min: minute; mL: milliliter; RAASi: renin-angiotensin-aldosterone system inhibitor; RBC: red blood cell; UACR: urine albumin-to-creatinine ratio; UPCR: urine protein-to-creatinine ra..."
758,IX. Recommendations,32,"The evidence-based clinical practice recommendations listed in the table below were developed using a systematic approach considering four domains as per the GRADE approach (see Summary of Guideline Development Methodology). These domains include confidence in the quality of the evidence, balance of desirable and undesirable outcomes (i.e., benefits and harms), patient values and preferences, and other implications (e.g., resource use, equity, acceptability). Table 4. Evidence-Based Clinical..."
759,IX. Recommendations,33,"Sub-topic Topic # Recommendation Strengtha Categoryb Weak for Not reviewed, Not changed 8. We suggest utilizing shared decision-making regarding kidney replacement therapy versus conservative management. Weak for Not reviewed, Amended 9. In patients with high co-occurring conditions/low functional status, we suggest nephrology referral with sufficient time for comprehensive preparation for conservative management or dialysis for treatment of kidney failure, depending on patient values and pr..."
760,IX. Recommendations,34,"Sub-topic Topic # Recommendation Strengtha Categoryb and continuing sodium-glucose co-transporter 2 inhibitors until start of dialysis. Strong for Reviewed, New-replaced 16. We recommend adding a glucagon-like peptide-1 receptor agonist to an angiotensin-converting enzyme inhibitor or angiotensin II receptor blocker in patients with type 2 diabetes and albuminuric chronic kidney disease to reduce the progression of chronic kidney disease, major adverse cardiovascular events, and all-cause mo..."
762,IX. Recommendations,36,"CKD were female sex, stage G3a CKD, and no medical history of diabetes or hypertension. One limitation of this study was the very low overall frequency of UACR testing (1.8%). One large cross-sectional study (62) of 199.81 million U.S. adults reported that 1.04 million adults who did not meet eGFR or albuminuria criteria for diagnosis of CKD had a high risk (≥5%) of CKD progression (probability of ≥40% decline in eGFR or kidney failure) within 3 years. Among these adults, 98% had hypertensio..."
766,IX. Recommendations,40,"Recommendation 4. We suggest the use of a validated, end-stage kidney disease risk prediction model (e.g., kidney failure risk equation [KFRE]) for the management of stage G3-G5 chronic kidney disease. (Weak for | Reviewed, Amended) Discussion Various risk prediction equations have been developed over the past decade to aid providers in caring for those with CKD. The KFRE (https://www.kidneyfailurerisk.com), developed in 2011 from the Canadian Chronic Kidney Disease cohort, uses variables th..."
767,IX. Recommendations,41,"The Work Group systematically reviewed the evidence related to this recommendation from both the 2025 and 2019 VA/DOD CKD CPG evidence bases. The Work Group specified the risk prediction models that have been validated, delineated their clinical utility, and clarified the population for whom each was studied (see Risk Equations Table below). Therefore, this recommendation is categorized as Reviewed, Amended. The Work Group’s confidence in the quality of evidence was Low. The body of evidence..."
769,IX. Recommendations,43,Consortium; CPG: clinical practice guideline; CPRS: computerized patient record system; CVD: cardiovascular disease; DM: diabetes mellitus; eGFR: estimated glomerular filtration rate; ESKD: end-stage kidney disease; HgbA1c: hemoglobin A1c; HDL: high density lipoprotein; HF: heart failure; HR: hazard ratio; HTN: hypertension; KDIGO: Kidney Disease: Improving Global Outcomes; MCVD: monogenic CVD; PCE: pooled cohort equation; PVD: peripheral vascular disease; SBP: systolic blood pressure; SDI: ...
770,IX. Recommendations,44,"Stevenson et al. (2019) (110) reviewed 43 studies in patients with CKD to evaluate the efficacy of eHealth interventions to change health behaviors (e.g., diet, medication) and improve outcomes (e.g., BP control, hospitalizations, quality of life, patient satisfaction with care). Of those 43 studies, only 2 RCTs (BRIGHT and MESMI) met inclusion criteria for the current evidence review. These studies, which assessed the use of an educational website/DVD versus usual care, revealed no differen..."
771,IX. Recommendations,45,"IDT appointments with coordinated care focused on tight control of BP, blood sugars, lipids, and albuminuria in patients with diabetes and CKD stage G3-G4 may slow progression to ESKD compared with usual care. However, the study was not blinded, only enrolled 120 subjects, and had a high attrition rate.(111) Other research, not included in the evidence base, showed that patients with late-stage CKD (eGFR <30 mL/min per 1.73m2) using interdisciplinary care were more successful in their ESKD t..."
772,IX. Recommendations,46,"resulting in partial or complete obliteration of vessel lumen, though <5% of patients were symptomatic.(116) Clinicians should also be aware that PICC lines and other vascular access devices may negatively impact future hemodialysis access by damaging central and peripheral vessels. Mature AVFs are associated with superior patency and lower complication rates compared with AVGs or dialysis catheters and are considered the gold standard for hemodialysis vascular access.(117) Since PICC lines ..."
773,IX. Recommendations,47,"As this is a Not reviewed, Amended recommendation, no new evidence was obtained. Two observational studies were identified in the 2019 VA/DOD CKD CPG SR, which both demonstrated that PICC lines were associated with an increased risk of failure to achieve a working AVF or AVG.(118,119) The Work Group rated these studies as Moderate quality evidence with limitations being their observational study designs and the potential for bias and confounding. The harms of failure to achieve adequate hemo..."
774,IX. Recommendations,48,"However, approximately half of respondents felt their choices had been limited for a variety of reasons, such as modality availability at their center, financial constraints, or the presence of medical or social contraindications for a given modality. The survey also found that patients were more satisfied when information was provided by health care professionals, though the level of satisfaction varied depending on modality (respondents were more often satisfied with information provided o..."
775,IX. Recommendations,49,"unadjusted confounders and lack of clarity on missing data. Thus, results may not be applicable across populations. In a retrospective review of 838 ESKD patients aged 65 years or older, Tam-Tham et al. demonstrated statistically significant lower mortality favoring dialysis for the first 3 years of follow-up.(126) Brown et al. found a survival benefit of approximately 13 months in a prospective cohort study (33 months for patients assigned to pre-dialysis clinic vs. 20 months for those foll..."
776,IX. Recommendations,50,"targets for dialysis adequacy and control of metabolic derangements. While this approach reflects respect for patient autonomy, the indications and infrastructure to support palliative dialysis have not been established in the U.S.(132) For example, there is currently no mechanism to separate quality and outcomes data for palliative dialysis patients in the assessment of dialysis unit quality benchmarks. Consequently, palliative dialysis is not universally offered at this time, and further s..."
777,IX. Recommendations,51,"factors, and prior experience with dialysis. Moreover, provider and caregiver beliefs and values may also impact patient decisions. Providers, including nephrologists, should thoughtfully consider the patient’s frame of mind, mood, and capability to make complex decisions (including extent of any cognitive impairment), when pursuing goals of care discussions.(122,123) Respect for patient autonomy in the decision to pursue or decline life-sustaining treatment with dialysis, the potential harm..."
778,IX. Recommendations,52,"Recommendation 11. We suggest intensive blood pressure management to reduce mortality and major adverse cardiovascular events in patients with estimated glomerular filtration rate below 60 mL/minute/1.73 m². (Weak for | Reviewed, Amended) Discussion The Work Group sought evidence to make recommendations about the impact of BP control on clinical outcomes and determine the appropriate BP target for patients with CKD. The evidence suggests that treating high BP in patients with CKD with a more..."
779,IX. Recommendations,53,"proteinuria, represented approximately half of the patients included in the SRs reviewed. The Work Group did not feel there was sufficient evidence to select a specific SBP target given the variability in enrolled populations studied, how BP measurements were conducted, and goal SBP assignment versus SBP achieved from the individual trials contained within the SRs. Providers may refer to the VA/DOD CPG for the Management of Hypertension in Primary Care (147) for further discussion of BP targ..."
780,IX. Recommendations,54,"The Work Group systematically reviewed evidence related to this recommendation.(157,163,164) Therefore, it is categorized as Reviewed, Amended. The Work Group’s confidence in the quality of the evidence was High. The benefits of using either an ACEI or ARB to slow the progression of CKD outweighed the potential harm of cough, angioedema, or hyperkalemia. ACEI and ARB should not be combined due to an increased risk of AKI (164) and hyperkalemia, and clinicians should counsel patients about th..."
781,IX. Recommendations,55,"plus amlodipine or benazepril plus hydrochlorothiazide and followed them for a mean of 36 months.(168) The primary endpoint was a composite of death from CVD, nonfatal myocardial infarction (MI), nonfatal stroke, hospitalization for angina, resuscitation after sudden cardiac arrest, and coronary revascularization. Blood pressure reduction was similar between the two groups over the course of the trial. The benazepril/amlodipine combination was superior to the benazepril/hydrochlorothiazide c..."
782,IX. Recommendations,56,"non-pharmacologic interventions and be disinclined to add to their pill burden or risk side effects. Use of single pill combinations is associated with higher medication adherence.(174) The VA and DOD have single pill combinations of ACEI+thiazide diuretic and ACEI+CCB, which may overcome patient reluctance to add another medication. Thus, the Work Group decided upon a Weak for recommendation. Recommendation 14. In patients with advanced chronic kidney disease (estimated glomerular filtratio..."
783,IX. Recommendations,57,"progression to ESKD in over 3,900 patients who experienced eGFR <30 mL/min/1.73 m2 on RAASi therapy. This study was not included in the evidence base reviewed by the Work Group due to having an excluded study design.(182) The meta-analysis of trials of ACEI or ARB in adults with CKD stage G3b-G5 by Cooper et al. (163) examined outcomes of validated markers of CKD progression, progression to ESKD, hypertension control, and major CVD events. Review of these trials showed no difference in BP co..."
784,IX. Recommendations,58,"regarding access to care were identified since RAASi are easily accessible and inexpensive, especially compared to newer agents that have shown benefit at slowing CKD progression. The Work Group acknowledged that the evidence reviewed for this guideline heavily relied on the STOP-ACEI trial and that the overall strength of evidence reviewed was Very low. However, the evidence suggested that there is no significant risk of worsening CKD progression or pushing patients with late stage G4 or G5..."
785,IX. Recommendations,59,"reduction in hospitalization for heart failure as well as all-cause mortality by 13-14%.(186,188) Outside of the evidence base, a study performed by Gregg et al. (37) showed that 37% of 96,345 Veterans prescribed SGLT2i discontinued use, though reasons for discontinuation were not cited, and SGLT2i discontinuation was associated with increased mortality and heart failure hospitalizations.(190,191) While there was low variability between RCTs included in the SRs and low risk of bias, a limita..."
790,IX. Recommendations,64,"While finerenone was generally well-tolerated by patients in the FIDELIO-DKD and FIGARO-DKD trials, the population studied was limited to those with potassium <4.8 mmol/L prior to finerenone initiation. Despite this prerequisite, hyperkalemia-related adverse events (14.0% vs. 6.9%) and hyperkalemia leading to permanent treatment discontinuation (1.7% vs. 0.6%) were more frequent with finerenone.(197) In addition, at baseline, less than 10% of patients in both trials were treated within an SG..."
791,IX. Recommendations,65,"studies contributed to the meta-analysis, depending on the outcome. The evidence for MACE and all-cause mortality was of High certainty while the evidence for cardiovascular death and MI was of Moderate certainty. Findings were consistent across subgroups, including those with and without CVD at baseline, those with and without diabetes, and patients <55 years versus >55 years old. The meta-analysis did not report outcomes stratified by baseline cholesterol levels. The authors estimated that..."
792,IX. Recommendations,66,"year cardiovascular risk using SDM. Almost all patients with CKD would fall into these categories. The KDIGO 2024 Clinical Practice Guideline for the Evaluation and Management of Chronic Kidney Disease (3) makes the following lipid management recommendations for adults with CKD not treated with chronic dialysis or kidney transplantation: For adults aged >50 years, they recommend treatment with a statin or statin/ezetimibe combination. In adults aged 18-49 years, they suggest statin treatment..."
793,IX. Recommendations,67,"Recommendation 20. In patients with autosomal dominant polycystic kidney disease, we recommend referral to a nephrology provider* for evaluation and assessment of appropriateness of treatment with tolvaptan. (Strong for | Reviewed, New-replaced) *2019 VA/DOD CKD CPG Recommendation #32 was amended based on support of nephrology subspecialty referral, Risk Evaluation and Mitigation Strategies (REMS) requirements (approval by a REMS trained nephrologist), and clinical ramifications of early ref..."
794,IX. Recommendations,68,"(9.5% in the tolvaptan group vs. 2.2% in the placebo group); however, only patients who tolerated tolvaptan during an 8-week screening phase, in which 6.8% withdrew due to inability to tolerate the drug, were randomized to the active portion of the trial. Patients in this pre-selected group receiving tolvaptan again reported higher rates of aquaretic side effects, diarrhea, and fatigue. In addition to the side effects noted above, significant concerns for the safety of tolvaptan have been id..."

In [190]:
ckd_relevant_sections = {
    "candidate_0029": [
        "IX. Recommendations",
        "VIII. Algorithm",
        "Appendix G. Alternative Text Descriptions of Algorithms",
        "Appendix I. Monitoring of CKD Table",
    ],
}

In [191]:
for candidate_id, sections in ckd_relevant_sections.items():
    covered_dev_eval_df.loc[
        covered_dev_eval_df["candidate_id"].eq(candidate_id),
        "relevant_sections",
    ] = pd.Series(
        [sections],
        index=covered_dev_eval_df.index[
            covered_dev_eval_df["candidate_id"].eq(candidate_id)
        ],
    )

In [192]:
for section in show_document_sections(
    "cdc_sti_2021"
):
    print(section)

Chlamydial Infections > Chlamydial Infection Among Adolescents and Adults
Chlamydial Infections > Chlamydial Infection Among Adolescents and Adults > Diagnostic Considerations
Chlamydial Infections > Chlamydial Infection Among Adolescents and Adults > Follow-Up
Chlamydial Infections > Chlamydial Infection Among Adolescents and Adults > Management of Sex Partners
Chlamydial Infections > Chlamydial Infection Among Adolescents and Adults > Other Management Considerations
Chlamydial Infections > Chlamydial Infection Among Adolescents and Adults > Special Considerations > HIV Infection
Chlamydial Infections > Chlamydial Infection Among Adolescents and Adults > Special Considerations > Pregnancy
Chlamydial Infections > Chlamydial Infection Among Adolescents and Adults > Treatment
Chlamydial Infections > Chlamydial Infection Among Infants and Children
Chlamydial Infections > Chlamydial Infection Among Infants and Children > Diagnostic Considerations
Chlamydial Infections > Chlamydial Infection Among Infants and Children > Follow-Up
Chlamydial Infections > Chlamydial Infection Among Infants and Children > Other Management Considerations
Chlamydial Infections > Chlamydial Infection Among Neonates
Chlamydial Infections > Chlamydial Infection Among Neonates > Infant Pneumonia Caused by C. trachomatis
Chlamydial Infections > Chlamydial Infection Among Neonates > Infant Pneumonia Caused by C. trachomatis > Diagnostic Considerations
Chlamydial Infections > Chlamydial Infection Among Neonates > Infant Pneumonia Caused by C. trachomatis > Follow-Up
Chlamydial Infections > Chlamydial Infection Among Neonates > Infant Pneumonia Caused by C. trachomatis > Management of Mothers and Their Sex Partners
Chlamydial Infections > Chlamydial Infection Among Neonates > Infant Pneumonia Caused by C. trachomatis > Treatment
Chlamydial Infections > Chlamydial Infection Among Neonates > Ophthalmia Neonatorum Caused by C. trachomatis
Chlamydial Infections > Chlamydial Infection Among Neonates > Ophthalmia Neonatorum Caused by C. trachomatis > Diagnostic Considerations
Chlamydial Infections > Chlamydial Infection Among Neonates > Ophthalmia Neonatorum Caused by C. trachomatis > Follow-Up
Chlamydial Infections > Chlamydial Infection Among Neonates > Ophthalmia Neonatorum Caused by C. trachomatis > Management of Mothers and Their Sex Partners
Chlamydial Infections > Chlamydial Infection Among Neonates > Ophthalmia Neonatorum Caused by C. trachomatis > Preventing Ophthalmia Neonatorum Caused by C. trachomatis
Chlamydial Infections > Chlamydial Infection Among Neonates > Ophthalmia Neonatorum Caused by C. trachomatis > Treatment
Clinical Prevention Guidance
Clinical Prevention Guidance > Partner Services
Clinical Prevention Guidance > Partner Services > Expedited Partner Therapy
Clinical Prevention Guidance > Primary Prevention Methods > Abstinence and Reduction of Number of Sex Partners
Clinical Prevention Guidance > Primary Prevention Methods > Cervical Diaphragms
Clinical Prevention Guidance > Primary Prevention Methods > Condoms > External Condoms
Clinical Prevention Guidance > Primary Prevention Methods > Condoms > Internal Condoms
Clinical Prevention Guidance > Primary Prevention Methods > Emergency Contraception
Clinical Prevention Guidance > Primary Prevention Methods > HIV Seroadaptive Strategies
Clinical Prevention Guidance > Primary Prevention Methods > HIV Treatment as Prevention: Antiretroviral Treatment of Persons with HIV to Prevent HIV Among Partners
Clinical Prevention Guidance > Primary Prevention Methods > Male Circumcision
Clinical Prevention Guidance > Primary Prevention Methods > Multipurpose Prevention Technologies
Clinical Prevention Guidance > Primary Prevention Methods > Nonbarrier Contraception, Female Surgical Sterilization, and Hysterectomy
Clinical Prevention Guidance > Primary Prevention Methods > Postexposure Prophylaxis for HIV and STIs
Clinical Prevention Guidance > Primary Prevention Methods > Pre-Exposure Prophylaxis for HIV
Clinical Prevention Guidance > Primary Prevention Methods > Pre-Exposure Prophylaxis for STIs
Clinical Prevention Guidance > Primary Prevention Methods > Pre-Exposure Vaccination
Clinical Prevention Guidance > Primary Prevention Methods > Topical Microbicides and Spermicides
Clinical Prevention Guidance > Reporting and Confidentiality
Clinical Prevention Guidance > Retesting After Treatment to Detect Repeat Infections
Clinical Prevention Guidance > STI and HIV Infection Prevention Counseling
Clinical Prevention Guidance > STI and HIV Infection Risk Assessment
Diseases Characterized by Genital, Anal, or Perianal Ulcers
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Chancroid
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Chancroid > Diagnostic Considerations
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Chancroid > Follow-Up
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Chancroid > Management of Sex Partners
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Chancroid > Other Management Considerations
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Chancroid > Special Considerations > Children
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Chancroid > Special Considerations > HIV Infection
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Chancroid > Special Considerations > Pregnancy
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Chancroid > Treatment
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Counseling
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Counseling > Asymptomatic HSV-2 Genital Herpes
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Counseling > HSV-1 Genital Herpes
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Counseling > Symptomatic HSV-2 Genital Herpes
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Diagnostic Considerations
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Diagnostic Considerations > Type-Specific Serologic Tests
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Diagnostic Considerations > Virologic Tests
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Genital Herpes Management
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Genital Herpes Management > Episodic Therapy for Recurrent HSV-2 Genital Herpes
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Genital Herpes Management > First Clinical Episode of Genital Herpes
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Genital Herpes Management > Recurrent HSV-1 Genital Herpes
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Genital Herpes Management > Recurrent HSV-2 Genital Herpes
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Genital Herpes Management > Severe Disease
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Genital Herpes Management > Suppressive Therapy for Recurrent HSV-2 Genital Herpes
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Genital Herpes Management > Valacyclovir 500 mg orally once a day*
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Hepatitis
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Management of Sex Partners
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Prevention
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Special Considerations > Antiviral-Resistant HSV Infection
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Special Considerations > Drug Allergy, Intolerance, or Adverse Reactions
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Special Considerations > Genital Herpes During Pregnancy
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Special Considerations > HIV Infection
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Special Considerations > Herpes Among Pregnant Women*
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Special Considerations > Neonatal Herpes
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Granuloma Inguinale (Donovanosis)
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Granuloma Inguinale (Donovanosis) > Diagnostic Considerations
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Granuloma Inguinale (Donovanosis) > Follow-Up
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Granuloma Inguinale (Donovanosis) > Management of Sex Partners
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Granuloma Inguinale (Donovanosis) > Other Management Considerations
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Granuloma Inguinale (Donovanosis) > Special Considerations > HIV Infection
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Granuloma Inguinale (Donovanosis) > Special Considerations > Pregnancy
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Granuloma Inguinale (Donovanosis) > Treatment
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Lymphogranuloma Venereum
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Lymphogranuloma Venereum > Diagnostic Considerations
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Lymphogranuloma Venereum > Follow-Up
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Lymphogranuloma Venereum > Management of Sex Partners
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Lymphogranuloma Venereum > Other Management Considerations
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Lymphogranuloma Venereum > Special Considerations > HIV Infection
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Lymphogranuloma Venereum > Special Considerations > Pregnancy
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Lymphogranuloma Venereum > Treatment
Diseases Characterized by Genital, Anal, or Perianal Ulcers > Lymphogranuloma Venereum > Treatment > Azithromycin 1 g orally once weekly for 3 weeks*
Diseases Characterized by Urethritis and Cervicitis > Cervicitis
Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Diagnostic Considerations
Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Etiology
Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Follow-Up
Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Management of Sex Partners
Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Other Management Considerations
Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Persistent or Recurrent Cervicitis
Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Special Considerations > Contraceptive Management
Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Special Considerations > HIV Infection
Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Special Considerations > Pregnancy
Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Treatment
Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Treatment > Recommended Regimen for Cervicitis*
Diseases Characterized by Urethritis and Cervicitis > Nongonococcal Urethritis
Diseases Characterized by Urethritis and Cervicitis > Nongonococcal Urethritis > Diagnostic Considerations
Diseases Characterized by Urethritis and Cervicitis > Nongonococcal Urethritis > Follow-Up
Diseases Characterized by Urethritis and Cervicitis > Nongonococcal Urethritis > Management Considerations
Diseases Characterized by Urethritis and Cervicitis > Nongonococcal Urethritis > Management of Sex Partners
Diseases Characterized by Urethritis and Cervicitis > Nongonococcal Urethritis > Persistent or Recurrent Nongonococcal Urethritis
Diseases Characterized by Urethritis and Cervicitis > Nongonococcal Urethritis > Special Considerations > HIV Infection
Diseases Characterized by Urethritis and Cervicitis > Nongonococcal Urethritis > Treatment
Diseases Characterized by Urethritis and Cervicitis > Urethritis
Diseases Characterized by Urethritis and Cervicitis > Urethritis > Diagnostic Considerations
Diseases Characterized by Urethritis and Cervicitis > Urethritis > Etiology
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Bacterial Vaginosis
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Bacterial Vaginosis > Diagnostic Considerations
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Bacterial Vaginosis > Follow-Up
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Bacterial Vaginosis > Management of Sex Partners
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Bacterial Vaginosis > Other Management Considerations
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Bacterial Vaginosis > Special Considerations > Drug Allergy, Intolerance, or Adverse Reactions
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Bacterial Vaginosis > Special Considerations > HIV Infection
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Bacterial Vaginosis > Special Considerations > Pregnancy
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Bacterial Vaginosis > Treatment
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Bacterial Vaginosis > Treatment > Clindamycin ovules 100 mg intravaginally once at bedtime for 3 days*
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Trichomoniasis
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Trichomoniasis > Diagnostic Considerations
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Trichomoniasis > Follow-Up
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Trichomoniasis > Management of Sex Partners
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Trichomoniasis > Other Management Considerations
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Trichomoniasis > Recurrent Trichomoniasis
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Trichomoniasis > Special Considerations > Drug Allergy, Intolerance, and Adverse Reactions
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Trichomoniasis > Special Considerations > HIV Infection
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Trichomoniasis > Special Considerations > Pregnancy
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Trichomoniasis > Treatment
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Vulvovaginal Candidiasis
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Vulvovaginal Candidiasis > Complicated Vulvovaginal Candidiasis > Diagnostic Considerations
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Vulvovaginal Candidiasis > Complicated Vulvovaginal Candidiasis > Management of Sex Partners
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Vulvovaginal Candidiasis > Complicated Vulvovaginal Candidiasis > Non–albicans Vulvovaginal Candidiasis
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Vulvovaginal Candidiasis > Complicated Vulvovaginal Candidiasis > Recurrent Vulvovaginal Candidiasis
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Vulvovaginal Candidiasis > Complicated Vulvovaginal Candidiasis > Severe Vulvovaginal Candidiasis
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Vulvovaginal Candidiasis > Complicated Vulvovaginal Candidiasis > Treatment
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Vulvovaginal Candidiasis > Special Considerations > Compromised Host
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Vulvovaginal Candidiasis > Special Considerations > HIV Infection
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Vulvovaginal Candidiasis > Special Considerations > Pregnancy
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Vulvovaginal Candidiasis > Uncomplicated Vulvovaginal Candidiasis > Diagnostic Considerations
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Vulvovaginal Candidiasis > Uncomplicated Vulvovaginal Candidiasis > Drug Allergy, Intolerance, and Adverse Reactions
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Vulvovaginal Candidiasis > Uncomplicated Vulvovaginal Candidiasis > Follow-Up
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Vulvovaginal Candidiasis > Uncomplicated Vulvovaginal Candidiasis > Management of Sex Partners
Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Vulvovaginal Candidiasis > Uncomplicated Vulvovaginal Candidiasis > Treatment
Ectoparasitic Infections > Pediculosis Pubis
Ectoparasitic Infections > Pediculosis Pubis > Diagnosis
Ectoparasitic Infections > Pediculosis Pubis > Follow-Up
Ectoparasitic Infections > Pediculosis Pubis > Management of Sex Partners
Ectoparasitic Infections > Pediculosis Pubis > Other Management Considerations
Ectoparasitic Infections > Pediculosis Pubis > Special Considerations > HIV Infection
Ectoparasitic Infections > Pediculosis Pubis > Special Considerations > Pregnancy
Ectoparasitic Infections > Pediculosis Pubis > Treatment
Ectoparasitic Infections > Scabies
Ectoparasitic Infections > Scabies > Crusted Scabies
Ectoparasitic Infections > Scabies > Diagnosis
Ectoparasitic Infections > Scabies > Follow-Up
Ectoparasitic Infections > Scabies > Management of Outbreaks in Communities, Nursing Homes, and Other Institutional Settings
Ectoparasitic Infections > Scabies > Management of Sex Partners and Household Contacts
Ectoparasitic Infections > Scabies > Other Management Considerations
Ectoparasitic Infections > Scabies > Special Considerations > HIV Infection
Ectoparasitic Infections > Scabies > Special Considerations > Infants, Young Children, and Pregnant or Lactating Women
Ectoparasitic Infections > Scabies > Treatment
Epididymitis
Epididymitis > Diagnostic Considerations
Epididymitis > Follow-Up
Epididymitis > Management of Sex Partners
Epididymitis > Other Management Considerations
Epididymitis > Special Considerations > Drug Allergy, Intolerance, and Adverse Reactions
Epididymitis > Special Considerations > HIV Infection
Epididymitis > Treatment
Gonococcal Infections > Gonococcal Infection Among Adolescents and Adults

### Проверка покрытия вопроса про Ureaplasma

В CDC guideline нет отдельного раздела `Ureaplasma`.

Перед включением вопроса в evaluation проверяем, обсуждается ли Ureaplasma
внутри текста других разделов, например urethritis или cervicitis.

In [193]:
ureaplasma_check = (
    retrieval_records_df[
        retrieval_records_df["document_id"].eq(
            "cdc_sti_2021"
        )
        &
        retrieval_records_df["text"].str.contains(
            r"ureaplasma",
            case=False,
            regex=True,
            na=False,
        )
    ][
        [
            "section_path",
            "pdf_page",
            "text",
        ]
    ]
)

pd.set_option(
    "display.max_colwidth",
    500,
)

ureaplasma_check

,section_path,pdf_page,text
305,Diseases Characterized by Urethritis and Cervicitis > Urethritis > Etiology,62,"Multiple organisms can cause infectious urethritis. The presence of gram-negative intracellular diplococci (GNID) or purple intracellular diplococci (MB or GV) on urethral smear is indicative of presumed gonococcal infection, which is frequently accompanied by chlamydial infection. Nongonococcal urethritis (NGU), which is diagnosed when microscopy of urethral secretions indicate inflammation without GNID or MB or GV purple intracellular diplococci, is caused by C. trachomatis in 15%–40% of c..."
320,Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Etiology,66,"C. trachomatis or N. gonorrhoeae is the most common etiology of cervicitis defined by diagnostic testing. Trichomoniasis, genital herpes (especially primary HSV-2 infection), or M. genitalium (761,765–768) also have been associated with cervicitis. However, in many cases of cervicitis, no organism is isolated, especially among women at relatively low risk for recent acquisition of these STIs (e.g., women aged >30 years) (769). Limited data indicate that BV and frequent douching might cause c..."

### Уточнение покрытия вопроса про Ureaplasma

Ureaplasma упоминается в разделах об этиологии urethritis и cervicitis.

Проверяем полный текст этих фрагментов, чтобы определить, содержит ли guideline
информацию, достаточную для ответа на основной вопрос пользователя.

In [194]:
for _, row in ureaplasma_check.iterrows():
    print("\n" + "=" * 100)
    print("SECTION:", row["section_path"])
    print("PDF PAGE:", row["pdf_page"])
    print()
    print(row["text"])

====================================================================================================
SECTION: Diseases Characterized by Urethritis and Cervicitis > Urethritis > Etiology
PDF PAGE: 62

Multiple organisms can cause infectious urethritis. The presence of gram-negative intracellular diplococci (GNID) or purple intracellular diplococci (MB or GV) on urethral smear is indicative of presumed gonococcal infection, which is frequently accompanied by chlamydial infection. Nongonococcal urethritis (NGU), which is diagnosed when microscopy of urethral secretions indicate inflammation without GNID or MB or GV purple intracellular diplococci, is caused by C. trachomatis in 15%–40% of cases; however, prevalence varies by age group, with a lower proportion of disease occurring among older men (699). Documentation of chlamydial infection as NGU etiology is essential because of the need for partner referral for evaluation and treatment to prevent complications of chlamydia, especially for female partners. Complications of C. trachomatis–associated NGU among males include epididymitis, prostatitis, and reactive arthritis. M. genitalium is associated with symptoms of urethritis and urethral inflammation and accounts for 15%–25% of NGU cases in the United States (691–693,696,697,700). Among men with symptoms of urethritis, M. genitalium was detected in 11% of those with urethritis in Australia (701), 12%–15% in the United Kingdom (702–704), 15% in South Africa (696), 19% in China (705), 21% in Korea, 22% in Japan (706), and 28.7% in the United States (range: 20.4%–38.8%) (697). Data are inconsistent regarding other Mycoplasma and Ureaplasma species as etiologic agents of urethritis (707). The majority of men with Ureaplasma infections do not have overt disease unless a high organism load is present. T. vaginalis can cause urethritis among heterosexual men; however, the prevalence varies substantially by U.S. geographic region, age, and sexual behavior and within specific populations. Studies among men with and without overt urethritis in developed countries document relatively low rates of T. vaginalis in the Netherlands (0.5%) (708), Japan (1.3%) (706,709), the United States (2.4%) (710), and the United Kingdom (3.6%) (703). Studies in other countries have documented higher rates, such as in Croatia (8.2%) (711) and Zimbabwe (8.4%) (712), particularly among symptomatic patients. Neisseria meningitidis can colonize mucosal surfaces and cause urethritis (713). Urogenital N. meningitidis rates and duration of carriage, prevalence of asymptomatic and symptomatic infection, and modes of transmission have not been systematically described; however, studies indicate that N. meningitidis can be transmitted through oral-penile contact (i.e., fellatio) (714–716). N. meningitidis has similar colony morphology appearance on culture and cannot be distinguished from N. gonorrhoeae on Gram stain. Identification of N. meningitidis as the etiologic agent with presumed gonococcal urethritis on the basis of Gram stain but negative NAAT for gonorrhea requires a confirmation by culture. Meningococcal urethritis is treated with the same antimicrobial regimens as gonococcal urethritis. Although evidence is limited regarding the risk for sexual transmission or recurrent infections with meningococcal urethritis, treatment of sex partners of patients with meningococcal urethritis with the same antimicrobial regimens as for exposure to gonococcal infection can be considered. No indication exists for treating

====================================================================================================
SECTION: Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Etiology
PDF PAGE: 66

C. trachomatis or N. gonorrhoeae is the most common etiology of cervicitis defined by diagnostic testing. Trichomoniasis, genital herpes (especially primary HSV-2 infection), or M. genitalium (761,765–768) also have been associated with cervicitis. However, in many cases of cervicitis, no organism is isolated, especially among women at relatively low risk for recent acquisition of these STIs (e.g., women aged >30 years) (769). Limited data indicate that BV and frequent douching might cause cervicitis (770–772). The majority of persistent cases of cervicitis are not caused by reinfection with C. trachomatis or N. gonorrhoeae; other factors might be involved (e.g., persistent abnormality of vaginal flora, M. genitalium, douching or exposure to other types of chemical irritants, dysplasia, or idiopathic inflammation in the zone of ectopy). Available data do not indicate an association between group B streptococcus colonization and cervicitis (773,774). No specific evidence exists for a role for Ureaplasma parvum or Ureaplasma urealyticum in cervicitis (707,761,765,775,776).

In [195]:
retrieval_eval_labeling_df.loc[
    retrieval_eval_labeling_df["candidate_id"].eq("candidate_0145"),
    "coverage",
] = "not_covered"

retrieval_eval_labeling_df.loc[
    retrieval_eval_labeling_df["candidate_id"].eq("candidate_0145"),
    "notes",
] = (
    "Ureaplasma is mentioned in CDC STI guideline, "
    "but the KB does not sufficiently cover the main questions "
    "about transmission, source of infection, HPV/BV association, "
    "or inference of infidelity."
)

In [196]:
covered_dev_eval_df = (
    retrieval_eval_labeling_df[
        retrieval_eval_labeling_df["coverage"].eq("covered")
    ]
    .reset_index(drop=True)
    .copy()
)

covered_dev_eval_df[
    [
        "candidate_id",
        "kb_topics",
        "input",
    ]
]

,candidate_id,kb_topics,input
0,candidate_0005,[major_depression],Hi my boyfriend and I have been together for over a year and just recently (about 5 months after his best friends death) he has begun to act strange. Hes temper has become a lot worse and he has a short fuse. He is only 20. He feels so much stress and pressure even when there isnt things to stress about. Hes not himself and admitted that he is feeling depressed lately. His moods switch in an instant. Is there something i can do about it? Does he need medical help for depression or manic depr...
1,candidate_0014,[low_back_pain],"Hi, I am suffering from lower back pain going to my lower right ribs. Ive undergone blood test, urinary test, whole abdominal ultrasound and even kidney xray but found nothing on it. Also lately i feel thirsty all the time. Is there any other kind of test that I need to undergo in order to determine the cause of this?."
2,candidate_0029,[ckd],"I have been told that I have stage 5 advanced chronic kidney disease, blood pressure perfect cholesterol perfect.Feel great look great, drs are surprised say that considering my blood work I shoulod be deathly sick but Im not at all. I was told that i need dialysis and transplant...shouldnt I be tested further"
3,candidate_0048,[low_back_pain],hi sir iam having a sciatica problem and lumber spine problem for this pain i had taken a electro homeopathy treatment in that doctor had given me a electric shock on my left leg main nerve for 3 times and the pain is gone for few days only after that it came again i had taken lot of pills but no cure now my doctor suggest me duzella 30 mg so how much its useful for me pls suggest me some good medicine iam fearing tht any side affects will come because my marriage is thier in a month and ia...
4,candidate_0078,[low_back_pain],"two months now into it...started off lower back pain then soreness in hip flexor both legs but more on right. now pain and ackey in both legs ham strings and quads. When driving, 10 min in, severe pain or acke from butt down ham into back of knee. I have to get out and stand up. then good for another 10 min. This is getting unbearable."
5,candidate_0097,[asthma],"ihave severe asthma and have been 5 times in the last 9 weeks and been given lots of steroids, so i am on insulin now. i am so wore ouy and can hardly get around. thw wheezing has stopped. i have high numbers of latic acid in the muscles. please tell me what to do."
6,candidate_0135,[asthma],"I experience respiratory distress symptoms (SOB, decreased O2, voice changes) when I am exposed to perfumes and a few other strong oders and flying dust/dirt. What could this be a symptoms of?I am 37 years old, weigh 145, and have no hx of asthma or any other respiratory issues."

In [197]:
retrieval_eval_labeling_df["coverage"].value_counts()

coverage
not_covered    29
covered         7
Name: count, dtype: int64

### Guideline-grounded evaluation set

Реальные вопросы из `dev` плохо совпадают со scope текущей knowledge base:
после ручной проверки осталось только 7 однозначно покрываемых вопросов.

Поэтому дополнительно создаётся контролируемый retrieval benchmark
непосредственно по содержанию clinical guidelines.

Для каждого документа формулируются естественные вопросы, на которые
есть явный ответ в knowledge base.

Вопросы:

- не копируют формулировки заголовков дословно;
- создаются до запуска dense retrieval;
- имеют заранее определённые релевантные разделы;
- распределены по всем документам knowledge base.

Результаты на real-dev и guideline-grounded вопросах будут оцениваться отдельно.

In [198]:
guideline_eval_rows = []

In [199]:
for section in show_document_sections(
    "who_hypertension_2021"
):
    print(section)

1 Introduction
3 Recommendations > 3.1 Blood pressure threshold for initiation of pharmacological treatment
3 Recommendations > 3.2 Laboratory testing before and during pharmacological treatment
3 Recommendations > 3.3 Cardiovascular disease risk assessment as guide to initiation of
3 Recommendations > 3.4 Drug classes to be used as first-line agents
3 Recommendations > 3.5 Combination therapy
3 Recommendations > 3.6 Target blood pressure
3 Recommendations > 3.7 Frequency of re-assessment
3 Recommendations > 3.8 Administration of treatment by nonphysician professionals
4 Special settings > 4.1 Hypertension in disaster, humanitarian and emergency settings
4 Special settings > 4.2 COVID-19 and hypertension
4 Special settings > 4.3 Pregnancy and hypertension
6 Implementation tools > 6.1 Guideline recommendations
6 Implementation tools > 6.2 Drug- and dose-specific protocols

In [200]:
guideline_eval_rows.extend(
    [
        {
            "eval_id": "who_01",
            "question_source": "guideline",
            "query": (
                "At what blood pressure level should pharmacological "
                "treatment for hypertension be started?"
            ),
            "relevant_document_id": "who_hypertension_2021",
            "relevant_sections": [
                (
                    "3 Recommendations > "
                    "3.1 Blood pressure threshold for initiation "
                    "of pharmacological treatment"
                )
            ],
        },
        {
            "eval_id": "who_02",
            "question_source": "guideline",
            "query": (
                "What laboratory tests should be considered before "
                "starting antihypertensive medication and during treatment?"
            ),
            "relevant_document_id": "who_hypertension_2021",
            "relevant_sections": [
                (
                    "3 Recommendations > "
                    "3.2 Laboratory testing before and during "
                    "pharmacological treatment"
                )
            ],
        },
        {
            "eval_id": "who_03",
            "question_source": "guideline",
            "query": (
                "Which classes of medication are recommended as "
                "first-line treatment for hypertension?"
            ),
            "relevant_document_id": "who_hypertension_2021",
            "relevant_sections": [
                (
                    "3 Recommendations > "
                    "3.4 Drug classes to be used as first-line agents"
                )
            ],
        },
        {
            "eval_id": "who_04",
            "question_source": "guideline",
            "query": (
                "When should combination drug therapy be used "
                "for treating hypertension?"
            ),
            "relevant_document_id": "who_hypertension_2021",
            "relevant_sections": [
                "3 Recommendations > 3.5 Combination therapy"
            ],
        },
        {
            "eval_id": "who_05",
            "question_source": "guideline",
            "query": (
                "What blood pressure target should treatment aim for "
                "in adults receiving therapy for hypertension?"
            ),
            "relevant_document_id": "who_hypertension_2021",
            "relevant_sections": [
                "3 Recommendations > 3.6 Target blood pressure"
            ],
        },
    ]
)

In [201]:
pd.DataFrame(guideline_eval_rows)[
    [
        "eval_id",
        "query",
        "relevant_document_id",
        "relevant_sections",
    ]
]

,eval_id,query,relevant_document_id,relevant_sections
0,who_01,At what blood pressure level should pharmacological treatment for hypertension be started?,who_hypertension_2021,[3 Recommendations > 3.1 Blood pressure threshold for initiation of pharmacological treatment]
1,who_02,What laboratory tests should be considered before starting antihypertensive medication and during treatment?,who_hypertension_2021,[3 Recommendations > 3.2 Laboratory testing before and during pharmacological treatment]
2,who_03,Which classes of medication are recommended as first-line treatment for hypertension?,who_hypertension_2021,[3 Recommendations > 3.4 Drug classes to be used as first-line agents]
3,who_04,When should combination drug therapy be used for treating hypertension?,who_hypertension_2021,[3 Recommendations > 3.5 Combination therapy]
4,who_05,What blood pressure target should treatment aim for in adults receiving therapy for hypertension?,who_hypertension_2021,[3 Recommendations > 3.6 Target blood pressure]

In [202]:
for section in show_document_sections(
    "va_dod_type2_diabetes_2023"
):
    print(section)

Appendix B: Glycemic Control Targets and Monitoring
Appendix C: Pharmacotherapy
Appendix I: Alternative Text Descriptions of Algorithm
I. Introduction
I. Introduction ........................................................................................................... 5
II. Background > A. Description of Type 2 Diabetes Mellitus
II. Background > B. Epidemiology and Impact on the General Population
III. Scope of This Guideline
III. Scope of This Guideline > A. Guideline Audience
III. Scope of This Guideline > B. Guideline Population
IV. Highlighted Features of this Guideline > A. Highlights in this Guideline Update
IV. Highlighted Features of this Guideline > B. Components of the Guideline
IV. Highlighted Features of this Guideline > C. Racial and Ethnic Demographic Terminology in This Guideline
IX. Recommendations
IX. Recommendations > A. Prediabetes
IX. Recommendations > B. Telehealth
IX. Recommendations > C. Diabetes Mellitus
IX. Recommendations > D. Non-Pharmacotherapy
IX. Recommendations > E. Pharmacotherapy
VII. Approach to Care in the Department of Veterans Affairs and the Department of Defense > A. Patient-Centered Care
VII. Approach to Care in the Department of Veterans Affairs and the Department of Defense > B. Shared Decision Making
VII. Approach to Care in the Department of Veterans Affairs and the Department of Defense > C. Patients with Co-occurring Conditions
VIII. Algorithm
VIII. Algorithm > A. Module A: T2DM Management
VIII. Algorithm > B. Module B: Self-Management Education and Support

In [203]:
guideline_eval_rows.extend(
    [
        {
            "eval_id": "t2d_01",
            "question_source": "guideline",
            "query": (
                "How should glycemic control be monitored in adults "
                "with type 2 diabetes?"
            ),
            "relevant_document_id": "va_dod_type2_diabetes_2023",
            "relevant_sections": [
                "Appendix B: Glycemic Control Targets and Monitoring",
            ],
        },
        {
            "eval_id": "t2d_02",
            "question_source": "guideline",
            "query": (
                "What lifestyle and other non-drug interventions are "
                "recommended for adults with type 2 diabetes?"
            ),
            "relevant_document_id": "va_dod_type2_diabetes_2023",
            "relevant_sections": [
                "IX. Recommendations > D. Non-Pharmacotherapy",
            ],
        },
        {
            "eval_id": "t2d_03",
            "question_source": "guideline",
            "query": (
                "What should be considered when choosing medications "
                "for treatment of type 2 diabetes?"
            ),
            "relevant_document_id": "va_dod_type2_diabetes_2023",
            "relevant_sections": [
                "IX. Recommendations > E. Pharmacotherapy",
                "Appendix C: Pharmacotherapy",
            ],
        },
        {
            "eval_id": "t2d_04",
            "question_source": "guideline",
            "query": (
                "What management strategies are recommended for adults "
                "with prediabetes to reduce progression to type 2 diabetes?"
            ),
            "relevant_document_id": "va_dod_type2_diabetes_2023",
            "relevant_sections": [
                "IX. Recommendations > A. Prediabetes",
            ],
        },
        {
            "eval_id": "t2d_05",
            "question_source": "guideline",
            "query": (
                "What education and support should patients receive "
                "to help them manage type 2 diabetes themselves?"
            ),
            "relevant_document_id": "va_dod_type2_diabetes_2023",
            "relevant_sections": [
                "VIII. Algorithm > B. Module B: Self-Management Education and Support",
            ],
        },
    ]
)

In [204]:
guideline_eval_df = pd.DataFrame(
    guideline_eval_rows
)

print(
    "Guideline questions:",
    len(guideline_eval_df),
)

guideline_eval_df[
    [
        "eval_id",
        "query",
        "relevant_document_id",
        "relevant_sections",
    ]
]

Guideline questions: 10

,eval_id,query,relevant_document_id,relevant_sections
0,who_01,At what blood pressure level should pharmacological treatment for hypertension be started?,who_hypertension_2021,[3 Recommendations > 3.1 Blood pressure threshold for initiation of pharmacological treatment]
1,who_02,What laboratory tests should be considered before starting antihypertensive medication and during treatment?,who_hypertension_2021,[3 Recommendations > 3.2 Laboratory testing before and during pharmacological treatment]
2,who_03,Which classes of medication are recommended as first-line treatment for hypertension?,who_hypertension_2021,[3 Recommendations > 3.4 Drug classes to be used as first-line agents]
3,who_04,When should combination drug therapy be used for treating hypertension?,who_hypertension_2021,[3 Recommendations > 3.5 Combination therapy]
4,who_05,What blood pressure target should treatment aim for in adults receiving therapy for hypertension?,who_hypertension_2021,[3 Recommendations > 3.6 Target blood pressure]
5,t2d_01,How should glycemic control be monitored in adults with type 2 diabetes?,va_dod_type2_diabetes_2023,[Appendix B: Glycemic Control Targets and Monitoring]
6,t2d_02,What lifestyle and other non-drug interventions are recommended for adults with type 2 diabetes?,va_dod_type2_diabetes_2023,[IX. Recommendations > D. Non-Pharmacotherapy]
7,t2d_03,What should be considered when choosing medications for treatment of type 2 diabetes?,va_dod_type2_diabetes_2023,"[IX. Recommendations > E. Pharmacotherapy, Appendix C: Pharmacotherapy]"
8,t2d_04,What management strategies are recommended for adults with prediabetes to reduce progression to type 2 diabetes?,va_dod_type2_diabetes_2023,[IX. Recommendations > A. Prediabetes]
9,t2d_05,What education and support should patients receive to help them manage type 2 diabetes themselves?,va_dod_type2_diabetes_2023,[VIII. Algorithm > B. Module B: Self-Management Education and Support]

In [205]:
guideline_eval_rows.extend(
    [
        {
            "eval_id": "ckd_01",
            "question_source": "guideline",
            "query": (
                "How should chronic kidney disease be evaluated, "
                "staged, and monitored over time?"
            ),
            "relevant_document_id": "va_dod_ckd_2025",
            "relevant_sections": [
                "VIII. Algorithm",
                "Appendix G. Alternative Text Descriptions of Algorithms",
                "Appendix I. Monitoring of CKD Table",
            ],
        },
        {
            "eval_id": "ckd_02",
            "question_source": "guideline",
            "query": (
                "When should a patient with chronic kidney disease "
                "be referred to a nephrology specialist?"
            ),
            "relevant_document_id": "va_dod_ckd_2025",
            "relevant_sections": [
                "IX. Recommendations",
                "Appendix G. Alternative Text Descriptions of Algorithms",
            ],
        },
        {
            "eval_id": "ckd_03",
            "question_source": "guideline",
            "query": (
                "How should the decision between dialysis and "
                "conservative management be made in advanced CKD?"
            ),
            "relevant_document_id": "va_dod_ckd_2025",
            "relevant_sections": [
                "IX. Recommendations",
            ],
        },
        {
            "eval_id": "ckd_04",
            "question_source": "guideline",
            "query": (
                "How should hyperkalemia be managed in a patient "
                "with chronic kidney disease?"
            ),
            "relevant_document_id": "va_dod_ckd_2025",
            "relevant_sections": [
                "Appendix M. Management of Hyperkalemia > C. Management",
                (
                    "Appendix M. Management of Hyperkalemia "
                    "> D. Dietary Considerations"
                ),
                (
                    "Appendix M. Management of Hyperkalemia "
                    "> E. Use of Potassium Binders"
                ),
            ],
        },
        {
            "eval_id": "ckd_05",
            "question_source": "guideline",
            "query": (
                "What medication-related precautions should be considered "
                "in patients with chronic kidney disease?"
            ),
            "relevant_document_id": "va_dod_ckd_2025",
            "relevant_sections": [
                (
                    "Appendix K. Nephrotoxic Agents and Medication "
                    "Dose Adjustments in CKD > B. Nephrotoxic Medications"
                ),
                (
                    "Appendix K. Nephrotoxic Agents and Medication "
                    "Dose Adjustments in CKD > C. Medication Management in CKD"
                ),
            ],
        },
    ]
)

In [206]:
guideline_eval_df = pd.DataFrame(
    guideline_eval_rows
)

print(
    "Guideline questions:",
    len(guideline_eval_df),
)

guideline_eval_df.tail(5)[
    [
        "eval_id",
        "query",
        "relevant_document_id",
        "relevant_sections",
    ]
]

Guideline questions: 15

,eval_id,query,relevant_document_id,relevant_sections
10,ckd_01,"How should chronic kidney disease be evaluated, staged, and monitored over time?",va_dod_ckd_2025,"[VIII. Algorithm, Appendix G. Alternative Text Descriptions of Algorithms, Appendix I. Monitoring of CKD Table]"
11,ckd_02,When should a patient with chronic kidney disease be referred to a nephrology specialist?,va_dod_ckd_2025,"[IX. Recommendations, Appendix G. Alternative Text Descriptions of Algorithms]"
12,ckd_03,How should the decision between dialysis and conservative management be made in advanced CKD?,va_dod_ckd_2025,[IX. Recommendations]
13,ckd_04,How should hyperkalemia be managed in a patient with chronic kidney disease?,va_dod_ckd_2025,"[Appendix M. Management of Hyperkalemia > C. Management, Appendix M. Management of Hyperkalemia > D. Dietary Considerations, Appendix M. Management of Hyperkalemia > E. Use of Potassium Binders]"
14,ckd_05,What medication-related precautions should be considered in patients with chronic kidney disease?,va_dod_ckd_2025,"[Appendix K. Nephrotoxic Agents and Medication Dose Adjustments in CKD > B. Nephrotoxic Medications, Appendix K. Nephrotoxic Agents and Medication Dose Adjustments in CKD > C. Medication Management in CKD]"

In [207]:
guideline_eval_rows.extend(
    [
        {
            "eval_id": "asthma_01",
            "question_source": "guideline",
            "query": (
                "How should asthma be diagnosed and assessed "
                "in a patient with respiratory symptoms?"
            ),
            "relevant_document_id": "va_dod_asthma_2025",
            "relevant_sections": [
                "IX. Recommendations > A. Diagnosis and Assessment",
                (
                    "Appendix K: Alternative Text Descriptions of Algorithms "
                    "> A. Module A: Assessment and Diagnosis of Asthma"
                ),
            ],
        },
        {
            "eval_id": "asthma_02",
            "question_source": "guideline",
            "query": (
                "How can the level of asthma control be assessed "
                "in a patient who already has asthma?"
            ),
            "relevant_document_id": "va_dod_asthma_2025",
            "relevant_sections": [
                (
                    "Appendix C: Assessments of Asthma Severity and Control "
                    "> B. Assessment of Asthma Control"
                ),
                "II. Background > B. Classification of Asthma Severity and Control",
            ],
        },
        {
            "eval_id": "asthma_03",
            "question_source": "guideline",
            "query": (
                "When should a patient with asthma be referred "
                "to a specialist?"
            ),
            "relevant_document_id": "va_dod_asthma_2025",
            "relevant_sections": [
                (
                    "Appendix C: Assessments of Asthma Severity and Control "
                    "> C. Indications for Specialist Referral"
                ),
            ],
        },
        {
            "eval_id": "asthma_04",
            "question_source": "guideline",
            "query": (
                "What treatment and management approaches are recommended "
                "for adults with asthma?"
            ),
            "relevant_document_id": "va_dod_asthma_2025",
            "relevant_sections": [
                "IX. Recommendations > B. Treatment and Management",
                (
                    "Appendix K: Alternative Text Descriptions of Algorithms "
                    "> B. Module B: Initiation of Therapy"
                ),
            ],
        },
        {
            "eval_id": "asthma_05",
            "question_source": "guideline",
            "query": (
                "What alternative diagnoses should be considered "
                "when symptoms resemble asthma?"
            ),
            "relevant_document_id": "va_dod_asthma_2025",
            "relevant_sections": [
                (
                    "Appendix C: Assessments of Asthma Severity and Control "
                    "> D. Identifying Alternative Diagnoses"
                ),
                (
                    "Appendix D: Details of a Comprehensive History "
                    "and Physical Exam > A. Details of a Comprehensive History"
                ),
            ],
        },
    ]
)

In [208]:
guideline_eval_df = pd.DataFrame(
    guideline_eval_rows
)

print(
    "Guideline questions:",
    len(guideline_eval_df),
)

guideline_eval_df.tail(5)[
    [
        "eval_id",
        "query",
        "relevant_document_id",
        "relevant_sections",
    ]
]

Guideline questions: 20

,eval_id,query,relevant_document_id,relevant_sections
15,asthma_01,How should asthma be diagnosed and assessed in a patient with respiratory symptoms?,va_dod_asthma_2025,"[IX. Recommendations > A. Diagnosis and Assessment, Appendix K: Alternative Text Descriptions of Algorithms > A. Module A: Assessment and Diagnosis of Asthma]"
16,asthma_02,How can the level of asthma control be assessed in a patient who already has asthma?,va_dod_asthma_2025,"[Appendix C: Assessments of Asthma Severity and Control > B. Assessment of Asthma Control, II. Background > B. Classification of Asthma Severity and Control]"
17,asthma_03,When should a patient with asthma be referred to a specialist?,va_dod_asthma_2025,[Appendix C: Assessments of Asthma Severity and Control > C. Indications for Specialist Referral]
18,asthma_04,What treatment and management approaches are recommended for adults with asthma?,va_dod_asthma_2025,"[IX. Recommendations > B. Treatment and Management, Appendix K: Alternative Text Descriptions of Algorithms > B. Module B: Initiation of Therapy]"
19,asthma_05,What alternative diagnoses should be considered when symptoms resemble asthma?,va_dod_asthma_2025,"[Appendix C: Assessments of Asthma Severity and Control > D. Identifying Alternative Diagnoses, Appendix D: Details of a Comprehensive History and Physical Exam > A. Details of a Comprehensive History]"

In [209]:
guideline_eval_rows.extend(
    [
        {
            "eval_id": "lbp_01",
            "question_source": "guideline",
            "query": (
                "How should a patient with low back pain be evaluated "
                "to determine whether further diagnostic testing is needed?"
            ),
            "relevant_document_id": "va_dod_low_back_pain_2022",
            "relevant_sections": [
                "IX. Recommendations > A. Evaluation and Diagnostic Approach",
                "VIII. Algorithm > A. Module A: Initial Evaluation of Low Back Pain",
                (
                    "Appendix I: Alternative Text Descriptions of Algorithm "
                    "> A. Module A: Initial Evaluation of Low Back Pain"
                ),
            ],
        },
        {
            "eval_id": "lbp_02",
            "question_source": "guideline",
            "query": (
                "What self-care and education should be recommended "
                "to patients with low back pain?"
            ),
            "relevant_document_id": "va_dod_low_back_pain_2022",
            "relevant_sections": [
                "IX. Recommendations > B. Patient Education and Self-care",
            ],
        },
        {
            "eval_id": "lbp_03",
            "question_source": "guideline",
            "query": (
                "Which non-drug and non-invasive treatments are recommended "
                "for managing low back pain?"
            ),
            "relevant_document_id": "va_dod_low_back_pain_2022",
            "relevant_sections": [
                (
                    "IX. Recommendations > C. "
                    "Non-pharmacologic and Non-invasive Therapy"
                ),
                "VIII. Algorithm > B. Module B: Management of Low Back Pain",
            ],
        },
        {
            "eval_id": "lbp_04",
            "question_source": "guideline",
            "query": (
                "What medications can be considered for the treatment "
                "of low back pain?"
            ),
            "relevant_document_id": "va_dod_low_back_pain_2022",
            "relevant_sections": [
                "IX. Recommendations > D. Pharmacotherapy",
                "**Appendix E: Dosing for Select Pharmacologic Agentsa,b**",
            ],
        },
        {
            "eval_id": "lbp_05",
            "question_source": "guideline",
            "query": (
                "What non-surgical invasive treatments may be considered "
                "for patients with persistent low back pain?"
            ),
            "relevant_document_id": "va_dod_low_back_pain_2022",
            "relevant_sections": [
                "IX. Recommendations > F. Non-surgical Invasive Therapy",
            ],
        },
    ]
)

In [210]:
guideline_eval_df = pd.DataFrame(
    guideline_eval_rows
)

print(
    "Guideline questions:",
    len(guideline_eval_df),
)

guideline_eval_df.tail(5)[
    [
        "eval_id",
        "query",
        "relevant_document_id",
        "relevant_sections",
    ]
]

Guideline questions: 25

,eval_id,query,relevant_document_id,relevant_sections
20,lbp_01,How should a patient with low back pain be evaluated to determine whether further diagnostic testing is needed?,va_dod_low_back_pain_2022,"[IX. Recommendations > A. Evaluation and Diagnostic Approach, VIII. Algorithm > A. Module A: Initial Evaluation of Low Back Pain, Appendix I: Alternative Text Descriptions of Algorithm > A. Module A: Initial Evaluation of Low Back Pain]"
21,lbp_02,What self-care and education should be recommended to patients with low back pain?,va_dod_low_back_pain_2022,[IX. Recommendations > B. Patient Education and Self-care]
22,lbp_03,Which non-drug and non-invasive treatments are recommended for managing low back pain?,va_dod_low_back_pain_2022,"[IX. Recommendations > C. Non-pharmacologic and Non-invasive Therapy, VIII. Algorithm > B. Module B: Management of Low Back Pain]"
23,lbp_04,What medications can be considered for the treatment of low back pain?,va_dod_low_back_pain_2022,"[IX. Recommendations > D. Pharmacotherapy, **Appendix E: Dosing for Select Pharmacologic Agentsa,b**]"
24,lbp_05,What non-surgical invasive treatments may be considered for patients with persistent low back pain?,va_dod_low_back_pain_2022,[IX. Recommendations > F. Non-surgical Invasive Therapy]

In [211]:
guideline_eval_rows.extend(
    [
        {
            "eval_id": "mdd_01",
            "question_source": "guideline",
            "query": (
                "How should a patient be initially assessed "
                "when major depressive disorder is suspected?"
            ),
            "relevant_document_id": "va_dod_major_depression_2022",
            "relevant_sections": [
                "VIII. Algorithm > A. Module A: Initial Assessment and Treatment",
                "IX. Recommendations > A. Screening",
            ],
        },
        {
            "eval_id": "mdd_02",
            "question_source": "guideline",
            "query": (
                "How should treatment outcomes be monitored "
                "in a patient being treated for major depression?"
            ),
            "relevant_document_id": "va_dod_major_depression_2022",
            "relevant_sections": [
                "IX. Recommendations > B. Monitoring Outcomes",
                (
                    "Appendix I: Quick Guide to the Patient Health Questionnaire "
                    "in Clinical Practice > C. Using the PHQ-9 "
                    "in Measurement-Based Care"
                ),
            ],
        },
        {
            "eval_id": "mdd_03",
            "question_source": "guideline",
            "query": (
                "What treatments are recommended for uncomplicated "
                "major depressive disorder?"
            ),
            "relevant_document_id": "va_dod_major_depression_2022",
            "relevant_sections": [
                "IX. Recommendations > D. Treatment of Uncomplicated MDD",
            ],
        },
        {
            "eval_id": "mdd_04",
            "question_source": "guideline",
            "query": (
                "What treatment options should be considered when depression "
                "is severe or has not responded adequately to initial treatment?"
            ),
            "relevant_document_id": "va_dod_major_depression_2022",
            "relevant_sections": [
                (
                    "IX. Recommendations > E. Treatment of MDD that is Severe "
                    "or has a Partial or Limited Response to Initial Treatment"
                ),
                "VIII. Algorithm > B. Module B: Advanced Care Management",
            ],
        },
        {
            "eval_id": "mdd_05",
            "question_source": "guideline",
            "query": (
                "What non-medication self-help or complementary approaches "
                "may be considered for major depression?"
            ),
            "relevant_document_id": "va_dod_major_depression_2022",
            "relevant_sections": [
                (
                    "IX. Recommendations > H. Self-help, "
                    "Complementary, and Alternative Treatments"
                ),
            ],
        },
    ]
)

In [212]:
guideline_eval_df = pd.DataFrame(
    guideline_eval_rows
)

print(
    "Guideline questions:",
    len(guideline_eval_df),
)

guideline_eval_df.tail(5)[
    [
        "eval_id",
        "query",
        "relevant_document_id",
        "relevant_sections",
    ]
]

Guideline questions: 30

,eval_id,query,relevant_document_id,relevant_sections
25,mdd_01,How should a patient be initially assessed when major depressive disorder is suspected?,va_dod_major_depression_2022,"[VIII. Algorithm > A. Module A: Initial Assessment and Treatment, IX. Recommendations > A. Screening]"
26,mdd_02,How should treatment outcomes be monitored in a patient being treated for major depression?,va_dod_major_depression_2022,"[IX. Recommendations > B. Monitoring Outcomes, Appendix I: Quick Guide to the Patient Health Questionnaire in Clinical Practice > C. Using the PHQ-9 in Measurement-Based Care]"
27,mdd_03,What treatments are recommended for uncomplicated major depressive disorder?,va_dod_major_depression_2022,[IX. Recommendations > D. Treatment of Uncomplicated MDD]
28,mdd_04,What treatment options should be considered when depression is severe or has not responded adequately to initial treatment?,va_dod_major_depression_2022,"[IX. Recommendations > E. Treatment of MDD that is Severe or has a Partial or Limited Response to Initial Treatment, VIII. Algorithm > B. Module B: Advanced Care Management]"
29,mdd_05,What non-medication self-help or complementary approaches may be considered for major depression?,va_dod_major_depression_2022,"[IX. Recommendations > H. Self-help, Complementary, and Alternative Treatments]"

In [213]:
for section in show_document_sections(
    "va_dod_pregnancy_2023"
):
    print(section)

I. Introduction
I. Introduction ........................................................................................................... 6 II. Background ........................................................................................................... 6
II. Background > A. Description of Pregnancy
II. Background > B. Current Trends in Pregnancy Epidemiology in the United States General Population
II. Background > C. Pregnancy in the Department of Defense and the Department of Veterans Affairs Populations
III. Scope of This Guideline
III. Scope of This Guideline > A. Guideline Audience
III. Scope of This Guideline > B. Guideline Population
IV. Highlighted Features of This Guideline > A. Highlights in This Guideline
IV. Highlighted Features of This Guideline > B. Components of This Guideline
IV. Highlighted Features of This Guideline > C. Racial and Ethnic Demographic Terminology in This Guideline
IV. Highlighted Features of This Guideline > D. Sex Terminology in This Guideline
IV. Highlighted Features of This Guideline > E. Topics Considered outside the Scope of This Guideline
IV. Highlighted Features of This Guideline > F. Guideline Development Team
IX. Algorithm
IX. Algorithm > A. Algorithm Key
IX. Algorithm > B. Interventions by Weeks’ Gestation
VII. Approach to Care in the Department of Veterans Affairs and the Department of Defense > A. Patient-Centered Care
VII. Approach to Care in the Department of Veterans Affairs and the Department of Defense > B. Shared Decision Making
VII. Approach to Care in the Department of Veterans Affairs and the Department of Defense > C. Patients with Co-occurring Conditions
VIII. Recommendations
VIII. Recommendations > A. Routine Care
VIII. Recommendations > B. Complicated Obstetrics
VIII. Recommendations > C. Mental Health
X. Routine Pregnancy Care
X. Routine Pregnancy Care .................................................................................... 78
X. Routine Pregnancy Care > A. Initial Prenatal Visit
X. Routine Pregnancy Care > B. Subsequent Prenatal Visits
X. Routine Pregnancy Care > C. Postpartum
X. Routine Pregnancy Care > D. Education
XI. Referral Indications > A. Advanced Prenatal Care Provider
XI. Referral Indications > B. Rehabilitation Care Provider
XI. Referral Indications > C. Registered Dietitian
XII. Emerging Topics > A. Reproductive Health and Epidemics
XII. Emerging Topics > B. Health Care Disparities
XII. Emerging Topics > C. Telemedicine
XII. Emerging Topics > D. Trans-Identifying and Nonbinary Persons’ Experience of Pregnancy

In [214]:
guideline_eval_rows.extend(
    [
        {
            "eval_id": "pregnancy_01",
            "question_source": "guideline",
            "query": (
                "What should be assessed and discussed during "
                "the initial prenatal visit?"
            ),
            "relevant_document_id": "va_dod_pregnancy_2023",
            "relevant_sections": [
                "X. Routine Pregnancy Care > A. Initial Prenatal Visit",
            ],
        },
        {
            "eval_id": "pregnancy_02",
            "question_source": "guideline",
            "query": (
                "What care and monitoring should be provided "
                "during follow-up prenatal visits?"
            ),
            "relevant_document_id": "va_dod_pregnancy_2023",
            "relevant_sections": [
                "X. Routine Pregnancy Care > B. Subsequent Prenatal Visits",
            ],
        },
        {
            "eval_id": "pregnancy_03",
            "question_source": "guideline",
            "query": (
                "What care should be provided to a patient "
                "during the postpartum period?"
            ),
            "relevant_document_id": "va_dod_pregnancy_2023",
            "relevant_sections": [
                "X. Routine Pregnancy Care > C. Postpartum",
            ],
        },
        {
            "eval_id": "pregnancy_04",
            "question_source": "guideline",
            "query": (
                "What education should patients receive "
                "as part of routine pregnancy care?"
            ),
            "relevant_document_id": "va_dod_pregnancy_2023",
            "relevant_sections": [
                "X. Routine Pregnancy Care > D. Education",
            ],
        },
        {
            "eval_id": "pregnancy_05",
            "question_source": "guideline",
            "query": (
                "When should a pregnant patient be referred "
                "to an advanced prenatal care provider?"
            ),
            "relevant_document_id": "va_dod_pregnancy_2023",
            "relevant_sections": [
                "XI. Referral Indications > A. Advanced Prenatal Care Provider",
                "VIII. Recommendations > B. Complicated Obstetrics",
            ],
        },
    ]
)

In [215]:
guideline_eval_df = pd.DataFrame(
    guideline_eval_rows
)

print(
    "Guideline questions:",
    len(guideline_eval_df),
)

guideline_eval_df.tail(5)[
    [
        "eval_id",
        "query",
        "relevant_document_id",
        "relevant_sections",
    ]
]

Guideline questions: 35

,eval_id,query,relevant_document_id,relevant_sections
30,pregnancy_01,What should be assessed and discussed during the initial prenatal visit?,va_dod_pregnancy_2023,[X. Routine Pregnancy Care > A. Initial Prenatal Visit]
31,pregnancy_02,What care and monitoring should be provided during follow-up prenatal visits?,va_dod_pregnancy_2023,[X. Routine Pregnancy Care > B. Subsequent Prenatal Visits]
32,pregnancy_03,What care should be provided to a patient during the postpartum period?,va_dod_pregnancy_2023,[X. Routine Pregnancy Care > C. Postpartum]
33,pregnancy_04,What education should patients receive as part of routine pregnancy care?,va_dod_pregnancy_2023,[X. Routine Pregnancy Care > D. Education]
34,pregnancy_05,When should a pregnant patient be referred to an advanced prenatal care provider?,va_dod_pregnancy_2023,"[XI. Referral Indications > A. Advanced Prenatal Care Provider, VIII. Recommendations > B. Complicated Obstetrics]"

In [216]:
guideline_eval_rows.extend(
    [
        {
            "eval_id": "sti_01",
            "question_source": "guideline",
            "query": (
                "What treatment is recommended for chlamydial infection "
                "in adolescents and adults?"
            ),
            "relevant_document_id": "cdc_sti_2021",
            "relevant_sections": [
                (
                    "Chlamydial Infections > "
                    "Chlamydial Infection Among Adolescents and Adults > Treatment"
                ),
            ],
        },
        {
            "eval_id": "sti_02",
            "question_source": "guideline",
            "query": (
                "How should a first clinical episode of genital herpes "
                "be treated?"
            ),
            "relevant_document_id": "cdc_sti_2021",
            "relevant_sections": [
                (
                    "Diseases Characterized by Genital, Anal, or Perianal Ulcers "
                    "> Genital Herpes > Genital Herpes Management "
                    "> First Clinical Episode of Genital Herpes"
                ),
            ],
        },
        {
            "eval_id": "sti_03",
            "question_source": "guideline",
            "query": (
                "How should cervicitis be evaluated to determine "
                "the likely infectious cause?"
            ),
            "relevant_document_id": "cdc_sti_2021",
            "relevant_sections": [
                (
                    "Diseases Characterized by Urethritis and Cervicitis "
                    "> Cervicitis > Diagnostic Considerations"
                ),
                (
                    "Diseases Characterized by Urethritis and Cervicitis "
                    "> Cervicitis > Etiology"
                ),
            ],
        },
        {
            "eval_id": "sti_04",
            "question_source": "guideline",
            "query": (
                "What tests are used to diagnose syphilis?"
            ),
            "relevant_document_id": "cdc_sti_2021",
            "relevant_sections": [
                "Syphilis > Diagnostic Considerations",
                (
                    "Syphilis > Diagnostic Considerations "
                    "> Nontreponemal Tests and Traditional Algorithm"
                ),
                (
                    "Syphilis > Diagnostic Considerations "
                    "> Treponemal Tests and Reverse Sequence Algorithm"
                ),
            ],
        },
        {
            "eval_id": "sti_05",
            "question_source": "guideline",
            "query": (
                "What treatments are recommended for bacterial vaginosis?"
            ),
            "relevant_document_id": "cdc_sti_2021",
            "relevant_sections": [
                (
                    "Diseases Characterized by Vulvovaginal Itching, Burning, "
                    "Irritation, Odor, or Discharge > Bacterial Vaginosis > Treatment"
                ),
            ],
        },
    ]
)

In [217]:
guideline_eval_df = pd.DataFrame(
    guideline_eval_rows
)

print(
    "Guideline questions:",
    len(guideline_eval_df),
)

print(
    guideline_eval_df[
        "relevant_document_id"
    ].value_counts()
)

Guideline questions: 40
relevant_document_id
who_hypertension_2021           5
va_dod_type2_diabetes_2023      5
va_dod_ckd_2025                 5
va_dod_asthma_2025              5
va_dod_low_back_pain_2022       5
va_dod_major_depression_2022    5
va_dod_pregnancy_2023           5
cdc_sti_2021                    5
Name: count, dtype: int64

In [218]:
existing_sections = set(
    zip(
        retrieval_records_df["document_id"],
        retrieval_records_df["section_path"],
    )
)

missing_gold_sections = []

for _, row in guideline_eval_df.iterrows():
    for section in row["relevant_sections"]:
        if (
            row["relevant_document_id"],
            section,
        ) not in existing_sections:
            missing_gold_sections.append(
                {
                    "eval_id": row["eval_id"],
                    "document_id": row["relevant_document_id"],
                    "section": section,
                }
            )

missing_gold_sections_df = pd.DataFrame(
    missing_gold_sections
)

print(
    "Missing gold sections:",
    len(missing_gold_sections_df),
)

missing_gold_sections_df

Missing gold sections: 1

,eval_id,document_id,section
0,lbp_04,va_dod_low_back_pain_2022,"**Appendix E: Dosing for Select Pharmacologic Agentsa,b**"

In [219]:
for row in guideline_eval_rows:
    if row["eval_id"] == "lbp_04":
        row["relevant_sections"] = [
            "IX. Recommendations > D. Pharmacotherapy",
            "Appendix E: Dosing for Select Pharmacologic Agentsa,b",
        ]

In [220]:
guideline_eval_df = pd.DataFrame(
    guideline_eval_rows
)

In [221]:
existing_sections = set(
    zip(
        retrieval_records_df["document_id"],
        retrieval_records_df["section_path"],
    )
)

missing_gold_sections = []

for _, row in guideline_eval_df.iterrows():
    for section in row["relevant_sections"]:
        if (
            row["relevant_document_id"],
            section,
        ) not in existing_sections:
            missing_gold_sections.append(
                {
                    "eval_id": row["eval_id"],
                    "document_id": row["relevant_document_id"],
                    "section": section,
                }
            )

missing_gold_sections_df = pd.DataFrame(
    missing_gold_sections
)

print(
    "Missing gold sections:",
    len(missing_gold_sections_df),
)

missing_gold_sections_df

Missing gold sections: 0

Empty DataFrame
Columns: []
Index: []

### Финальная разметка real-dev вопросов

После ручной проверки coverage осталось 7 естественных пользовательских вопросов,
для которых текущая knowledge base действительно содержит релевантную информацию.

Gold-разметка фиксируется до запуска retrieval.

Релевантность на этом этапе определяется на уровне `section_path`:
retrieval считается успешным, если среди top-k chunks присутствует chunk
из одного из заранее размеченных релевантных разделов.

In [222]:
real_dev_gold = {
    "candidate_0005": {
        "relevant_document_id": "va_dod_major_depression_2022",
        "relevant_sections": [
            "VIII. Algorithm > A. Module A: Initial Assessment and Treatment",
            "IX. Recommendations > C. Treatment Setting",
            "IX. Recommendations > D. Treatment of Uncomplicated MDD",
            (
                "IX. Recommendations > H. Self-help, "
                "Complementary, and Alternative Treatments"
            ),
        ],
    },

    "candidate_0014": {
        "relevant_document_id": "va_dod_low_back_pain_2022",
        "relevant_sections": [
            "IX. Recommendations > A. Evaluation and Diagnostic Approach",
            "VIII. Algorithm > A. Module A: Initial Evaluation of Low Back Pain",
            (
                "Appendix I: Alternative Text Descriptions of Algorithm "
                "> A. Module A: Initial Evaluation of Low Back Pain"
            ),
        ],
    },

    "candidate_0029": {
        "relevant_document_id": "va_dod_ckd_2025",
        "relevant_sections": [
            "IX. Recommendations",
            "VIII. Algorithm",
            "Appendix G. Alternative Text Descriptions of Algorithms",
            "Appendix I. Monitoring of CKD Table",
        ],
    },

    "candidate_0048": {
        "relevant_document_id": "va_dod_low_back_pain_2022",
        "relevant_sections": [
            "IX. Recommendations > D. Pharmacotherapy",
            (
                "IX. Recommendations > C. "
                "Non-pharmacologic and Non-invasive Therapy"
            ),
            "VIII. Algorithm > B. Module B: Management of Low Back Pain",
            (
                "Appendix I: Alternative Text Descriptions of Algorithm "
                "> B. Module B: Management of Low Back Pain"
            ),
        ],
    },

    "candidate_0078": {
        "relevant_document_id": "va_dod_low_back_pain_2022",
        "relevant_sections": [
            "IX. Recommendations > A. Evaluation and Diagnostic Approach",
            "VIII. Algorithm > A. Module A: Initial Evaluation of Low Back Pain",
            "VIII. Algorithm > B. Module B: Management of Low Back Pain",
        ],
    },

    "candidate_0097": {
        "relevant_document_id": "va_dod_asthma_2025",
        "relevant_sections": [
            (
                "Appendix C: Assessments of Asthma Severity and Control "
                "> B. Assessment of Asthma Control"
            ),
            (
                "Appendix C: Assessments of Asthma Severity and Control "
                "> C. Indications for Specialist Referral"
            ),
            "IX. Recommendations > B. Treatment and Management",
        ],
    },

    "candidate_0135": {
        "relevant_document_id": "va_dod_asthma_2025",
        "relevant_sections": [
            "IX. Recommendations > A. Diagnosis and Assessment",
            (
                "Appendix C: Assessments of Asthma Severity and Control "
                "> D. Identifying Alternative Diagnoses"
            ),
            (
                "Appendix D: Details of a Comprehensive History and Physical Exam "
                "> A. Details of a Comprehensive History"
            ),
            (
                "Appendix K: Alternative Text Descriptions of Algorithms "
                "> A. Module A: Assessment and Diagnosis of Asthma"
            ),
        ],
    },
}

In [223]:
real_dev_eval_rows = []

for candidate_id, gold in real_dev_gold.items():
    source_row = retrieval_eval_labeling_df.loc[
        retrieval_eval_labeling_df["candidate_id"].eq(candidate_id)
    ].iloc[0]

    real_dev_eval_rows.append(
        {
            "eval_id": f'dev_{candidate_id.split("_")[-1]}',
            "candidate_id": candidate_id,
            "question_source": "real_dev",
            "query": source_row["input"],
            "relevant_document_id": gold["relevant_document_id"],
            "relevant_sections": gold["relevant_sections"],
        }
    )

real_dev_eval_df = pd.DataFrame(
    real_dev_eval_rows
)

real_dev_eval_df[
    [
        "eval_id",
        "candidate_id",
        "relevant_document_id",
        "relevant_sections",
    ]
]

,eval_id,candidate_id,relevant_document_id,relevant_sections
0,dev_0005,candidate_0005,va_dod_major_depression_2022,"[VIII. Algorithm > A. Module A: Initial Assessment and Treatment, IX. Recommendations > C. Treatment Setting, IX. Recommendations > D. Treatment of Uncomplicated MDD, IX. Recommendations > H. Self-help, Complementary, and Alternative Treatments]"
1,dev_0014,candidate_0014,va_dod_low_back_pain_2022,"[IX. Recommendations > A. Evaluation and Diagnostic Approach, VIII. Algorithm > A. Module A: Initial Evaluation of Low Back Pain, Appendix I: Alternative Text Descriptions of Algorithm > A. Module A: Initial Evaluation of Low Back Pain]"
2,dev_0029,candidate_0029,va_dod_ckd_2025,"[IX. Recommendations, VIII. Algorithm, Appendix G. Alternative Text Descriptions of Algorithms, Appendix I. Monitoring of CKD Table]"
3,dev_0048,candidate_0048,va_dod_low_back_pain_2022,"[IX. Recommendations > D. Pharmacotherapy, IX. Recommendations > C. Non-pharmacologic and Non-invasive Therapy, VIII. Algorithm > B. Module B: Management of Low Back Pain, Appendix I: Alternative Text Descriptions of Algorithm > B. Module B: Management of Low Back Pain]"
4,dev_0078,candidate_0078,va_dod_low_back_pain_2022,"[IX. Recommendations > A. Evaluation and Diagnostic Approach, VIII. Algorithm > A. Module A: Initial Evaluation of Low Back Pain, VIII. Algorithm > B. Module B: Management of Low Back Pain]"
5,dev_0097,candidate_0097,va_dod_asthma_2025,"[Appendix C: Assessments of Asthma Severity and Control > B. Assessment of Asthma Control, Appendix C: Assessments of Asthma Severity and Control > C. Indications for Specialist Referral, IX. Recommendations > B. Treatment and Management]"
6,dev_0135,candidate_0135,va_dod_asthma_2025,"[IX. Recommendations > A. Diagnosis and Assessment, Appendix C: Assessments of Asthma Severity and Control > D. Identifying Alternative Diagnoses, Appendix D: Details of a Comprehensive History and Physical Exam > A. Details of a Comprehensive History, Appendix K: Alternative Text Descriptions of Algorithms > A. Module A: Assessment and Diagnosis of Asthma]"

In [224]:
existing_sections = set(
    zip(
        retrieval_records_df["document_id"],
        retrieval_records_df["section_path"],
    )
)

missing_real_dev_sections = []

for _, row in real_dev_eval_df.iterrows():
    for section in row["relevant_sections"]:
        if (
            row["relevant_document_id"],
            section,
        ) not in existing_sections:
            missing_real_dev_sections.append(
                {
                    "eval_id": row["eval_id"],
                    "document_id": row["relevant_document_id"],
                    "section": section,
                }
            )

missing_real_dev_sections_df = pd.DataFrame(
    missing_real_dev_sections
)

print(
    "Real-dev questions:",
    len(real_dev_eval_df),
)

print(
    "Missing real-dev gold sections:",
    len(missing_real_dev_sections_df),
)

missing_real_dev_sections_df

Real-dev questions: 7
Missing real-dev gold sections: 0

Empty DataFrame
Columns: []
Index: []

### Финальный retrieval evaluation set

Итоговый benchmark состоит из двух независимых частей:

- `real_dev` — 7 естественных пользовательских вопросов из `dev`, которые
  вручную признаны покрываемыми текущей knowledge base;
- `guideline` — 40 контролируемых вопросов, по 5 на каждый документ KB.

Всего: 47 вопросов.

Gold-релевантность задана на уровне `section_path` и была определена
до просмотра результатов dense retrieval.

После сохранения этого набора gold-разметка не изменяется на основании
результатов retriever.

In [225]:
guideline_eval_df = guideline_eval_df.copy()
real_dev_eval_df = real_dev_eval_df.copy()

guideline_eval_df["candidate_id"] = None

retrieval_eval_df = pd.concat(
    [
        real_dev_eval_df,
        guideline_eval_df,
    ],
    ignore_index=True,
    sort=False,
)

retrieval_eval_df = retrieval_eval_df[
    [
        "eval_id",
        "candidate_id",
        "question_source",
        "query",
        "relevant_document_id",
        "relevant_sections",
    ]
].copy()

retrieval_eval_df

,eval_id,candidate_id,question_source,query,relevant_document_id,relevant_sections
0,dev_0005,candidate_0005,real_dev,Hi my boyfriend and I have been together for over a year and just recently (about 5 months after his best friends death) he has begun to act strange. Hes temper has become a lot worse and he has a short fuse. He is only 20. He feels so much stress and pressure even when there isnt things to stress about. Hes not himself and admitted that he is feeling depressed lately. His moods switch in an instant. Is there something i can do about it? Does he need medical help for depression or manic depr...,va_dod_major_depression_2022,"[VIII. Algorithm > A. Module A: Initial Assessment and Treatment, IX. Recommendations > C. Treatment Setting, IX. Recommendations > D. Treatment of Uncomplicated MDD, IX. Recommendations > H. Self-help, Complementary, and Alternative Treatments]"
1,dev_0014,candidate_0014,real_dev,"Hi, I am suffering from lower back pain going to my lower right ribs. Ive undergone blood test, urinary test, whole abdominal ultrasound and even kidney xray but found nothing on it. Also lately i feel thirsty all the time. Is there any other kind of test that I need to undergo in order to determine the cause of this?.",va_dod_low_back_pain_2022,"[IX. Recommendations > A. Evaluation and Diagnostic Approach, VIII. Algorithm > A. Module A: Initial Evaluation of Low Back Pain, Appendix I: Alternative Text Descriptions of Algorithm > A. Module A: Initial Evaluation of Low Back Pain]"
2,dev_0029,candidate_0029,real_dev,"I have been told that I have stage 5 advanced chronic kidney disease, blood pressure perfect cholesterol perfect.Feel great look great, drs are surprised say that considering my blood work I shoulod be deathly sick but Im not at all. I was told that i need dialysis and transplant...shouldnt I be tested further",va_dod_ckd_2025,"[IX. Recommendations, VIII. Algorithm, Appendix G. Alternative Text Descriptions of Algorithms, Appendix I. Monitoring of CKD Table]"
3,dev_0048,candidate_0048,real_dev,hi sir iam having a sciatica problem and lumber spine problem for this pain i had taken a electro homeopathy treatment in that doctor had given me a electric shock on my left leg main nerve for 3 times and the pain is gone for few days only after that it came again i had taken lot of pills but no cure now my doctor suggest me duzella 30 mg so how much its useful for me pls suggest me some good medicine iam fearing tht any side affects will come because my marriage is thier in a month and ia...,va_dod_low_back_pain_2022,"[IX. Recommendations > D. Pharmacotherapy, IX. Recommendations > C. Non-pharmacologic and Non-invasive Therapy, VIII. Algorithm > B. Module B: Management of Low Back Pain, Appendix I: Alternative Text Descriptions of Algorithm > B. Module B: Management of Low Back Pain]"
4,dev_0078,candidate_0078,real_dev,"two months now into it...started off lower back pain then soreness in hip flexor both legs but more on right. now pain and ackey in both legs ham strings and quads. When driving, 10 min in, severe pain or acke from butt down ham into back of knee. I have to get out and stand up. then good for another 10 min. This is getting unbearable.",va_dod_low_back_pain_2022,"[IX. Recommendations > A. Evaluation and Diagnostic Approach, VIII. Algorithm > A. Module A: Initial Evaluation of Low Back Pain, VIII. Algorithm > B. Module B: Management of Low Back Pain]"
5,dev_0097,candidate_0097,real_dev,"ihave severe asthma and have been 5 times in the last 9 weeks and been given lots of steroids, so i am on insulin now. i am so wore ouy and can hardly get around. thw wheezing has stopped. i have high numbers of latic acid in the muscles. please tell me what to do.",va_dod_asthma_2025,"[Appendix C: Assessments of Asthma Severity and Control > B. Assessment of Asthma Control, Appendix C: Assessments of Asthma Severity and Control > C. Indications for Specialist Referral, IX. Recommendations > B. Treatment and Management]"
6,dev_0135,candidate_0135,real_dev,"I experience respiratory distress symptoms (SOB, decreased O2, voice changes) when I am exposed to perfumes and a few other strong oders and flying dust/dirt. What could this be a symptoms of?I am 37 years old, weigh 145, and have no hx of asthma or any other respiratory issues.",va_dod_asthma_2025,"[IX. Recommendations > A. Diagnosis and Assessment, Appendix C: Assessments of Asthma Severity and Control > D. Identifying Alternative Diagnoses, Appendix D: Details of a Comprehensive History and Physical Exam > A. Details of a Comprehensive History, Appendix K: Alternative Text Descriptions of Algorithms > A. Module A: Assessment and Diagnosis of Asthma]"
7,who_01,None,guideline,At what blood pressure level should pharmacological treatment for hypertension be started?,who_hypertension_2021,[3 Recommendations > 3.1 Blood pressure threshold for initiation of pharmacological treatment]
8,who_02,None,guideline,What laboratory tests should be considered before starting antihypertensive medication and during treatment?,who_hypertension_2021,[3 Recommendations > 3.2 Laboratory testing before and during pharmacological treatment]
9,who_03,None,guideline,Which classes of medication are recommended as first-line treatment for hypertension?,who_hypertension_2021,[3 Recommendations > 3.4 Drug classes to be used as first-line agents]
10,who_04,None,guideline,When should combination drug therapy be used for treating hypertension?,who_hypertension_2021,[3 Recommendations > 3.5 Combination therapy]
11,who_05,None,guideline,What blood pressure target should treatment aim for in adults receiving therapy for hypertension?,who_hypertension_2021,[3 Recommendations > 3.6 Target blood pressure]
12,t2d_01,None,guideline,How should glycemic control be monitored in adults with type 2 diabetes?,va_dod_type2_diabetes_2023,[Appendix B: Glycemic Control Targets and Monitoring]
13,t2d_02,None,guideline,What lifestyle and other non-drug interventions are recommended for adults with type 2 diabetes?,va_dod_type2_diabetes_2023,[IX. Recommendations > D. Non-Pharmacotherapy]
14,t2d_03,None,guideline,What should be considered when choosing medications for treatment of type 2 diabetes?,va_dod_type2_diabetes_2023,"[IX. Recommendations > E. Pharmacotherapy, Appendix C: Pharmacotherapy]"
15,t2d_04,None,guideline,What management strategies are recommended for adults with prediabetes to reduce progression to type 2 diabetes?,va_dod_type2_diabetes_2023,[IX. Recommendations > A. Prediabetes]
16,t2d_05,None,guideline,What education and support should patients receive to help them manage type 2 diabetes themselves?,va_dod_type2_diabetes_2023,[VIII. Algorithm > B. Module B: Self-Management Education and Support]
17,ckd_01,None,guideline,"How should chronic kidney disease be evaluated, staged, and monitored over time?",va_dod_ckd_2025,"[VIII. Algorithm, Appendix G. Alternative Text Descriptions of Algorithms, Appendix I. Monitoring of CKD Table]"
18,ckd_02,None,guideline,When should a patient with chronic kidney disease be referred to a nephrology specialist?,va_dod_ckd_2025,"[IX. Recommendations, Appendix G. Alternative Text Descriptions of Algorithms]"
19,ckd_03,None,guideline,How should the decision between dialysis and conservative management be made in advanced CKD?,va_dod_ckd_2025,[IX. Recommendations]
20,ckd_04,None,guideline,How should hyperkalemia be managed in a patient with chronic kidney disease?,va_dod_ckd_2025,"[Appendix M. Management of Hyperkalemia > C. Management, Appendix M. Management of Hyperkalemia > D. Dietary Considerations, Appendix M. Management of Hyperkalemia > E. Use of Potassium Binders]"
21,ckd_05,None,guideline,What medication-related precautions should be considered in patients with chronic kidney disease?,va_dod_ckd_2025,"[Appendix K. Nephrotoxic Agents and Medication Dose Adjustments in CKD > B. Nephrotoxic Medications, Appendix K. Nephrotoxic Agents and Medication Dose Adjustments in CKD > C. Medication Management in CKD]"
22,asthma_01,None,guideline,How should asthma be diagnosed and assessed in a patient with respiratory symptoms?,va_dod_asthma_2025,"[IX. Recommendations > A. Diagnosis and Assessment, Appendix K: Alternative Text Descriptions of Algorithms > A. Module A: Assessment and Diagnosis of Asthma]"
23,asthma_02,None,guideline,How can the level of asthma control be assessed in a patient who already has asthma?,va_dod_asthma_2025,"[Appendix C: Assessments of Asthma Severity and Control > B. Assessment of Asthma Control, II. Background > B. Classification of Asthma Severity and Control]"
24,asthma_03,None,guideline,When should a patient with asthma be referred to a specialist?,va_dod_asthma_2025,[Appendix C: Assessments of Asthma Severity and Control > C. Indications for Specialist Referral]
25,asthma_04,None,guideline,What treatment and management approaches are recommended for adults with asthma?,va_dod_asthma_2025,"[IX. Recommendations > B. Treatment and Management, Appendix K: Alternative Text Descriptions of Algorithms > B. Module B: Initiation of Therapy]"
26,asthma_05,None,guideline,What alternative diagnoses should be considered when symptoms resemble asthma?,va_dod_asthma_2025,"[Appendix C: Assessments of Asthma Severity and Control > D. Identifying Alternative Diagnoses, Appendix D: Details of a Comprehensive History and Physical Exam > A. Details of a Comprehensive History]"
27,lbp_01,None,guideline,How should a patient with low back pain be evaluated to determine whether further diagnostic testing is needed?,va_dod_low_back_pain_2022,"[IX. Recommendations > A. Evaluation and Diagnostic Approach, VIII. Algorithm > A. Module A: Initial Evaluation of Low Back Pain, Appendix I: Alternative Text Descriptions of Algorithm > A. Module A: Initial Evaluation of Low Back Pain]"
28,lbp_02,None,guideline,What self-care and education should be recommended to patients with low back pain?,va_dod_low_back_pain_2022,[IX. Recommendations > B. Patient Education and Self-care]
29,lbp_03,None,guideline,Which non-drug and non-invasive treatments are recommended for managing low back pain?,va_dod_low_back_pain_2022,"[IX. Recommendations > C. Non-pharmacologic and Non-invasive Therapy, VIII. Algorithm > B. Module B: Management of Low Back Pain]"
30,lbp_04,None,guideline,What medications can be considered for the treatment of low back pain?,va_dod_low_back_pain_2022,"[IX. Recommendations > D. Pharmacotherapy, Appendix E: Dosing for Select Pharmacologic Agentsa,b]"
31,lbp_05,None,guideline,What non-surgical invasive treatments may be considered for patients with persistent low back pain?,va_dod_low_back_pain_2022,[IX. Recommendations > F. Non-surgical Invasive Therapy]
32,mdd_01,None,guideline,How should a patient be initially assessed when major depressive disorder is suspected?,va_dod_major_depression_2022,"[VIII. Algorithm > A. Module A: Initial Assessment and Treatment, IX. Recommendations > A. Screening]"
33,mdd_02,None,guideline,How should treatment outcomes be monitored in a patient being treated for major depression?,va_dod_major_depression_2022,"[IX. Recommendations > B. Monitoring Outcomes, Appendix I: Quick Guide to the Patient Health Questionnaire in Clinical Practice > C. Using the PHQ-9 in Measurement-Based Care]"
34,mdd_03,None,guideline,What treatments are recommended for uncomplicated major depressive disorder?,va_dod_major_depression_2022,[IX. Recommendations > D. Treatment of Uncomplicated MDD]
35,mdd_04,None,guideline,What treatment options should be considered when depression is severe or has not responded adequately to initial treatment?,va_dod_major_depression_2022,"[IX. Recommendations > E. Treatment of MDD that is Severe or has a Partial or Limited Response to Initial Treatment, VIII. Algorithm > B. Module B: Advanced Care Management]"
36,mdd_05,None,guideline,What non-medication self-help or complementary approaches may be considered for major depression?,va_dod_major_depression_2022,"[IX. Recommendations > H. Self-help, Complementary, and Alternative Treatments]"
37,pregnancy_01,None,guideline,What should be assessed and discussed during the initial prenatal visit?,va_dod_pregnancy_2023,[X. Routine Pregnancy Care > A. Initial Prenatal Visit]
38,pregnancy_02,None,guideline,What care and monitoring should be provided during follow-up prenatal visits?,va_dod_pregnancy_2023,[X. Routine Pregnancy Care > B. Subsequent Prenatal Visits]
39,pregnancy_03,None,guideline,What care should be provided to a patient during the postpartum period?,va_dod_pregnancy_2023,[X. Routine Pregnancy Care > C. Postpartum]
40,pregnancy_04,None,guideline,What education should patients receive as part of routine pregnancy care?,va_dod_pregnancy_2023,[X. Routine Pregnancy Care > D. Education]
41,pregnancy_05,None,guideline,When should a pregnant patient be referred to an advanced prenatal care provider?,va_dod_pregnancy_2023,"[XI. Referral Indications > A. Advanced Prenatal Care Provider, VIII. Recommendations > B. Complicated Obstetrics]"
42,sti_01,None,guideline,What treatment is recommended for chlamydial infection in adolescents and adults?,cdc_sti_2021,[Chlamydial Infections > Chlamydial Infection Among Adolescents and Adults > Treatment]
43,sti_02,None,guideline,How should a first clinical episode of genital herpes be treated?,cdc_sti_2021,"[Diseases Characterized by Genital, Anal, or Perianal Ulcers > Genital Herpes > Genital Herpes Management > First Clinical Episode of Genital Herpes]"
44,sti_03,None,guideline,How should cervicitis be evaluated to determine the likely infectious cause?,cdc_sti_2021,"[Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Diagnostic Considerations, Diseases Characterized by Urethritis and Cervicitis > Cervicitis > Etiology]"
45,sti_04,None,guideline,What tests are used to diagnose syphilis?,cdc_sti_2021,"[Syphilis > Diagnostic Considerations, Syphilis > Diagnostic Considerations > Nontreponemal Tests and Traditional Algorithm, Syphilis > Diagnostic Considerations > Treponemal Tests and Reverse Sequence Algorithm]"
46,sti_05,None,guideline,What treatments are recommended for bacterial vaginosis?,cdc_sti_2021,"[Diseases Characterized by Vulvovaginal Itching, Burning, Irritation, Odor, or Discharge > Bacterial Vaginosis > Treatment]"

In [226]:
print("Total questions:", len(retrieval_eval_df))

print(
    "\nBy source:"
)
print(
    retrieval_eval_df[
        "question_source"
    ].value_counts()
)

print(
    "\nUnique eval_id:",
    retrieval_eval_df["eval_id"].is_unique,
)

print(
    "Unique queries:",
    retrieval_eval_df["query"].is_unique,
)

print(
    "Missing queries:",
    retrieval_eval_df["query"].isna().sum(),
)

print(
    "Missing gold documents:",
    retrieval_eval_df[
        "relevant_document_id"
    ].isna().sum(),
)

print(
    "Empty relevant_sections:",
    retrieval_eval_df[
        "relevant_sections"
    ].apply(len).eq(0).sum(),
)

Total questions: 47

By source:
question_source
guideline    40
real_dev      7
Name: count, dtype: int64

Unique eval_id: True
Unique queries: True
Missing queries: 0
Missing gold documents: 0
Empty relevant_sections: 0

In [227]:
existing_sections = set(
    zip(
        retrieval_records_df["document_id"],
        retrieval_records_df["section_path"],
    )
)

missing_sections = []

for _, row in retrieval_eval_df.iterrows():
    for section in row["relevant_sections"]:
        if (
            row["relevant_document_id"],
            section,
        ) not in existing_sections:
            missing_sections.append(
                {
                    "eval_id": row["eval_id"],
                    "document_id": row["relevant_document_id"],
                    "section": section,
                }
            )

missing_sections_df = pd.DataFrame(
    missing_sections
)

print(
    "Missing gold sections:",
    len(missing_sections_df),
)

missing_sections_df

Missing gold sections: 0

Empty DataFrame
Columns: []
Index: []

In [228]:
RETRIEVAL_EVAL_PATH = (
    MATERIALS_DIR
    / "retrieval_eval_v1.jsonl"
)

retrieval_eval_df.to_json(
    RETRIEVAL_EVAL_PATH,
    orient="records",
    lines=True,
    force_ascii=False,
)

print(
    "Saved:",
    RETRIEVAL_EVAL_PATH,
)

Saved: ..\materials\retrieval_eval_v1.jsonl

In [229]:
retrieval_eval_frozen_df = pd.read_json(
    RETRIEVAL_EVAL_PATH,
    lines=True,
)

print(
    retrieval_eval_frozen_df.shape
)

print(
    type(
        retrieval_eval_frozen_df.loc[
            0,
            "relevant_sections",
        ]
    )
)

(47, 6)
<class 'list'>

In [230]:
retrieval_eval_frozen_df = pd.read_json(
    RETRIEVAL_EVAL_PATH,
    lines=True,
)

### Оценка dense retrieval на frozen benchmark

Для каждого вопроса получаем top-10 chunks текущим dense retriever.

Chunk считается релевантным, если одновременно:

- `document_id` совпадает с gold-документом;
- `section_path` входит в заранее размеченный список релевантных разделов.

Считаем:

- Hit@1
- Hit@3
- Hit@5
- MRR@10

Результаты считаются отдельно для `real_dev` и `guideline`,
поскольку эти две части benchmark имеют разную сложность и происхождение.

In [231]:
def evaluate_retrieval_query(row, top_k=10):
    results = dense_search(
        row["query"],
        top_k=top_k,
    ).reset_index(drop=True).copy()

    gold_document = row["relevant_document_id"]
    gold_sections = set(row["relevant_sections"])

    results["is_relevant"] = (
        results["document_id"].eq(gold_document)
        &
        results["section_path"].isin(gold_sections)
    )

    relevant_positions = np.flatnonzero(
        results["is_relevant"].to_numpy()
    )

    if len(relevant_positions) > 0:
        first_relevant_rank = int(
            relevant_positions[0] + 1
        )
    else:
        first_relevant_rank = None

    return {
        "eval_id": row["eval_id"],
        "candidate_id": row["candidate_id"],
        "question_source": row["question_source"],
        "query": row["query"],

        "first_relevant_rank": first_relevant_rank,

        "hit_at_1": (
            first_relevant_rank is not None
            and first_relevant_rank <= 1
        ),
        "hit_at_3": (
            first_relevant_rank is not None
            and first_relevant_rank <= 3
        ),
        "hit_at_5": (
            first_relevant_rank is not None
            and first_relevant_rank <= 5
        ),

        "rr_at_10": (
            1 / first_relevant_rank
            if first_relevant_rank is not None
            else 0.0
        ),

        "top1_document_id": (
            results.iloc[0]["document_id"]
            if len(results) > 0
            else None
        ),
        "top1_section_path": (
            results.iloc[0]["section_path"]
            if len(results) > 0
            else None
        ),
        "top1_score": (
            float(results.iloc[0]["score"])
            if len(results) > 0
            else None
        ),
    }

In [232]:
retrieval_eval_results = []

for _, row in retrieval_eval_frozen_df.iterrows():
    retrieval_eval_results.append(
        evaluate_retrieval_query(
            row,
            top_k=10,
        )
    )

retrieval_eval_results_df = pd.DataFrame(
    retrieval_eval_results
)

retrieval_eval_results_df.head()

,eval_id,candidate_id,question_source,query,first_relevant_rank,hit_at_1,hit_at_3,hit_at_5,rr_at_10,top1_document_id,top1_section_path,top1_score
0,dev_0005,candidate_0005,real_dev,Hi my boyfriend and I have been together for over a year and just recently (about 5 months after his best friends death) he has begun to act strange. Hes temper has become a lot worse and he has a short fuse. He is only 20. He feels so much stress and pressure even when there isnt things to stress about. Hes not himself and admitted that he is feeling depressed lately. His moods switch in an instant. Is there something i can do about it? Does he need medical help for depression or manic depr...,8.0,False,False,False,0.125,va_dod_major_depression_2022,II. Background > A. Description of Major Depressive Disorder (MDD),0.628073
1,dev_0014,candidate_0014,real_dev,"Hi, I am suffering from lower back pain going to my lower right ribs. Ive undergone blood test, urinary test, whole abdominal ultrasound and even kidney xray but found nothing on it. Also lately i feel thirsty all the time. Is there any other kind of test that I need to undergo in order to determine the cause of this?.",1.0,True,True,True,1.000,va_dod_low_back_pain_2022,IX. Recommendations > A. Evaluation and Diagnostic Approach,0.668335
2,dev_0029,candidate_0029,real_dev,"I have been told that I have stage 5 advanced chronic kidney disease, blood pressure perfect cholesterol perfect.Feel great look great, drs are surprised say that considering my blood work I shoulod be deathly sick but Im not at all. I was told that i need dialysis and transplant...shouldnt I be tested further",1.0,True,True,True,1.000,va_dod_ckd_2025,IX. Recommendations,0.723086
3,dev_0048,candidate_0048,real_dev,hi sir iam having a sciatica problem and lumber spine problem for this pain i had taken a electro homeopathy treatment in that doctor had given me a electric shock on my left leg main nerve for 3 times and the pain is gone for few days only after that it came again i had taken lot of pills but no cure now my doctor suggest me duzella 30 mg so how much its useful for me pls suggest me some good medicine iam fearing tht any side affects will come because my marriage is thier in a month and ia...,1.0,True,True,True,1.000,va_dod_low_back_pain_2022,IX. Recommendations > D. Pharmacotherapy,0.692542
4,dev_0078,candidate_0078,real_dev,"two months now into it...started off lower back pain then soreness in hip flexor both legs but more on right. now pain and ackey in both legs ham strings and quads. When driving, 10 min in, severe pain or acke from butt down ham into back of knee. I have to get out and stand up. then good for another 10 min. This is getting unbearable.",2.0,False,True,True,0.500,va_dod_low_back_pain_2022,II. Background > A. Description of Low Back Pain,0.646642

In [233]:
def summarize_retrieval_metrics(df):
    return pd.Series(
        {
            "n": len(df),
            "Hit@1": df["hit_at_1"].mean(),
            "Hit@3": df["hit_at_3"].mean(),
            "Hit@5": df["hit_at_5"].mean(),
            "MRR@10": df["rr_at_10"].mean(),
        }
    )

In [234]:
overall_metrics = summarize_retrieval_metrics(
    retrieval_eval_results_df
)

overall_metrics

n         47.000000
Hit@1      0.829787
Hit@3      0.936170
Hit@5      0.936170
MRR@10     0.882092
dtype: float64

In [ ]:
metrics_by_source = (
    retrieval_eval_results_df
    .groupby("question_source")
    .apply(summarize_retrieval_metrics)
)

metrics_by_source

In [236]:
retrieval_failures_df = (
    retrieval_eval_results_df[
        ~retrieval_eval_results_df["hit_at_5"]
    ][
        [
            "eval_id",
            "question_source",
            "query",
            "first_relevant_rank",
            "top1_document_id",
            "top1_section_path",
            "top1_score",
        ]
    ]
    .reset_index(drop=True)
)

print(
    "Failures at Hit@5:",
    len(retrieval_failures_df),
)

retrieval_failures_df

Failures at Hit@5: 3

,eval_id,question_source,query,first_relevant_rank,top1_document_id,top1_section_path,top1_score
0,dev_0005,real_dev,Hi my boyfriend and I have been together for over a year and just recently (about 5 months after his best friends death) he has begun to act strange. Hes temper has become a lot worse and he has a short fuse. He is only 20. He feels so much stress and pressure even when there isnt things to stress about. Hes not himself and admitted that he is feeling depressed lately. His moods switch in an instant. Is there something i can do about it? Does he need medical help for depression or manic depr...,8.0,va_dod_major_depression_2022,II. Background > A. Description of Major Depressive Disorder (MDD),0.628073
1,t2d_01,guideline,How should glycemic control be monitored in adults with type 2 diabetes?,NaN,va_dod_type2_diabetes_2023,IX. Recommendations > C. Diabetes Mellitus,0.768070
2,asthma_01,guideline,How should asthma be diagnosed and assessed in a patient with respiratory symptoms?,NaN,va_dod_asthma_2025,VIII. Algorithm,0.734461

In [237]:
retrieval_eval_results_df[
    [
        "eval_id",
        "question_source",
        "first_relevant_rank",
    ]
].sort_values(
    [
        "question_source",
        "first_relevant_rank",
    ],
    na_position="last",
)

         eval_id question_source  first_relevant_rank
7         who_01       guideline                  1.0
8         who_02       guideline                  1.0
9         who_03       guideline                  1.0
10        who_04       guideline                  1.0
11        who_05       guideline                  1.0
13        t2d_02       guideline                  1.0
14        t2d_03       guideline                  1.0
15        t2d_04       guideline                  1.0
16        t2d_05       guideline                  1.0
18        ckd_02       guideline                  1.0
19        ckd_03       guideline                  1.0
20        ckd_04       guideline                  1.0
21        ckd_05       guideline                  1.0
23     asthma_02       guideline                  1.0
24     asthma_03       guideline                  1.0
25     asthma_04       guideline                  1.0
26     asthma_05       guideline                  1.0
28        lbp_02       guideline                  1.0
29        lbp_03       guideline                  1.0
30        lbp_04       guideline                  1.0
33        mdd_02       guideline                  1.0
34        mdd_03       guideline                  1.0
35        mdd_04       guideline                  1.0
36        mdd_05       guideline                  1.0
37  pregnancy_01       guideline                  1.0
38  pregnancy_02       guideline                  1.0
39  pregnancy_03       guideline                  1.0
40  pregnancy_04       guideline                  1.0
41  pregnancy_05       guideline                  1.0
42        sti_01       guideline                  1.0
43        sti_02       guideline                  1.0
44        sti_03       guideline                  1.0
45        sti_04       guideline                  1.0
46        sti_05       guideline                  1.0
17        ckd_01       guideline                  2.0
27        lbp_01       guideline                  2.0
32        mdd_01       guideline                  2.0
31        lbp_05       guideline                  3.0
12        t2d_01       guideline                  NaN
22     asthma_01       guideline                  NaN
1       dev_0014        real_dev                  1.0
2       dev_0029        real_dev                  1.0
3       dev_0048        real_dev                  1.0
5       dev_0097        real_dev                  1.0
6       dev_0135        real_dev                  1.0
4       dev_0078        real_dev                  2.0
0       dev_0005        real_dev                  8.0

### Анализ ошибок retrieval

Ошибки `Hit@5` разбираются вручную.

Для каждого случая проверяется:

1. действительно ли top-ranked chunks нерелевантны;
2. не является ли gold-разметка неполной;
3. найден ли правильный документ, но неверно ранжирован конкретный раздел.

Gold не изменяется автоматически по результатам retriever.

In [238]:
def inspect_retrieval_case(eval_id, top_k=10):
    row = retrieval_eval_frozen_df[
        retrieval_eval_frozen_df["eval_id"].eq(eval_id)
    ].iloc[0]

    results = dense_search(
        row["query"],
        top_k=top_k,
    ).reset_index(drop=True).copy()

    gold_sections = set(
        row["relevant_sections"]
    )

    results["rank"] = (
        np.arange(len(results)) + 1
    )

    results["gold_match"] = (
        results["document_id"].eq(
            row["relevant_document_id"]
        )
        &
        results["section_path"].isin(
            gold_sections
        )
    )

    print("=" * 100)
    print("EVAL ID:", eval_id)
    print("\nQUERY:")
    print(row["query"])

    print("\nGOLD DOCUMENT:")
    print(row["relevant_document_id"])

    print("\nGOLD SECTIONS:")
    for section in row["relevant_sections"]:
        print("-", section)

    return results[
        [
            "rank",
            "score",
            "document_id",
            "section_path",
            "page",
            "gold_match",
            "text",
        ]
    ]

In [239]:
t2d_01_results = inspect_retrieval_case(
    "t2d_01"
)

pd.set_option(
    "display.max_colwidth",
    500,
)

t2d_01_results

====================================================================================================
EVAL ID: t2d_01

QUERY:
How should glycemic control be monitored in adults with type 2 diabetes?

GOLD DOCUMENT:
va_dod_type2_diabetes_2023

GOLD SECTIONS:
- Appendix B: Glycemic Control Targets and Monitoring

,rank,score,document_id,section_path,page,gold_match,text
0,1,0.768070,va_dod_type2_diabetes_2023,IX. Recommendations > C. Diabetes Mellitus,39,False,"the following recommendation: For adults with type 2 diabetes mellitus, we suggest using high glycemic variability over time (e.g., fluctuation in HbA1c or fasting blood glucose) as a prognostic indicator for risk of hypoglycemia, morbidity, and mortality."
1,2,0.761366,va_dod_type2_diabetes_2023,IX. Recommendations > E. Pharmacotherapy,69,False,"Recommendation 25. In adults with type 2 diabetes mellitus, especially those 65 years and older, we suggest prioritizing drug classes other than insulin, sulfonylureas, or meglitinides to minimize the risk of hypoglycemia, if glycemic control can be achieved with other treatments. (Weak for | Reviewed, New-added) 26. In adults with type 2 diabetes mellitus who have co-occurring cognitive impairment or risk of falls, there is insufficient evidence to recommend for or against specific treatmen..."
2,3,0.744628,va_dod_type2_diabetes_2023,IX. Recommendations,25,False,"Topic Sub-topic # Recommendation Strengtha Categoryb Neither for nor against Reviewed, New­added 4. There is insufficient evidence to recommend for or against routine screening or using a specific tool to screen for or diagnose diabetes distress. 5. Weak for Reviewed, New­added In adults with type 2 diabetes mellitus and co­occurring non­alcoholic fatty liver disease, we suggest clinicians should assess for fibrosis using a non­invasive tool (e.g., Fibrosis­4). Screening for Comorbidities Ne..."
3,4,0.739464,va_dod_type2_diabetes_2023,IX. Recommendations > C. Diabetes Mellitus,37,False,"be burdensome for providers with limited time. Most screening tools were developed to target older patients, so their accuracy in younger patients is unclear. The Work Group systematically searched for evidence and did not identify any studies that met inclusion criteria regarding routine screening for fall risks and cognitive decline in adult patients with T2DM. Therefore, this recommendation is categorized as Reviewed, New-added. The Work Group’s confidence in the quality of the evidence w..."
4,5,0.732190,va_dod_type2_diabetes_2023,IX. Recommendations,25,False,"’s appraisal of the risk benefit ratio, patient characteristics, presence or absence of type 2 diabetes mellitus complications, comorbidities, and life expectancy. 10. We suggest an HbA1c range of 7.0–8.5% for most patients, if it can be safely achieved. Weak for Not reviewed, Amended Glycemic Management 11. Weak for Reviewed, New­added In insulin­treated adults with type 2 diabetes mellitus who are not achieving glycemic goals, we suggest real­time continuous glucose monitoring to decrease ..."
5,6,0.725484,va_dod_type2_diabetes_2023,IX. Recommendations > C. Diabetes Mellitus,46,False,"Discussion Although evidence is increasing that continuous glucose monitoring (CGM) can improve glucose control and might reduce hypoglycemia in T1DM patients, whether CGM improves outcomes in patients with T2DM is unclear. However, the systematic evidence review found that results differed depending on the type of CGM. For real-time CGM (rtCGM) (i.e., glucose readings automatically and continuously pushed to the user’s receiver or smartphone), we found moderate quality evidence that rtCGM u..."
6,7,0.721560,va_dod_type2_diabetes_2023,IX. Recommendations,26,False,"feedback, hypnosis, guided imagery, massage therapy, yoga, or tai chi to improve outcomes. 19. Strong for Reviewed, New­added For adults with type 2 diabetes mellitus with atherosclerotic cardiovascular disease, we recommend glucagon­like peptide­1 receptor agonists or sodium­glucose cotransporter­2 inhibitors with proven cardiovascular benefits to decrease the risk of major adverse cardiovascular events. 20. Weak for Reviewed, New­added For adults with type 2 diabetes mellitus at high risk ..."
7,8,0.720276,va_dod_type2_diabetes_2023,I. Introduction,5,False,"Recommendation Strength). This CPG provides an evidence-based framework for evaluating and managing care for adult patients with T2DM toward improving clinical outcomes. Successful implementation of this CPG will · Assess the patient’s condition and collaborate with the patient, family, and caregivers to determine optimal management of patient care; · Emphasize the use of patient-centered care and shared decision making; · Minimize preventable complications and morbidity; and · Optimize indi..."
8,9,0.720103,va_dod_type2_diabetes_2023,IX. Recommendations,27,False,"Topic Sub-topic # Recommendation Strengtha Categoryb 23. Strong for Reviewed, New-added For adults with type 2 diabetes mellitus and chronic kidney disease who are not good candidates for a sodium-glucose cotransporter-2 inhibitor, we recommend a glucagon-like peptide-1 receptor agonist with proven renal protection to improve macroalbuminuria. 24. Weak for Reviewed, New-added In adults with type 2 diabetes mellitus who have cardiovascular disease or renal disease, we suggest that the additio..."
9,10,0.719348,va_dod_type2_diabetes_2023,IX. Recommendations > C. Diabetes Mellitus,39,False,"causal effect on adverse events and whether prospectively reducing fasting blood glucose or HbA1c variability will favorably impact outcomes are also unknown. The Work Group systematically reviewed evidence related to this recommendation and considered the assessment of the evidence put forth in the 2017 VA/DoD DM CPG. (74-77, 83) Therefore, it is categorized as Reviewed, New-replaced. The Work Group’s confidence in the quality of the evidence was very low. The body of evidence had some limi..."

In [240]:
asthma_01_results = inspect_retrieval_case(
    "asthma_01"
)

asthma_01_results

====================================================================================================
EVAL ID: asthma_01

QUERY:
How should asthma be diagnosed and assessed in a patient with respiratory symptoms?

GOLD DOCUMENT:
va_dod_asthma_2025

GOLD SECTIONS:
- IX. Recommendations > A. Diagnosis and Assessment
- Appendix K: Alternative Text Descriptions of Algorithms > A. Module A: Assessment and Diagnosis of Asthma

,rank,score,document_id,section_path,page,gold_match,text
0,1,0.734461,va_dod_asthma_2025,VIII. Algorithm,21,False,Module A. Assessment and Diagnosis of Asthma 1 P with symptoms and signs compatible with asthma (see Si a A) 2 4 ollow up as Is the patient Treat exacerbation Yes appropriate acutely ill No Is there a confident clinical diagnosis of No Treat alternative Yes diagnosis asthma (see Si a and Is there an alternative diagnosis A i C) No 8 Yes Yes Is the patient capable of spirometry and is it Obtain spirometry readily available 10 No Is spirometry compatible Yes with asthma (consistent with obstru...
1,2,0.733807,va_dod_asthma_2025,II. Background > A. Description of Asthma,7,False,"weak. In some cases, asthma exacerbations can be severe and potentially life threatening. Airway inflammation and bronchial hyperreactivity are considered the primary underlying pathologic processes. Asthma is characterized by airway obstruction that is usually at least partially reversible. Despite these unifying characteristics, asthma is a very heterogeneous condition. There is significant variability in presenting symptoms, degree of airway obstruction, level of impairment, responsivenes..."
2,3,0.718827,va_dod_asthma_2025,IX. Recommendations > B. Treatment and Management,57,False,"of patients with stable asthma was included in the 2009 and 2019 VA/DOD Asthma CPGs, these recommendations were based on guidance from other organizations. Current literature does not support routine (e.g., quarterly) spirometry for stable patients with asthma in the general population. However, there may be specific requirements that need to be considered for active-duty members of the military. While there are no obvious harms associated with spirometry, there may be added burden and many ..."
3,4,0.716059,va_dod_asthma_2025,IX. Recommendations > B. Treatment and Management,57,False,"to mitigate concerns related to resources and stigma. Thus, the Work Group decided upon a Weak for recommendation. d. Monitoring and Follow-up Recommendation 18. We suggest against utilizing spirometry for routine monitoring of patients with stable asthma. (Weak against | Not reviewed, Not changed) Discussion The diagnosis of asthma is a clinical diagnosis based on history, physical examination, and findings suggestive of airway hyperactivity. While objective measurements of airway reactivit..."
4,5,0.714595,va_dod_asthma_2025,Appendix C: Assessments of Asthma Severity and Control > C. Indications for Specialist Referral,88,False,"Patients may benefit from specialist referral to pulmonology, allergy/immunology, ENT and others, for assistance in asthma management in the following circumstances: • Patient has ever had a life-threatening asthma exacerbation • Patients needing advanced therapies, such as biologics, roflumilast, or a chronic macrolide antibiotic. Also, any patients requiring more than two courses of oral corticosteroids in one year or had an exacerbation requiring hospitalization • Other conditions that co..."
5,6,0.706535,va_dod_asthma_2025,Appendix D: Details of a Comprehensive History and Physical Exam > A. Details of a Comprehensive History,93,False,"• The history should focus on the characterization of symptoms related to airway obstruction or airway hyper-responsiveness, note that patients usually, but not always, present with two or more symptoms:  Cough  Wheezing  Shortness of breath  Chest tightness  Sputum production • The pattern of symptoms should be characterized:  Onset  Duration  Frequency  Diurnal variation  Seasonality • Precipitating and aggravating factors should be explored:  Viral infections  Exercise  Envir..."
6,7,0.706210,va_dod_asthma_2025,VIII. Algorithm,25,False,"Sidebar E: Asthma Education and Self-Management Support Patients and caregivers should be informed of the diagnosis of asthma. Their current understanding of asthma and treatment adherence should be assessed, they should be provided evidence-based education and materials/resources, and they should be given the opportunity to ask questions so they can fully understand their asthma. Consistent follow-up should ensure the patient and caregiver are confident in their ability to self-manage their..."
7,8,0.705993,va_dod_asthma_2025,Appendix C: Assessments of Asthma Severity and Control > D. Identifying Alternative Diagnoses,88,False,Table C-4. Clinical Features Differentiating COPD and Asthma Clinical Features COPD Asthma Smoker or ex-smoker Nearly all Possibly Symptoms under age 35 Rare Often Chronic productive cough Common Uncommon Breathlessness Persistent and progressive Variable Nighttime waking with breathlessness and/or wheeze Uncommon Common Uncommon Common Commonly associated with atopic symptoms and seasonal allergies Significant diurnal or day-to-day variability of symptoms Uncommon Common Favorable response ...
8,9,0.704278,va_dod_asthma_2025,VIII. Algorithm,24,False,"Sidebar C: Alternative Evaluation for Asthma Asthma is a clinical diagnosis, though diagnostic studies and response to treatment may be supportive of the diagnosis. In situations in which routine spirometry does not demonstrate obstruction yet there remains a clinical suspicion for asthma, any of the following options should be offered dependent upon site availability and patient/provider preferences:  Spirometry with bronchodilator testing (if not previously performed)  Bronchoprovocation..."
9,10,0.703074,va_dod_asthma_2025,VIII. Algorithm,23,False,"Sidebar A: Asthma Symptoms  Adult: Daytime or nighttime chronic recurring cough, wheeze, chest tightness, and shortness of breath  Child: Daytime or nighttime prolonged (more than 2 weeks) or recurring cough, wheeze, chest tightness, shortness of breath and other associated non-respiratory symptoms including irritability and being fatigued or tired Sidebar B: Assessment  Symptoms (see Sidebar A)  Pattern (exercise, diurnal vs. nocturnal symptoms)  Precipitating triggers (exercise, aller..."

In [241]:
dev_0005_results = inspect_retrieval_case(
    "dev_0005"
)

dev_0005_results

====================================================================================================
EVAL ID: dev_0005

QUERY:
Hi my boyfriend and I have been together for over a year and just recently (about 5 months after his best friends death) he has begun to act strange. Hes temper has become a lot worse and he has a short fuse. He is only 20. He feels so much stress and pressure even when there isnt things to stress about. Hes not himself and admitted that he is feeling depressed lately. His moods switch in an instant. Is there something i can do about it? Does he need medical help for depression or manic depression? Is there something besides medication to help?

GOLD DOCUMENT:
va_dod_major_depression_2022

GOLD SECTIONS:
- VIII. Algorithm > A. Module A: Initial Assessment and Treatment
- IX. Recommendations > C. Treatment Setting
- IX. Recommendations > D. Treatment of Uncomplicated MDD
- IX. Recommendations > H. Self-help, Complementary, and Alternative Treatments

,rank,score,document_id,section_path,page,gold_match,text
0,1,0.628073,va_dod_major_depression_2022,II. Background > A. Description of Major Depressive Disorder (MDD),7,False,"the most prevalent and disabling form of depression. In addition to the immediate symptoms of depression, MDD precipitates overall poor quality of life (QoL), decreased productivity, increased obesity and sedentary behavior, and increased risk of mortality from suicide and other causes. Social difficulties potentially emerge from the condition, including stigma, loss of employment, and relationship conflict. Approaches used in the literature to categorize the severity of MDD are discussed in..."
1,2,0.626393,va_dod_major_depression_2022,Appendix I: Quick Guide to the Patient Health Questionnaire in Clinical Practice > B. Scoring the PHQ-9 (223),128,False,"Table I-3). Note: The diagnoses of MDD requires ruling out a history of a manic episode (Bipolar Disorder) and a physical disorder, medication or other drug as the biological cause of the depressive symptoms. In the context of bereavement or other significant loss, symptoms consistent with a major depression can occur, and the diagnosis of MDD is considered if there is indication the symptoms are distinguished from normal response to loss given the individual’s history, cultural norms, and t..."
2,3,0.622863,va_dod_major_depression_2022,IX. Recommendations,23,False,"of the cardinal symptoms, and severe MDD had 8 – 9 cardinal symptoms. Regarding chronic depression, also termed persistent depressive disorder (or dysthymia) in DSM-5, symptoms must be present for most days over two years. Typically, symptoms do not remit for greater than two months at a time. Appendix K also describes depression subsets in detail. Topic # Recommendation Strengtha Categoryb 1. We suggest that all patients not currently receiving treatment for depression be screened for depre..."
3,4,0.622756,va_dod_major_depression_2022,IX. Recommendations,24,False,": · Severe (e.g., PHQ-9 >20) · Persistent major depressive disorder (duration greater than two years) · Recurrent (with two or more episodes) Weak for Reviewed, 16. Amended For patients with MDD who have demonstrated partial or no response to an adequate trial of initial pharmacotherapy, we suggest (not rank ordered): · Switching to another antidepressant (including TCAs, MAOIs, or those in Recommendation 12) · Switching to psychotherapy · Augmenting with a psychotherapy · Augmenting with a ..."
4,5,0.622244,va_dod_major_depression_2022,Appendix I: Quick Guide to the Patient Health Questionnaire in Clinical Practice > E. Additional Clinical Considerations,131,False,"After completing a provisional diagnosis with the PHQ-9, additional clinical considerations exist that may shape management and treatment options.(224) · Has a psychosocial stressor(s) triggered current symptoms? · What is the duration of the current disturbance, and has the patient received any treatment for it? · To what extent are the symptoms of the patient impairing their capacity to complete daily work and life duties and responsibilities? · Is there a history of similar episodes, and ..."
5,6,0.621646,va_dod_major_depression_2022,IX. Recommendations > G. Recommendations for Specific Populations,58,False,"symptoms.(177) However, that meta-analysis and an RCT by Cohen et al. (2010) showed significantly better recovery and improvement of symptoms for patients in couples-focused therapy compared to patients on a waitlist control or no treatment.(178) The Work Group was unable to make recommendations related to couples-focused therapy as adjunct or augmentation strategy because no studies comparing couples-focused therapy with combined treatment were found. Current findings were limited by small ..."
6,7,0.617259,va_dod_major_depression_2022,IX. Recommendations > G. Recommendations for Specific Populations,57,False,"Gould et al. (2012) (n=1,712) also supported the use of CBT for older adults, although the quality of the evidence was poor.(175) One study found that CBT significantly reduced symptoms of depression over non-active controls. Two studies found no significant difference in effect between CBT versus active control and CBT alone versus CBT plus another treatment. As with younger populations, the benefits of psychotherapy treatment outweigh the risks. There is some anticipated variation in value..."
7,8,0.613236,va_dod_major_depression_2022,"IX. Recommendations > H. Self-help, Complementary, and Alternative Treatments",64,True,"five times a week, using a visual pacing guide. Results demonstrated that the combination of heart rate variability biofeedback and psychotherapy increased heart rate variability and decreased depressive symptoms more effectively than psychotherapy alone. However, the overall quality rating of the study was poor due to unclear randomization, unclear allocation concealment, unclear whether outcome assessors were blinded, and no information on dropout. There is some variability in patient pref..."
8,9,0.609436,va_dod_major_depression_2022,IX. Recommendations > E. Treatment of MDD that is Severe or has a Partial or Limited Response to Initial Treatment,52,False,"itates repeated trips to a treatment facility for receiving ongoing maintenance doses in many cases. There is currently limited access in some regions (e.g., rural areas) for both treatments due to a lack of providers with adequate clinical resources, experience, and training. Further, the current evidence for efficacy is lacking for people over age 65, which is a significant portion of the Veteran population. The Work Group systematically reviewed evidence related to this recommendation (15..."
9,10,0.608251,va_dod_major_depression_2022,IX. Recommendations > G. Recommendations for Specific Populations,58,False,", for example. Other considerations are that patient values and preferences for couples-focused therapy and partners willing to engage may vary. Other factors to weigh when choosing this intervention are the availability of providers trained in the couples-focused and the additional challenges with scheduling and engaging with the partner, particularly for active duty military couples where deployments and other factors can disrupt the continuity of therapy. The Work Group considered the ass..."

### Анализ ошибок strict section-level evaluation

Все три случая, классифицированные как `Hit@5 = False`, были проверены вручную.

Проверка показала, что они не являются однозначными ошибками dense retrieval:

- `asthma_01`: top-1 chunk содержит алгоритм assessment and diagnosis of asthma;
- `t2d_01`: top-ranked chunks содержат информацию о glycemic variability,
  HbA1c и continuous glucose monitoring;
- `dev_0005`: top-ranked chunks содержат информацию о differential assessment
  при bereavement, исключении bipolar disorder и дополнительных clinical
  considerations; заранее размеченный non-medication section появляется на rank 8.

Таким образом, strict matching по заранее выбранным `section_path`
может давать false negatives, поскольку одна и та же клиническая информация
представлена в нескольких разделах guideline.

Поэтому section-level Hit@k используется как консервативная метрика,
а ошибки дополнительно анализируются вручную.

In [242]:
failure_audit_df = pd.DataFrame(
    [
        {
            "eval_id": "dev_0005",
            "strict_hit_at_5": False,
            "audit_result": "gold_incomplete",
            "best_answer_bearing_rank": 2,
            "notes": (
                "Rank 2 discusses ruling out manic episode and distinguishing "
                "MDD from normal bereavement; rank 5 contains additional "
                "clinical assessment considerations; predefined self-help "
                "section appears at rank 8."
            ),
        },
        {
            "eval_id": "t2d_01",
            "strict_hit_at_5": False,
            "audit_result": "gold_incomplete",
            "best_answer_bearing_rank": 1,
            "notes": (
                "Top-ranked recommendations contain information on glycemic "
                "variability, HbA1c and CGM, although gold contained only "
                "Appendix B."
            ),
        },
        {
            "eval_id": "asthma_01",
            "strict_hit_at_5": False,
            "audit_result": "gold_incomplete",
            "best_answer_bearing_rank": 1,
            "notes": (
                "Top-1 chunk is the Assessment and Diagnosis of Asthma "
                "algorithm and directly addresses the query."
            ),
        },
    ]
)

failure_audit_df

,eval_id,strict_hit_at_5,audit_result,best_answer_bearing_rank,notes
0,dev_0005,False,gold_incomplete,2,Rank 2 discusses ruling out manic episode and distinguishing MDD from normal bereavement; rank 5 contains additional clinical assessment considerations; predefined self-help section appears at rank 8.
1,t2d_01,False,gold_incomplete,1,"Top-ranked recommendations contain information on glycemic variability, HbA1c and CGM, although gold contained only Appendix B."
2,asthma_01,False,gold_incomplete,1,Top-1 chunk is the Assessment and Diagnosis of Asthma algorithm and directly addresses the query.

In [243]:
def evaluate_document_retrieval(row, top_k=10):
    results = dense_search(
        row["query"],
        top_k=top_k,
    ).reset_index(drop=True)

    matches = (
        results["document_id"]
        .eq(row["relevant_document_id"])
        .to_numpy()
    )

    positions = np.flatnonzero(matches)

    first_document_rank = (
        int(positions[0] + 1)
        if len(positions) > 0
        else None
    )

    return {
        "eval_id": row["eval_id"],
        "question_source": row["question_source"],
        "first_document_rank": first_document_rank,
        "doc_hit_at_1": (
            first_document_rank is not None
            and first_document_rank <= 1
        ),
        "doc_hit_at_3": (
            first_document_rank is not None
            and first_document_rank <= 3
        ),
        "doc_hit_at_5": (
            first_document_rank is not None
            and first_document_rank <= 5
        ),
    }

In [244]:
document_eval_results_df = pd.DataFrame(
    [
        evaluate_document_retrieval(row)
        for _, row in retrieval_eval_frozen_df.iterrows()
    ]
)

document_metrics_by_source = (
    document_eval_results_df
    .groupby("question_source")
    .agg(
        n=("eval_id", "size"),
        Doc_Hit_at_1=("doc_hit_at_1", "mean"),
        Doc_Hit_at_3=("doc_hit_at_3", "mean"),
        Doc_Hit_at_5=("doc_hit_at_5", "mean"),
    )
)

document_metrics_by_source

                  n  Doc_Hit_at_1  Doc_Hit_at_3  Doc_Hit_at_5
question_source
guideline        40           1.0           1.0           1.0
real_dev          7           1.0           1.0           1.0

In [245]:
pd.Series(
    {
        "n": len(document_eval_results_df),
        "Doc Hit@1": document_eval_results_df["doc_hit_at_1"].mean(),
        "Doc Hit@3": document_eval_results_df["doc_hit_at_3"].mean(),
        "Doc Hit@5": document_eval_results_df["doc_hit_at_5"].mean(),
    }
)

n            47.0
Doc Hit@1     1.0
Doc Hit@3     1.0
Doc Hit@5     1.0
dtype: float64

In [246]:
guideline_results_with_docs = (
    retrieval_eval_results_df[
        retrieval_eval_results_df["question_source"].eq("guideline")
    ]
    .merge(
        retrieval_eval_frozen_df[
            [
                "eval_id",
                "relevant_document_id",
            ]
        ],
        on="eval_id",
        how="left",
    )
)

metrics_by_document = (
    guideline_results_with_docs
    .groupby("relevant_document_id")
    .agg(
        n=("eval_id", "size"),
        Hit_at_1=("hit_at_1", "mean"),
        Hit_at_3=("hit_at_3", "mean"),
        Hit_at_5=("hit_at_5", "mean"),
        MRR_at_10=("rr_at_10", "mean"),
    )
    .sort_index()
)

metrics_by_document

                              n  Hit_at_1  Hit_at_3  Hit_at_5  MRR_at_10
relevant_document_id
cdc_sti_2021                  5       1.0       1.0       1.0   1.000000
va_dod_asthma_2025            5       0.8       0.8       0.8   0.800000
va_dod_ckd_2025               5       0.8       1.0       1.0   0.900000
va_dod_low_back_pain_2022     5       0.6       1.0       1.0   0.766667
va_dod_major_depression_2022  5       0.8       1.0       1.0   0.900000
va_dod_pregnancy_2023         5       1.0       1.0       1.0   1.000000
va_dod_type2_diabetes_2023    5       0.8       0.8       0.8   0.800000
who_hypertension_2021         5       1.0       1.0       1.0   1.000000

In [247]:
RESULTS_DIR = Path("../results")
RESULTS_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

retrieval_eval_results_df.to_csv(
    RESULTS_DIR / "retrieval_dense_eval_v1.csv",
    index=False,
)

failure_audit_df.to_csv(
    RESULTS_DIR / "retrieval_dense_failure_audit_v1.csv",
    index=False,
)

metrics_by_document.to_csv(
    RESULTS_DIR / "retrieval_dense_metrics_by_document_v1.csv"
)

### Вывод по dense retrieval

Для оценки retrieval был зафиксирован benchmark из 47 вопросов:

- 40 guideline-grounded вопросов, по 5 на каждый документ;
- 7 естественных вопросов из `dev`, вручную признанных покрываемыми KB.

На strict section-level evaluation dense retrieval показал:

- Hit@1 = 0.830
- Hit@3 = 0.936
- Hit@5 = 0.936
- MRR@10 = 0.882

На уровне документа правильный guideline находился на первом месте
для всех 47 вопросов:

- Document Hit@1 = 1.00

Три strict Hit@5 failures были дополнительно проверены вручную.
Во всех случаях retriever возвращал содержательно релевантные chunks,
но их `section_path` отсутствовал в заранее заданном gold-наборе.

Это показывает ограничение section-level evaluation:
одна и та же клиническая информация может находиться в нескольких
recommendations, algorithms, appendices или background sections.

Поэтому strict Hit@k сохраняется как консервативная воспроизводимая метрика,
а ручной audit используется для интерпретации false negatives.

На данном benchmark нет оснований менять embedding model или chunking:
dense retrieval стабильно определяет правильный источник и в большинстве
случаев высоко ранжирует релевантные passages.

Ограничения оценки:

- real-dev subset мал (n=7);
- guideline-grounded вопросы являются контролируемыми и проще реальных
  пользовательских запросов;
- section_path является приближённой, а не полной passage-level
  разметкой релевантности.

In [248]:
import pandas as pd
import pyarrow

print("pandas:", pd.__version__)
print("pyarrow:", pyarrow.__version__)

pandas: 2.3.3
pyarrow: 25.0.1

In [249]:
RETRIEVAL_DATA_DIR = Path(
    "../data/processed/retrieval"
)

RETRIEVAL_DATA_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

chunks_df.to_parquet(
    RETRIEVAL_DATA_DIR / "chunks.parquet",
    index=False,
)

print(
    "Saved chunks:",
    RETRIEVAL_DATA_DIR / "chunks.parquet",
)

print(
    "Chunks:",
    len(chunks_df),
)

Saved chunks: ..\data\processed\retrieval\chunks.parquet
Chunks: 2135

In [250]:
np.save(
    RETRIEVAL_DATA_DIR / "embeddings.npy",
    document_embeddings,
)

print(
    "Saved embeddings:",
    RETRIEVAL_DATA_DIR / "embeddings.npy",
)

print(
    "Shape:",
    document_embeddings.shape,
)

Saved embeddings: ..\data\processed\retrieval\embeddings.npy
Shape: (2135, 768)

In [ ]:
import json

retrieval_config = {
    "embedding_model": EMBEDDING_MODEL_NAME,
    "query_prefix": BGE_QUERY_INSTRUCTION,
    "target_chunk_tokens": TARGET_CHUNK_TOKENS,
    "chunk_overlap_tokens": CHUNK_OVERLAP_TOKENS,
    "normalize_embeddings": True,
    "embedding_dimension": int(
        document_embeddings.shape[1]
    ),
    "num_chunks": int(
        len(chunks_df)
    ),
}

with open(
    RETRIEVAL_DATA_DIR / "config.json",
    "w",
    encoding="utf-8",
) as f:
    json.dump(
        retrieval_config,
        f,
        indent=2,
        ensure_ascii=False,
    )